// Türk Mutfağı 2. bölüm: Et Yemekleri, Tavuk Yemekleri, Balık & Deniz Ürünleri.
import { type SeedTarif } from './seed-tarifler-turk';

const M = 'Türk Mutfağı';

export const TURK_2: SeedTarif[] = [
  // ─── ET YEMEKLERİ ───
  {
    isim: 'Karnıyarık', mutfak: M, kategori: 'Et Yemekleri', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Patlıcan', '6 adet'],
      ['Kıyma', '300 g'],
      ['Soğan', '1 adet büyük'],
      ['Sarımsak', '2 diş'],
      ['Domates', '2 adet'],
      ['Sivri Biber', '6 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Ayçiçek Yağı', 'kızartma için (1 su bardağı)'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Patlıcanları alacalı soyun: soyacakla boydan boya bir şerit soyup bir şerit bırakın, zebra deseni gibi. Bu yöntem hem güzel görünür hem de kabuğun tamamı soyulmadığı için patlıcan pişerken dağılmaz, formunu korur. Orta boy, ince uzun patlıcan seçin; şişman olanların çekirdeği çok olur.',
      'Soyulmuş patlıcanları tuzlu suda 15-20 dakika bekletin. Bu adım iki işe yarar: patlıcanın acı suyunu çeker ve gözeneklerini kapatıp kızartırken daha az yağ emmesini sağlar. Süre sonunda çıkarıp kâğıt havluyla İYİCE kurulayın — ıslak patlıcan kızgın yağı tehlikeli biçimde sıçratır.',
      'Geniş bir tavada yağı kızdırın (bir parça patlıcan attığınızda hemen cızırdamalı) ve patlıcanları ara ara çevirerek her tarafı altın rengi ve içi yumuşayana kadar kızartın. Daha hafif bir sonuç isterseniz fırında da yapabilirsiniz: üzerlerine yağ gezdirip 200 derecede 25 dakika. Kızaranları kâğıt havlulu tabağa alıp fazla yağını verdirin.',
      'İç harç: soğanı minik doğrayıp 2 kaşık yağda 4-5 dakika, pembeleşene kadar kavurun. Kıymayı ekleyip önce topaklarını kaşıkla dağıtın, sonra rengi tamamen kahverengileşene ve saldığı suyu çekene kadar pişirin. Suyunu çekmesi önemli; sulu harç patlıcanı ıslatır.',
      'Ezilmiş sarımsağı ve salçayı ekleyip 1 dakika kavurun, kokusu açılsın. Küp doğranmış 1 domatesi ekleyip tuz ve karabiberle 5 dakika daha, domates yumuşayıp harç toparlanana kadar pişirin. İsterseniz bir tutam kıyılmış maydanoz da katın.',
      'Kızarmış patlıcanları fırın kabına yan yana dizin. Her birinin ortasını kaşık veya bıçakla boydan boya yarın ama tabana kadar kesmeyin; iki yana nazikçe bastırıp açın — kayık gibi bir yuva oluşsun.',
      'Açtığınız yuvalara kıymalı harcı tepeleme doldurun. Her patlıcanın üzerine birer dilim domates ve birer sivri biber yerleştirin (biber pişerken hoş bir koku verir).',
      'Kabın kenarından (patlıcanların üzerine değil) yarım su bardağı sıcak su ekleyin — bu su, fırında kuru kalmamalarını sağlar. Önceden ısıtılmış 180 derece fırında 25-30 dakika, biberler kızarana kadar pişirin. Yanında tereyağlı pirinç pilavı ve cacıkla servis edin.',
    ],
  },
  {
    isim: 'İzmir Köfte', mutfak: M, kategori: 'Et Yemekleri', sure: 55, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '500 g'],
      ['Soğan', '1 adet'],
      ['Yumurta', '1 adet'],
      ['Galeta Unu', '3 yemek kaşığı'],
      ['Patates', '3 adet (450 g)'],
      ['Domates', '2 adet'],
      ['Sivri Biber', '4 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Kimyon', '1 çay kaşığı'],
      ['Ayçiçek Yağı', 'yarım su bardağı'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Köfte harcı için kıymayı geniş bir kaba alın. Soğanı rendenin ince tarafında rendeleyin (böylece harca dağılır, iri parçalar köfteyi dağıtmaz), sularını hafifçe sıkıp ekleyin. Yumurta, galeta unu, kimyon, tuz ve karabiberi de ilave edin. Kimyon İzmir köftesinin karakter baharatıdır, eksik etmeyin.',
      'Harcı elinizle en az 5-8 dakika, macun kıvamına gelip elinize yapışmaya başlayana kadar yoğurun. Bu uzun yoğurma, etin proteinlerini birbirine bağlar ve köftenin pişerken dağılmasını önler. Sonra üzerini örtüp buzdolabında en az 20-30 dakika dinlendirin; soğuk ve dinlenmiş harç hem kolay şekil alır hem sağlam durur.',
      'Harçtan ceviz büyüklüğünde parçalar koparın. Avucunuzda önce pürüzsüz bir top yapın, sonra iki avuç arasında hafifçe bastırıp uzatarak 6-7 cm\'lik parmak köfte şekli verin. Elinizi hafif ıslatırsanız harç yapışmaz.',
      'Geniş tavada az yağı yüksek ateşte kızdırın. Köfteleri koyup her tarafı kahverengi bir kabuk bağlayana kadar 3-4 dakika mühürleyin — burada amaç köfteyi pişirmek değil, dışını kızartıp suyunu içinde kilitlemek; içi fırında pişecek. Mühürlenenleri fırın kabına dizin.',
      'Patatesleri soyup kalın elma dilimleri halinde doğrayın; aynı tavada, köftelerden kalan lezzetli yağda hafifçe kızartıp köftelerin arasına dizin (ön kızartma, patateslerin fırında yumuşayıp dağılmasını önler). Domates dilimlerini ve sivri biberleri de aralara yerleştirin.',
      'Salçayı 1,5 su bardağı sıcak suda pürüzsüzce ezip tuz ekleyin ve bu sosu kabın üzerine eşitçe gezdirin. Sos, köfte ve patatesin yarısına gelmeli — İzmir köftesi hafif sulu, sosuyla sevilen bir yemektir.',
      'Önceden ısıtılmış 190 derece fırında, patatesler çatalla delindiğinde yumuşak olana ve üzeri kızarana kadar 25-30 dakika pişirin. Sıcak sıcak, sosuna ekmek banarak servis edin.',
    ],
  },
  {
    isim: 'Tas Kebabı', mutfak: M, kategori: 'Et Yemekleri', sure: 75, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '500 g'],
      ['Soğan', '2 adet'],
      ['Sarımsak', '2 diş'],
      ['Patates', '2 adet'],
      ['Havuç', '1 adet'],
      ['Dolmalık Biber', '1 adet'],
      ['Salça', '1,5 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Kalın tabanlı bir tencereyi orta-yüksek ateşte iyice ısıtıp tereyağını eritin. Etleri tek kat halinde ekleyin — koyar koymaz güçlü bir cızırtı duymalısınız. Bu ses, etin mühürlendiğinin işaretidir; tava yeterince kızmamışsa et su salıp haşlanır ve o kavrulmuş lezzet oluşmaz. Etleri kalabalık koymayın, gerekirse iki partide mühürleyin.',
      'Et önce mutlaka su salar; panik yapmayın, bu normaldir. Karıştırarak bu suyun tamamen çekilmesini bekleyin (10-15 dakika sürebilir). Su çekildikten sonra etler kendi yağında hafifçe kızarmaya başlar — asıl lezzet burada oluşur. Suyu çekilmeden ve et renk almadan diğer malzemeleri eklemeyin.',
      'Yemeklik (orta boy) doğranmış soğanı ve ince kıyılmış sarımsağı ekleyip 5 dakika, soğanlar yumuşayıp şeffaflaşana kadar etle birlikte kavurun.',
      'Salçayı ekleyip 2 dakika, ham kokusu geçip rengi koyulaşana kadar karıştırın. Salçayı yağda kavurmak, tas kebabına o koyu kırmızı rengi ve dolgun tadı verir.',
      'İri küp doğranmış patates, kalın halka havuç ve iri doğranmış biberi ekleyip 2-3 dakika çevirin, sebzeler yağla tanışsın.',
      'Etlerin üzerini bir parmak geçecek kadar SICAK su ekleyin (soğuk su pişmeyi durdurur ve eti sertleştirir). Kaynayınca kapağı kapatıp ateşi kısın ve et çatalla dağılacak kadar yumuşayana dek 45 dakika ağır ağır pişirin. Sabır bu yemeğin sırrı — düşük ateşte uzun pişen et lokum gibi olur.',
      'Son 10 dakikada tuz ve karabiberi ekleyin (tuzu erken atmak eti sertleştirebilir). Sos koyu ve azalmış, et parçaları parlak olmalı. Yanında sade pirinç pilavıyla servis edin.',
    ],
  },
  {
    isim: 'Etli Kuru Fasulye', mutfak: M, kategori: 'Et Yemekleri', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Kuru Fasulye', '2 su bardağı (350 g)'],
      ['Kuşbaşı Et', '300 g'],
      ['Soğan', '1 adet büyük'],
      ['Salça', '2 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Kuru fasulyeyi bir gece önceden, hacminin en az iki katı bol suda ıslatın. Bu ıslatma süresi hem pişme süresini yarıya indirir hem de fasulyenin gaz yapan şekerlerini suya bırakıp sindirimi kolaylaştırır. Ertesi gün ıslatma suyunu MUTLAKA dökün, taze suyla yarı yumuşayana kadar 30 dakika haşlayıp süzün. Vaktiniz yoksa hazır haşlanmış fasulye de olur.',
      'Kalın tabanlı tencerede tereyağını eritip etleri ekleyin. Önce saldıkları suyu tamamen çekene, sonra hafifçe kızarana kadar orta ateşte kavurun — bu kavurma etin lezzetini yemeğin geneline yayar.',
      'Yemeklik doğranmış soğanı ekleyip 5 dakika, yumuşayıp şeffaflaşana kadar kavurun.',
      'Salçayı ekleyip 2 dakika, ham kokusu geçene kadar kavurun. İsterseniz bu aşamada bir tutam da tereyağı ekleyip salçayı iyice açabilirsiniz.',
      'Yarı haşlanmış fasulyeleri ekleyip 2 dakika baharatla çevirin, sonra 3 su bardağı SICAK su ekleyin. Suyun sıcak olması pişmeyi kesintisiz sürdürür.',
      'Kaynayınca kapağı kapatıp ateşi kısın ve fasulyeler avuçta ezilecek kadar yumuşayana, suyu hafif koyulaşıp yağı üzerine çıkana kadar 40-50 dakika ağır ağır pişirin. Ara ara kontrol edin; su fazla çekilirse azar azar sıcak su ekleyin. Fasulyenin tanesinin dağılmadan yumuşaması, doğru pişmenin işaretidir.',
      'Son 10 dakikada tuz ve pul biberi ekleyin (tuz baştan atılırsa fasulyenin kabuğu sertleşip geç pişer). Pirinç pilavı, turşu ve soğanla — klasik üçlüyle — servis edin. Bir gün beklediğinde daha da lezzetlenir.',
    ],
  },
  {
    isim: 'Orman Kebabı', mutfak: M, kategori: 'Et Yemekleri', sure: 70, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '500 g'],
      ['Kuru Soğan (Arpacık)', '10 adet'],
      ['Havuç', '2 adet'],
      ['Patates', '2 adet'],
      ['Bezelye', '1 su bardağı (150 g)'],
      ['Salça', '1 yemek kaşığı'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Kekik', '1 çay kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Tencerede zeytinyağını ısıtıp etleri yüksek ateşte, her tarafı renk alana kadar mühürleyin.',
      'Etler suyunu salıp çekince soyulmuş arpacık soğanları bütün halde ekleyin, 3-4 dakika çevirin.',
      'Havucu kalın halkalar, patatesi iri küpler halinde doğrayıp ekleyin.',
      'Salçayı ekleyip karıştırın; bezelye, kekik, tuz ve karabiberi ilave edin.',
      '2 su bardağı sıcak su ekleyip kapağı kapatın.',
      'Kısık ateşte, et ve sebzeler yumuşayana kadar 45 dakika pişirin. Sulu bir kebap olacak; ekmekle içi bandıra bandıra yenir.',
    ],
  },
  {
    isim: 'Hünkar Beğendi', mutfak: M, kategori: 'Et Yemekleri', sure: 80, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '500 g'],
      ['Patlıcan', '4 adet büyük'],
      ['Soğan', '1 adet'],
      ['Salça', '1,5 yemek kaşığı'],
      ['Un', '2 yemek kaşığı'],
      ['Süt', '1,5 su bardağı (300 ml)'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Kaşar Peyniri', '1 su bardağı rendelenmiş (80 g)'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Önce et: 1 kaşık tereyağında etleri suyunu çekene kadar kavurun; soğanı ekleyip yumuşatın, salçayı ekleyip 2 dakika pişirin. Üzerini geçecek kadar sıcak su ekleyip kısık ateşte 45 dakika, et yumuşayana kadar pişirin.',
      'Patlıcanları ocakta (ızgara teli üstünde) ya da 220 derece fırında, kabukları kömürleşene kadar her tarafını çevirerek közleyin. Közlenmiş koku beğendinin imzasıdır.',
      'Közlenen patlıcanları biraz soğutup kabuklarını soyun; içini bıçakla iyice kıyın. Kararmaması için üzerine yarım limon sıkabilirsiniz.',
      'Beğendi sosu: tencerede 2 kaşık tereyağını eritin, unu ekleyip 2 dakika kavurun. Sütü azar azar ekleyip çırpın; pürüzsüz koyu bir sos olsun.',
      'Kıyılmış patlıcanı sosa ekleyip 3-4 dakika karıştırarak pişirin. Rendelenmiş kaşarı ekleyin, eriyince ocağı kapatın. Tuzunu ayarlayın.',
      'Servis: tabağa önce beğendiyi yayın, ortasına etli harcı yerleştirin. Osmanlı saray mutfağından sofranıza!',
    ],
  },
  {
    isim: 'Etli Biber Dolması', mutfak: M, kategori: 'Et Yemekleri', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Dolmalık Biber', '10 adet'],
      ['Kıyma', '300 g'],
      ['Pirinç', 'yarım su bardağı (90 g)'],
      ['Soğan', '1 adet'],
      ['Domates', '2 adet'],
      ['Salça', '1,5 yemek kaşığı'],
      ['Maydanoz', 'yarım demet'],
      ['Zeytinyağı', '2 yemek kaşığı'],
      ['Yoğurt', 'servis için'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Dolmalık biberleri seçerken kısa, tıknaz ve düz tabanlı olanları tercih edin — bunlar tencerede dik durur. Sap kısmını bıçakla daire çizerek şapka gibi kesin ama koparıp atmayın; bu şapkalar sonra kapak olacak. İçindeki çekirdek ve beyaz zarları parmağınızla ya da kaşık sapıyla temizleyin, sonra ters çevirip vurarak son çekirdekleri de dökün.',
      'Harç: kıyma, iyice yıkanıp süzülmüş pirinç, rendelenmiş soğan (suyuyla birlikte), 1 kaşık salça, ince kıyılmış maydanoz, 1 domatesin rendesi, zeytinyağı, tuz ve karabiberi geniş bir kapta elinizle 3-4 dakika, malzemeler birbirine iyice yedirilene kadar yoğurun. İyi yoğrulmuş harç pişerken dağılmaz.',
      'Harcı biberlere kaşıkla doldurun ama tepeleme değil, dörtte üçüne kadar. Pirinç pişerken suyu emip iki katına şişer; ağzına kadar doldurursanız biber patlar ya da içi çiğ kalır. Doldururken hafifçe bastırıp boşluk bırakmayın.',
      'Her biberin ağzını kestiğiniz şapkasıyla veya bir domates dilimiyle kapatın. Biberleri tencereye ağızları yukarı bakacak şekilde, dik ve birbirine yaslanarak sıkıca dizin — sıkı diziliş, pişerken devrilip harcın dökülmesini önler.',
      'Kalan yarım kaşık salçayı 2 su bardağı sıcak suda ezip tuz ekleyin ve tencerenin kenarından (biberlerin üzerine değil) dökün; su biberlerin yarısına kadar gelmeli. Üzerine ters bir tabak kapatırsanız biberler sabit kalır.',
      'Kapağı kapatıp önce kaynatın, sonra ateşi kısıp pirinçler tamamen yumuşayana ve su neredeyse çekilene kadar 40-45 dakika pişirin. Bir biberin harcından bir pirinç tanesi alıp ezerek kontrol edin. Ocaktan alıp 10 dakika dinlendirin; ılıkken sarımsaklı yoğurtla servis edin — etli dolmanın yanında yoğurt şarttır.',
    ],
  },
  {
    isim: 'Lahana Sarması', mutfak: M, kategori: 'Et Yemekleri', sure: 80, tur: 'yemek',
    malzemeler: [
      ['Lahana', '1 adet orta boy'],
      ['Kıyma', '300 g'],
      ['Pirinç', 'yarım su bardağı (90 g)'],
      ['Soğan', '1 adet'],
      ['Salça', '2 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Lahananın dip kısmındaki sert göbeği, bıçağı koni şeklinde daldırıp oyarak çıkarın — yaprakların gövdeye bağlandığı yer burasıdır, çıkınca yapraklar kolayca ayrılır. Büyük bir tencerede tuzlu su kaynatın, lahanayı göbek boşluğu aşağı bakacak şekilde daldırın. 4-5 dakika sonra dıştaki yapraklar yumuşayıp kendiliğinden gevşer; maşayla teker teker alın. İç yapraklar için lahanayı biraz daha haşlamaya devam edin.',
      'Harç: kıyma, iyice yıkanmış pirinç, rendelenmiş soğan, 1 kaşık salça, pul biber, karabiber ve tuzu geniş bir kapta elinizle iyice yoğurun. Karadeniz usulünde bu harca bazen mısır unu da katılır.',
      'Haşlanmış yaprakların ortasındaki kalın, sert damarı bıçağı yatırarak inceltin (kalın damar sarmayı zorlaştırır ve dişe gelir). Büyük yaprakları avuç içi büyüklüğünde parçalara bölün; küçük yaprakları olduğu gibi kullanın.',
      'Her yaprak parçasının geniş kenarına bir tatlı kaşığı harç koyun, harcı parmakla ince bir çubuk şekline getirin. Önce iki yanı harcın üzerine içe katlayın, sonra alttan başlayarak sıkıca, sigara gibi sarın. Sıkı sarmak önemli — gevşek sarma pişerken açılır ve harcı dağıtır. Ama çok da sıkmayın, pirinç şişecek yer bulamaz.',
      'Tencerenin dibine, dağılan veya artan yapraklardan bir kat serin (bu, sarmaların dibe yapışıp yanmasını önler). Sarmaları kapanma yerleri alta gelecek şekilde, sıra sıra ve sıkı sıkı dizin. Üzerine ters düz bir tabak kapatın; tabağın ağırlığı sarmaları sabit tutar, kaynarken oynayıp açılmalarını engeller.',
      'Kalan salçayı 2,5 su bardağı sıcak suda ezip tuz ekleyin, tabağın kenarından dökün; su sarmaların üzerini az geçmeli. Kapağı kapatıp kaynatın, sonra ateşi kısıp pirinçler yumuşayana ve su çekilene kadar 50 dakika pişirin. Ocaktan alıp 15 dakika dinlendirin — dinlenen sarma daha kolay alınır. Sarımsaklı yoğurtla servis edin.',
    ],
  },
  {
    isim: 'Patlıcan Musakka', mutfak: M, kategori: 'Et Yemekleri', sure: 55, tur: 'yemek',
    malzemeler: [
      ['Patlıcan', '4 adet'],
      ['Kıyma', '300 g'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['Domates', '2 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Ayçiçek Yağı', 'kızartma için'],
      ['Maydanoz', 'birkaç dal'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Patlıcanları alacalı soyup kalın dilimler halinde kesin; tuzlu suda 15 dakika bekletip kurulayın.',
      'Dilimleri kızgın yağda iki taraflı hafifçe kızartın ve kağıt havluya alın. Daha hafif olsun isterseniz fırında da pişirebilirsiniz.',
      'Kıymayı kuru tavada suyunu çekene kadar pişirin; doğranmış soğan ve sarımsağı ekleyip 5 dakika kavurun.',
      'Salçayı ve rendelenmiş 1 domatesi ekleyin; tuz ve karabiberle 5 dakika pişirin.',
      'Fırın kabına bir kat patlıcan, üzerine kıymalı harç yayın. Kalan domatesi dilimleyip üzerine dizin.',
      'Yarım su bardağı sıcak su ekleyip 180 derece fırında 20 dakika pişirin. Kıyılmış maydanoz serperek servis edin.',
    ],
  },
  {
    isim: 'Kuzu İncik Haşlama', mutfak: M, kategori: 'Et Yemekleri', sure: 120, tur: 'yemek',
    malzemeler: [
      ['Kuzu İncik', '4 adet'],
      ['Soğan', '2 adet'],
      ['Havuç', '2 adet'],
      ['Patates', '3 adet'],
      ['Defne Yaprağı', '2 adet'],
      ['Tuz', '2 tatlı kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
    ],
    adimlar: [
      'İncikleri geniş bir tencereye yerleştirin, üzerlerini 3 parmak geçecek kadar soğuk su ekleyin.',
      'Kaynamaya başlayınca yüzeyde gri bir köpük birikecek; bu köpüğü kaşıkla alın. Köpüğü almak suyun berrak kalmasını sağlar.',
      'Soğanları dörde bölüp defne yapraklarıyla birlikte ekleyin. Ocağı iyice kısın ve kapağı aralık bırakıp 1,5 saat pişirin.',
      'Havucu iri halkalar, patatesi dörde bölünmüş şekilde ekleyin; tuzu da şimdi atın (baştan atılan tuz eti sertleştirir).',
      'Sebzeler yumuşayana kadar 25-30 dakika daha pişirin.',
      'Et kemikten kendiliğinden ayrılıyorsa hazırdır. Derin tabaklara bir incik, yanına sebzeler ve bolca haşlama suyu koyup karabiber serperek servis edin.',
    ],
  },
  {
    isim: 'Dana Rosto', mutfak: M, kategori: 'Et Yemekleri', sure: 100, tur: 'yemek',
    malzemeler: [
      ['Dana Rosto Eti', '800 g (tek parça)'],
      ['Soğan', '2 adet'],
      ['Havuç', '2 adet'],
      ['Sarımsak', '4 diş'],
      ['Salça', '1 yemek kaşığı'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Tuz', '2 tatlı kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
    ],
    adimlar: [
      'Eti oda sıcaklığında yarım saat bekletin; buzdolabından çıkan et tencereye girince sertleşir.',
      'Geniş tencerede zeytinyağını iyice kızdırın. Eti tek parça halinde koyun ve her yüzünü 2-3 dakika, kahverengileşene kadar mühürleyin. Bu kabuk, etin suyunu içinde hapseder.',
      'Eti tabağa alın. Aynı tencerede iri doğranmış soğan, havuç ve sarımsağı 5 dakika kavurun.',
      'Salçayı ekleyip karıştırın; eti sebzelerin üzerine oturtun.',
      '3 su bardağı sıcak su ekleyin, kapağı sıkıca kapatın ve kısık ateşte 1,5 saat pişirin. Yarım saatte bir eti çevirin.',
      'Eti tahtaya alıp 10 dakika dinlendirin — dinlenmeden keserseniz suyu akar. Sonra ince dilimler halinde kesin.',
      'Tenceredeki sebzeli sosu blenderdan geçirin; dilimlerin üzerine gezdirip patates püresiyle servis edin.',
    ],
  },
  {
    isim: 'Sulu Köfte', mutfak: M, kategori: 'Et Yemekleri', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '400 g'],
      ['İnce Bulgur', 'yarım su bardağı (80 g)'],
      ['Soğan', '1 adet'],
      ['Patates', '2 adet'],
      ['Salça', '1,5 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Maydanoz', 'birkaç dal'],
      ['Kimyon', '1 çay kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Kıyma, bulgur, rendelenmiş soğan, kimyon, tuz ve karabiberi 5 dakika yoğurun.',
      'Harçtan fındık büyüklüğünde parçalar koparıp avucunuzda minik toplar yapın. Küçük olmaları önemli — kaşığa iki üç tane gelecek.',
      'Tencerede tereyağını eritip salçayı 1 dakika kavurun; 5 su bardağı sıcak su ekleyip kaynatın.',
      'Patatesleri küçük küpler halinde doğrayıp kaynayan suya ekleyin, 5 dakika pişirin.',
      'Köfteleri tek tek suya bırakın. Karıştırmak için kaşık kullanmayın, tencereyi tutup hafifçe sallayın — köfteler dağılmasın.',
      'Kısık ateşte 25 dakika pişirin. Kıyılmış maydanoz serpip sıcacık servis edin.',
    ],
  },
  {
    isim: 'Adana Kebap (Tava Usulü)', mutfak: M, kategori: 'Et Yemekleri', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '500 g (yağlı, tercihen kuzu)'],
      ['Kırmızı Biber', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['Pul Biber', '1 yemek kaşığı'],
      ['İsot Biber', '1 tatlı kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Lavaş', '4 adet'],
      ['Domates', '2 adet (közleme için)'],
      ['Sivri Biber', '4 adet (közleme için)'],
      ['Sumak', 'soğan salatası için'],
      ['Soğan', '1 adet'],
    ],
    adimlar: [
      'Kırmızı biberi ve sarımsağı çok ince kıyın (robotta çekebilirsiniz, ama sulandırmayın).',
      'Kıymayı geniş kaba alın; biber, sarımsak, pul biber, isot ve tuzu ekleyin. En az 10 dakika, harç macun kıvamına gelene kadar yoğurun. Adana harcı ne kadar yoğrulursa şişte o kadar iyi tutar.',
      'Harcı 30 dakika buzdolabında dinlendirin — soğuk harç şekil almayı kolaylaştırır.',
      'Harcı 4 parçaya bölün. Elinizi ıslatıp her parçayı uzun, yassı kebap şekline getirin (şişiniz varsa şişe sıvayın).',
      'Döküm tavayı yağsız olarak iyice kızdırın. Kebapları koyup her yüzünü 3-4 dakika, güzelce kararıp pişene kadar çevirin. Domates ve biberleri de kenarda közleyin.',
      'Soğanı piyazlık doğrayıp sumak ve bir tutam tuzla ovun.',
      'Lavaşı tavada ısıtıp kebabın altına serin — etin suyunu çeksin. Kebap, közlenmiş sebzeler ve sumaklı soğanla servis edin.',
    ],
  },
  {
    isim: 'İskender', mutfak: M, kategori: 'Et Yemekleri', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '400 g (ince dilimlenmiş)'],
      ['Lavaş', '3 adet (veya 2 pide)'],
      ['Domates', '3 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Tereyağı', '4 yemek kaşığı (80 g)'],
      ['Yoğurt', '1,5 su bardağı (300 g)'],
      ['Sivri Biber', '2 adet'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Etleri mümkün olduğunca ince dilimleyin (yarı donmuş et daha kolay dilimlenir).',
      'Domates sosu için: 2 domatesi rendeleyin. Küçük tencerede 1 kaşık tereyağını eritin, salçayı ekleyip 1 dakika kavurun; rendelenmiş domatesi ekleyip tuzla 10 dakika, koyulaşana kadar pişirin.',
      'Etleri geniş tavada 1 kaşık tereyağıyla yüksek ateşte, suyunu çekip hafif kızarana kadar 6-8 dakika soteleyin; tuz ve karabiber ekleyin.',
      'Lavaşları küçük kareler halinde kesin ve kuru tavada ya da fırında hafifçe kızartın.',
      'Tabağın tabanına kızarmış lavaşları döşeyin; üzerine domates sosunun yarısını gezdirin ki yumuşasınlar.',
      'Etleri lavaşın üzerine yayın, kalan sosu üzerine dökün. Bir kenara bolca yoğurt koyun.',
      'Son dokunuş: kalan 2 kaşık tereyağını küçük tavada köpürene kadar kızdırıp cazırdaya cazırdaya tabağın üzerine gezdirin. Közlenmiş biberle servis edin.',
    ],
  },
  {
    isim: 'Ali Nazik', mutfak: M, kategori: 'Et Yemekleri', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Patlıcan', '4 adet büyük'],
      ['Kuşbaşı Et', '400 g (veya kıyma)'],
      ['Yoğurt', '1,5 su bardağı (300 g)'],
      ['Sarımsak', '2 diş'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Salça', '1 yemek kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Patlıcanları ocak alevinde ya da 220 derece fırında, kabukları tamamen kömürleşene kadar döndüre döndüre közleyin.',
      'Közlenen patlıcanları poşete koyup 5 dakika terletin — kabukları kolayca soyulur. Soyup içlerini bıçakla kıyın.',
      'Kıyılmış patlıcanı tavada 1 kaşık tereyağıyla 3-4 dakika soteleyin; suyu uçsun.',
      'Yoğurdu ezilmiş sarımsak ve bir tutam tuzla karıştırıp ılık patlıcana ekleyin, karıştırın. Taban hazır: sarımsaklı, yoğurtlu köz patlıcan.',
      'Etleri 1 kaşık tereyağında suyunu çekip kızarana kadar soteleyin; salçayı ekleyip 2 dakika daha pişirin, tuz-karabiber ekleyin.',
      'Tabağa önce patlıcanlı tabanı yayın, ortasına etleri yerleştirin. Üzerine pul biberli kızgın tereyağı gezdirerek servis edin.',
    ],
  },
  {
    isim: 'Et Kavurma', mutfak: M, kategori: 'Et Yemekleri', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '600 g'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Soğan', '1 adet'],
      ['Sivri Biber', '2 adet'],
      ['Kekik', '1 çay kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
    ],
    adimlar: [
      'Etleri küçük kuşbaşı doğrayın ve oda sıcaklığına gelmesini bekleyin.',
      'Tencereye etleri yağsız koyun, orta ateşte kapağı kapalı pişirmeye başlayın. Et önce suyunu salacak.',
      'Ara ara karıştırarak, etin kendi suyunda yumuşamasını bekleyin; su çekilene kadar 30-40 dakika sürer. Su çekilmeden yağ eklemeyin.',
      'Su tamamen çekilince tereyağını ekleyin ve ateşi biraz açın.',
      'İnce doğranmış soğan ve biberi ekleyip etlerle birlikte 8-10 dakika, etler hafif kızarana kadar kavurun.',
      'Tuz, karabiber ve kekiği ekleyip 2 dakika daha çevirin. Sade pilavla ya da sıcak ekmekle harikadır.',
    ],
  },
  {
    isim: 'İçli Köfte (Haşlama)', mutfak: M, kategori: 'Et Yemekleri', sure: 90, tur: 'yemek',
    malzemeler: [
      ['İnce Bulgur', '3 su bardağı (480 g)'],
      ['İrmik', '2 yemek kaşığı'],
      ['Kıyma', '300 g (iç için)'],
      ['Soğan', '2 adet'],
      ['Ceviz', 'yarım su bardağı çekilmiş (50 g)'],
      ['Maydanoz', 'yarım demet'],
      ['Salça', '1 yemek kaşığı'],
      ['Tereyağı', '1 yemek kaşığı (20 g)'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Kimyon', '1 çay kaşığı'],
      ['Tuz', '2 tatlı kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
    ],
    adimlar: [
      'İç harç: kıymayı tavada suyunu çekene kadar pişirin. Doğranmış 1 soğanı ve tereyağını ekleyip kavurun; salça, ceviz, kıyılmış maydanoz, kimyon, tuz ve karabiberi ekleyip 3 dakika pişirin. Soğumaya bırakın.',
      'Dış hamur: bulguru kaba koyup üzerine 1,5 su bardağı kaynar su dökün, karıştırıp 20 dakika kapalı bekletin.',
      'Şişen bulgura irmik, 1 rendelenmiş soğan, 1 tatlı kaşığı tuz ve pul biber ekleyin. Elinizi ıslata ıslata en az 15 dakika, hamur gibi yoğurulabilir olana kadar yoğurun.',
      'Avucunuza yumurta büyüklüğünde hamur alın, yuvarlayın. Başparmağınızla ortasına derin bir çukur açın ve çukuru döndüre döndüre inceltin.',
      'İçine bir kaşık soğumuş harç koyun; ağzını nazikçe kapatıp iki ucu hafif sivri mekik şekli verin. Çatlak olursa ıslak elle sıvayın.',
      'Kaynayan tuzlu suda köfteleri 8-10 dakika, suyun yüzüne çıkana kadar haşlayın. Delikli kepçeyle alıp sıcak servis edin.',
    ],
  },
  {
    isim: 'Kadınbudu Köfte', mutfak: M, kategori: 'Et Yemekleri', sure: 55, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '400 g'],
      ['Pirinç', 'yarım su bardağı (90 g)'],
      ['Soğan', '1 adet'],
      ['Yumurta', '3 adet (2 tanesi bulamak için)'],
      ['Un', '3 yemek kaşığı'],
      ['Maydanoz', 'birkaç dal'],
      ['Ayçiçek Yağı', 'kızartma için'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Pirinci haşlayıp süzün ve soğumaya bırakın.',
      'Kıymanın yarısını tavada, doğranmış soğanla birlikte suyunu çekene kadar pişirip soğutun. Diğer yarısı çiğ kalacak — bu ikili karışım kadınbudunun sırrıdır.',
      'Çiğ kıyma, pişmiş kıyma, haşlanmış pirinç, 1 yumurta, kıyılmış maydanoz, tuz ve karabiberi iyice yoğurun.',
      'Harçtan iri parçalar alıp oval, yassı köfteler yapın.',
      'Bir kasede kalan 2 yumurtayı çırpın; başka bir tabağa unu koyun. Köfteleri önce una, sonra yumurtaya bulayın.',
      'Kızgın bol yağda, iki tarafı altın sarısı olana kadar kızartın. Kağıt havluda dinlendirip püre veya pilavla servis edin.',
    ],
  },
  {
    isim: 'Hasanpaşa Köfte', mutfak: M, kategori: 'Et Yemekleri', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '500 g'],
      ['Soğan', '1 adet'],
      ['Galeta Unu', '2 yemek kaşığı'],
      ['Yumurta', '1 adet'],
      ['Patates', '4 adet (püre için)'],
      ['Süt', 'yarım su bardağı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Kaşar Peyniri', '1 su bardağı rendelenmiş (80 g)'],
      ['Salça', '1 yemek kaşığı'],
      ['Kimyon', '1 çay kaşığı'],
      ['Tuz', '2 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Köfte harcı: kıyma, rendelenmiş soğan, galeta unu, yumurta, kimyon, tuz ve karabiberi 5 dakika yoğurun.',
      'Harçtan iri toplar yapıp fırın kabına dizin; her topun ortasına parmağınızla veya kaşığın arkasıyla çukur açın — küçük birer çanak gibi olacaklar.',
      '200 derece fırında 15 dakika ön pişirme yapın.',
      'Püre için: patatesleri haşlayıp ezin; sıcakken süt, 1 kaşık tereyağı ve tuz ekleyip pürüzsüzleşene kadar karıştırın.',
      'Fırından çıkan köftelerin çukurlarına pürelerden bolca doldurun, üzerlerine rendelenmiş kaşar serpin.',
      'Salçayı 1 su bardağı sıcak suda ezip kabın kenarlarından dökün. 190 derece fırında, peynirler kızarana kadar 15 dakika daha pişirin.',
    ],
  },
  {
    isim: 'Kuru Köfte', mutfak: M, kategori: 'Et Yemekleri', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '500 g'],
      ['Soğan', '1 adet'],
      ['Ekmek', '2 dilim bayat (içi)'],
      ['Yumurta', '1 adet'],
      ['Maydanoz', 'yarım demet'],
      ['Kimyon', '1 tatlı kaşığı'],
      ['Ayçiçek Yağı', 'kızartma için'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
    ],
    adimlar: [
      'Bayat ekmeğin kabuklarını ayırın, içini suda ıslatıp sıkın ve ufalayın.',
      'Kıyma, rendelenmiş soğan, ıslatılmış ekmek içi, yumurta, kıyılmış maydanoz ve baharatları derin bir kapta buluşturun.',
      'Harcı en az 5 dakika, hamur gibi olana kadar yoğurun. Üzerini kapatıp buzdolabında 30 dakika dinlendirin — bu köftenin dağılmamasını sağlar.',
      'Elinizi hafif yağlayıp ceviz büyüklüğünde parçalar koparın; yuvarlayıp hafifçe bastırarak yassılaştırın.',
      'Tavada yağı orta ateşte kızdırın. Köftelerin her yüzünü 3-4 dakika, güzelce kızarana kadar pişirin; sık çevirmeyin, kabuk tutmasına izin verin.',
      'Kağıt havluya alıp fazla yağını verdirin. Piyaz ile ikilisi efsanedir!',
    ],
  },

  // ─── TAVUK YEMEKLERİ ───
  {
    isim: 'Tavuk Sote', mutfak: M, kategori: 'Tavuk Yemekleri', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Tavuk Göğsü', '500 g'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['Sivri Biber', '2 adet'],
      ['Dolmalık Biber', '1 adet'],
      ['Domates', '2 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Ayçiçek Yağı', '3 yemek kaşığı'],
      ['Kekik', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Tavukları küçük kuşbaşı doğrayın ve kağıt havluyla kurulayın — kuru tavuk daha güzel kızarır.',
      'Geniş tavada yağı iyice kızdırın. Tavukları ekleyip yüksek ateşte, suyunu salıp çekene ve hafif kızarana kadar 8-10 dakika soteleyin.',
      'Doğranmış soğanı ekleyip 3 dakika, sonra biberleri ekleyip 3 dakika daha pişirin.',
      'Ezilmiş sarımsak ve salçayı ekleyin, 1 dakika karıştırın.',
      'Küp doğranmış domatesleri, tuz, karabiber ve kekiği ekleyin.',
      'Kapağı kapatıp kısık ateşte 15 dakika, domatesler eriyip sos kıvamı olana kadar pişirin. Pilavla sıcak servis edin.',
    ],
  },
  {
    isim: 'Fırında Bütün Tavuk', mutfak: M, kategori: 'Tavuk Yemekleri', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Bütün Tavuk', '1 adet (1,5 kg)'],
      ['Patates', '4 adet'],
      ['Havuç', '2 adet'],
      ['Sarımsak', '4 diş'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Kekik', '1 tatlı kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '2 tatlı kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
    ],
    adimlar: [
      'Tavuğu yıkayıp kağıt havluyla iyice kurulayın; kuru deri çıtır kızarır.',
      'Küçük bir kasede zeytinyağı, ezilmiş sarımsak, kekik, pul biber, tuz ve karabiberi karıştırıp sos yapın.',
      'Sosu tavuğun her yerine, elinizle derinin altına da ulaşarak iyice yedirin. Yarım saat beklerse daha lezzetli olur.',
      'Patatesleri ve havuçları iri parçalar halinde doğrayıp tepsinin tabanına yayın; kalan sosla harmanlayın.',
      'Tavuğu sebzelerin ortasına göğsü yukarı bakacak şekilde yerleştirin. Üzerini alüminyum folyoyla örtün.',
      '190 derece önceden ısıtılmış fırında 1 saat pişirin; sonra folyoyu açıp 20-25 dakika, derisi kızarana kadar pişirmeye devam edin.',
      'Fırından çıkarıp 10 dakika dinlendirin, sonra kesip sebzelerle servis edin.',
    ],
  },
  {
    isim: 'Tavuk Şiş', mutfak: M, kategori: 'Tavuk Yemekleri', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Tavuk Göğsü', '600 g'],
      ['Yoğurt', '3 yemek kaşığı'],
      ['Salça', '1 yemek kaşığı'],
      ['Sarımsak', '2 diş'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Dolmalık Biber', '2 adet'],
      ['Domates', '2 adet küçük'],
      ['Kekik', '1 çay kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Tavukları 3 cm\'lik küpler halinde doğrayın — çok küçük olursa kurur, çok büyük olursa geç pişer.',
      'Marine sosu: yoğurt, salça, ezilmiş sarımsak, zeytinyağı, kekik, pul biber ve tuzu karıştırın.',
      'Tavukları sosla iyice harmanlayıp üzerini kapatın; buzdolabında en az 2 saat (mümkünse bir gece) marine edin. Bu bekleme tavukları yumuşacık yapar.',
      'Tahta şiş kullanacaksanız şişleri 20 dakika suda bekletin — yanmazlar.',
      'Tavukları, aralarına biber ve domates parçaları koyarak şişlere dizin.',
      'Izgara ya da döküm tavayı iyice kızdırın; şişleri her yüzü 3-4 dakika, toplam 12-15 dakika pişirin. En kalın parçayı kesin: içi beyazsa hazırdır.',
      'Lavaş ve sumaklı soğanla servis edin.',
    ],
  },
  {
    isim: 'Kremalı Mantarlı Tavuk', mutfak: M, kategori: 'Tavuk Yemekleri', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Tavuk Göğsü', '500 g'],
      ['Mantar', '300 g'],
      ['Krema', '1 paket (200 ml)'],
      ['Sarımsak', '2 diş'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Kaşar Peyniri', 'yarım su bardağı rendelenmiş (40 g)'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Tavukları ince baget şeklinde dilimleyin. Mantarları silip dörde bölün.',
      'Tavada 1 kaşık tereyağını eritin; tavukları yüksek ateşte, iki tarafı kızarana kadar 6-7 dakika pişirip tabağa alın.',
      'Aynı tavaya kalan tereyağını ve mantarları ekleyin. Mantarlar su salıp çekene kadar 8 dakika pişirin.',
      'Ezilmiş sarımsağı ekleyip 1 dakika kokusunu çıkarın.',
      'Tavukları tavaya geri alın; kremayı ekleyip karıştırın.',
      'Kısık ateşte 5 dakika, sos hafif koyulaşana kadar pişirin. Kaşarı ekleyip eriyince ocağı kapatın. Makarna veya pilavla servis edin.',
    ],
  },
  {
    isim: 'Tavuk Kapama', mutfak: M, kategori: 'Tavuk Yemekleri', sure: 70, tur: 'yemek',
    malzemeler: [
      ['Tavuk But', '6 adet'],
      ['Kuru Soğan (Arpacık)', '10 adet'],
      ['Havuç', '2 adet'],
      ['Bezelye', '1 su bardağı (150 g)'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Tencerede zeytinyağını ısıtıp butları her tarafı hafif kızarana kadar 8-10 dakika mühürleyin.',
      'Soyulmuş arpacık soğanları bütün olarak ekleyin.',
      'Havucu kalın halkalar halinde doğrayıp bezelyeyle birlikte ekleyin.',
      '1 su bardağı sıcak su, tuz ve karabiberi ekleyip kapağı sıkıca kapatın.',
      'Kısık ateşte 45 dakika, tavuk kemikten ayrılacak kıvama gelene kadar pişirin. Kapağı mümkün olduğunca az açın — "kapama" adı buradan gelir, buharında pişer.',
      'Pilav üstünde, suyuyla birlikte servis edin.',
    ],
  },
  {
    isim: 'Sebzeli Tavuk Güveç', mutfak: M, kategori: 'Tavuk Yemekleri', sure: 75, tur: 'yemek',
    malzemeler: [
      ['Tavuk Göğsü', '500 g'],
      ['Patlıcan', '1 adet'],
      ['Kabak', '1 adet'],
      ['Patates', '2 adet'],
      ['Sivri Biber', '2 adet'],
      ['Domates', '2 adet'],
      ['Sarımsak', '3 diş'],
      ['Salça', '1 yemek kaşığı'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Kekik', '1 çay kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Tavukları kuşbaşı, tüm sebzeleri iri küpler halinde doğrayın. Patlıcanı tuzlu suda 10 dakika bekletip acısını alın.',
      'Derin bir kapta tavuk, sebzeler, ezilmiş sarımsak, salça, zeytinyağı, kekik ve tuzu elinizle harmanlayın; salça her yere bulaşsın.',
      'Karışımı güveç kabına (yoksa derin fırın kabına) aktarın. Domatesleri dilimleyip en üste kapatın.',
      'Yarım su bardağı sıcak su ekleyin, kapağını (yoksa folyo) kapatın.',
      '200 derece fırında 1 saat pişirin. Son 10 dakika kapağı açıp üzerini hafif kızartın.',
      'Güveç kabıyla sofraya taşıyın — dumanı üstünde servis edin.',
    ],
  },
  {
    isim: 'Izgara Tavuk Pirzola', mutfak: M, kategori: 'Tavuk Yemekleri', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Tavuk But', '6 adet (kemiksiz açılmış)'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Sarımsak', '2 diş'],
      ['Kekik', '1 tatlı kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Roka', '1 demet (servis için)'],
      ['Limon', '1 adet'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Kemiksiz but etlerini et tokmağıyla (yoksa tencere tabanıyla) hafifçe dövüp eşit kalınlığa getirin — eşit kalınlık eşit pişme demek.',
      'Zeytinyağı, ezilmiş sarımsak, kekik ve pul biberi karıştırıp etlere sürün. 20 dakika oda sıcaklığında marine edin.',
      'Izgara tavayı duman çıkacak kadar kızdırın.',
      'Etleri koyun ve ilk yüzü 4-5 dakika, hiç kımıldatmadan pişirin; güzel ızgara izleri oluşsun.',
      'Çevirip diğer yüzü de 4-5 dakika pişirin. Tuzu pişerken ekleyin.',
      'Yıkanmış roka ve limon dilimleriyle servis edin.',
    ],
  },
  {
    isim: 'Tavuklu Pilav', mutfak: M, kategori: 'Tavuk Yemekleri', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Tavuk Göğsü', '400 g'],
      ['Pirinç', '2 su bardağı (360 g)'],
      ['Tel Şehriye', '2 yemek kaşığı'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Tuz', '2 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Tavuğu 5 su bardağı suda, 1 tatlı kaşığı tuzla 20 dakika haşlayın. Tavuğu alıp didikleyin; suyu süzüp kenarda bekletin — pilavı bu suyla pişireceğiz.',
      'Pirinci tuzlu ılık suda 20 dakika bekletip yıkayın ve süzün; nişastası gitsin, pilav tane tane olsun.',
      'Tencerede tereyağını eritip şehriyeleri koyu pembe olana kadar karıştırarak kavurun — yanmasın, acele ettirmeyin.',
      'Pirinci ekleyip 3 dakika, taneler ısınana kadar birlikte kavurun.',
      '3 su bardağı sıcak tavuk suyu ve kalan tuzu ekleyin. Bir kez karıştırıp kapağı kapatın.',
      'Kısık ateşte suyunu çekene kadar (yaklaşık 12 dakika) pişirin. Ocağı kapatıp didiklenmiş tavukları pilavın üzerine yayın; kapağın altına kağıt havlu koyup 15 dakika demlendirin.',
      'Nazikçe karıştırıp servis edin — kabaran buharın kokusu her şeye değer!',
    ],
  },

  // ─── BALIK & DENİZ ÜRÜNLERİ ───
  {
    isim: 'Hamsi Tava', mutfak: M, kategori: 'Balık & Deniz Ürünleri', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Hamsi', '500 g (temizlenmiş)'],
      ['Un', '1 su bardağı (yarısı mısır unu olursa daha çıtır)'],
      ['Ayçiçek Yağı', '1 su bardağı'],
      ['Limon', '1 adet'],
      ['Soğan', '1 adet (servis için)'],
      ['Sumak', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Hamsilerin başını koparıp karnını başparmağınızla açın ve kılçığını kuyruğa doğru çekerek çıkarın (balıkçınıza da temizletebilirsiniz). Yıkayıp süzün.',
      'Hamsileri hafifçe tuzlayın.',
      'Unu geniş bir tabağa koyun. Hamsileri tek tek una bulayın ve fazla ununu silkeleyin.',
      'Tavada yağı iyice kızdırın — bir parça ekmek attığınızda hemen cızırdamalı.',
      'Hamsileri tavaya yan yana, kuyrukları merkeze bakacak şekilde güneş gibi dizin. İlk yüzü 3 dakika kızartın.',
      'Büyük bir tabak yardımıyla hepsini tek seferde çevirin (tabağı tavaya kapatıp ters çevirin, sonra tavaya geri kaydırın). Diğer yüzü de 3 dakika kızartın.',
      'Sumaklı kırmızı soğan ve bol limonla sıcak servis edin.',
    ],
  },
  {
    isim: 'Levrek Buğulama', mutfak: M, kategori: 'Balık & Deniz Ürünleri', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Levrek', '2 adet (fileto, 4 parça)'],
      ['Domates', '2 adet'],
      ['Sivri Biber', '2 adet'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['Limon', '1 adet'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Maydanoz', 'birkaç dal'],
      ['Defne Yaprağı', '1 adet'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Soğanı ince yarım ay, domatesleri yarım halka, biberleri uzunlamasına doğrayın.',
      'Geniş ve sığ bir tencerenin tabanına zeytinyağını gezdirip soğanların yarısını yayın.',
      'Levrek filetolarını derileri alta gelecek şekilde soğanların üzerine yerleştirin; tuz ve karabiber serpin.',
      'Kalan soğan, domates, biber, ezilmiş sarımsak ve defne yaprağını balıkların üzerine dağıtın. Limonun yarısını dilimleyip aralara yerleştirin.',
      'Yarım su bardağı sıcak su ve kalan limonun suyunu ekleyin. Kapağı sıkıca kapatın.',
      'Kısık ateşte 20 dakika pişirin — kapağı açmayın, balık buharda pişsin. Balık çatalla kolayca pul pul ayrılıyorsa hazırdır.',
      'Kıyılmış maydanoz serpip tencereden servis edin.',
    ],
  },
  {
    isim: 'Fırında Somon', mutfak: M, kategori: 'Balık & Deniz Ürünleri', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Somon', '4 dilim fileto (600 g)'],
      ['Limon', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Kekik', '1 çay kaşığı'],
      ['Patates', '2 adet (garnitür için)'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Fırını 200 dereceye ısıtın. Tepsiye pişirme kağıdı serin.',
      'Patatesleri ince dilimleyip tepsiye yayın, üzerine 1 kaşık zeytinyağı ve tuz gezdirin; fırında 15 dakika ön pişirme yapın (somon patatesten hızlı pişer).',
      'Bu arada zeytinyağı, ezilmiş sarımsak, limonun yarısının suyu, kekik, tuz ve karabiberi karıştırıp sos yapın.',
      'Somon dilimlerini patateslerin üzerine yerleştirip sosu fırçayla (yoksa kaşıkla) üzerlerine sürün. Kalan limonu dilimleyip üzerlerine koyun.',
      'Fırında 12-15 dakika pişirin. Somonun rengi tamamen açık pembe olup çatalla katman katman ayrılıyorsa tamamdır — fazla pişirmeyin, kurur.',
      'Roka salatası eşliğinde servis edin.',
    ],
  },
  {
    isim: 'Karides Güveç', mutfak: M, kategori: 'Balık & Deniz Ürünleri', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Karides', '400 g (ayıklanmış)'],
      ['Domates', '3 adet'],
      ['Sivri Biber', '2 adet'],
      ['Sarımsak', '4 diş'],
      ['Mantar', '150 g'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Kaşar Peyniri', '1 su bardağı rendelenmiş (80 g)'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Karidesleri yıkayıp süzün. Domatesleri rendeleyin, biberleri ve mantarları küçük doğrayın, sarımsakları ince kıyın.',
      'Tavada tereyağını eritip sarımsak ve biberi 2 dakika soteleyin.',
      'Mantarları ekleyip suyunu çekene kadar 5 dakika pişirin.',
      'Rendelenmiş domatesi ekleyin; tuz ve pul biberle 8-10 dakika, sos koyulaşana kadar pişirin.',
      'Karidesleri ekleyip sadece 2 dakika çevirin — karides çok çabuk pişer, fazla pişerse lastik gibi olur.',
      'Karışımı küçük güveç kaplarına (yoksa fırın kabına) paylaştırın, üzerlerine kaşar serpin.',
      'Önceden ısıtılmış 220 derece fırında, peynir eriyip kızarana kadar 8-10 dakika pişirin. Ekmekle sıcak sıcak servis edin.',
    ],
  },
];
