// Türk Mutfağı 5. bölüm: reçeller, turşular ve daha fazla klasik tarif.
// Hepsi gramajlı malzeme, derin/özgün anlatım ve yerel fotoğrafla gelir.
import { type SeedTarif } from './seed-tarifler-turk';

const M = 'Türk Mutfağı';

export const TURK_5: SeedTarif[] = [
  // ─── REÇEL & KONSERVE ───
  {
    isim: 'Vişne Reçeli', mutfak: M, kategori: 'Reçel & Konserve', sure: 60, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Vişne', '1 kg (çekirdeksiz)'],
      ['Şeker', '750 g'],
      ['Limon', '0,5 adet'],
    ],
    adimlar: [
      'Vişneleri yıkayıp saplarını ve çekirdeklerini çıkarın. Çekirdek çıkarırken akan suyu dökmeyin, reçele katın — tadın çoğu o sudadır. Vişne ekşiliğiyle dengeli bir meyve olduğu için şeker oranı bilerek yüksek tutulur; az şeker hem tadı bozar hem reçelin bozulmasını hızlandırır.',
      'Vişne ve şekeri geniş, kalın tabanlı bir tencerede KAT KAT dizin (bir sıra vişne, bir sıra şeker) ve üzerini örtüp oda sıcaklığında 3-4 saat, mümkünse bir gece bekletin. Şeker vişnenin suyunu çeker; böylece su eklemeden, meyvenin kendi suyunda pişen berrak bir reçel elde edersiniz.',
      'Tencereyi orta ateşe alın. Karıştırmadan kaynamaya bırakın; kaynayınca yüzeyde pembe bir köpük toplanır, bunu kaşıkla alın (köpük alınmazsa reçel bulanık olur). Ateşi kısıp arada tencereyi hafifçe çalkalayarak (kaşıkla ezmeden) 30-40 dakika pişirin.',
      'Kıvam testi: soğuk bir tabağa bir damla reçel damlatın, birkaç saniye bekleyip parmağınızla ittirin. Damla akmadan buruşuyorsa kıvam tamamdır. Reçel soğuyunca koyulaşacağı için tencerede fazla katılaşana kadar beklemeyin — akışkanken alın.',
      'Piştikten sonra yarım limonun suyunu ekleyin. Limon hem şekerin kristalleşip donmasını (şekerlenme) önler hem de rengi canlandırır. 2 dakika daha kaynatıp ocaktan alın.',
      'Reçeli SICAKKEN, önceden kaynar suda sterilize edilmiş kuru kavanozlara doldurun, ağzını sıkıca kapatıp ters çevirin. Ters durarak soğuması vakum yapıp uzun süre bozulmadan durmasını sağlar. Kaymaklı ekmek veya sade yoğurtla harikadır.',
    ],
  },
  {
    isim: 'Çilek Reçeli', mutfak: M, kategori: 'Reçel & Konserve', sure: 50, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Çilek', '1 kg'],
      ['Şeker', '700 g'],
      ['Limon', '1 adet'],
    ],
    adimlar: [
      'Çilekleri saplarını koparmadan yıkayın (sapı önce koparırsanız çilek su emip sulanır), sonra saplarını çıkarın. Küçük çilekleri bütün, büyükleri ikiye bölün. Çileğin pektini düşük olduğu için limon burada sadece lezzet değil, jelleşme için de şart.',
      'Çilekleri ve şekeri geniş bir kapta karıştırıp üzerini örtün, en az 4 saat (tercihen gece boyu) bekletin. Çilekler suyunu salıp şekerle bir şurup oluşturacak. Bu bekletme reçelin su eklemeden, kendi özünde pişmesini sağlar.',
      'Karışımı kalın tabanlı geniş bir tencereye alıp orta-yüksek ateşte kaynatın. Geniş tencere buharlaşmayı hızlandırıp reçeli daha çabuk kıvamlandırır ve çileğin taze rengini korur — dar tencerede uzun pişince renk kararır.',
      'Kaynadıkça çıkan pembe köpüğü alın. Ara sıra nazikçe karıştırın ama çilekleri ezmemeye çalışın; bütün kalmaları makbuldür. 20-25 dakika, şurup koyulaşana kadar pişirin.',
      'Limonun suyunu ekleyip 5 dakika daha kaynatın. Soğuk tabak testiyle kıvamı kontrol edin (damla buruşup akmıyorsa hazır). Çilek reçeli akışkan kalır, çok koyulaştırmayın.',
      'Sıcak reçeli sterilize kavanozlara doldurup ağzını kapatın ve ters çevirerek soğutun. Serin ve karanlık bir yerde saklayın. Kahvaltının vazgeçilmezi olur.',
    ],
  },
  {
    isim: 'Kayısı Reçeli', mutfak: M, kategori: 'Reçel & Konserve', sure: 55, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Kayısı', '1 kg (sert, olgun)'],
      ['Şeker', '700 g'],
      ['Limon', '0,5 adet'],
    ],
    adimlar: [
      'Kayısılar için hafif sert, tam olgunlaşmamış meyve seçin; aşırı yumuşak kayısı pişince dağılıp lapaya döner. Yıkayıp ikiye bölün ve çekirdeklerini çıkarın. İsterseniz birkaç çekirdeğin içindeki bademi çıkarıp reçele katabilirsiniz — geleneksel bir dokunuştur.',
      'Kayısı dilimlerini ve şekeri kat kat dizip üzerini örtün, 4-5 saat bekletin. Kayısı suyunu salana kadar sabredin; bu, reçele su katmadan berrak bir şurup verir.',
      'Tencereyi orta ateşe alıp kaynatın. Yüzeydeki köpüğü alın. Kayısı narin bir meyve olduğu için fazla karıştırmayın; tencereyi hafifçe çalkalamak yeterli. Ateşi kısıp 25-30 dakika pişirin.',
      'Dilimler şeffaflaşıp şurup bal kıvamına yaklaşınca kıvam testi yapın: soğuk tabaktaki damla akmıyorsa tamamdır. Kayısı reçeli, jölemsi değil, dilimlerin şurupta yüzdüğü akışkan bir reçeldir.',
      'Yarım limonun suyunu ekleyip 2-3 dakika daha kaynatın; limon şekerlenmeyi önler ve kayısının turuncu rengini parlatır.',
      'Sıcak reçeli sterilize kavanozlara doldurup ağzını kapatın, ters çevirip soğutun. Sabah kahvaltısında taze ekmek üzerinde muhteşemdir.',
    ],
  },
  {
    isim: 'Gül Reçeli', mutfak: M, kategori: 'Reçel & Konserve', sure: 50, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Gül Yaprağı', '250 g (kokulu, ilaçsız)'],
      ['Şeker', '600 g'],
      ['Limon', '1 adet'],
    ],
    adimlar: [
      'Gül reçeli için mutlaka yenilebilir, ilaçlanmamış kokulu gül (isparta gülü/kır gülü) yaprakları kullanın; süs gülü olmaz. Yaprakların dip kısmındaki beyaz ve acı bölümü makasla kırpın — bu acı uç alınmazsa reçel buruk olur.',
      'Gül yapraklarını bir kaba alıp üzerine şekerin yarısını ve yarım limonun suyunu ekleyin. Ellerinizle, yapraklar suyunu salıp pörsüyene kadar 5-10 dakika ovun. Bu ovma hem rengini hem kokusunu açığa çıkarır; işlem sonunda yapraklar koyulaşıp hacmi küçülür.',
      'Kalan şekeri ve 2 su bardağı suyu tencerede kaynatıp şurup yapın, 5 dakika kaynasın. Ovulmuş gül yapraklarını bu şuruba ekleyin.',
      'Kısık ateşte 20-25 dakika, yapraklar iyice yumuşayıp şurup kıvam alana kadar pişirin. Fazla pişirmeyin; uzun pişen gül reçeli kokusunu kaybeder ve rengi kararır. Narin bir reçeldir.',
      'Kalan limon suyunu ekleyin. Limon hem şekerlenmeyi önler hem de reçelin soluk pembemsi rengini canlı, parlak bir tona çevirir — kimyasal bir tepkimeyle renk anında güzelleşir.',
      'Soğuk tabak testiyle kıvamı kontrol edip sıcakken sterilize kavanozlara doldurun. Gül reçeli, sütlü tatlıların ve dondurmanın üzerinde de enfestir.',
    ],
  },
  {
    isim: 'Portakal Marmelatı', mutfak: M, kategori: 'Reçel & Konserve', sure: 70, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Portakal', '5 adet'],
      ['Şeker', '600 g'],
      ['Limon', '1 adet'],
    ],
    adimlar: [
      'Marmelatı reçelden ayıran, kabuğun da kullanılması ve narenciyenin doğal pektiniyle jelleşmesidir. Portakalları iyice fırçalayıp yıkayın (kabuğu kullanacağız). Kabuklarını rendeyle sadece turuncu kısmını alacak şekilde rendeleyin veya ince şeritler halinde soyun; altındaki beyaz kısım (albedo) acı olduğu için mümkünse dahil etmeyin.',
      'Portakalların beyaz kabuğunu tamamen soyup içlerini çıkarın, çekirdeklerini ayıklayın ve etli kısımları küçük parçalara bölün. Çekirdekleri atmayın — bir tülbente koyup düğümleyin; çekirdekler pektin deposudur ve marmelatın jelleşmesini sağlar.',
      'Portakal etini, rendelenmiş kabuğu, şekeri, çekirdek tülbentini ve 1 su bardağı suyu tencereye alın. Kaynatıp ateşi kısın ve kabuklar iyice yumuşayana kadar 40-45 dakika pişirin. Ara sıra karıştırın.',
      'Çekirdek tülbentini çıkarıp (soğuyunca sıkın, jelimsi pektini tencereye dönsün) atın. Karışım koyulaşıp parlak bir hal alacak. Kıvam testi: soğuk tabaktaki damla parmakla itilince buruşup kırışıyorsa marmelat jelleşmeye hazır demektir.',
      'Limonun suyunu ekleyip 5 dakika daha kaynatın. Narenciye marmelatı soğudukça belirgin şekilde katılaşır, bu yüzden akışkanken ocaktan alın — tencerede jel kıvamına gelene kadar beklerseniz soğuyunca taş gibi olur.',
      'Sıcak marmelatı sterilize kavanozlara doldurup kapatın, ters çevirip soğutun. Kızarmış ekmek üzerinde, tereyağıyla İngiliz kahvaltısının klasiğidir.',
    ],
  },
  {
    isim: 'Ayva Reçeli', mutfak: M, kategori: 'Reçel & Konserve', sure: 75, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Ayva', '1 kg'],
      ['Şeker', '750 g'],
      ['Limon', '1 adet'],
      ['Tarçın', '1 çubuk (isteğe bağlı)'],
    ],
    adimlar: [
      'Ayvaları soyup rendeleyin veya ince küp doğrayın. Ayva havayla temas edince hızla kararır; doğradıkça limonlu suya atın. Soyduğunuz kabukları ve çekirdekleri ATMAYIN — bunlar pektin ve renk deposudur; bir tülbente koyun.',
      'Rendelenmiş ayvayı, şekeri, kabuk-çekirdek tülbentini ve ayvayı örtecek kadar suyu tencereye alın. Ayva reçelinin sırrı yavaş ve uzun pişmesidir; işte o zaman beyazımsı renk yavaş yavaş o meşhur yakut kırmızısına döner.',
      'Kaynatıp ateşi kısın, isterseniz bir çubuk tarçın ekleyin. Kapağı hafif aralık bırakarak 45-60 dakika, ara sıra karıştırarak pişirin. Sabırlı olun; renk değişimi zaman alır, ne kadar uzun piştikçe o kadar kırmızılaşır.',
      'Ayva parçaları şeffaflaşıp reçel koyu bir renk ve kıvam alınca kabuk tülbentini çıkarıp sıkın (jelimsi pektin tencereye dönsün). Kıvam testi: soğuk tabaktaki damla akmıyorsa hazırdır.',
      'Limonun suyunu ekleyip 5 dakika daha kaynatın. Ayva bol pektinli olduğu için reçel soğuyunca belirgin katılaşır; bu yüzden hafif akışkanken ocaktan alın.',
      'Sıcakken sterilize kavanozlara doldurup kapatın ve ters çevirip soğutun. Kaymakla servis edildiğinde bir kış klasiğidir.',
    ],
  },

  // ─── TURŞULAR ───
  {
    isim: 'Karışık Turşu', mutfak: M, kategori: 'Turşular', sure: 40, tur: 'yemek', porsiyon: 10,
    malzemeler: [
      ['Salatalık', '500 g (turşuluk)'],
      ['Lahana', '0,25 adet'],
      ['Havuç', '2 adet'],
      ['Sivri Biber', '5 adet'],
      ['Sarımsak', '1 baş'],
      ['Sirke', '2 su bardağı'],
      ['Tuz', '3 yemek kaşığı (kaya tuzu)'],
      ['Nohut', '1 yemek kaşığı (mayalanma için)'],
    ],
    adimlar: [
      'Turşunun bozulmadan, çıtır kalmasının ilk kuralı: tüm malzemeler ve kavanoz KURU olmalı, üzerlerinde damla su kalmamalı. Sebzeleri yıkadıktan sonra bir bezle iyice kurulayın; ıslak sebze turşuyu yumuşatır ve küflendirir.',
      'Salatalıkları turşuluk (küçük, sert) seçin ve iki ucundan azıcık kesin. Havuçları kalın çubuklar, lahanayı iri parçalar halinde doğrayın. Sivri biberleri çatalla birkaç yerinden delin ki salamura içine işlesin. Sarımsakları soyup bütün bırakın.',
      'Sebzeleri temiz, kuru bir kavanoza sıkıştırarak yerleştirin. Aralarına sarımsakları ve turşunun daha canlı mayalanması için bir avuç nohut serpin (nohut fermantasyonu hızlandırır ve suyu berraklaştırır).',
      'Salamurayı hazırlayın: 4 su bardağı içme suyunu kaynatıp SOĞUTUN, içine tuzu ve sirkeyi ekleyip iyice karıştırın. Tuz oranı kritiktir: az tuz turşuyu yumuşatıp bozar, çok tuz sertleştirir. Kaba bir ölçü olarak 1 litre suya 2-3 yemek kaşığı kaya tuzu idealdir.',
      'Salamurayı kavanoza, sebzeleri tamamen örtecek şekilde dökün. Sebzelerin salamuranın üstüne çıkmaması için üzerine temiz bir taş veya su dolu küçük bir poşet koyarak bastırın; hava alan sebze küflenir.',
      'Kavanozun ağzını kapatıp oda sıcaklığında, güneş görmeyen bir yerde 2-3 hafta mayalanmaya bırakın. İlk günlerde ara sıra kavanozu ters-düz ederek tuzun dağılmasını sağlayın. Salamura bulanıklaşıp ekşi bir koku aldığında turşu olmuştur; sonra serin bir yere/buzdolabına alın.',
    ],
  },
  {
    isim: 'Salatalık Turşusu', mutfak: M, kategori: 'Turşular', sure: 30, tur: 'yemek', porsiyon: 10,
    malzemeler: [
      ['Salatalık', '1 kg (turşuluk, küçük)'],
      ['Sarımsak', '6 diş'],
      ['Dereotu', '1 demet'],
      ['Sivri Biber', '3 adet'],
      ['Sirke', '1,5 su bardağı'],
      ['Tuz', '3 yemek kaşığı (kaya tuzu)'],
    ],
    adimlar: [
      'Küçük, sert turşuluk salatalıklar seçin; iri ve yumuşak salatalık pişmiş gibi gevşer. Salatalıkları yıkayıp iki ucundan azıcık kesin (bu, salamuranın içine daha iyi işlemesini sağlar). Çok büyükse boyuna ikiye bölün. Hepsini bir bezle kurulayın — turşuda kuruluk şarttır.',
      'Temiz, kuru bir kavanozun dibine birkaç dal dereotu ve birkaç diş sarımsak koyun. Salatalıkları dik ve sıkışık şekilde dizin; aralarına kalan sarımsakları, çatalla delinmiş sivri biberleri ve dereotunu yerleştirin. Sıkı dizmek salatalıkların yüzmesini önler.',
      'Salamura için 3 su bardağı suyu kaynatıp iyice soğutun (sıcak salamura salatalığı haşlayıp yumuşatır). Soğuyan suya tuzu ve sirkeyi ekleyip karıştırın. Tuz denemesi: salamuraya taze bir yumurta koyduğunuzda yüzeyde durup metelik kadarı görünüyorsa tuz kıvamındadır (eski usul ölçü).',
      'Salamurayı salatalıkları tamamen örtecek şekilde kavanoza dökün. Üstte kalan salatalık küflenir; üzerine ağırlık koyup hepsini salamuranın altında tutun.',
      'Kavanozun ağzını sıkıca kapatıp serin, karanlık bir yerde 2 hafta bekletin. Salamura zamanla bulanır ve hafif köpürür — bu, turşunun mayalandığının işaretidir, endişelenmeyin.',
      'Salatalıklar zeytin yeşilinden mat bir yeşile döndüğünde ve ekşidiğinde turşu hazırdır. Buzdolabına alıp soğuk servis edin; kızartmaların ve pilavların yanında çıtır çıtır bir eşlikçidir.',
    ],
  },

  // ─── ÇORBALAR ───
  {
    isim: 'Beyran', mutfak: M, kategori: 'Çorbalar', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '400 g (kuzu incik/kol)'],
      ['Pirinç', '1 su bardağı'],
      ['Sarımsak', '1 baş'],
      ['Tereyağı', '2 yemek kaşığı'],
      ['Pul Biber', '2 yemek kaşığı (acı)'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Limon', '1 adet'],
    ],
    adimlar: [
      'Beyran, Gaziantep\'in geleneksel, kızgın ve acı sabah çorbasıdır; sırrı, etin uzun süre haşlanıp lifleri dağılana kadar pişirilmesinde saklıdır. Kuzu etini bol suyla tencereye alıp kaynatın, köpüğünü alın ve kısık ateşte 1,5-2 saat, et çatalla didiklenecek kadar yumuşayana dek haşlayın. Haşlama suyunu (et suyu) sakın dökmeyin, çorbanın canı odur.',
      'Pirinci ayrı bir tencerede, biraz et suyu ekleyerek lapa olacak şekilde haşlayın. Haşlanan eti didikleyip iyice ufalayın.',
      'Servis, geleneksel olarak tek kişilik güveçlerde/kaselerde yapılır: her kâsenin dibine bir kepçe haşlanmış pirinç ve üzerine bolca didiklenmiş et koyun.',
      'Sarımsakları ince kıyın veya ezin. Küçük bir tavada tereyağını iyice kızdırın, acı pul biberi ekleyip 5-10 saniye, yağ koyu kırmızıya boyanana kadar kavurun (yakmayın, acılaşır). Bu kızgın acı yağ beyranın imzasıdır.',
      'Her kâseye bir kaşık dolusu çiğ sarımsak ve kızgın acı yağ ekleyin. Üzerine kaynar et suyunu dökün — kaynar suyun sarımsağı ve pul biberi anında uyandırması, o keskin kokuyu ve tadı verir.',
      'Bolca limon sıkıp hemen, kaynar sıcaklıkta servis edin. Beyran ılık yenmez; ateşi, acısı ve sarımsağıyla insanı ayağa kaldıran bir çorbadır.',
    ],
  },
  {
    isim: 'Analı Kızlı', mutfak: M, kategori: 'Çorbalar', sure: 75, tur: 'yemek',
    malzemeler: [
      ['İnce Bulgur', '2 su bardağı'],
      ['Kıyma', '250 g'],
      ['Nohut', '1 su bardağı (haşlanmış)'],
      ['Soğan', '2 adet'],
      ['Salça', '2 yemek kaşığı'],
      ['Kuru Nane', '1 tatlı kaşığı'],
      ['Pul Biber', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Adı, iki farklı köfteden gelir: içi boş küçük köfteler "kızlar", içi kıymalı iri köfteler "analar"dır. Önce köfte hamurunu yapın: ince bulguru bir kaseye alıp üzerine 1 su bardağı sıcak su ekleyin, üzerini örtüp 15-20 dakika şişmeye bırakın. Bulgur suyu çekip yumuşayınca yarım kaşık tuz ekleyip ele yapışmayan, yoğrulabilir bir hamur olana kadar 10 dakika yoğurun.',
      'İç harç için 1 soğanı ince doğrayıp az yağda kavurun, kıymayı ekleyip suyunu salıp çekene kadar pişirin, tuz-karabiber ekleyin ve soğumaya bırakın.',
      '"Analar" için: bulgur hamurundan ceviz kadar parça alın, avucunuzda açıp ortasına iç harçtan koyun, kapatıp yumurta biçimi verin. "Kızlar" için: nohut büyüklüğünde küçük parçaları avuçta yuvarlayıp içi dolu minik köfteler yapın (bunlar dolgusuzdur). Hepsini unlanmış tepsiye dizin.',
      'Çorba tabanı için diğer soğanı doğrayıp yağda kavurun, salçayı ekleyip 2 dakika çevirin. Üzerine 8-10 su bardağı sıcak su ve haşlanmış nohudu ekleyip kaynatın.',
      'Kaynayan çorbaya önce iri "analar"ı ekleyip 10 dakika pişirin (büyük oldukları için daha uzun sürer), sonra küçük "kızlar"ı ekleyip 8-10 dakika daha pişirin. Köfteler suyun yüzüne çıkıp piştiğinde hazırdır; dağılmasınlar diye çok karıştırmayın.',
      'Kuru nane ve pul biberi ekleyip 2 dakika daha kaynatın, tuzunu ayarlayın. İsterseniz ayrı bir kâsede nane-pul biberli kızgın tereyağı hazırlayıp üzerine gezdirin. Sıcak, limonla servis edin.',
    ],
  },
  {
    isim: 'Balık Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Levrek', '2 adet (veya beyaz etli balık)'],
      ['Havuç', '1 adet'],
      ['Patates', '1 adet'],
      ['Soğan', '1 adet'],
      ['Un', '1 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı'],
      ['Yumurta', '1 adet (sarısı)'],
      ['Limon', '1 adet'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Çorbanın gövdesini balık suyu kurar. Balığın etini fileto olarak ayırın ama kılçık, kafa ve kuyruğu ATMAYIN. Bu kılçık ve kafaları, bir soğan yarısı, defne yaprağı ve tuzla birlikte 4-5 bardak suda 20 dakika kaynatıp süzün — elde ettiğiniz berrak balık suyu çorbanın temelidir. Kılçıkları dikkatle süzün.',
      'Havuç, patates ve soğanı küçük küpler halinde doğrayın. Tencerede tereyağını eritip soğanı kavurun, unu ekleyip 1-2 dakika, çiğ kokusu geçene kadar çevirin (un çorbaya hafif kıvam verir).',
      'Süzülmüş balık suyunu azar azar, çırparak ekleyin (un topaklanmasın). Havuç ve patatesi ekleyip sebzeler yumuşayana kadar 15 dakika pişirin.',
      'Balık filetolarını küp doğrayıp çorbaya ekleyin. Balık çok çabuk pişer; 5-6 dakika, eti donuklaşıp pul pul ayrılana kadar pişirmek yeterli. Fazla kaynatırsanız balık dağılır ve sertleşir.',
      'Terbiye için yumurta sarısını yarım limon suyu ve birkaç kaşık ılık çorba ile çırpın, yavaşça çorbaya ekleyip karıştırın ve KAYNATMADAN ocaktan alın. Terbiye çorbaya kadifemsi bir kıvam ve hafif ekşilik verir.',
      'Tuzunu ayarlayıp kâselere paylaştırın, üzerine kıyılmış maydanoz serpip bol limonla servis edin. Deniz kıyısının en sevilen başlangıcıdır.',
    ],
  },

  // ─── KAHVALTILIK ───
  {
    isim: 'Mıhlama', mutfak: M, kategori: 'Kahvaltılık', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Tulum Peyniri', '250 g (veya taze kaşar)'],
      ['Tereyağı', '3 yemek kaşığı'],
      ['Mısır Unu', '3 yemek kaşığı'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Karadeniz\'in meşhur kahvaltısı mıhlama (kuymak), tereyağı, mısır unu ve tel tel uzayan peynirin buluşmasıdır. En doğru sonuç için taze, tuzsuz Trabzon/kolot peyniri veya taze kaşar kullanın; olgun peynir uzamaz, yağını salıp dağılır. Peyniri küçük parçalara bölün.',
      'Kalın tabanlı bir tavada (geleneksel olarak sac tava) tereyağını kısık ateşte eritin. Mısır ununu ekleyip sürekli karıştırarak 4-5 dakika kavurun. Un tereyağını çekip hafif renk alacak ve fındıksı bir koku yayacak; bu kavurma mıhlamaya lezzetini verir, atlanmaz.',
      'Ateşi en kısığa alıp peynir parçalarını ekleyin. Şimdi sabır ve sürekli karıştırma zamanı: peynir eridikçe karışım önce topaklanır, sonra tereyağı ve unla birleşip pürüzsüzleşir.',
      'Peynir tamamen eriyip karışım tel tel uzamaya başlayınca mıhlama hazırdır. Kaşıkla kaldırdığınızda uzayıp kopmuyorsa tam kıvamındadır. Fazla pişirirseniz peynir sertleşip lastikleşir, bu yüzden uzamaya başlar başlamaz ocaktan alın.',
      'Üzerinde eriyen tereyağı gölcükleri oluşması normaldir, hatta makbuldür. Sıcacık, tavasıyla sofraya getirin.',
      'Mıhlama soğuyunca sertleşip uzama özelliğini kaybeder, bu yüzden hemen, cızır cızır sıcakken yenmeli. Yanında taze ekmek ve bir bardak çayla Karadeniz kahvaltısının yıldızıdır.',
    ],
  },
  {
    isim: 'Kaygana', mutfak: M, kategori: 'Kahvaltılık', sure: 25, tur: 'yemek',
    malzemeler: [
      ['Yumurta', '4 adet'],
      ['Un', '3 yemek kaşığı'],
      ['Süt', '0,5 su bardağı'],
      ['Maydanoz', '0,5 demet'],
      ['Taze Soğan', '3 dal'],
      ['Tuz', '1 çay kaşığı'],
      ['Ayçiçek Yağı', 'kızartma için'],
    ],
    adimlar: [
      'Kaygana, omlet ile krep arası, yöreye göre tatlı ya da tuzlu yapılan eski bir Anadolu kahvaltısıdır. Bu tuzlu yeşillikli versiyonda maydanoz ve taze soğanı ince ince kıyın. Yumurtaları bir kaseye kırıp tuzla birlikte iyice çırpın.',
      'Çırpılmış yumurtaya sütü ekleyin, sonra unu eleyerek azar azar ilave edin ve topak kalmayana kadar çırpın. Kıvam, akışkan bir krep hamuru gibi olmalı — çok koyu olursa süt, çok cıvık olursa un ekleyip ayarlayın.',
      'Kıyılmış maydanoz ve taze soğanı hamura ekleyip karıştırın. Yeşillikler hamura homojen dağılsın.',
      'Geniş bir tavayı orta ateşte ısıtıp ince bir tabaka yağ gezdirin. Hamurdan bir kepçe alıp tavaya dökün ve tavayı çevirerek ince bir daire halinde yayın (kalın dökerseniz içi çiğ kalır).',
      'Altı kızarıp kenarları tavadan ayrılmaya başlayınca (2-3 dakika) spatülayla dikkatlice çevirin. Diğer yüzünü de altın rengi olana kadar pişirin. İçi pişmiş, dışı hafif çıtır olmalı.',
      'Sıcak sıcak servis edin. Yanında beyaz peynir, zeytin ve çayla; tatlısını sevenler üzerine pekmez veya bal gezdirebilir. Pratik, doyurucu bir kahvaltıdır.',
    ],
  },

  // ─── MEZE ───
  {
    isim: 'Girit Ezmesi', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 20, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Beyaz Peynir', '250 g (eski/olgun)'],
      ['Ceviz', '0,5 su bardağı'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Sarımsak', '1 diş'],
      ['Dereotu', '0,5 demet'],
      ['Limon', '0,5 adet'],
      ['Pul Biber', '1 çay kaşığı'],
    ],
    adimlar: [
      'Girit ezmesinin karakterini olgun, keskin beyaz peynir verir; taze ve tatsız peynir kullanmayın. Peyniri bir çatalla veya rondoda iyice ezin. Çok tuzluysa 10 dakika suda bekletip süzün, yoksa ezme fazla tuzlu olur.',
      'Cevizleri bıçakla iri kıyın. Bir kısmını ezmeye katacak, bir kısmını üzerine süs için ayıracaksınız. İri kıyılmış ceviz, ezmenin kremamsı dokusuna hoş bir çıtırlık katar.',
      'Ezilmiş peynire ezilmiş sarımsağı, kıyılmış dereotunu, cevizin çoğunu ve pul biberi ekleyin. Sarımsağı az tutun; girit ezmesi peynirin ve otların dengesidir, sarımsak sadece arkada durmalı.',
      'Zeytinyağını azar azar ekleyerek çatalla ezip karıştırın. Yağ, kuru peyniri açıp yayılabilir, kremamsı bir kıvama getirir. Fazla katıysa biraz daha zeytinyağı ekleyin. Yarım limonun suyunu ekleyip tazelik verin.',
      'Tadına bakın — tuzu peynirden geldiği için genelde ek tuz gerekmez. Ekşilik, sarımsak ve pul biber dengesini damağınıza göre ayarlayın.',
      'Servis tabağına yayıp üzerine ayırdığınız cevizleri, bir tutam pul biber ve zeytinyağı gezdirin. Soğuk, kıtır ekmek veya kavrulmuş pide ile mezelerin arasında parlar.',
    ],
  },

  // ─── ET YEMEKLERİ ───
  {
    isim: 'Urfa Kebabı', mutfak: M, kategori: 'Et Yemekleri', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '600 g (kuzu, yağlı)'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['İsot Biber', '1 yemek kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Lavaş', '4 adet (servis)'],
    ],
    adimlar: [
      'Urfa kebabı, Adana\'nın acılı kardeşinin aksine ACISIZDIR; karakterini Urfa isotunun (acı olmayan, tütsülü-koyu kırmızı pul biber) derin, dumanlı tadı verir. Kıymanın kuzu ve yağlı olması şart; yağsız kıyma ızgarada kuruyup dağılır. En iyisi kıymayı zırh bıçağıyla veya çift çekilmiş almaktır.',
      'Soğanı ve sarımsağı rendeleyip suyunu tülbentle iyice sıkın — sadece aromasını istiyoruz, suyu harcı gevşetir. Kıymaya isot, karabiber, tuz ve sıkılmış soğan-sarımsağı ekleyin.',
      'Harcı en az 10-15 dakika, avuç içinizle bastıra bastıra yoğurun. Uzun yoğurma etin proteinini açar, harç birbirine kenetlenip şişte veya ızgarada dağılmadan durur. İyi yoğrulmuş harç yapışkan ve homojen olur. Buzdolabında yarım saat dinlendirin.',
      'Islak elle harçtan parçalar alıp yassı, geniş şişlere bastırarak yayın; şişiniz yoksa ızgara/tava için parmak kalınlığında uzun köfteler şekillendirin. Harcı şişe iyice yapıştırın ki pişerken düşmesin.',
      'Kebabı iyice kızmış mangalda veya döküm tavada pişirin. Önce bir yüzünü, altı mühürlenene kadar oynatmadan pişirin, sonra çevirin. Yağı damladıkça alevlenir; közün orta hararetli olması, dışı yakmadan içi pişirmek için idealdir.',
      'Pişen kebapları sıcak lavaşın içine alıp birkaç dakika dinlendirin — lavaş etin suyunu ve dumanlı yağını emer. Yanında közlenmiş domates-biber, sumaklı soğan ve maydanozla servis edin.',
    ],
  },
  {
    isim: 'Beyti Kebap', mutfak: M, kategori: 'Et Yemekleri', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '500 g'],
      ['Lavaş', '3 adet'],
      ['Kaşar Peyniri', '150 g'],
      ['Yoğurt', '2 su bardağı'],
      ['Salça', '2 yemek kaşığı'],
      ['Tereyağı', '3 yemek kaşığı'],
      ['Sarımsak', '2 diş'],
      ['Karabiber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Beyti, kıyma kebabının lavaşa sarılıp dilimlendiği, üzerine domates sosu ve yoğurt gelen bir İstanbul klasiğidir. Önce köfte harcını hazırlayın: kıymaya rendelenip suyu sıkılmış sarımsak, karabiber ve tuz ekleyin, 10 dakika yoğurup dinlendirin.',
      'Harcı uzun, ince silindirler (parmak kalınlığında) halinde şekillendirip ızgarada veya tavada her tarafı kızarana kadar pişirin. İçi pişmiş, dışı mühürlenmiş olmalı.',
      'Bir lavaşı serin, ortasına bir sıra köfteyi ve yanına dilimlenmiş kaşar peynirini dizin. Lavaşı sıkıca rulo yapıp sarın. Sonra bu ruloyu 3-4 cm kalınlığında dilimleyin — her dilim, ortasında köfte-peynir olan bir sarmal olur.',
      'Dilimleri yağlanmış fırın kabına kesik yüzleri yukarı bakacak şekilde dizin, üzerine biraz eritilmiş tereyağı gezdirip 180°C fırında 10 dakika, peynir eriyip lavaş çıtırlaşana kadar pişirin.',
      'Domates sosu için tereyağında salçayı 2 dakika kavurun, yarım bardak su ekleyip koyulaşana kadar pişirin. Sarımsaklı yoğurt için yoğurdu ezilmiş sarımsak ve tuzla çırpın.',
      'Servis tabağına beyti dilimlerini dizin, bir kenarına sarımsaklı yoğurdu koyun ve üzerlerine sıcak domates sosunu gezdirin. İsterseniz ayrı bir tavada nane-pul biberli kızgın tereyağını her şeyin üzerine dökün. Sıcak servis edin.',
    ],
  },
  {
    isim: 'Testi Kebabı', mutfak: M, kategori: 'Et Yemekleri', sure: 180, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '600 g (kuzu)'],
      ['Patates', '2 adet'],
      ['Patlıcan', '1 adet'],
      ['Dolmalık Biber', '2 adet'],
      ['Domates', '2 adet'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '3 diş'],
      ['Tereyağı', '2 yemek kaşığı'],
      ['Salça', '1 yemek kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Testi kebabı, malzemelerin toprak bir testi içinde, ağzı hamurla mühürlenerek uzun süre pişirildiği Kapadokya usulüdür — testi yoksa ağzı kapaklı güveç veya fırın torbası da işi görür. Eti bir lokmalık doğrayıp kağıt havluyla kurulayın.',
      'Patlıcan, patates, biber ve domatesi iri küpler halinde doğrayın; soğanı iri, sarımsağı bütün bırakın. Sebzeleri büyük doğramak, uzun pişme sırasında dağılmalarını önler.',
      'Et ve tüm sebzeleri geniş bir kapta buluşturun. Salça, tereyağı, karabiber ve tuzu ekleyip elinizle nazikçe karıştırın, tüm malzemeler baharata bulansın. Klasik testi kebabında su neredeyse hiç eklenmez; malzemeler kendi suyunda, buğulanarak pişer ve tatlar yoğunlaşır.',
      'Karışımı testiye veya güvece doldurun. Testi kullanıyorsanız ağzını ıslak ekmek hamuruyla sıkıca kapatın (buhar kaçmasın); güveç kullanıyorsanız kapağını kapatıp kenarlarını hamurla mühürleyin veya sıkıca folyoyla örtün.',
      'Önceden 160°C\'ye ısıtılmış fırında 2,5-3 saat pişirin. Bu düşük ısıda uzun pişirme, kuzu etinin kollajenini eritip eti çatalla dağılacak kadar yumuşatır ve tatların birbirine geçmesini sağlar. Acele edip ısıyı yükseltmeyin; et sertleşir.',
      'Testiyi geleneksel olarak sofrada, bir bıçak sırtıyla boyun kısmından vurarak kırıp açarlar — güveçse kapağını açın. İçeriden çıkan buğu ve koku muhteşemdir. Sıcak, pilav veya ekmekle servis edin.',
    ],
  },
  {
    isim: 'Çökertme Kebabı', mutfak: M, kategori: 'Et Yemekleri', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '500 g (dana bonfile/kontrfile)'],
      ['Patates', '3 adet'],
      ['Yoğurt', '2 su bardağı'],
      ['Domates', '2 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Tereyağı', '3 yemek kaşığı'],
      ['Sarımsak', '2 diş'],
      ['Ayçiçek Yağı', 'kızartma için'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Bodrum\'un meşhur kebabı çökertme, üç katmanın uyumudur: kıtır patates, sarımsaklı yoğurt ve soteklenmiş et. Önce patatesleri kibrit çöpü inceliğinde jülyen doğrayın, yıkayıp nişastasını akıtın ve bir bezle İYİCE kurulayın — ıslak patates kızarmaz, birbirine yapışır.',
      'Patatesleri kızgın yağda, altın sarısı ve çıtır olana kadar kızartın. Kağıt havluya alıp hemen hafifçe tuzlayın. Çökertmenin altı bu kıtır patates yatağıdır.',
      'Eti ince şeritler halinde doğrayın. Kalın bir tavayı iyice kızdırıp eti yağsız veya çok az yağla, yüksek ateşte soteleyin. Eti tavaya az az atın; kalabalık tava eti haşlar. Suyunu salıp çekince, tuzunu ekleyip kızarana kadar kavurun.',
      'Sarımsaklı yoğurt için yoğurdu ezilmiş sarımsak ve bir tutam tuzla çırpın; oda sıcaklığında olması servis için daha iyidir (buzdolabından çıkmış soğuk yoğurt sıcak yemekle kötü gider).',
      'Domates sosu için ayrı bir tavada tereyağını eritip salçayı ve rendelenmiş domatesi ekleyin, koyulaşana kadar pişirip tuzlayın.',
      'Servis: tabağa önce kıtır patatesleri yayın, üzerine sarımsaklı yoğurdu kaşıkla gezdirin, ortasına soteklenmiş eti koyun ve en üste sıcak domates-tereyağı sosunu dökün. Hemen servis edin ki patates çıtırlığını korusun.',
    ],
  },
  {
    isim: 'Kağıt Kebabı', mutfak: M, kategori: 'Et Yemekleri', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '500 g (kuzu)'],
      ['Patates', '2 adet'],
      ['Havuç', '1 adet'],
      ['Bezelye', '0,5 su bardağı'],
      ['Dolmalık Biber', '1 adet'],
      ['Domates', '2 adet'],
      ['Soğan', '1 adet'],
      ['Tereyağı', '2 yemek kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Kağıt kebabı, et ve sebzelerin yağlı kağıt (pişirme kağıdı) içinde, kendi buharında piştiği hafif ve aromatik bir yemektir. Eti bir lokmalık doğrayıp bir tavada, kendi suyunu salıp çekene ve hafif kızarana kadar tereyağıyla soteleyin. Bu ön kızartma ete renk ve derinlik verir.',
      'Patates ve havucu küp, biberi ve soğanı iri doğrayın, domatesleri küp kesin. Sebzeleri çiğ olarak kullanacağız; kağıtta et ile birlikte pişecekler.',
      'Büyük birer parça yağlı kağıdı tezgaha serin. Ortasına önce soteklenmiş etten, sonra karışık sebzelerden pay koyun. Üzerine bir parça tereyağı, tuz ve karabiber ekleyin. Az miktarda (1-2 kaşık) domates suyu veya et suyu eklemek buğulanmayı güzelleştirir.',
      'Kağıdı, içindeki buharı hapsedecek şekilde sıkıca kapatın: kenarları katlayıp bohça yapın veya iki ucunu şeker gibi bükün. Buhar kaçmazsa yemek kendi suyunda, harika kokularla pişer.',
      'Bohçaları fırın tepsisine dizip önceden 180°C ısıtılmış fırında 50-60 dakika pişirin. Kağıt şişecek — bu, içeride buharın çalıştığının işaretidir. Et yumuşayıp sebzeler pişince hazırdır.',
      'Kağıt kebabı geleneksel olarak porsiyonluk kağıdıyla servis edilir; herkes kendi bohçasını sofrada açar ve içeriden yükselen buhar-koku iştah açar. Yanında pilavla sıcak servis edin.',
    ],
  },
  {
    isim: 'Çöp Şiş', mutfak: M, kategori: 'Et Yemekleri', sure: 120, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '600 g (kuzu, küçük)'],
      ['Soğan', '1 adet'],
      ['Domates', '2 adet (rende)'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Kekik', '1 tatlı kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Lavaş', '4 adet (servis)'],
    ],
    adimlar: [
      'Çöp şiş, adını dizildiği küçük ince tahta çöplerden alır; eti küçük, bir lokmalık ve az yağlı kuşbaşı doğramak esastır. Küçük parçalar hem çabuk pişer hem de her lokmada mühürlenmiş kızarmış yüzey verir.',
      'Marine sosu için soğanı rendeleyip suyuyla birlikte bir kaba alın (çöp şişte soğan suyu eti yumuşatan asıl unsurdur). Rendelenmiş domatesi, zeytinyağını, kekiği ve karabiberi ekleyin. TUZ KOYMAYIN — tuz marine sırasında etin suyunu çeker, kurutur; tuz pişerken/pişince eklenir.',
      'Et parçalarını bu sosun içine atıp iyice karıştırın, üzerini örtüp buzdolabında en az 2 saat, mümkünse gece boyu marine edin. Soğan ve domatesin enzimleri eti içten yumuşatır, baharat aromasını işler.',
      'Marine olmuş etleri küçük şişlere veya ıslatılmış tahta çöplere, aralarında minik boşluklar bırakarak dizin (sıkışık dizilen et buharda kalır, kızarmaz). Fazla marine sosunu silkeleyin.',
      'Şişleri iyice kızmış, orta hararetli köz üzerinde pişirin. Küçük etler çok çabuk pişer; şişleri sık sık çevirerek her yüzünü mühürleyin. 6-8 dakikada, dışı kızarıp içi sulu kalacak şekilde pişer — fazla tutarsanız kurur.',
      'Pişen şişleri sıcak lavaşa alıp üzerine tuz serpin ve birkaç dakika dinlendirin. Yanında sumaklı soğan, közlenmiş biber-domates ve ayranla servis edin.',
    ],
  },
  {
    isim: 'Tekirdağ Köftesi', mutfak: M, kategori: 'Et Yemekleri', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '500 g (dana-kuzu)'],
      ['Ekmek', '2 dilim (içi)'],
      ['Sarımsak', '3 diş'],
      ['Karbonat', '0,5 çay kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Kimyon', '0,5 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Tekirdağ köftesini karakterize eden, bol SARIMSAK ve uzun dinlendirmedir; ince uzun şekli ve baharat dengesiyle tanınır. Bayat ekmeğin içini biraz suda ıslatıp sıkın, kıymaya ekleyin.',
      'Sarımsakları ezip (Tekirdağ köftesinde sarımsak cömerttir), karbonat, karabiber, kimyon ve tuzu ekleyin. Karbonat köfteye hafif kabarıklık ve yumuşaklık verir.',
      'Harcı en az 10 dakika, avuçlarınızla bastırarak iyice yoğurun; sonra bir kaba çarpa çarpa (tezgaha vurarak) havasını alın. Bu döverek yoğurma köftenin sıkı ve dağılmaz olmasını sağlar. Üzerini örtüp buzdolabında en az 2-3 saat, ideali bir gece dinlendirin — bu dinlenme tadın oturması için şarttır.',
      'Islak elle harçtan parçalar alıp avuç içinde ince, uzun (parmak gibi) köfteler yuvarlayın. İnce ve uzun şekil Tekirdağ köftesinin klasik görünümüdür ve eşit pişmesini sağlar.',
      'Köfteleri iyice kızmış ızgara veya döküm tavada pişirin. İlk yüzünü, altı güzelce kızarıp mühürlenene kadar oynatmadan pişirin, sonra çevirin. Erken çevirirseniz yapışır.',
      'Dışı karamelize, içi sulu pişen köfteleri sıcak servis edin. Yanında piyaz (haşlanmış kuru fasulye salatası), ızgara biber ve ekmek Tekirdağ köftesinin klasik üçlüsüdür.',
    ],
  },
  {
    isim: 'Papaz Yahnisi', mutfak: M, kategori: 'Et Yemekleri', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '600 g (dana)'],
      ['Kuru Soğan (Arpacık)', '500 g (arpacık soğan)'],
      ['Sarımsak', '1 baş'],
      ['Salça', '1 yemek kaşığı'],
      ['Sirke', '3 yemek kaşığı'],
      ['Defne Yaprağı', '2 adet'],
      ['Tereyağı', '2 yemek kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Papaz yahnisini diğer et yemeklerinden ayıran iki şey: bol küçük arpacık soğan ve sirkenin verdiği hafif ekşi tattır. Arpacık soğanları soymak zahmetlidir; 1-2 dakika kaynar suda bekletirseniz kabukları kolayca çıkar. Sarımsakları da bütün, soymadan bir arada bırakabilirsiniz.',
      'Eti bir lokmalık doğrayıp kurulayın. Tencerede tereyağını kızdırıp eti, suyunu salıp çekene ve dış yüzeyi kızarana kadar yüksek ateşte kavurun. Bu mühürleme etin suyunu içinde tutar.',
      'Salçayı ekleyip 2 dakika kavurun, ham kokusu geçsin. Üzerine eti örtecek kadar sıcak su ekleyin, defne yapraklarını atın, kapağı kapatıp kısık ateşte 45 dakika, et yarı yumuşayana kadar pişirin.',
      'Arpacık soğanları ve bütün sarımsakları tencereye ekleyin. Soğanları baştan eklerseniz uzun pişmede dağılıp erir; yarı yolda eklemek bütün ve dolgun kalmalarını sağlar. Kısık ateşte 30 dakika daha pişirin.',
      'Sirkeyi, karabiberi ve tuzu ekleyin. Sirke yahniye o karakteristik hafif ekşiliği verir; bu aşamada eklenir ki keskinliği pişmeyle yumuşasın ama kaybolmasın. 10-15 dakika daha, sos koyulaşıp yağ üzerine çıkana kadar pişirin.',
      'Et çatalla dağılacak kadar yumuşak, soğanlar bütün ve parlak olmalı. Sıcak, pilav veya taze ekmekle servis edin; soğuk kış günlerinin doyurucu, ekşimsi bir klasiğidir.',
    ],
  },
  {
    isim: 'Sahanda Yumurta', mutfak: M, kategori: 'Kahvaltılık', sure: 10, tur: 'yemek', porsiyon: 2,
    malzemeler: [
      ['Yumurta', '4 adet'],
      ['Tereyağı', '2 yemek kaşığı'],
      ['Tuz', '1 çay kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
    ],
    adimlar: [
      'Basit görünse de mükemmel sahanda yumurtanın püf noktaları vardır. Yumurtaları önce tek tek küçük bir kaseye kırın (doğrudan tavaya kırarsanız kabuk kaçabilir veya sarısı patlayabilir). Yumurtaların oda sıcaklığında olması daha eşit pişmelerini sağlar.',
      'Küçük bir tavayı (tercihen döküm veya yapışmaz sahan) KISIK ateşte ısıtın ve tereyağını eritin. Tereyağı köpürsün ama kızarıp kahverengileşmesin — yüksek ateş yumurtanın altını lastikleştirir, kenarlarını yakar.',
      'Tereyağı eriyip hafif köpürünce yumurtaları kaseden nazikçe tavaya kaydırın. Sarıların bütün kalmasına dikkat edin.',
      'Ateşi kısık tutup pişirin. Beyazların eşit pişmesi için iki yöntem var: ya tavanın kapağını kapatıp üstteki beyazı buğuda pişirirsiniz, ya da eriyen tereyağını bir kaşıkla yumurtaların üzerine gezdirirsiniz. Sarıların akışkan kalmasını istiyorsanız kapağı geç kapatın.',
      'Beyazlar tamamen donup sarılar hâlâ parlak ve titrek olunca (2-3 dakika) ocaktan alın. Tavanın kalıcı sıcağı pişirmeye biraz daha devam edeceği için tam kıvamdan bir tık önce alın.',
      'Üzerine tuz, karabiber ve isteğe göre pul biber serpin. Tuzu sona atmak sarının üzerinde çirkin beyaz noktalar oluşmasını önler. Tavasıyla, taze ekmekle sofraya getirin — sarıya ekmek banmak kahvaltının en güzel anıdır.',
    ],
  },

  // ─── ET YEMEKLERİ (devam) ───
  {
    isim: 'Şiş Köfte', mutfak: M, kategori: 'Et Yemekleri', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '600 g (yağlı kuzu-dana)'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['Kimyon', '1 çay kaşığı'],
      ['Pul Biber', '1 tatlı kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Şiş köftenin dağılmadan şişte durmasının sırrı, yağlı kıyma ve uzun yoğurmadır. Soğanı rendeleyip suyunu tülbentle iyice sıkın; sadece aromasını istiyoruz, suyu harcı gevşetir. Sarımsağı ezin.',
      'Kıymaya sıkılmış soğan, sarımsak, kimyon, pul biber, karabiber ve tuzu ekleyin. Kimyon şiş köftenin karakteristik baharatıdır, eksik olmasın.',
      'Harcı en az 10-15 dakika, avuç içinizle bastıra bastıra yoğurun. Ardından harcı kaseye tekrar tekrar çarparak (döverek) havasını alın. Bu işlem etin proteinlerini açıp harcı yapışkan, birbirine kenetli hale getirir — köftenin şişte durmasını sağlayan tam da budur. Buzdolabında en az 1 saat dinlendirin.',
      'Islak elle harçtan parça alıp yassı, geniş metal şişlere sıvazlayarak yayın. Harcı şişe iyice yapıştırın; gevşek sararsanız pişerken düşer. Şişiniz yoksa parmak kalınlığında uzun köfteler yapıp ızgara/tavada pişirebilirsiniz.',
      'Şişleri orta hararetli, iyice kızmış köz üzerinde pişirin. Yağı damladıkça alevlenir; alevi kontrol edin, közün ısısı dışı yakmadan içi pişirmeli. Şişleri düzenli çevirerek her yüzünü mühürleyin.',
      'Dışı karamelize olup içi sulu kalacak şekilde 8-10 dakikada pişer. Fazla tutarsanız kurur. Sıcak lavaşa alıp közlenmiş domates-biber, sumaklı soğan ve pilavla servis edin.',
    ],
  },
  {
    isim: 'Elbasan Tava', mutfak: M, kategori: 'Et Yemekleri', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '600 g (kuzu)'],
      ['Yoğurt', '3 su bardağı (süzme)'],
      ['Yumurta', '3 adet'],
      ['Un', '2 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı'],
      ['Sarımsak', '3 diş'],
      ['Karabiber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Rumeli/Arnavut kökenli Elbasan tava, haşlanmış kuzunun yumurtalı yoğurt sosuyla fırınlandığı zengin bir yemektir. Önce kuzu etini bol suda, defne ve tuzla, çatalla dağılacak kadar (1-1,5 saat) haşlayın. Haşlama suyunu (et suyu) saklayın; sosta kullanacağız.',
      'Haşlanan etleri güveç veya fırın kabına yerleştirin. Küçük bir tavada tereyağını eritip ezilmiş sarımsağı hafifçe çevirin, etlerin üzerine gezdirin — sarımsaklı tereyağı ete derinlik katar.',
      'Yoğurt sosu için yumurtaları bir kaseye çırpın, üzerine unu ekleyip topaksız hale gelene kadar çırpmaya devam edin. Sonra süzme yoğurdu ekleyip pürüzsüz bir sos elde edin. Un, sosun fırında kesilmeden, kremamsı kalmasını sağlayan bağlayıcıdır.',
      'Sosu, kıvamını ayarlamak için yaklaşık 1 su bardağı ILIK et suyuyla inceltin (sıcak et suyu yumurtayı pıhtılaştırır, ılık olmalı). Tuz ve karabiberi ekleyin.',
      'Hazırladığınız yoğurt sosunu etlerin üzerine, hepsini örtecek şekilde dökün. Sosun üzeri düz olsun.',
      'Önceden 180°C ısıtılmış fırında 35-40 dakika, üzeri altın sarısı, alacalı kızarıklıklar oluşana kadar pişirin. Sos üstte hafif kabarıp tutacak, kenarları fokurdayacak. Fırından çıkınca 10 dakika dinlendirip sıcak servis edin; pilav yanına çok yakışır.',
    ],
  },
  {
    isim: 'Patlıcan Kebabı', mutfak: M, kategori: 'Et Yemekleri', sure: 75, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '500 g (yağlı)'],
      ['Patlıcan', '4 adet'],
      ['Domates', '3 adet'],
      ['Sivri Biber', '4 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Sarımsak', '3 diş'],
      ['Tereyağı', '2 yemek kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Patlıcan kebabı, köfte ve patlıcanın fırında dizilip birlikte piştiği bir Antep/Antakya klasiğidir. Önce köfte harcını yapın: kıymaya rendelenmiş sarımsak, tuz ve karabiber ekleyip 10 dakika yoğurun, dinlendirin. Harçtan küçük yuvarlak köfteler şekillendirin.',
      'Patlıcanları alacalı soyun (bir şerit kabuklu, bir şerit soyulmuş — bu hem görüntü verir hem pişerken dağılmasını önler) ve köftelerle aynı kalınlıkta yuvarlak dilimleyin. İsterseniz acısını almak için tuzlu suda 15 dakika bekletip sıkın.',
      'Yağlı bir fırın tepsisine, bir patlıcan dilimi bir köfte olacak şekilde, hafif yatık ve sıkışık biçimde sırayla dizin (yelpaze gibi). Aralara çatalla delinmiş sivri biberleri yerleştirin. Bu dizilim hem güzel görünür hem tatların birbirine geçmesini sağlar.',
      'Domatesleri rendeleyip salça, ezilmiş sarımsak, tuz ve yarım bardak suyla karıştırıp bir sos yapın. Bu sosu dizili köfte-patlıcanların üzerine gezdirin; her yeri hafif ıslatın.',
      'Üzerine küçük tereyağı parçaları serpin. Tepsinin üzerini folyoyla örtün — ilk pişirmede folyo, patlıcanın buğuda yumuşamasını ve köftenin kurumamasını sağlar.',
      'Önceden 190°C ısıtılmış fırında folyolu 30 dakika pişirin, sonra folyoyu açıp 15-20 dakika daha, üzeri kızarıp suyu çekilene kadar pişirin. Köfteler pişmiş, patlıcanlar yumuşamış, sos koyulaşmış olmalı. Sıcak, pilav veya ekmekle servis edin.',
    ],
  },
  {
    isim: 'Manisa Kebabı', mutfak: M, kategori: 'Et Yemekleri', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '500 g'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['Domates', '3 adet'],
      ['Sivri Biber', '4 adet'],
      ['Tereyağı', '3 yemek kaşığı'],
      ['Lavaş', '4 adet'],
      ['Kimyon', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Manisa kebabı, ızgara köftenin tereyağlı domates sosu ve pide/lavaş üzerinde servis edildiği bir Ege klasiğidir. Köfte için kıymaya rendelenmiş soğan (suyu sıkılmış), ezilmiş sarımsak, kimyon, tuz ve karabiber ekleyip 10 dakika yoğurun ve dinlendirin.',
      'Harçtan ince, uzunca (parmak) köfteler şekillendirip iyice kızmış ızgara veya tavada, her yüzü kızarana kadar pişirin. İçi pişmiş, dışı mühürlenmiş olmalı.',
      'Sivri biberleri ve isterseniz birkaç domatesi ızgarada/tavada közleyin. Közlenmiş biberin dumanlı tadı bu kebabın önemli bir parçasıdır.',
      'Domates sosu için domatesleri rendeleyin. Bir tavada tereyağını eritip rendelenmiş domatesi ekleyin, tuzlayıp suyunu salıp koyulaşana ve tereyağıyla birleşip parlaklaşana kadar 8-10 dakika pişirin.',
      'Lavaşları küçük parçalara bölüp servis tabağının tabanına yayın. Üzerlerine sıcak domates sosunun bir kısmını gezdirin — lavaş sosu emip yumuşasın, kebabın altı böyle lezzetlenir.',
      'Soslu lavaşların üzerine ızgara köfteleri dizin, üzerlerine kalan sıcak domates sosunu ve eritilmiş tereyağını gezdirin. Közlenmiş biberleri kenara koyup, isteğe göre bir kenarına sarımsaklı yoğurt ekleyerek sıcak servis edin.',
    ],
  },

  // ─── TAVUK ───
  {
    isim: 'Tavuk Döner', mutfak: M, kategori: 'Tavuk Yemekleri', sure: 120, tur: 'yemek',
    malzemeler: [
      ['Tavuk But', '800 g (kemiksiz, derili)'],
      ['Yoğurt', '4 yemek kaşığı'],
      ['Salça', '1 yemek kaşığı'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '3 diş'],
      ['Kekik', '1 tatlı kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Ayçiçek Yağı', '2 yemek kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Evde döner çevirmesek de, marine ve doğru pişirmeyle o tadı yakalayabiliriz. Tavuk butlarını kullanın; göğüs eti kolay kuruyup lifli olur, but eti sulu ve yumuşak kalır. Etleri ince şeritler halinde doğrayın.',
      'Marine için yoğurt, salça, rendelenmiş soğan (suyuyla), ezilmiş sarımsak, kekik, karabiber, yağ ve tuzu bir kapta karıştırın. Yoğurt eti yumuşatan asıl unsurdur; asidi etin liflerini gevşetir. Tavuk şeritlerini bu marineye iyice bulayın.',
      'Üzerini örtüp buzdolabında en az 2 saat, ideali gece boyu marine edin. Uzun marine döner tadının derinliğini verir.',
      'Geniş, kalın bir tavayı yüksek ateşte iyice kızdırın. Tavuk şeritlerini tavayı kalabalık etmeden, birkaç partide ekleyin — kalabalık tava eti haşlar, kızartmaz. Amaç, şeritlerin kenarlarının kızarıp yer yer kavrulmasıdır.',
      'Her partiyi, suyunu salıp çekene ve kenarları kızarıp hafif çıtırlaşana kadar yüksek ateşte soteleyin. Bu kızarmış kenarlar dönerin o karakteristik tadını verir. Pişenleri bir kaba alın.',
      'Tüm partiler pişince hepsini tavada birleştirip 1-2 dakika daha çevirin. Sıcak lavaşa sarıp veya pilav üzerinde; domates, soğan, marul ve sarımsaklı sos ile servis edin.',
    ],
  },
  {
    isim: 'Çıtır Tavuk', mutfak: M, kategori: 'Tavuk Yemekleri', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Tavuk Göğsü', '600 g'],
      ['Un', '1 su bardağı'],
      ['Yumurta', '2 adet'],
      ['Galeta Unu', '1,5 su bardağı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Ayçiçek Yağı', 'kızartma için'],
    ],
    adimlar: [
      'Çıtır tavuğun sırrı üçlü kaplama sistemidir. Tavuk göğsünü ince şeritler veya nugget büyüklüğünde parçalar halinde doğrayın. Eşit boyut, eşit pişme demektir. İsterseniz daha sulu olması için önce 30 dakika tuzlu-yoğurtlu suda bekletebilirsiniz.',
      'Üç ayrı tabak hazırlayın: birincide un (tuz-karabiberle çeşnilendirilmiş), ikincide çırpılmış yumurta, üçüncüde galeta unu (pul biber ekleyin). Bu sıra kritiktir: un tavuğun nemini alıp yumurtanın tutmasını sağlar, yumurta galeta ununu yapıştırır.',
      'Her tavuk parçasını önce una bulayıp fazlasını silkeleyin, sonra yumurtaya batırın, en son galeta ununa iyice bastırarak bulayın. Galeta ununu avuçla hafifçe bastırmak kaplamanın kalın ve çıtır olmasını sağlar.',
      'Derin bir tavada yağı 170-180°C\'ye kızdırın. Yağın sıcaklığını test etmek için bir tutam galeta unu atın; hemen cızırdayıp yüzeye çıkıyorsa hazırdır. Yağ az kızgınsa tavuk yağ çeker ve hamurlaşır.',
      'Tavukları tavayı kalabalık etmeden, birkaç partide kızartın. Kalabalık tava yağın ısısını düşürür. Parçaları ara sıra çevirerek her yüzü altın-kahve rengi ve çıtır olana kadar 5-6 dakika kızartın.',
      'Kızaranları delikli kaşıkla alıp kağıt havluya dizin (fazla yağı çeksin) ve hemen hafifçe tuzlayın. Sıcak sıcak, yanında patates ve sos ile servis edin; bekledikçe çıtırlığını kaybeder.',
    ],
  },

  // ─── BALIK & DENİZ ÜRÜNLERİ ───
  {
    isim: 'Balık Ekmek', mutfak: M, kategori: 'Balık & Deniz Ürünleri', sure: 30, tur: 'yemek', porsiyon: 2,
    malzemeler: [
      ['Uskumru', '2 adet (veya istavrit)'],
      ['Ekmek', '2 adet (sandviç/bazlama)'],
      ['Soğan', '1 adet'],
      ['Marul', '4 yaprak'],
      ['Domates', '1 adet'],
      ['Limon', '1 adet'],
      ['Zeytinyağı', '2 yemek kaşığı'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'İstanbul\'un vazgeçilmez sokak lezzeti balık ekmek, aslında sadeliğin şaheseridir. Balıkları (uskumru/istavrit) temizleyip fileto çıkarın veya kılçığını ayıklayıp açın. Tuz ve biraz limon sıkıp 10 dakika bekletmek balık kokusunu alır.',
      'Soğanı ince yarım ay dilimleyip bir tutam tuz ve sumakla ovun; ovmak soğanın acısını alır ve suyunu çıkarır. Marulu ince kıyın, domatesi dilimleyin. Bu taze yeşillikler balığın yağıyla dengeyi kurar.',
      'Balık filetolarını hafif zeytinyağıyla, iyice kızmış bir ızgara veya tavada pişirin. Önce derili tarafını, deri çıtırlaşana kadar; sonra çevirip et tarafını kısa süre pişirin. Balık çabuk pişer; eti donuklaşıp pul pul ayrılınca hazırdır, fazla tutmayın.',
      'Ekmekleri hafifçe ısıtın veya ızgarada gevretin. Isıtılmış ekmek hem daha lezzetli hem de balığın suyuyla dağılmaz.',
      'Ekmeğin içine önce marul, sonra ızgara balık filetosunu, üzerine sumaklı soğan ve domates dilimlerini yerleştirin.',
      'Servisten hemen önce bolca limon sıkın — balık ekmeğin ruhu, sıcak balığın üzerine sıkılan limondadır. İsteğe göre biraz tuz ve pul biber ekleyip hemen, sıcakken yiyin.',
    ],
  },
  {
    isim: 'Midye Tava', mutfak: M, kategori: 'Balık & Deniz Ürünleri', sure: 40, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Midye', '30 adet (iç midye)'],
      ['Un', '1 su bardağı'],
      ['Nişasta', '2 yemek kaşığı'],
      ['Soda', '1 su bardağı'],
      ['Ceviz', '1 su bardağı (tarator)'],
      ['Ekmek', '2 dilim (tarator)'],
      ['Sarımsak', '2 diş'],
      ['Sirke', '2 yemek kaşığı'],
      ['Tuz', '1 çay kaşığı'],
      ['Ayçiçek Yağı', 'kızartma için'],
    ],
    adimlar: [
      'Midye tavanın çıtır kabuğunun sırrı, sodalı hamur ve nişastadır. İç midyeleri (kabuksuz) iyice yıkayıp bir bezle kurulayın; ıslak midye hamuru tutmaz ve yağı sıçratır.',
      'Kızartma hamuru için unu, nişastayı ve bir tutam tuzu karıştırın. Üzerine soğuk sodayı azar azar ekleyerek, akışkan bir krep hamuru kıvamına getirin. Sodanın karbonasyonu ve nişasta, kızarınca cam gibi çıtır bir kabuk oluşturur. Hamuru 10 dakika dinlendirin.',
      'Tarator sosu için ekmek içlerini suda ıslatıp sıkın. Cevizi, sarımsağı, ıslatılmış ekmeği, sirkeyi ve tuzu rondoda çekin; azar azar zeytinyağı ve su ekleyerek pürüzsüz, kaymaksı bir sos elde edin. Midye tavanın olmazsa olmaz eşlikçisidir.',
      'Derin bir tavada yağı iyice kızdırın (170-180°C). Midyeleri önce hafifçe una bulayıp sonra hamura batırın; çift kaplama daha çıtır olur. Fazla hamuru süzülsün.',
      'Midyeleri kızgın yağa, tavayı kalabalık etmeden atın. Hamur şişip altın sarısı ve çıtır olana kadar 2-3 dakika kızartın. Yağ yeterince kızgın değilse midye yağ çekip ağırlaşır.',
      'Kızaranları delikli kaşıkla kağıt havluya alın. Şişe veya kürdana dizip sıcakken, bol tarator sosuna batırarak servis edin — sıcak-çıtır midye ile serin-sarımsaklı tarator kusursuz bir ikilidir.',
    ],
  },

  // ─── PİLAV ───
  {
    isim: 'Perde Pilavı', mutfak: M, kategori: 'Pilav & Makarna', sure: 90, tur: 'yemek', porsiyon: 6,
    malzemeler: [
      ['Pirinç', '2 su bardağı'],
      ['Tavuk But', '400 g (kemiksiz)'],
      ['Badem', '0,5 su bardağı'],
      ['Kuru Üzüm', '0,5 su bardağı'],
      ['Çam Fıstığı', '2 yemek kaşığı'],
      ['Tereyağı', '4 yemek kaşığı'],
      ['Un', '2 su bardağı (hamur)'],
      ['Yumurta', '1 adet (hamur)'],
      ['Yoğurt', '2 yemek kaşığı (hamur)'],
      ['Karabiber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Siirt\'in görkemli pilavı perde pilavı, iç pilavın ince bir hamurla kaplanıp fırınlandığı bayramlık bir yemektir. Önce iç pilavı hazırlayın: bademleri sıcak suda bekletip kabuğunu soyun. Tereyağında bademi ve çam fıstığını kavurun, sonra küp doğranmış tavuk butlarını ekleyip suyunu çekip kızarana kadar pişirin.',
      'Yıkanmış pirinci tavuk ve kuruyemişlere ekleyip 3-4 dakika kavurun, kuru üzümü, karabiberi ve tuzu ekleyin. Üzerine 2,5 bardak sıcak tavuk suyu/su ekleyip pirinç suyunu çekene kadar pişirin. Pilav diri kalmalı; asıl pişme fırında tamamlanacak.',
      'Hamuru hazırlayın: un, yumurta, yoğurt, bir tutam tuz ve azar azar su ile kulak memesi yumuşaklığında hamur yoğurun. 20 dakika dinlendirip iki parçaya bölün ve ince açın.',
      'Yuvarlak, derin bir kabı (kelepçeli kek kalıbı ideal) tereyağıyla iyice yağlayın. Açtığınız büyük hamuru kalıba, kenarlardan taşacak şekilde serin. Estetik için tabana birkaç badem ve kuru üzüm dizebilirsiniz.',
      'İç pilavı hamurun üzerine doldurup bastırın. Taşan hamur kenarlarını pilavın üzerine katlayın, ikinci hamur parçasıyla üstünü kapatıp kenarları iyice yapıştırıp mühürleyin — pilav tamamen hamurla kaplı, kapalı bir "perde" olmalı.',
      'Üzerine yumurta sarısı sürüp 180°C fırında 40-45 dakika, hamur altın rengi ve çıtır olana kadar pişirin. 10 dakika dinlendirip bir tabağa ters çevirerek çıkarın. Kesince içinden çıkan pilav görkemlidir; bayram sofralarının gururudur.',
    ],
  },

  // ─── HAMUR İŞİ ───
  {
    isim: 'Etli Ekmek', mutfak: M, kategori: 'Hamur İşi', sure: 90, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Un', '3 su bardağı'],
      ['Maya', '1 çay kaşığı (instant)'],
      ['Kıyma', '300 g'],
      ['Soğan', '1 adet'],
      ['Domates', '2 adet'],
      ['Sivri Biber', '2 adet'],
      ['Maydanoz', '0,5 demet'],
      ['Salça', '1 yemek kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Konya\'nın ince, uzun ve çıtır etli ekmeği, lahmacundan daha kalın hamuru ve bol iç harcıyla ayrılır. Hamur için unu, mayayı, tuzu ve yaklaşık 1 su bardağı ılık suyu yoğurup yumuşak, ele yapışmayan bir hamur elde edin. Üzerini örtüp 1 saat, hacmi artana kadar mayalandırın.',
      'İç harç için soğanı, domatesi, biberi ve maydanozu çok ince kıyın (veya rondoda kısa çekin — sulu olmasın). Kıymayı, salçayı, tuz ve karabiberi ekleyip bir macun kıvamına gelene kadar iyice karıştırın. Harcın az sulu olması hamurun altını ıslatmamak için önemlidir.',
      'Mayalanan hamuru 4 bezeye bölün. Her bezeyi unlanmış tezgahta ince, uzun bir oval (yaklaşık 40 cm) halinde açın. Etli ekmek uzun ve incedir; yuvarlak değil, kayık biçiminde açın.',
      'İç harcı hamurun üzerine ince bir tabaka halinde, kenarda ince bir bordür bırakarak yayın. Harcı elle bastırarak hamura yapıştırın; böylece pişerken ayrılmaz.',
      'En iyi sonuç için fırınınızı maksimum sıcaklıkta (250-280°C), tercihen içinde bir pişirme taşı/ters tepsiyle önceden iyice ısıtın. Yüksek ısı, hamurun hızla kabarıp çıtırlaşmasını ve etin suyunu içeride tutmasını sağlar.',
      'Etli ekmeği kızgın taşın/tepsinin üzerine alıp 8-10 dakika, kenarları kabarıp altı kızarana ve et pişene kadar pişirin. Fırından çıkınca üzerine tereyağı sürüp, dilimleyerek sıcak servis edin; yanında ayran şart.',
    ],
  },
  {
    isim: 'Ramazan Pidesi', mutfak: M, kategori: 'Hamur İşi', sure: 120, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Un', '4 su bardağı'],
      ['Maya', '1 paket (instant, 10 g)'],
      ['Yoğurt', '2 yemek kaşığı'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Yumurta', '1 adet (üzeri)'],
      ['Susam', '2 yemek kaşığı'],
      ['Çörek Otu', '1 yemek kaşığı'],
    ],
    adimlar: [
      'Ramazan sofralarının yumuşacık pidesi, doğru mayalanma ve o meşhur baklava deseniyle olur. Bir kaba unu, mayayı, şekeri ve tuzu (tuzu mayadan uzağa) alın. Yoğurdu ve yaklaşık 1,5 bardak ılık suyu ekleyip 10 dakika, yumuşak ve hafif yapışkan bir hamur olana kadar yoğurun. Yoğurt pidenin yumuşak kalmasını sağlar.',
      'Kabın üzerini nemli bezle örtüp ılık yerde 1-1,5 saat, hacmi iki katına çıkana kadar mayalandırın. İyi mayalanan hamur pidenin içini süngerimsi ve hafif yapar.',
      'Mayalanan hamurun gazını nazikçe alın (çok yoğurup tüm havasını kaçırmayın) ve 2 bezeye bölün. Her bezeyi elle, yağlı tepside yuvarlak/oval ve yaklaşık 2 cm kalınlığında yayın. Merdane kullanmayın; elle yaymak içindeki havayı korur.',
      'Yumurta sarısını 1 kaşık yoğurtla çırpıp pidenin üzerine sürün. Şimdi imza deseni: parmak uçlarınızı suya batırıp pidenin üzerine, kenardan içe doğru bastırarak çapraz baklava deseni oluşturun. Parmakla bastırmak hem desen verir hem pidenin ortasının aşırı kabarmasını önler.',
      'Üzerine susam ve çörek otu serpin. Pideyi son bir 15-20 dakika daha dinlendirin (son mayalanma) — bu, fırında güzel kabarması için önemlidir.',
      'Önceden 240°C ısıtılmış fırında 12-15 dakika, üzeri altın-kızıl olana kadar pişirin. Fırından çıkar çıkmaz üzerine temiz bir bez örtün; buharıyla kabuğu yumuşar. Sıcak, iftar sofrasının baş tacıdır.',
    ],
  },
  {
    isim: 'Boyoz', mutfak: M, kategori: 'Hamur İşi', sure: 150, tur: 'yemek', porsiyon: 6,
    malzemeler: [
      ['Un', '4 su bardağı'],
      ['Ayçiçek Yağı', '1 su bardağı'],
      ['Tahin', '3 yemek kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Yumurta', '1 adet (üzeri)'],
    ],
    adimlar: [
      'İzmir\'in Sefarad kökenli meşhur hamur işi boyozun sırrı, hamurun yağla katmanlanıp uzun dinlendirilmesindedir. Önce unu, tuzu ve yaklaşık 1,5 bardak ılık suyu yoğurup pürüzsüz, sert olmayan bir hamur yapın. Üzerini örtüp 30 dakika dinlendirin.',
      'Hamuru cevizden biraz büyük bezelere bölün. Her bezeyi bolca yağlanmış tezgahta, elinizle iterek KAĞIT gibi incecik, şeffaf açın — merdane değil, yağlı elle esneterek açmak boyozun inceliğini verir. Yırtılırsa üst üste bindirin.',
      'İnce açılan hamurun üzerine tahin-yağ karışımı sürün. Sonra hamuru bir uçtan rulo yapıp, ruloyu salyangoz gibi kendi üzerine sarın. Bu katmanlama, pişince ortaya çıkan o kat kat, gevrek dokuyu oluşturur.',
      'Sarılmış bezeleri yağlı bir tepsiye dizip üzerini örtün ve buzdolabında EN AZ birkaç saat, ideali bir gece dinlendirin. Uzun dinlenme, boyozun karakteristik katmanlı yapısı için olmazsa olmazdır.',
      'Dinlenen bezeleri avuçla hafifçe bastırıp yuvarlak, kalınca diskler haline getirin. Yağlı kağıt serili tepsiye aralıklı dizin, üzerlerine çırpılmış yumurta sürün.',
      'Önceden 200°C ısıtılmış fırında 30-35 dakika, üzerleri altın sarısı ve çıtır olana kadar pişirin. Geleneksel olarak yanında haşlanmış yumurta ve bir tutam karabiberle, sıcak kahvaltı olarak yenir.',
    ],
  },
  {
    isim: 'Kete', mutfak: M, kategori: 'Hamur İşi', sure: 90, tur: 'yemek', porsiyon: 6,
    malzemeler: [
      ['Un', '4 su bardağı'],
      ['Yoğurt', '0,5 su bardağı'],
      ['Tereyağı', '150 g'],
      ['Yumurta', '1 adet'],
      ['Kabartma Tozu', '1 çay kaşığı'],
      ['Süt', '2 yemek kaşığı (üzeri)'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Kete, iç harcı kavrulmuş un olan Anadolu\'nun geleneksel çöreğidir; bölgeye göre farklı yapılır. Bu Erzurum usulünde asıl lezzet, içine konan kavrulmuş undadır. Önce iç harcı yapın: yarım kısım tereyağını tavada eritip 1,5 su bardağı unu ekleyin ve kısık ateşte sürekli karıştırarak 10-12 dakika, un koyu kremaya dönüp fındıksı koku yayana kadar kavurun. Soğumaya bırakın.',
      'Hamur için kalan yumuşak tereyağını, yoğurdu, yumurtayı (birazını üzeri için ayırın), kabartma tozunu ve tuzu karıştırın. Unu azar azar ekleyerek yumuşak, ele yapışmayan bir hamur yoğurun. 20 dakika dinlendirin.',
      'Kavrulmuş un soğuyunca ovalayıp topaklarını dağıtın; kumlu, dağılan bir harç olmalı. İsteğe göre içine biraz şeker (tatlı kete) veya sadece tuz katabilirsiniz.',
      'Hamurdan yumruk büyüklüğünde parçalar alıp tezgahta oval açın. Ortasına kavrulmuş un harcından koyup hamuru üzerine kapatın ve tekrar hafifçe açarak yassı, oval bir kete şekli verin. Harç dışarı taşmasın diye kenarları iyi kapatın.',
      'Keteleri yağlı kağıt serili tepsiye dizin. Üzerlerine yumurta-süt karışımı sürün ve çatalla üzerlerine hafif desenler çizin (hem süs hem de pişerken kabarmayı kontrol eder).',
      'Önceden 180°C ısıtılmış fırında 30-35 dakika, üzerleri altın sarısı olana kadar pişirin. İçi kavrulmuş unla kat kat dağılan, ağızda eriyen bir çörektir; çayla harika gider.',
    ],
  },

  // ─── TATLILAR ───
  {
    isim: 'Tel Kadayıf', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Kadayıf', '500 g (tel kadayıf)'],
      ['Ceviz', '2 su bardağı'],
      ['Tereyağı', '200 g'],
      ['Şeker', '3 su bardağı'],
      ['Limon', '0,5 adet'],
    ],
    adimlar: [
      'Şerbeti önceden hazırlayıp SOĞUTUN: 3 bardak şeker + 3 bardak su kaynayıp 12-15 dakika pişsin, yarım limon suyu ekleyip alın. Altın kural: sıcak kadayıfa soğuk şerbet dökülür; ikisi de sıcaksa kadayıf şerbeti çekmez, hamurlaşır.',
      'Tel kadayıfı geniş bir kaba alıp bıçakla iri iri doğrayın, sonra elinizle tel tel açıp kabartın — birbirine yapışık tutamları ayırmak, tereyağının her tele işlemesini sağlar.',
      'Tereyağını eritip (mümkünse sadeleştirilmiş/durulanmış tereyağı daha çıtır sonuç verir) kadayıf tellerinin üzerine dökün ve ellerinizle her teli yağa bulayacak şekilde iyice ovun. Bu ovma, kadayıfın fırında altın rengi ve çıtır olması için şarttır.',
      'Yağlanmış tepsinin tabanına kadayıfın yarısını yayıp elle bastırın. Üzerine iri çekilmiş cevizi eşit dağıtın. Kalan kadayıfı üstüne kapatıp yine avuçla bastırarak sıkıştırın; sıkı bastırılan kadayıf dağılmaz, düzgün dilimlenir.',
      'Önceden 180°C ısıtılmış fırında 35-40 dakika, üzeri altın sarısına dönene kadar pişirin. Alt tarafın da kızarması için son 10 dakika tepsinin altını kontrol edin; bazen altını kızartmak için ocakta da gezdirilir.',
      'Fırından çıkar çıkmaz, SICAK kadayıfın üzerine SOĞUK şerbeti kepçeyle eşit gezdirin. Çıtır çıtır ses gelir — bu, şerbetin doğru çekildiğinin işaretidir. 30 dakika dinlendirip şerbeti çektikten sonra kesip servis edin; üzerine kaymak çok yakışır.',
    ],
  },
  {
    isim: 'Şöbiyet', mutfak: M, kategori: 'Tatlılar', sure: 90, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Baklavalık Yufka', '10 yaprak'],
      ['Antep Fıstığı', '1 su bardağı'],
      ['Süt', '2 su bardağı (muhallebi)'],
      ['İrmik', '2 yemek kaşığı'],
      ['Tereyağı', '200 g'],
      ['Şeker', '3 su bardağı'],
      ['Limon', '0,5 adet'],
    ],
    adimlar: [
      'Şöbiyeti klasik baklavadan ayıran, içindeki hafif muhallebili (kaymaklı) dolgudur. Önce şerbeti yapıp soğutun (3 bardak şeker + 3 bardak su, 15 dk kaynasın, limon eklenip alınsın). Muhallebi dolgusu için sütü, irmiği ve 1 kaşık şekeri karıştırıp kısık ateşte, koyu bir muhallebi kıvamı alana kadar pişirip soğutun.',
      'Baklavalık yufkaları ikişerli çalışın. Bir yufkayı tereyağıyla yağlayıp üzerine ikinciyi koyun. Yağlanmış yufkaları kare parçalara bölün.',
      'Her kare parçanın ortasına iri çekilmiş antep fıstığı ve üzerine bir tatlı kaşığı soğumuş muhallebi koyun. Muhallebi az olsun; fazlası pişerken taşar.',
      'Şöbiyetin şekli üçgen-zarftır: karenin köşelerini ortaya doğru katlayıp bohça yapın veya ikiye katlayıp üçgen oluşturun ve kenarları bastırıp kapatın. Sızdırmaz kapatmak, muhallebinin dışarı akmamasını sağlar.',
      'Şöbiyetleri yağlı tepsiye dizin, üzerlerine bolca eritilmiş tereyağı gezdirin. Önceden 170°C ısıtılmış fırında 35-40 dakika, üzerleri altın-kızıl ve çıtır olana kadar pişirin.',
      'Fırından çıkar çıkmaz üzerine SOĞUK şerbeti gezdirin (sıcak baklavaya soğuk şerbet kuralı). 30 dakika dinlendirip şerbeti çektikten sonra servis edin. Üzerine antep fıstığı serpin.',
    ],
  },
  {
    isim: 'Un Helvası', mutfak: M, kategori: 'Tatlılar', sure: 30, tur: 'yemek', porsiyon: 6,
    malzemeler: [
      ['Un', '2 su bardağı'],
      ['Tereyağı', '150 g'],
      ['Şeker', '1,5 su bardağı'],
      ['Süt', '2 su bardağı'],
      ['Su', '1 su bardağı'],
      ['Çam Fıstığı', '3 yemek kaşığı'],
    ],
    adimlar: [
      'Un helvasının tamamı sabır ve kavurma tekniğidir. Önce şurubu hazırlayın: şeker, süt ve suyu bir tencerede kaynatıp şeker eriyene kadar karıştırın, sıcak tutun. Şurubu ayrı hazırlamak, helvaya eklerken işi kolaylaştırır.',
      'Kalın tabanlı geniş bir tavada tereyağını eritin, çam fıstığını ekleyip pembeleşene kadar kavurun ve fıstıkları bir kenara ayırın (yanmasınlar).',
      'Aynı tereyağına unu ekleyin. Şimdi asıl iş başlıyor: KISIK ateşte, tahta kaşıkla SÜREKLİ karıştırarak unu kavurun. Un önce topaklanır, sonra tereyağını çeker; 15-20 dakika boyunca karıştırmaya devam edin. Un yavaş yavaş bej, sonra açık kahve, en sonunda tarçınımsı bir renge döner ve yoğun fındıksı bir koku yayar. Renk ne kadar koyulaşırsa helva o kadar aromalı olur — ama yakmayın.',
      'Un istediğiniz kavrulmuş rengi alınca ocağı kısın ve ayırdığınız fıstıkları geri ekleyin. Şimdi dikkat: sıcak helvaya sıcak şurubu ekleyeceğiz.',
      'Sıcak şurubu, kavrulmuş unun üzerine azar azar, sürekli karıştırarak ekleyin. Karışım şiddetle fokurdar ve buhar çıkarır (dikkatli olun, sıçrar). Un şurubu emip koyulaşacak. Sürekli karıştırarak, karışım tavanın dibinden ayrılıp top haline gelene kadar pişirin.',
      'Ocaktan alıp kapağını kapatın ve 10 dakika demlenmeye bırakın — bu dinlenme helvanın kıvamını oturtur. Sonra kaşıkla porsiyonlar alıp servis tabağına ters çevirerek şekil verin. Ilık veya soğuk, üzerine fıstık serperek servis edin.',
    ],
  },
  {
    isim: 'Kemalpaşa Tatlısı', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Lor Peyniri', '250 g (tuzsuz)'],
      ['İrmik', '0,5 su bardağı'],
      ['Un', '1 su bardağı'],
      ['Yumurta', '1 adet'],
      ['Kabartma Tozu', '1 çay kaşığı'],
      ['Şeker', '3 su bardağı (şerbet)'],
      ['Limon', '0,5 adet'],
    ],
    adimlar: [
      'Bursa Mustafakemalpaşa yöresinin bu peynirli tatlısı, küçük topların şerbette şişip süngerleşmesiyle olur. Şerbeti önce yapıp ILIK tutun: 3 bardak şeker + 3,5 bardak su kaynayıp 10 dakika pişsin, limon eklenip alınsın.',
      'Tuzsuz lor peynirini bir kaba alıp çatalla iyice ezin. Yumurtayı ekleyip karıştırın, sonra irmik ve kabartma tozunu ekleyin. Peynir tuzluysa mutlaka birkaç saat suda bekletip tuzunu alın, yoksa tatlı tuzlu olur.',
      'Unu azar azar ekleyerek yumuşak, ele hafif yapışan ama şekil verilebilen bir hamur elde edin. Çok un koymayın; sert hamur, şerbeti çekmeyen sert tatlı verir. Hamuru 10 dakika dinlendirin.',
      'Islak elle hamurdan ceviz büyüklüğünde parçalar alıp pürüzsüz toplar yuvarlayın, hafifçe bastırıp yassıltın. Ortalarına parmakla küçük bir çukur yapın — bu çukur şerbeti daha iyi tutar.',
      'Topları yağlı kağıtlı tepsiye dizip önceden 180°C ısıtılmış fırında 20-25 dakika, üzerleri altın rengi olana kadar pişirin. İçleri kek gibi kabaracak.',
      'Fırından çıkan SICAK topları ILIK şerbetin içine atın (veya ılık şerbeti üzerlerine dökün). Kısık ateşte 5 dakika şerbette çevirerek kaynatın; toplar şerbeti emip şişecek ve süngerleşecek. Ocaktan alıp dinlendirin. Üzerine kaymak veya dondurma ile servis edin.',
    ],
  },
  {
    isim: 'Bülbül Yuvası', mutfak: M, kategori: 'Tatlılar', sure: 75, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Baklavalık Yufka', '8 yaprak'],
      ['Ceviz', '1 su bardağı'],
      ['Antep Fıstığı', '0,5 su bardağı'],
      ['Tereyağı', '150 g'],
      ['Şeker', '3 su bardağı'],
      ['Limon', '0,5 adet'],
    ],
    adimlar: [
      'Bülbül yuvası, ortası fıstık dolu, halka şeklinde zarif bir baklava çeşididir. Şerbeti önce hazırlayıp soğutun (3 bardak şeker + 3 bardak su, 15 dk kaynasın, limon eklenip alınsın).',
      'Bir baklavalık yufkayı açıp tereyağıyla hafifçe yağlayın. İnce, uzun bir oklava (veya kalın şiş) alın ve yufkanın alt kenarına yerleştirin.',
      'Yufkayı oklavanın etrafına gevşekçe sarın. Sonra sarılı yufkayı oklavanın iki ucundan tutup ortaya doğru büzerek akordeon gibi kırıştırın — bu kırıştırma bülbül yuvasının o dalgalı, kıvrımlı yüzeyini verir. Oklavayı nazikçe çekip çıkarın; elinizde büzülmüş uzun bir rulo kalır.',
      'Bu ruloyu bir uçtan sarıp halka/yuva şekli verin, uçları birbirine bastırıp kapatın. Ortasında bir çukur kalsın. Yağlanmış tepsiye dizin ve her yuvanın ortasındaki çukura iri çekilmiş ceviz-fıstık koyun.',
      'Üzerlerine bolca eritilmiş tereyağı gezdirip önceden 170°C ısıtılmış fırında 30-35 dakika, üzerleri altın-kızıl ve çıtır olana kadar pişirin.',
      'Fırından çıkar çıkmaz üzerlerine SOĞUK şerbeti gezdirin. 30 dakika dinlendirip şerbeti çektikten sonra ortalarındaki fıstıkları tazeleyip servis edin. Çıtır dış, şerbetli kat ve fıstıklı orta — üç dokunun uyumudur.',
    ],
  },
  {
    isim: 'Profiterol', mutfak: M, kategori: 'Tatlılar', sure: 75, tur: 'yemek', porsiyon: 6,
    malzemeler: [
      ['Un', '1 su bardağı'],
      ['Yumurta', '4 adet'],
      ['Tereyağı', '100 g'],
      ['Su', '1 su bardağı'],
      ['Süt', '3 su bardağı (krema)'],
      ['Nişasta', '3 yemek kaşığı'],
      ['Şeker', '0,5 su bardağı'],
      ['Bitter Çikolata', '150 g'],
      ['Krema', '1 su bardağı'],
    ],
    adimlar: [
      'Profiterolün minik topları, "choux" adı verilen özel bir hamurdan yapılır. Su ve tereyağını tencerede kaynatın, kaynayınca ocağı kısıp unun TAMAMINI bir kerede ekleyin ve hızla karıştırın. Hamur top olup tencerenin dibinden ayrılana kadar 1-2 dakika pişirip ocaktan alın, biraz soğutun.',
      'Hamur ılıyınca yumurtaları TEK TEK ekleyin; her yumurtadan sonra hamur parlak ve pürüzsüz olana kadar iyice çırpın. Sıradaki yumurtayı, bir önceki tamamen karışmadan eklemeyin. Doğru choux hamuru parlak, kaşıktan zorlanarak akan kıvamdadır.',
      'Hamuru sıkma torbasına alıp yağlı kağıtlı tepsiye ceviz büyüklüğünde toplar sıkın (aralarında yer bırakın, şişecekler). Önceden 200°C ısıtılmış fırında 25-30 dakika pişirin ve KESİNLİKLE fırın kapağını erken açmayın — ani soğuk hava topları söndürür. Toplar kabarıp altın rengi ve içi boş olmalı.',
      'İç krema için sütün çoğunu şekerle kaynatın. Nişastayı biraz soğuk sütte ezip kaynayan süte ekleyin, muhallebi kıvamı alana kadar karıştırarak pişirip soğutun. Bu krema profiterol toplarının içini dolduracak.',
      'Soğuyan topların altını veya yanını delip sıkma torbasıyla içlerine muhallebi kremasını doldurun. Doldurulmuş topları servis kabına yığın.',
      'Çikolata sosu için kremayı ısıtıp kırılmış bitter çikolatayı ekleyin, karıştırarak pürüzsüz, parlak bir ganaj yapın. Sıcak sosu profiterol toplarının üzerine bolca dökün. Buzdolabında soğutup servis edin; pastanelerin klasik soğuk tatlısıdır.',
    ],
  },
  {
    isim: 'Lokum', mutfak: M, kategori: 'Tatlılar', sure: 90, tur: 'yemek', porsiyon: 10,
    malzemeler: [
      ['Şeker', '4 su bardağı'],
      ['Nişasta', '1 su bardağı'],
      ['Su', '5 su bardağı'],
      ['Limon', '1 adet'],
      ['Antep Fıstığı', '1 su bardağı'],
      ['Pudra Şekeri', '0,5 su bardağı'],
    ],
    adimlar: [
      'Ev yapımı lokum sabır ister ama kıvamı yakalayınca büyülü bir kıvam elde edilir. İki ayrı karışım hazırlanır. Birincisi şeker şurubu: şekeri, 2 bardak suyu ve yarım limonun suyunu (şekerlenmeyi önler) tencerede kaynatın, şeker eriyip hafif kıvam alsın.',
      'İkinci karışım nişasta bulamacı: 1 bardak nişastayı 3 bardak soğuk suda topaksız çözün. Nişastayı mutlaka soğuk suda çözün; sıcağa atarsanız anında topaklanır.',
      'Kaynayan şeker şurubuna nişasta bulamacını ince ince, sürekli çırparak ekleyin. Şimdi lokumun en zorlu kısmı: KISIK ateşte, tahta kaşıkla neredeyse hiç durmadan karıştırarak 45-60 dakika pişirin. Karışım önce beyaz ve sıvıdır; zamanla sararır, şeffaflaşır ve giderek koyulaşıp esner. Sabır şart — erken alırsanız lokum donmaz, cıvık kalır.',
      'Kıvam testi: karışım kaşıktan ağır ağır, esneyerek akıyor ve rengi ballı-amber bir şeffaflığa döndüyse hazırdır. Bu aşamada kalan limon suyunu ve iri çekilmiş antep fıstığını ekleyip karıştırın.',
      'Nişasta serpilmiş veya yağlı kağıtla kaplanmış bir kabı hazırlayın. Lokum karışımını bu kaba döküp spatülayla düzleyin, yaklaşık 2-3 cm kalınlıkta olsun.',
      'Oda sıcaklığında EN AZ 4-5 saat, tercihen bir gece, tamamen soğuyup katılaşana kadar bekletin (buzdolabına koymayın, terler). Bıçağı pudra şekerine bulayarak lokumu kesin, her parçayı pudra şekeri-nişasta karışımına bulayın. Kapalı kapta uzun süre durur.',
    ],
  },
  {
    isim: 'Pişmaniye', mutfak: M, kategori: 'Tatlılar', sure: 90, tur: 'yemek', porsiyon: 10,
    malzemeler: [
      ['Un', '1 su bardağı'],
      ['Tereyağı', '150 g'],
      ['Şeker', '3 su bardağı'],
      ['Su', '1 su bardağı'],
      ['Limon', '0,5 adet'],
    ],
    adimlar: [
      'Pişmaniye (keten helvası), tel tel çekilmiş şekerin kavrulmuş unla buluştuğu, ustalık isteyen bir tatlıdır — ev yapımı zorludur ama yöntem şudur. Önce un-tereyağı kavurması: tereyağını tavada eritip unu ekleyin ve KISIK ateşte, sürekli karıştırarak 15-20 dakika, un altın-bej bir renk ve fındıksı koku alana kadar kavurun. Bunu ayrı bir kaba alıp ılık tutun.',
      'Şeker şurubunu yapın: şeker, su ve yarım limon suyunu kaynatın. Şuruba bir şeker termometresi koyun; 140-150°C (sert top/kırılgan kıvam) aşamasına gelene kadar KARIŞTIRMADAN kaynatın. Bu sıcaklık kritiktir: az olursa şeker tel tel çekilmez, çok olursa yanar.',
      'Şurup kıvama gelince, yağlı bir mermer zemine veya geniş tepsiye dökün. Hafif ılıyıp elle tutulabilir hale gelince (dikkat, çok sıcak) bir halka şekli verin.',
      'Şimdi pişmaniyenin sihri: şeker halkasını sürekli, kavrulmuş una bulayarak çekin ve büküp katlayın, tekrar çekin. Her çekişte teller incelir; onlarca kez çeke büke bu işlemi tekrarlarsanız şeker binlerce ipeksi tele dönüşür. Bu, geleneksel olarak iki kişinin birlikte yaptığı zahmetli bir iştir.',
      'Teller yeterince incelip pamuk gibi olunca, kavrulmuş unla tamamen kaplanmış lifli bir yığın elde edersiniz. Bu, pişmaniyenin o eriyen, tel tel dokusudur.',
      'Küçük tutamlar halinde kesip servis edin. Nemden çabuk etkilenir, bu yüzden hava almayan kapta saklayın. Türk kahvesinin yanında bir gelenek, çocukların da bayıldığı bir lezzettir.',
    ],
  },
  {
    isim: 'Pestil', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Kayısı', '1 kg (veya dut/erik)'],
      ['Şeker', '0,5 su bardağı'],
      ['Nişasta', '2 yemek kaşığı'],
      ['Limon', '0,5 adet'],
    ],
    adimlar: [
      'Pestil, meyve pulpunun ince tabaka halinde kurutulmasıyla yapılan geleneksel bir kuru meyve tatlısıdır; Anadolu\'da dut, kayısı ve erikten yapılır. Meyveleri (burada kayısı) yıkayıp çekirdeklerini çıkarın ve iri doğrayın.',
      'Meyveleri az suyla tencerede, tamamen dağılıp yumuşayana kadar 15-20 dakika pişirin. Yumuşayınca el blenderıyla pürüzsüz bir pulp (püre) haline getirin.',
      'Pürüzsüz meyve pulpunu tekrar ocağa alın, şekeri (meyvenin ekşiliğine göre ayarlayın) ve yarım limon suyunu ekleyin. Nişastayı birkaç kaşık soğuk suda ezip ekleyin — nişasta pestilin bağlanıp kuruyunca esnek, kopmaz bir tabaka olmasını sağlar.',
      'Karışımı kısık ateşte, sürekli karıştırarak koyu, akışkan bir marmelat kıvamına gelene kadar pişirin. Dibi tutmasın diye kaşığı elinizden bırakmayın.',
      'Geniş bir tepsiyi yağlı kağıtla kaplayın (veya hafif yağlayın). Sıcak meyve pulpunu tepsiye döküp spatülayla OLABİLDİĞİNCE İNCE, eşit bir tabaka halinde yayın. Tabaka ne kadar ince olursa o kadar iyi ve eşit kurur.',
      'Geleneksel olarak güneşte 2-3 gün kurutulur; evde ise fırını en düşük ısıda (50-60°C) kapağı aralık bırakarak birkaç saat çalıştırıp kurutabilirsiniz. Pestil, üzeri artık yapışmayıp elle kaldırılabildiğinde ve esnek-kopmaz olduğunda hazırdır. Şeritler halinde kesip saklayın; içine ceviz sararak da yenir.',
    ],
  },
];
