// Türk Mutfağı 3. bölüm: Zeytinyağlılar & Sebze, Pilav & Makarna, Hamur İşi, Tatlılar.
import { type SeedTarif } from './seed-tarifler-turk';

const M = 'Türk Mutfağı';

export const TURK_3: SeedTarif[] = [
  // ─── ZEYTİNYAĞLILAR & SEBZE ───
  {
    isim: 'İmam Bayıldı', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Patlıcan', '6 adet küçük'],
      ['Soğan', '3 adet'],
      ['Sarımsak', '4 diş'],
      ['Domates', '2 adet'],
      ['Maydanoz', 'yarım demet'],
      ['Zeytinyağı', 'yarım su bardağı (100 ml)'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'İnce, uzun ve küçük patlıcan seçin (çekirdeği az, eti bol olur). Alacalı soyun: bir şerit soyup bir şerit bırakın; bu, hem şık görünür hem patlıcanın dağılmadan durmasını sağlar. Tuzlu suda 15-20 dakika bekletin (acısını alır, az yağ çeker), sonra kâğıt havluyla iyice kurulayın.',
      'Tavada 3-4 kaşık zeytinyağı ısıtın ve patlıcanları her tarafı hafifçe kızarıp yumuşayana kadar orta ateşte çevirerek pişirin. Amaç patlıcanları tamamen pişirmek değil, kabuklarını yumuşatıp yuva açmaya hazır hale getirmek. Kâğıt havluya alın.',
      'İç harç, İmam Bayıldı\'nın ruhudur ve sabır ister: soğanları ince yarım ay doğrayın. Aynı tavada kalan yağa (gerekirse biraz daha ekleyin) soğanları alın ve KISIK ateşte 10-12 dakika, ara sıra karıştırarak, iyice yumuşayıp şekerlenene (hafif kavrulup tatlanana) kadar pişirin. Yemeğin adı "imam bayıldı" — rivayete göre imam bu yağlı, tatlı soğanlı lezzetten bayılmış; o lezzet işte bu yavaş pişen soğanda saklı.',
      'İnce kıyılmış sarımsağı ekleyip 1 dakika çevirin, sonra küp doğranmış 1 domatesi, şekeri ve tuzu ekleyip 5 dakika, domates suyunu bırakıp harç toparlanana kadar pişirin. Ocaktan alıp ince kıyılmış maydanozu karıştırın.',
      'Patlıcanları geniş, sığ bir tencereye yan yana dizin. Her birinin ortasını boydan boya, tabana kadar kesmeden yarıp iki yana bastırarak açın; içine soğanlı harcı bolca doldurun. Üzerlerine birer domates dilimi ve isterseniz birer parça sivri biber koyun.',
      'Yarım su bardağı sıcak su ve 1 kaşık zeytinyağını tencerenin kenarından (harcın üzerine değil) ekleyin. Kapağı kapatıp kısık ateşte 25-30 dakika, patlıcanlar tamamen yumuşayıp suyunu çekene kadar pişirin.',
      'En önemli kural: İmam Bayıldı SICAK yenmez. Tencerede oda sıcaklığına gelene kadar soğutun, hatta buzdolabında bekletip serin servis edin. Zeytinyağlılar soğudukça yağ ve baharat sebzeye işler, gerçek lezzet ancak o zaman ortaya çıkar.',
    ],
  },
  {
    isim: 'Zeytinyağlı Taze Fasulye', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Taze Fasulye', '500 g'],
      ['Soğan', '1 adet'],
      ['Domates', '2 adet'],
      ['Zeytinyağı', 'yarım çay bardağı (50 ml)'],
      ['Şeker', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Fasulyelerin iki ucunu koparın ve yan tarafındaki kılçık teli (varsa) uçla birlikte çekip çıkarın — bu tel dişe gelir. Boyuna büyük fasulyeleri ikiye ya da üçe bölün, yıkayıp süzün. Taze, gevrek fasulye seçin; kırdığınızda "cıt" diye kırılmalı.',
      'Soğanı ince doğrayıp tencerede zeytinyağıyla KISIK ateşte 5-6 dakika, şeffaflaşana kadar kavurun. Zeytinyağlılarda soğanı yakmadan, yavaşça yumuşatmak esastır.',
      'Fasulyeleri ekleyip 5 dakika birlikte çevirin; yağla iyice tanışsınlar, renkleri canlansın.',
      'Rendelenmiş domatesi, şekeri ve tuzu ekleyin. Bir tutam şeker, domatesin ekşiliğini dengeler ve zeytinyağlıya o hafif tatlımsı, yuvarlak tadı verir — atlamayın.',
      '1 su bardağı sıcak su ekleyip kapağı kapatın; kısık ateşte 35-40 dakika, fasulyeler çatalla kolayca ezilecek kadar yumuşayana ve suyu neredeyse çekilene kadar pişirin. Zeytinyağlı fasulye diri değil, ağızda dağılacak kadar yumuşak olmalı.',
      'Ocaktan alıp tencerede, kapağı açık soğumaya bırakın. Oda sıcaklığında ya da buzdolabında soğutup servis edin; üzerine taze zeytinyağı gezdirip limon sıkın. Bir gün beklerse lezzeti daha da oturur.',
    ],
  },
  {
    isim: 'Zeytinyağlı Yaprak Sarma', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Asma Yaprağı', '300 g (salamura)'],
      ['Pirinç', '2 su bardağı (360 g)'],
      ['Soğan', '3 adet'],
      ['Çam Fıstığı', '2 yemek kaşığı'],
      ['Kuru Üzüm', '2 yemek kaşığı'],
      ['Zeytinyağı', 'yarım su bardağı (100 ml)'],
      ['Limon', '2 adet'],
      ['Tarçın', 'yarım çay kaşığı'],
      ['Kuru Nane', '1 tatlı kaşığı'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Salamura yaprakları kaynar suda 3-4 dakika haşlayıp soğuk suda yıkayın; tuzu gitsin. Saplarını koparın.',
      'İç harç: zeytinyağının yarısında çam fıstıklarını pembeleşene kadar kavurun; ince doğranmış soğanları ekleyip 8 dakika yumuşatın.',
      'Yıkanmış pirinci ekleyip 3 dakika kavurun. Üzüm, tarçın, nane, şeker, tuz, karabiber ve 1 su bardağı sıcak su ekleyin; su çekilene kadar 5 dakika pişirip soğumaya bırakın. Pirinç yarı pişmiş olacak — tam pişmesi sarmanın içinde olur.',
      'Sarma vakti: yaprağı parlak yüzü alta, damarlı yüzü üste gelecek şekilde önünüze açın. Sap kısmına bir tatlı kaşığı harç koyun.',
      'Önce alt kenarı harcın üzerine katlayın, sonra iki yanı içe kapatıp yaprağı kalem gibi ince ve sıkı sarın.',
      'Tencerenin tabanına birkaç yaprak serin (dibi tutmasın), sarmaları sıkıca yan yana dizin. Üzerine limon dilimlerini yayıp düz bir tabak kapatın.',
      'Kalan zeytinyağı, 1 limonun suyu ve sarmaları yarı geçecek kadar sıcak su ekleyin. Kısık ateşte 45 dakika pişirin.',
      'Tencerede soğutup soğuk servis edin. Sabır ister ama her lokması buna değer!',
    ],
  },
  {
    isim: 'Zeytinyağlı Enginar', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Enginar', '4 adet (temizlenmiş)'],
      ['Havuç', '1 adet'],
      ['Patates', '1 adet'],
      ['Bezelye', 'yarım su bardağı (75 g)'],
      ['Soğan', '1 adet küçük'],
      ['Zeytinyağı', 'yarım çay bardağı (50 ml)'],
      ['Limon', '1,5 adet'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Dereotu', 'birkaç dal'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Enginarları kararmasınlar diye limonlu suda bekletin (1 limonun suyunu sıktığınız su yeterli).',
      'Havuç, patates ve soğanı minik küpler halinde doğrayın.',
      'Enginarları geniş bir tencereye çukur kısımları yukarı bakacak şekilde yerleştirin.',
      'Küp sebzeleri ve bezelyeyi enginarların çukurlarına ve aralarına paylaştırın.',
      'Zeytinyağı, yarım limonun suyu, şeker, tuz ve 1,5 su bardağı sıcak suyu ekleyin.',
      'Kapağı kapatıp kısık ateşte 30 dakika, enginarlar bıçakla kolayca delinene kadar pişirin.',
      'Tencerede soğutun; kıyılmış dereotu serpip oda sıcaklığında servis edin.',
    ],
  },
  {
    isim: 'Zeytinyağlı Barbunya', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Barbunya', '2 su bardağı (350 g, kuru) veya 500 g taze'],
      ['Soğan', '1 adet'],
      ['Havuç', '1 adet'],
      ['Domates', '2 adet'],
      ['Salça', '1 tatlı kaşığı'],
      ['Zeytinyağı', 'yarım çay bardağı (50 ml)'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Limon', 'servis için'],
      ['Maydanoz', 'birkaç dal'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Kuru barbunya kullanıyorsanız bir gece ıslatın ve yarı yumuşayana kadar 25 dakika haşlayıp süzün.',
      'Soğanı ince doğrayıp zeytinyağında 5 dakika yumuşatın; halka halka doğranmış havucu ekleyip 3 dakika çevirin.',
      'Salçayı ekleyip 1 dakika kavurun; rendelenmiş domatesi ekleyip 3 dakika pişirin.',
      'Barbunyaları, şekeri ve tuzu ekleyin; 2 su bardağı sıcak su koyun.',
      'Kapağı kapatıp kısık ateşte 30-35 dakika, taneler yumuşacık olana kadar pişirin.',
      'Tencerede soğutun. Kıyılmış maydanoz ve limon dilimleriyle soğuk servis edin.',
    ],
  },
  {
    isim: 'Kabak Mücver', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Kabak', '3 adet (600 g)'],
      ['Yumurta', '2 adet'],
      ['Un', '4 yemek kaşığı'],
      ['Beyaz Peynir', '100 g'],
      ['Dereotu', 'yarım demet'],
      ['Taze Soğan', '3 dal'],
      ['Ayçiçek Yağı', 'kızartma için'],
      ['Yoğurt', 'servis için'],
      ['Tuz', '1 çay kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Kabakları yıkayıp rendenin iri tarafında rendeleyin. Rendelenmiş kabağa bir tutam tuz serpip 10 dakika bekletin — tuz, kabağın bol suyunu dışarı çeker.',
      'Mücverin başarısının %90\'ı bu adımda: rendelenmiş kabağı avuç avuç alıp iki elinizin arasında suyunu ADAMAKILLI sıkın, sıkılan suyu dökün. Islak kabak harcı sulandırır; mücver tavada dağılır, bol yağ çeker ve çıtır olmaz. İyi sıkılmış kabak neredeyse kuru görünmeli.',
      'Sıkılmış kabağı geniş bir kaba alın; yumurtaları, ufalanmış beyaz peyniri, ince kıyılmış dereotu ve taze soğanı ekleyin. Peynir tuzlu olduğu için tuzu en son, tada bakarak ayarlayın.',
      'Unu azar azar ekleyip karıştırın; kaşıktan zor akan, koyu bir kek hamuru kıvamı hedefleyin. Fazla cıvıksa 1 kaşık daha un, fazla katıysa çok az su ekleyin. Karabiberi de ekleyin.',
      'Geniş tavada 4-5 kaşık yağı orta ateşte kızdırın (yağ yeterince kızmazsa mücver yağ emer). Harçtan kaşık kaşık alıp tavaya bırakın ve kaşığın arkasıyla hafifçe yayıp yassılaştırın; kalın olursa içi çiğ kalır.',
      'Her yüzünü 3-4 dakika, kenarları çıtır ve altın kahve olana kadar kızartın; erken çevirmeyin, kabuk bağlasın. Kâğıt havluya alıp fazla yağını süzdürün.',
      'Sarımsaklı yoğurtla sıcak servis edin. Soğuk da lezzetlidir, ertesi gün kahvaltıya da yakışır.',
    ],
  },
  {
    isim: 'Ispanak Yemeği', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Ispanak', '750 g'],
      ['Soğan', '1 adet'],
      ['Pirinç', '2 yemek kaşığı'],
      ['Salça', '1 yemek kaşığı'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Yoğurt', 'servis için'],
      ['Sarımsak', '1 diş (yoğurt için)'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Ispanakları köklerinden ayırın ve bol suda, kum kalmayana kadar birkaç kez yıkayın. İri doğrayın.',
      'Soğanı ince doğrayıp zeytinyağında 4-5 dakika kavurun; salçayı ekleyip 1 dakika daha pişirin.',
      'Ispanakları ekleyin. Dağ gibi görünecek ama korkmayın — 2 dakikada söner, kendi suyunu salar.',
      'Yıkanmış pirinci ve tuzu ekleyin; yarım su bardağı sıcak su koyun.',
      'Kapağı kapatıp kısık ateşte 20 dakika, pirinçler yumuşayana kadar pişirin.',
      'Sarımsaklı yoğurtla sıcak servis edin — ıspanağın en yakışanı budur.',
    ],
  },
  {
    isim: 'Zeytinyağlı Pırasa', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Pırasa', '4 adet (800 g)'],
      ['Havuç', '1 adet'],
      ['Pirinç', '2 yemek kaşığı'],
      ['Zeytinyağı', 'yarım çay bardağı (50 ml)'],
      ['Limon', '1 adet'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Pırasaların koyu yeşil uçlarını ve köklerini kesin; kalan beyaz-açık yeşil kısımları 2 cm kalınlığında halkalar halinde doğrayın. Aralarında toprak olabilir, bol suda yıkayın.',
      'Havucu yarım halkalar şeklinde doğrayın.',
      'Tencereye zeytinyağını koyup havuçları 3 dakika soteleyin.',
      'Pırasaları ekleyip 5 dakika, hafif yumuşayana kadar birlikte çevirin.',
      'Yıkanmış pirinci, şekeri, tuzu ve 1 su bardağı sıcak suyu ekleyin.',
      'Kapağı kapatıp kısık ateşte 25-30 dakika pişirin. Soğuduktan sonra limon sıkarak servis edin.',
    ],
  },
  {
    isim: 'Türlü', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Patlıcan', '2 adet'],
      ['Kabak', '2 adet'],
      ['Patates', '2 adet'],
      ['Taze Fasulye', '200 g'],
      ['Sivri Biber', '3 adet'],
      ['Soğan', '1 adet'],
      ['Domates', '3 adet'],
      ['Sarımsak', '3 diş'],
      ['Salça', '1 yemek kaşığı'],
      ['Zeytinyağı', 'yarım çay bardağı (50 ml)'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Türlü, adı gibi "türlü türlü" sebzenin buluştuğu bir yemektir; ne bulursanız katabilirsiniz. Bütün sebzeleri yıkayın. Patlıcanları alacalı soyup iri küpler halinde doğrayın ve acısı çıksın diye tuzlu suda 10-15 dakika bekletin. Kabak, patates ve biberleri de iri iri doğrayın (küçük doğranan sebze türlüde dağılır, iri olmalı); fasulyelerin uçlarını alıp ikiye bölün.',
      'Kalın tabanlı geniş tencerede soğanı zeytinyağıyla 5 dakika, yumuşayana kadar kavurun; ezilmiş sarımsağı ve salçayı ekleyip 1 dakika daha, kokusu çıkana kadar pişirin.',
      'Sebzeleri pişme sürelerine göre sırayla ekleyin: önce en sert olan patates ve fasulyeyi koyup 5 dakika çevirin ki ötekilerle aynı anda yumuşasınlar.',
      'Sonra patlıcan, kabak ve biberi ekleyin (bunlar daha çabuk pişer). Rendelenmiş domatesleri en üste dökün — türlüde domates genelde karıştırılmaz, üstte pişip sebzelere sosunu salar.',
      'Tuzu ve 1 su bardağı sıcak suyu kenardan ekleyip kapağı kapatın (sebzeler pişerken kendi suyunu da salacağı için az su yeter).',
      'Kısık ateşte 35-40 dakika, tüm sebzeler yumuşayana kadar pişirin. Kaşıkla KARIŞTIRMAYIN — bunun yerine ara sıra tencerenin kulplarından tutup hafifçe sallayın; böylece sebzeler ezilip lapaya dönmez, formunu korur. Zeytinyağlı olarak soğuk da, sıcak ana yemek olarak da yenir; yanında yoğurt çok yakışır.',
    ],
  },

  // ─── PİLAV & MAKARNA ───
  {
    isim: 'Tereyağlı Pirinç Pilavı', mutfak: M, kategori: 'Pilav & Makarna', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Pirinç', '2 su bardağı (360 g)'],
      ['Tel Şehriye', '2 yemek kaşığı'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Pirinci bir kaba koyun, üzerine 1 tatlı kaşığı tuz atıp sıcak su ekleyin ve 20 dakika bekletin. Sonra soğuk suyla, su berrak akana kadar yıkayıp süzün — nişastası gidince pilav tane tane olur.',
      'Tencerede tereyağını orta ateşte eritin. Şehriyeleri ekleyip sürekli karıştırarak koyu pembe olana kadar kavurun — gözünüzü ayırmayın, bir anda yanabilir.',
      'Süzülmüş pirinci ekleyin ve 3 dakika, taneler cam gibi parlayana kadar birlikte kavurun.',
      '3 su bardağı sıcak su ve kalan tuzu ekleyin. Bir kez karıştırıp kapağı kapatın; bir daha karıştırmak yok!',
      'Önce orta ateşte kaynamasını bekleyin, sonra ocağı en kısığa alın ve suyunu tamamen çekene kadar 10-12 dakika pişirin.',
      'Ocağı kapatın; kapağın altına kağıt havlu yerleştirip 15 dakika demlendirin. Havlu fazla buharı emer, pilav kuru ve tane tane olur. Nazikçe karıştırıp servis edin.',
    ],
  },
  {
    isim: 'Bulgur Pilavı', mutfak: M, kategori: 'Pilav & Makarna', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Bulgur', '2 su bardağı (340 g, pilavlık)'],
      ['Soğan', '1 adet'],
      ['Sivri Biber', '2 adet'],
      ['Domates', '2 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Soğanı ve sivri biberleri küçük küpler halinde doğrayın; domatesleri rendeleyin. Pilavlık (iri) bulgur kullanın, köftelik (ince) bulgurdan pilav lapa olur.',
      'Kalın tabanlı tencerede tereyağını eritip soğanı 3-4 dakika, yumuşayana kadar kavurun; biberleri ekleyip 2 dakika daha çevirin.',
      'Salçayı ekleyip 1 dakika, ham kokusu geçene kadar kavurun; rendelenmiş domatesi ekleyip suyu çekilene ve yağı üzerine çıkana kadar 3-4 dakika pişirin.',
      'Bulguru ekleyin (bulgur pirinç gibi uzun uzun yıkanmaz; kısaca durulayıp süzmek yeter). Baharatlı sosla 2-3 dakika kavurun ki her tane yağı emsin — bu kavurma bulgur pilavını tane tane yapar.',
      '3 su bardağı SICAK su ve tuzu ekleyin (bulgur için su:bulgur oranı yaklaşık 1,5:1\'dir). Bir kez karıştırıp kapağı kapatın. Önce kaynatın, sonra ateşi en kısığa alıp suyunu tamamen çekene kadar 12-15 dakika pişirin.',
      'Ocaktan alıp kapağın altına bir kâğıt havlu koyup 10 dakika demlendirin (havlu fazla buharı emer, pilav dağılmaz). Çatalla havalandırarak karıştırın. Cacık ve yoğurtla, ya da et yemeklerinin yanında servis edin.',
    ],
  },
  {
    isim: 'İç Pilav', mutfak: M, kategori: 'Pilav & Makarna', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Pirinç', '2 su bardağı (360 g)'],
      ['Çam Fıstığı', '2 yemek kaşığı'],
      ['Kuru Üzüm', '2 yemek kaşığı'],
      ['Soğan', '1 adet'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Tarçın', 'yarım çay kaşığı'],
      ['Maydanoz', 'birkaç dal'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Pirinci tuzlu sıcak suda 20 dakika bekletip yıkayın. Kuru üzümleri de ılık suda 10 dakika bekletin.',
      'Tencerede tereyağını eritip çam fıstıklarını kısık ateşte, sürekli karıştırarak pembeleştirin — fıstıklar saniyeler içinde yanabilir, başından ayrılmayın.',
      'İnce doğranmış soğanı ekleyip 5 dakika yumuşatın.',
      'Pirinci ekleyip 3 dakika kavurun.',
      'Süzülmüş üzümleri, tarçını, karabiberi, tuzu ve 3 su bardağı sıcak suyu ekleyin.',
      'Kapağı kapatıp kısık ateşte suyunu çekene kadar 12 dakika pişirin; 15 dakika demlendirin.',
      'Kıyılmış maydanozu ekleyip nazikçe karıştırın. Tavuğun yanına da yakışır, tek başına da yenir.',
    ],
  },
  {
    isim: 'Nohutlu Pilav', mutfak: M, kategori: 'Pilav & Makarna', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Pirinç', '2 su bardağı (360 g)'],
      ['Nohut', '1 su bardağı haşlanmış (160 g)'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Pirinci bir kaseye alıp üzerine 1 tatlı kaşığı tuz ve sıcak su ekleyin, 20 dakika bekletin. Sonra soğuk suyla, su berrak akana kadar durulayıp süzün. Bu bekletme ve yıkama, pirincin nişastasını alıp pilavın tane tane olmasını sağlar.',
      'Nohutları bir gece ıslatıp yumuşayana kadar haşlayın (ya da vakit yoksa hazır haşlanmış nohut kullanın; suyunu süzüp durulayın). Kabuklarını sevmiyorsanız haşladıktan sonra avuçlarınız arasında ovup ayıklayabilirsiniz.',
      'Kalın tabanlı tencerede tereyağını eritin, süzülmüş pirinci ekleyip 3 dakika, taneler cam gibi parlayana kadar kavurun. Bu kavurma pilavın olmazsa olmazı.',
      'Nohutları ekleyip 1 dakika birlikte çevirin.',
      '3 su bardağı sıcak su ve kalan tuzu ekleyin. Bir kez karıştırıp kapağı kapatın; önce kaynatın, sonra ateşi en kısığa alıp suyunu tamamen çekene kadar 12 dakika pişirin. Kapağı sık sık açıp karıştırmayın.',
      'Ocaktan alıp kapağın altına kâğıt havlu koyarak 15 dakika demlendirin, sonra çatalla havalandırın. Suyun yerine tavuk suyu kullanırsanız lezzeti kat kat artar — düğün pilavı böyle yapılır.',
    ],
  },
  {
    isim: 'Fırın Makarna', mutfak: M, kategori: 'Pilav & Makarna', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Makarna', '500 g (kalem veya burgu)'],
      ['Yumurta', '3 adet'],
      ['Süt', '2 su bardağı (400 ml)'],
      ['Kaşar Peyniri', '2 su bardağı rendelenmiş (160 g)'],
      ['Beyaz Peynir', '100 g (isteğe bağlı)'],
      ['Tereyağı', '1 yemek kaşığı (20 g)'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Makarnayı paketin yazdığından 2 dakika az haşlayın — fırında pişmeye devam edecek. Süzüp içine tereyağını karıştırın, yapışmasın.',
      'Sos için: yumurta, süt, tuz ve karabiberi bir kasede çırpın.',
      'Makarnanın içine kaşarın yarısını ve ufalanmış beyaz peyniri karıştırın.',
      'Yağlanmış fırın kabına makarnayı yayın; sütlü karışımı üzerine eşit şekilde dökün. Kabı hafifçe sallayın, sos her yere ulaşsın.',
      'Kalan kaşarı üzerine bolca serpin.',
      'Önceden ısıtılmış 180 derece fırında 25-30 dakika, üzeri altın rengi kızarana kadar pişirin. 10 dakika dinlendirip dilimleyin — çıtır köşeleri kapışılır!',
    ],
  },
  {
    isim: 'Cevizli Erişte', mutfak: M, kategori: 'Pilav & Makarna', sure: 25, tur: 'yemek',
    malzemeler: [
      ['Erişte', '400 g'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Ceviz', '1 su bardağı çekilmiş (100 g)'],
      ['Lor Peyniri', '150 g'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Bol suyu kaynatıp tuzu ekleyin; erişteleri 8-10 dakika, yumuşayana kadar haşlayın ve süzün.',
      'Geniş tavada tereyağını eritin; hafif kestane rengi alana kadar 1-2 dakika bekleyin — bu "kızmış tereyağı" eriştenin ruh ikizidir.',
      'Cevizleri ekleyip 1 dakika kavurun.',
      'Erişteleri tavaya alıp 2-3 dakika, tereyağıyla iyice harmanlanana kadar çevirin.',
      'Ocağı kapatın, lor peynirini üzerine serpin ve bir kez karıştırıp hemen servis edin.',
    ],
  },
  {
    isim: 'Sebzeli Bulgur Pilavı', mutfak: M, kategori: 'Pilav & Makarna', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Bulgur', '2 su bardağı (340 g)'],
      ['Kabak', '1 adet'],
      ['Havuç', '1 adet'],
      ['Sivri Biber', '2 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Kabak ve havucu küçük küpler, biberleri minik halkalar halinde doğrayın.',
      'Zeytinyağında önce havucu 3 dakika, sonra kabak ve biberi ekleyip 4 dakika soteleyin.',
      'Salçayı ekleyip 1 dakika kavurun.',
      'Yıkanmış bulguru ekleyip 2 dakika karıştırın.',
      '3 su bardağı sıcak su ve tuzu ekleyin; kapağı kapatıp kısık ateşte 12-15 dakika pişirin.',
      '10 dakika demlendirip havalandırarak karıştırın. Yoğurtla servis edin.',
    ],
  },

  // ─── HAMUR İŞİ ───
  {
    isim: 'Sigara Böreği', mutfak: M, kategori: 'Hamur İşi', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Yufka', '3 adet'],
      ['Beyaz Peynir', '250 g'],
      ['Maydanoz', 'yarım demet'],
      ['Ayçiçek Yağı', 'kızartma için (1,5 su bardağı)'],
    ],
    adimlar: [
      'Peyniri bir kasede çatalla ezin; ince kıyılmış maydanozu ekleyip karıştırın.',
      'Yufkayı tezgaha serin. Önce ikiye, sonra her yarımı üçgen dilimler halinde kesin (bir yufkadan 8 üçgen çıkar).',
      'Her üçgenin geniş kenarına bir tatlı kaşığı peynirli harç koyun.',
      'Geniş kenardan sarmaya başlayın; bir tur sarınca iki yan ucu içe katlayıp sıkıca sigara gibi sarmaya devam edin.',
      'Uç kısmına parmağınızla biraz su sürüp yapıştırın — kızarırken açılmasın.',
      'Yağı orta ateşte kızdırın (çok kızgın olursa içi ısınmadan dışı yanar). Börekleri azar azar atıp her tarafı altın sarısı olana kadar çevirerek kızartın.',
      'Kağıt havluya alıp fazla yağını verdirin. Çayla sıcak servis edin!',
    ],
  },
  {
    isim: 'Peynirli Gözleme', mutfak: M, kategori: 'Hamur İşi', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Un', '3 su bardağı (360 g)'],
      ['Beyaz Peynir', '200 g'],
      ['Maydanoz', 'birkaç dal'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Unu geniş kaba eleyin, tuzu ekleyin. Ortasını havuz gibi açıp 1 su bardağı ılık suyu azar azar ekleyerek yoğurun.',
      'Kulak memesi yumuşaklığında bir hamur elde edince üzerini nemli bezle örtüp 20 dakika dinlendirin. Dinlenen hamur kolay açılır.',
      'Peyniri ezip kıyılmış maydanozla karıştırın.',
      'Hamuru 4 bezeye ayırın. Unlanmış tezgahta her bezeyi oklavayla, tabak büyüklüğünde incecik açın.',
      'Yarısına peynirli harcı yayıp boş yarısını üzerine kapatın; kenarlarını bastırın.',
      'Teflon tavayı (veya sacı) orta ateşte ısıtın. Gözlemeyi yağsız tavada, her yüzü kahverengi benekler alana kadar 2-3\'er dakika pişirin.',
      'Sıcakken üzerine tereyağı sürün — eriyen tereyağı gözlemenin tacıdır.',
    ],
  },
  {
    isim: 'Kıymalı Pide', mutfak: M, kategori: 'Hamur İşi', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Un', '3,5 su bardağı (420 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Kıyma', '300 g'],
      ['Soğan', '1 adet'],
      ['Sivri Biber', '2 adet'],
      ['Domates', '1 adet'],
      ['Tereyağı', '2 yemek kaşığı (sürmek için)'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
      ['Pul Biber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Mayayı ve şekeri 1,5 su bardağı ılık suda eritin; 5 dakika bekleyin, üzeri köpürünce maya canlanmış demektir.',
      'Unu ve tuzu ekleyip 10 dakika, ele yapışmayan yumuşak bir hamur olana kadar yoğurun. Üzerini örtüp sıcak bir köşede 40 dakika, iki katına çıkana kadar mayalandırın.',
      'Harç: kıymayı, minik doğranmış soğan, biber ve domatesle çiğ olarak karıştırın; tuz, karabiber ve pul biberi ekleyin. Pişmiş değil çiğ harç — fırında etin suyu pideye işler.',
      'Hamuru 4 bezeye bölün. Her bezeyi unlu tezgahta uzun bir elips şeklinde, yarım santim kalınlığında açın.',
      'Harcı ortaya boydan boya yayın; kenar boşluğu bırakın. İki uzun kenarı harcın üzerine hafifçe kıvırın, uçları birleştirip kayık şekli verin.',
      'Pideleri yağlı kağıt serili tepsiye alın. Önceden ısıtılmış 230 derece fırında 12-15 dakika, kenarları kızarana kadar pişirin.',
      'Çıkar çıkmaz kenarlarına tereyağı sürün, dilimleyip sıcak servis edin.',
    ],
  },
  {
    isim: 'Lahmacun', mutfak: M, kategori: 'Hamur İşi', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Un', '3 su bardağı (360 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Kıyma', '250 g (yağlı)'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['Sivri Biber', '2 adet'],
      ['Domates', '2 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Maydanoz', 'yarım demet'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Limon', 'servis için'],
    ],
    adimlar: [
      'Hamur: mayayı 1 su bardağı ılık suda eritin; un ve tuzla yumuşak bir hamur yoğurup 30 dakika mayalandırın.',
      'Harç: soğan, sarımsak, biber, domates ve maydanozu robotta çekin; süzgeçte 5 dakika süzün — sulu harç hamuru ıslatır. Kıyma, salça, pul biber ve tuzla karıştırın.',
      'Hamuru 6 küçük bezeye ayırın. Her bezeyi tabak büyüklüğünde, olabildiğince ince açın — lahmacunun sırrı incecik hamurdadır.',
      'Harcı ince bir tabaka halinde, kenarlarına kadar parmaklarınızla yayın (kalın sürmeyin, kurur).',
      'Fırının en yüksek ayarını (250 derece) önceden iyice ısıtın; tepsiyi de fırında ısıtırsanız tabanı çıtır olur.',
      'Lahmacunları sıcak tepsiye alıp 6-8 dakika, kenarları hafif kızarana kadar pişirin.',
      'İçine maydanoz koyup limon sıkın, dürüm yapıp afiyetle yiyin!',
    ],
  },
  {
    isim: 'Mantı', mutfak: M, kategori: 'Hamur İşi', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Un', '3 su bardağı (360 g)'],
      ['Yumurta', '1 adet'],
      ['Kıyma', '250 g'],
      ['Soğan', '1 adet'],
      ['Yoğurt', '2 su bardağı (400 g)'],
      ['Sarımsak', '2 diş'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Salça', '1 tatlı kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Kuru Nane', '1 çay kaşığı'],
      ['Tuz', '2 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Hamur: un, yumurta, 1 çay kaşığı tuz ve yarım su bardağı suyla sert bir hamur yoğurun. Nemli bezle örtüp 30 dakika dinlendirin.',
      'İç harç: kıymayı rendelenmiş soğan, tuz ve karabiberle karıştırın.',
      'Hamuru ikiye bölüp unlu tezgahta olabildiğince ince açın (2-3 mm). Bıçakla 3x3 cm karelere kesin.',
      'Her karenin ortasına nohut büyüklüğünde harç koyun. Dört köşeyi ortada birleştirip parmak uçlarınızla sıkıca yapıştırın — bohça gibi.',
      'Bol tuzlu suyu kaynatın; mantıları atıp 8-10 dakika, hamur yumuşayana kadar haşlayın ve delikli kepçeyle alın.',
      'Yoğurdu ezilmiş sarımsak ve bir tutam tuzla çırpın; mantıların üzerine dökün.',
      'Tavada tereyağını eritip salça, pul biber ve naneyi ekleyin; köpüren sosu yoğurdun üzerine gezdirin. Elleriniz dert görmesin!',
    ],
  },
  {
    isim: 'Ispanaklı Börek', mutfak: M, kategori: 'Hamur İşi', sure: 55, tur: 'yemek',
    malzemeler: [
      ['Yufka', '3 adet'],
      ['Ispanak', '500 g'],
      ['Soğan', '1 adet'],
      ['Lor Peyniri', '150 g'],
      ['Yumurta', '2 adet'],
      ['Süt', '1 su bardağı (200 ml)'],
      ['Ayçiçek Yağı', 'yarım çay bardağı'],
      ['Çörek Otu', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Ispanakları yıkayıp doğrayın. Soğanı 2 kaşık yağda kavurun, ıspanakları ekleyip suyu çekilene kadar 5-6 dakika pişirin; tuzlayın ve soğutun. Lor peynirini karıştırın.',
      'Sos: 1 yumurta + 1 yumurta akı (sarısını üstü için ayırın), süt ve kalan yağı çırpın.',
      'Fırın tepsisini yağlayın. İlk yufkayı serin (kenarları taşsın), üzerine sostan gezdirin.',
      'İkinci yufkayı buruşturarak serin — buruşuk katlar böreği kat kat ve kabarık yapar. Yine sos gezdirip ıspanaklı harcın yarısını yayın.',
      'Taşan kenarları içe katlayın; kalan yufka ve harçla katları tekrarlayıp en üstü düz yufkayla kapatın.',
      'Ayırdığınız yumurta sarısını üzerine sürün, çörek otu serpin. Dilimlere kesin — pişmeden kesmek servisi kolaylaştırır.',
      'Önceden ısıtılmış 180 derece fırında 35 dakika, üzeri kızarana kadar pişirin.',
    ],
  },
  {
    isim: 'Poğaça', mutfak: M, kategori: 'Hamur İşi', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Un', '4 su bardağı (480 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Süt', '1 su bardağı ılık (200 ml)'],
      ['Ayçiçek Yağı', 'yarım su bardağı (100 ml)'],
      ['Yumurta', '2 adet (1 tanesi üzeri için)'],
      ['Şeker', '1 yemek kaşığı'],
      ['Beyaz Peynir', '200 g (iç için)'],
      ['Maydanoz', 'birkaç dal'],
      ['Çörek Otu', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Ilık süte maya ve şekeri ekleyip eritin; 5 dakika köpürmesini bekleyin.',
      'Geniş kaba mayalı sütü, yağı, 1 yumurtanın akını (sarısı üstüne) ve tuzu koyun. Unu azar azar ekleyerek, ele yapışmayan yumuşacık bir hamur yoğurun.',
      'Üzerini örtüp sıcak yerde 30-40 dakika, hamur iki katına çıkana kadar mayalandırın.',
      'Peyniri ezip maydanozla karıştırın.',
      'Hamurdan mandalina büyüklüğünde bezeler koparın. Her bezeyi avucunuzda açın, ortasına peynir koyup kapatın ve yuvarlayın.',
      'Poğaçaları yağlı kağıtlı tepsiye aralıklı dizin. Üzerlerine yumurta sarısı sürüp çörek otu serpin.',
      'Önceden ısıtılmış 180 derece fırında 20-25 dakika, üzerleri parlak kahve olana kadar pişirin. Puf puf poğaçalar hazır!',
    ],
  },
  {
    isim: 'Pişi', mutfak: M, kategori: 'Hamur İşi', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Un', '3,5 su bardağı (420 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Ayçiçek Yağı', 'kızartma için (2 su bardağı)'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Mayayı ve şekeri 1,5 su bardağı ılık suda eritip 5 dakika bekletin.',
      'Un ve tuzu ekleyip yumuşak, hafif ele yapışan bir hamur yoğurun.',
      'Üzerini örtüp 30-40 dakika, iki katına çıkana kadar mayalandırın.',
      'Elinizi yağlayıp hamurdan yumurta büyüklüğünde parçalar koparın; her birini elinizle bastırarak yassı yuvarlaklar yapın (ortasına parmakla delik açarsanız daha iyi kabarır).',
      'Bol yağı orta-yüksek ateşte kızdırın; küçük bir hamur parçası atınca hemen yüzeye çıkmalı.',
      'Pişileri azar azar atıp her yüzünü 1-2 dakika, altın rengi kabarana kadar kızartın.',
      'Kağıt havluya alın. Yanına peynir, üstüne pudra şekeri — nasıl seviyorsanız öyle yiyin, ikisi de olur!',
    ],
  },
  {
    isim: 'Su Böreği', mutfak: M, kategori: 'Hamur İşi', sure: 100, tur: 'yemek',
    malzemeler: [
      ['Un', '4 su bardağı (480 g)'],
      ['Yumurta', '4 adet'],
      ['Beyaz Peynir', '300 g'],
      ['Maydanoz', 'yarım demet'],
      ['Tereyağı', '125 g'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Un, yumurta ve tuzla orta sertlikte bir hamur yoğurun; 30 dakika dinlendirin. Hamuru 6 bezeye ayırın.',
      'Her bezeyi unlu tezgahta, tepsinizden biraz büyük ve olabildiğince ince açın.',
      'Geniş tencerede tuzlu su kaynatın; yanına da içinde soğuk su olan büyük bir kap hazırlayın.',
      'Yufkaları tek tek kaynar suya atıp 30-40 saniye haşlayın; delikli kepçeyle alıp hemen soğuk suya sokun, sonra temiz bir beze serip suyunu alın. Bu haşlama, su böreğine o eşsiz yumuşaklığı verir.',
      'Tereyağını eritin. Yağlanmış tepsiye ilk haşlanmış yufkayı serin, üzerine eritilmiş tereyağı gezdirin. Her katta tekrarlayın.',
      'Üçüncü kattan sonra ezilmiş peynir + maydanoz harcını yayın; kalan yufkalarla devam edin.',
      'En üst kata bolca tereyağı sürün. 190 derece fırında, üzeri altın rengi olana kadar 30-35 dakika pişirin (ilk 15 dakikadan sonra alt-üst çevirebilirseniz iki taraf da kızarır).',
      'Dilimleyip çayla servis edin — emek ister ama su böreği gibisi yoktur.',
    ],
  },
  {
    isim: 'Açma', mutfak: M, kategori: 'Hamur İşi', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Un', '4,5 su bardağı (540 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Süt', '1 su bardağı ılık (200 ml)'],
      ['Ayçiçek Yağı', 'yarım su bardağı (100 ml)'],
      ['Yumurta', '2 adet (1 tanesi üzeri için)'],
      ['Şeker', '2 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı yumuşak (40 g)'],
      ['Susam', '1 yemek kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Ilık sütte maya ve şekeri eritip 5 dakika bekletin.',
      'Yağ, 1 yumurta akı ve tuzu ekleyin; unu azar azar katarak çok yumuşak, hafif yapışkan bir hamur yoğurun. Açmanın pofuduğu bu yumuşak hamurdan gelir.',
      'Üzerini örtüp 45 dakika, iki katına çıkana kadar mayalandırın.',
      'Hamurdan iri bezeler koparıp her birini elinizle uzun şerit haline getirin; şeride yumuşak tereyağı sürün.',
      'Şeridi kendi etrafında burun, sonra iki ucunu birleştirip simit gibi halka yapın.',
      'Açmaları tepsiye dizip 15 dakika daha dinlendirin; üzerlerine yumurta sarısı sürüp susam serpin.',
      '180 derece fırında 20-22 dakika, üzerleri parlak kahverengi olana kadar pişirin.',
    ],
  },
  {
    isim: 'Bazlama', mutfak: M, kategori: 'Hamur İşi', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Un', '4 su bardağı (480 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Yoğurt', '2 yemek kaşığı'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Tereyağı', 'üzerine sürmek için'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Mayayı ve şekeri 1,5 su bardağı ılık suda eritin; 5 dakika bekletin.',
      'Yoğurt, tuz ve unu ekleyip yumuşak bir hamur yoğurun.',
      'Üzerini örtüp 45 dakika mayalandırın.',
      'Hamuru 6 bezeye ayırın; her bezeyi elinizle veya oklavayla 1 cm kalınlığında yuvarlaklar halinde açın. 10 dakika daha dinlendirin.',
      'Teflon tavayı veya sacı orta ateşte ısıtın (yağsız).',
      'Bazlamaları tek tek tavaya koyun; altı benek benek kızarınca çevirin. Doğru pişiyorsa balon gibi kabaracak! Her yüzü 2-3 dakika pişirin.',
      'Sıcakken üzerine tereyağı sürün. Köy kahvaltısının yıldızı hazır.',
    ],
  },

  // ─── TATLILAR ───
  {
    isim: 'Fırın Sütlaç', mutfak: M, kategori: 'Tatlılar', sure: 70, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Pirinç', 'yarım su bardağı (90 g)'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '2 yemek kaşığı'],
      ['Vanilya', '1 paket'],
    ],
    adimlar: [
      'Pirinci yıkayıp 1,5 su bardağı suyla, suyunu çekene kadar 15 dakika haşlayın.',
      'Sütü ekleyip orta ateşte, dibi tutmasın diye ara ara karıştırarak kaynatın.',
      'Şekeri ekleyin. Nişastayı yarım çay bardağı soğuk sütte (veya suda) ezip tencereye azar azar, karıştırarak ekleyin.',
      'Kısık ateşte 10 dakika, hafif koyulaşana kadar karıştırarak pişirin; vanilyayı ekleyip ocağı kapatın.',
      'Fırına dayanıklı kaselere paylaştırın. Kaseleri derin bir fırın tepsisine dizin ve tepsiye, kaselerin yarısına gelecek kadar soğuk su doldurun (benmari usulü — taşmayı ve dibinin yanmasını önler).',
      'Fırının üst ızgarası (turbo/gril) açık şekilde 220 derecede, üzerleri kahverengi lekeler alana kadar 10-15 dakika pişirin.',
      'Soğuduktan sonra buzdolabında en az 2 saat bekletin. Soğuk sütlaç bambaşkadır!',
    ],
  },
  {
    isim: 'Kazandibi', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '4 yemek kaşığı'],
      ['Un', '2 yemek kaşığı'],
      ['Tereyağı', '1 yemek kaşığı (tepsi için)'],
      ['Pudra Şekeri', '3 yemek kaşığı (taban için)'],
      ['Vanilya', '1 paket'],
      ['Tarçın', 'servis için'],
    ],
    adimlar: [
      'Süt, şeker, nişasta ve unu tencerede soğukken çırpın — soğukken karıştırmak topaklanmayı önler.',
      'Orta ateşte, sürekli karıştırarak muhallebi koyulaşana kadar 10-12 dakika pişirin; vanilyayı ekleyin.',
      'Dikdörtgen bir tepsinin tabanını tereyağıyla yağlayıp pudra şekerini eşit şekilde serpin.',
      'Muhallebiyi tepsiye dökün ve düzleyin.',
      'Şimdi kritik kısım: tepsiyi doğrudan ocağın üzerine koyun (orta ateş) ve tepsiyi döndüre döndüre tabanını yakın. Şeker karamelleşirken çıtırtı duyacaksınız; hafif yanık koku normal, istediğimiz tam da bu. 6-8 dakika sürer.',
      'Soğuduktan sonra buzdolabında 3 saat dinlendirin.',
      'Dikdörtgen dilimler kesin; spatulayla alıp yanık tarafı üste gelecek şekilde ters çevirerek tabağa koyun. Tarçın serpin ve rulo yapmadan ya da yaparak — keyfinize kalmış — servis edin.',
    ],
  },
  {
    isim: 'Muhallebi', mutfak: M, kategori: 'Tatlılar', sure: 25, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '4 yemek kaşığı'],
      ['Vanilya', '1 paket'],
      ['Fındık', '2 yemek kaşığı çekilmiş (üzeri için)'],
      ['Tarçın', 'üzeri için'],
    ],
    adimlar: [
      'Süt, şeker ve nişastayı tencerede soğukken çırpma teliyle karıştırın.',
      'Tencereyi orta ateşe alın ve karıştırmayı hiç bırakmadan pişirin. Karıştırmayı bırakırsanız dibi tutar, topak olur — kolunuz yorulacak ama değecek!',
      'Kaynayıp koyulaşınca (kaşığın arkasını kaplayınca) 2 dakika daha pişirin.',
      'Vanilyayı ekleyip son bir kez karıştırın ve ocağı kapatın.',
      'Kaselere paylaştırın. Oda sıcaklığına gelince buzdolabında 2 saat soğutun.',
      'Üzerine çekilmiş fındık veya tarçın serperek servis edin.',
    ],
  },
  {
    isim: 'İrmik Helvası', mutfak: M, kategori: 'Tatlılar', sure: 40, tur: 'yemek',
    malzemeler: [
      ['İrmik', '2 su bardağı (340 g)'],
      ['Tereyağı', '125 g'],
      ['Çam Fıstığı', '2 yemek kaşığı'],
      ['Süt', '2 su bardağı (400 ml)'],
      ['Su', '1 su bardağı'],
      ['Şeker', '2 su bardağı (400 g)'],
      ['Tarçın', 'servis için'],
    ],
    adimlar: [
      'Önce şerbeti hazırlayın: süt, su ve şekeri kaynatıp şeker eriyince ocağı kapatın; sıcak bekletin.',
      'Geniş tencerede tereyağını eritin; irmiği ve çam fıstıklarını ekleyin.',
      'Kısık ateşte, tahta kaşıkla sürekli karıştırarak kavurun. Bu iş sabır ister: 20-25 dakika boyunca karıştırın. İrmik koyu altın rengine dönüp fıstıklar pembeleşince ve mis gibi koku mutfağı sarınca hazırdır.',
      'Ocağı en kısığa alın ve sıcak şerbeti dikkatlice, azar azar dökün — fokurdayıp sıçrayabilir, elinizi uzak tutun.',
      'Karıştırıp kapağı kapatın; 10 dakika, suyunu tamamen çekene kadar kısık ateşte pişirin.',
      'Ocağı kapatıp 10 dakika demlendirin. Kaşıkla havalandırıp servis tabağına alın; tarçın serpin. Kavrulmuş irmiğin kokusu evi bayram yerine çevirir!',
    ],
  },
  {
    isim: 'Revani', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['İrmik', '1 su bardağı (170 g)'],
      ['Un', '1 su bardağı (120 g)'],
      ['Yumurta', '3 adet'],
      ['Yoğurt', '1 su bardağı (200 g)'],
      ['Şeker', 'kek için yarım, şerbet için 2,5 su bardağı'],
      ['Ayçiçek Yağı', 'yarım su bardağı (100 ml)'],
      ['Kabartma Tozu', '1 paket'],
      ['Vanilya', '1 paket'],
      ['Limon', 'çeyrek adet (şerbet için)'],
      ['Hindistan Cevizi Rendesi', 'üzeri için'],
    ],
    adimlar: [
      'Önce şerbet (şerbetli tatlıda kural: ya şerbet sıcak tatlı soğuk, ya tersi): 2,5 su bardağı şeker + 3 su bardağı suyu kaynatın; limon dilimini atıp 10 dakika kaynatıp soğumaya bırakın.',
      'Kek: yumurta ve yarım bardak şekeri, renk açılana kadar 3-4 dakika çırpın.',
      'Yoğurt ve yağı ekleyip çırpın; irmik, un, kabartma tozu ve vanilyayı ekleyip spatulayla karıştırın.',
      'Hamuru yağlanmış fırın kabına dökün; 170 derece fırında 30-35 dakika, üzeri kızarana kadar pişirin (kürdan batırın, temiz çıksın).',
      'Fırından çıkan sıcak kekin üzerine soğuk şerbeti kepçe kepçe, her yerine gezdirerek dökün.',
      'Üzerini kapatıp 1 saat bekleyin; kek şerbeti tamamen çeksin. Hindistan cevizi serpip dilimleyerek servis edin.',
    ],
  },
  {
    isim: 'Şekerpare', mutfak: M, kategori: 'Tatlılar', sure: 55, tur: 'yemek',
    malzemeler: [
      ['Un', '2,5 su bardağı (300 g)'],
      ['İrmik', 'yarım su bardağı (85 g)'],
      ['Tereyağı', '125 g (oda sıcaklığında)'],
      ['Pudra Şekeri', '1 su bardağı (120 g)'],
      ['Yumurta', '1 adet'],
      ['Kabartma Tozu', '1 paket'],
      ['Badem', '20 adet (üzeri için)'],
      ['Şeker', '2,5 su bardağı (şerbet için)'],
      ['Limon', 'çeyrek adet'],
    ],
    adimlar: [
      'Şerbet: 2,5 bardak şeker ve 3 bardak suyu 10 dakika kaynatın, limonu sıkıp soğumaya bırakın.',
      'Hamur: yumuşak tereyağı, pudra şekeri ve yumurtayı karıştırın; irmik, kabartma tozu ve unu azar azar ekleyip yumuşak bir hamur yapın. Fazla yoğurmayın — fazla yoğrulan hamur sertleşir.',
      'Ceviz büyüklüğünde parçalar koparıp pürüzsüz toplar yapın; aralıklı olarak tepsiye dizin (pişince yayılırlar).',
      'Her topun ortasına hafifçe bastırıp birer badem yerleştirin.',
      '170 derece fırında 20-25 dakika pişirin. Çok kızartmayın — açık altın sarısı yeterli; koyulaşırsa şerbeti çekmez.',
      'Fırından çıkan sıcak şekerparelerin üzerine soğuk şerbeti dökün.',
      'En az 2 saat bekleyin; şerbeti çeke çeke yumuşacık olacaklar.',
    ],
  },
  {
    isim: 'Ev Baklavası', mutfak: M, kategori: 'Tatlılar', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Baklavalık Yufka', '1 paket (40 yaprak)'],
      ['Ceviz', '2,5 su bardağı çekilmiş (250 g)'],
      ['Tereyağı', '250 g'],
      ['Şeker', '3 su bardağı (şerbet için)'],
      ['Limon', 'çeyrek adet'],
    ],
    adimlar: [
      'Şerbet: 3 bardak şeker + 3,5 bardak suyu kaynatın; 15 dakika kaynayıp hafif koyulaşınca limon sıkın ve soğumaya bırakın.',
      'Tereyağını eritin; üstteki köpüğü kaşıkla alın (köpüksüz yağ baklavayı daha parlak yapar).',
      'Tepsiyi yağlayın. Yufkaları teker teker serin: her 2 yaprakta bir, fırçayla eritilmiş tereyağı gezdirin. İlk 20 yaprağı bu şekilde dizin.',
      'Çekilmiş cevizi eşit şekilde yayın.',
      'Kalan 20 yaprağı da aynı şekilde, 2 yaprakta bir yağlayarak dizin. En üste bolca yağ sürün.',
      'Keskin bıçakla önce boyuna şeritler, sonra çapraz keserek baklava dilimleri oluşturun. Pişmeden kesmek şart — piştikten sonra kesilmez, dağılır.',
      'Önceden ısıtılmış 170 derece fırında 35-40 dakika, üzeri altın rengi olana kadar pişirin.',
      'Fırından çıkan sıcak baklavaya soğuk şerbeti yavaşça, her yerine gezdirerek dökün. Cızırtı sesi şerbetin doğru sıcaklıkta olduğunun kanıtı! En az 2 saat dinlendirin.',
    ],
  },
  {
    isim: 'Künefe', mutfak: M, kategori: 'Tatlılar', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Kadayıf', '500 g'],
      ['Lor Peyniri', '300 g (tuzsuz; künefelik peynir idealdir)'],
      ['Tereyağı', '150 g'],
      ['Şeker', '2 su bardağı (şerbet için)'],
      ['Antep Fıstığı', '2 yemek kaşığı çekilmiş'],
      ['Limon', 'çeyrek adet'],
    ],
    adimlar: [
      'Şerbet: 2 bardak şeker + 2 bardak suyu 10 dakika kaynatıp limon sıkın; ılık bekletin (künefede şerbet ılık dökülür).',
      'Kadayıfı bıçakla ince ince kıyın — uzun teller sarma yapar, kısa teller daha iyi.',
      'Tereyağını eritip kadayıfın üzerine dökün; elinizle iyice, her tel yağlanana kadar harmanlayın.',
      'Yağlanmış geniş tavaya (veya künefe tepsisine) kadayıfın yarısını koyup elinizle iyice bastırın.',
      'Peyniri eşit şekilde yayın; kenarlara 1 cm boşluk bırakın (peynir taşmasın).',
      'Kalan kadayıfı üzerine kapatıp yine iyice bastırın.',
      'Orta-kısık ateşte, tavayı döndüre döndüre alt tarafı altın kahve olana kadar 7-8 dakika pişirin. Sonra büyük bir tabak yardımıyla ters çevirip diğer tarafı da aynı şekilde pişirin.',
      'Sıcak künefenin üzerine ılık şerbeti dökün — cızz! Fıstık serpip hemen, peyniri uzaya uzaya yenecek sıcaklıkta servis edin.',
    ],
  },
  {
    isim: 'Aşure', mutfak: M, kategori: 'Tatlılar', sure: 120, tur: 'yemek',
    malzemeler: [
      ['Bulgur', '1 su bardağı (aşurelik buğday idealdir)'],
      ['Nohut', 'yarım su bardağı haşlanmış'],
      ['Kuru Fasulye', 'yarım su bardağı haşlanmış'],
      ['Kuru Kayısı', '8 adet'],
      ['Kuru Üzüm', 'yarım su bardağı'],
      ['Şeker', '2 su bardağı (400 g)'],
      ['Ceviz', 'yarım su bardağı'],
      ['Fındık', 'üzeri için'],
      ['Tarçın', 'üzeri için'],
    ],
    adimlar: [
      'Buğdayı (bulguru) bir gece önceden ıslatın. Nohut ve fasulyeyi de ayrı kaplarda ıslatıp ertesi gün yumuşayana kadar haşlayın.',
      'Buğdayı bol suyla (8 su bardağı) tencereye alın; taneler iyice yumuşayıp su hafif çorbamsı olana kadar 1 saat pişirin.',
      'Haşlanmış nohut ve fasulyeyi ekleyin.',
      'Kayısıları küçük doğrayıp üzümlerle birlikte ekleyin; 15 dakika birlikte kaynatın.',
      'Şekeri ekleyin ve karıştırarak 15 dakika daha pişirin. Kıvamı bal gibi, akışkan ama koyu olmalı; gerekirse sıcak su ekleyin.',
      'İri çekilmiş cevizi karıştırıp ocağı kapatın.',
      'Kaselere paylaştırın; soğuyunca üzerlerini fındık, ceviz ve tarçınla süsleyin. Komşulara dağıtmak serbest — aşurenin geleneği budur!',
    ],
  },
  {
    isim: 'Muzlu Magnolia', mutfak: M, kategori: 'Tatlılar', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '4 yemek kaşığı'],
      ['Vanilya', '1 paket'],
      ['Labne', '200 g'],
      ['Muz', '3 adet'],
      ['Bisküvi', '1 paket (150 g)'],
    ],
    adimlar: [
      'Süt, şeker ve nişastayı soğukken çırpıp orta ateşte, sürekli karıştırarak muhallebi kıvamına getirin; vanilyayı ekleyip ocaktan alın.',
      'Muhallebi ılıyınca labneyi ekleyip çırpın — labne, magnoliaya o ipeksi dokusunu verir.',
      '2 muzu çatalla ezip kremaya karıştırın.',
      'Bisküvileri poşete koyup oklavayla kırıntı haline getirin (robotta da çekebilirsiniz).',
      'Kaselere önce bir kat bisküvi kırıntısı, sonra muzlu krema koyun; katları tekrarlayın.',
      'En üstü bisküvi kırıntısı ve muz dilimleriyle süsleyin.',
      'Buzdolabında en az 2 saat soğutun. Kaşığı daldırınca katmanların görünmesi ayrı keyif!',
    ],
  },
  {
    isim: 'Kabak Tatlısı', mutfak: M, kategori: 'Tatlılar', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Bal Kabağı', '1 kg (temizlenmiş)'],
      ['Şeker', '1,5 su bardağı (300 g)'],
      ['Ceviz', '1 su bardağı iri çekilmiş'],
      ['Tahin', 'servis için (isteğe bağlı)'],
    ],
    adimlar: [
      'Kabağı kabuklarından ve çekirdeklerinden temizleyip iri dilimler halinde kesin.',
      'Dilimleri tencereye dizin ve şekeri üzerlerine eşit şekilde serpin.',
      'Kapağı kapatıp bir gece (en az 4 saat) bekletin. Sabah bakınca şaşırmayın: şeker, kabağın suyunu çekip şerbete dönüşmüş olacak. Su eklemeye gerek yok!',
      'Tencereyi kısık ateşe alın; kendi şerbetiyle, kapağı kapalı 35-40 dakika, kabaklar şeffaflaşıp yumuşayana kadar pişirin.',
      'Kapağı açıp 5 dakika daha kaynatın; şerbet koyulaşsın.',
      'Soğuduktan sonra servis tabağına alın; şerbetini üzerine gezdirin. Bol ceviz ve dilerseniz tahinle servis edin — Antep usulü tahinli kabak tatlısı başka bir alemdir.',
    ],
  },
  {
    isim: 'Ayva Tatlısı', mutfak: M, kategori: 'Tatlılar', sure: 70, tur: 'yemek',
    malzemeler: [
      ['Ayva', '3 adet büyük'],
      ['Şeker', '1,5 su bardağı (300 g)'],
      ['Limon', 'yarım adet'],
      ['Kaymak', 'servis için'],
      ['Antep Fıstığı', '2 yemek kaşığı çekilmiş'],
    ],
    adimlar: [
      'Ayvaları soyun, ikiye bölün ve çekirdek yuvalarını kaşıkla oyun. Kararmamaları için limonlu suda bekletin. Çekirdekleri atmayın!',
      'Ayvaları oyuk kısımları yukarı bakacak şekilde geniş tencereye dizin.',
      'Her yarımın üzerine ve oyuklarına şekeri paylaştırın. Çekirdekleri aralara atın — çekirdekler hem güzel kızıl rengi verir hem şerbeti pelte yapar.',
      '1 su bardağı su ekleyip kapağı kapatın; kısık ateşte 50-60 dakika, ayvalar yumuşayıp kızıl bir renk alana kadar pişirin. Renk için sabır gerekir, aceleyle olmaz.',
      'Kapağı açıp şerbet koyulaşana kadar 10 dakika daha pişirin.',
      'Soğuduktan sonra her yarımın oyuğuna bir top kaymak yerleştirip fıstık serpin. Bayram sofralarının klasiği hazır!',
    ],
  },
  {
    isim: 'Keşkül', mutfak: M, kategori: 'Tatlılar', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Badem', '1 su bardağı çekilmiş (100 g)'],
      ['Nişasta', '3 yemek kaşığı'],
      ['Yumurta', '2 adet (sadece sarısı)'],
      ['Vanilya', '1 paket'],
      ['Hindistan Cevizi Rendesi', 'üzeri için'],
    ],
    adimlar: [
      'Bademleri robotta un gibi olana kadar çekin — keşkülün kimliği bademdir.',
      'Tencerede süt, şeker, nişasta ve yumurta sarılarını soğukken çırpın.',
      'Çekilmiş bademleri ekleyip orta ateşe alın.',
      'Sürekli karıştırarak, koyulaşana kadar 12-15 dakika pişirin.',
      'Vanilyayı ekleyip ocağı kapatın; 2 dakika daha karıştırın.',
      'Kaselere paylaştırıp soğutun; buzdolabında 2 saat dinlendirin.',
      'Üzerine hindistan cevizi ve dilerseniz çekilmiş badem serperek servis edin.',
    ],
  },
  {
    isim: 'Güllaç', mutfak: M, kategori: 'Tatlılar', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Güllaç Yaprağı', '1 paket (10 yaprak)'],
      ['Süt', '1,5 litre'],
      ['Şeker', '2 su bardağı (400 g)'],
      ['Ceviz', '1,5 su bardağı çekilmiş'],
      ['Antep Fıstığı', 'üzeri için'],
      ['Vanilya', '1 paket (veya 1 kaşık gül suyu)'],
    ],
    adimlar: [
      'Sütü şekerle birlikte, şeker eriyene kadar ısıtın — kaynatmayın, ılık-sıcak arası olsun. Vanilyayı (ya da gül suyunu) ekleyin.',
      'Geniş bir tepsiye 1 güllaç yaprağını mat yüzü üste gelecek şekilde yerleştirin.',
      'Üzerine sıcak sütlü karışımdan kepçeyle gezdirin; yaprak yumuşayıp şeffaflaşacak.',
      'Her katta aynısını tekrarlayarak 5 yaprak dizin. Beşinci yaprağın üzerine çekilmiş cevizi yayın.',
      'Kalan 5 yaprağı da aynı şekilde, her katı sütleyerek dizin.',
      'Kalan sütü en üstten yavaşça dökün; yapraklar tamamen süte doysun.',
      'Buzdolabında 2 saat dinlendirin. Kare dilimler kesip üzerini bol antep fıstığıyla süsleyin. Ramazan sofralarının en zarif tatlısı!',
    ],
  },
  {
    isim: 'Tulumba Tatlısı', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Un', '1,5 su bardağı (180 g)'],
      ['Yumurta', '3 adet'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Nişasta', '1 yemek kaşığı'],
      ['İrmik', '1 yemek kaşığı'],
      ['Şeker', '3 su bardağı (şerbet için)'],
      ['Limon', 'çeyrek adet'],
      ['Ayçiçek Yağı', 'kızartma için (3 su bardağı)'],
    ],
    adimlar: [
      'Şerbet: 3 bardak şeker + 3 bardak suyu 15 dakika kaynatıp limon sıkın; tamamen soğumaya bırakın. Tulumbada şerbet buz gibi olmalı.',
      'Hamur: 1,5 su bardağı suyu tereyağıyla kaynatın. Unu bir kerede ekleyip tahta kaşıkla, top haline gelene kadar karıştırın; 2 dakika pişirip ocaktan alın.',
      'Hamur ılıyınca yumurtaları TEK TEK ekleyin; her yumurtadan sonra iyice yoğurun. İrmik ve nişastayı da ekleyin. Parlak, yumuşak ama akmayan bir hamur olmalı.',
      'Hamuru yıldız uçlu krema sıkma torbasına doldurun.',
      'ÖNEMLİ PÜF NOKTASI: yağı ısıtmadan, oda sıcaklığında tencereye koyun. Hamuru 3-4 cm parçalar halinde soğuk yağın içine sıkıp makasla kesin. Sonra tencereyi orta ateşe alın.',
      'Yağ yavaş yavaş ısınırken tulumbalar önce dibe çöker, sonra şişerek yüzeye çıkar. Karıştırarak her tarafı altın rengi kızarana kadar pişirin.',
      'Kızaran tulumbaları delikli kepçeyle alıp doğrudan soğuk şerbete atın; 4-5 dakika şerbette bekletip süzgeçli kepçeyle çıkarın. Dışı çıtır, içi şerbet dolu!',
    ],
  },
  {
    isim: 'Lokma', mutfak: M, kategori: 'Tatlılar', sure: 75, tur: 'yemek',
    malzemeler: [
      ['Un', '3 su bardağı (360 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Şeker', '1 tatlı kaşığı (hamur için) + 3 su bardağı (şerbet için)'],
      ['Nişasta', '1 yemek kaşığı'],
      ['Limon', 'çeyrek adet'],
      ['Ayçiçek Yağı', 'kızartma için'],
      ['Tarçın', 'üzeri için'],
      ['Tuz', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Şerbet: 3 bardak şeker + 3 bardak su, 15 dakika kaynasın; limon sıkıp soğutun.',
      'Hamur: mayayı 1 tatlı kaşığı şekerle 2 su bardağı ılık suda eritin. Un, nişasta ve tuzu ekleyip çırpma teliyle çırpın — bu hamur yoğrulmaz, cıvık bir hamurdur, boza kıvamında olmalı.',
      'Üzerini örtüp 1 saat mayalandırın; hamur köpük köpük kabaracak.',
      'Yağı kızdırın (orta-yüksek ateş). Bir elinizle avucunuza hamur alın, yumruğunuzu sıkın — baş parmakla işaret parmağınızın arasından çıkan hamuru yağlı bir kaşıkla kesip yağa bırakın. (Zor gelirse iki kaşıkla da şekil verebilirsiniz.)',
      'Lokmaları, altın rengi alana kadar çevire çevire kızartın.',
      'Kızaranları delikli kepçeyle alıp soğuk şerbetin içine atın; 2-3 dakika bekletip çıkarın.',
      'Üzerine tarçın serperek servis edin. Sıcak sıcak, yanında çayla!',
    ],
  },
  {
    isim: 'Trileçe', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Yumurta', '4 adet'],
      ['Şeker', '1 su bardağı (kek için) + yarım su bardağı (karamel için)'],
      ['Un', '1,5 su bardağı (180 g)'],
      ['Kabartma Tozu', '1 paket'],
      ['Vanilya', '1 paket'],
      ['Süt', '4 su bardağı (sosu için: 3 + karamel için: 1)'],
      ['Krema', '1 paket (200 ml)'],
    ],
    adimlar: [
      'Kek: yumurta ve 1 bardak şekeri, hacmi 3 katına çıkana kadar 5 dakika çırpın — kabarıklık bu çırpmadan gelir.',
      'Un, kabartma tozu ve vanilyayı eleyerek ekleyin; spatulayla, söndürmeden alttan üste karıştırın.',
      'Yağlı kağıt serili dikdörtgen kaba döküp 170 derece fırında 25 dakika pişirin. Soğumaya bırakın.',
      'Islatma sosu: 3 su bardağı süt ve kremayı karıştırın.',
      'Soğuyan kekin her yerini çatalla delik deşik edin — sosun içine işlemesi için ne kadar delik, o kadar iyi.',
      'Sütlü sosu kekin üzerine kepçe kepçe dökün. İlk başta "çok geldi" diye düşüneceksiniz ama kek hepsini emecek. Buzdolabında 2 saat dinlendirin.',
      'Karamel: yarım bardak şekeri tencerede, karıştırmadan eritin; kehribar rengini alınca 1 bardak sıcak sütü dikkatlice ekleyip pürüzsüzleşene kadar karıştırın. Soğutun.',
      'Karameli kekin üzerine ince bir tabaka halinde yayın. Dilimleyip soğuk servis edin — çatalı batırınca süt salıveren o meşhur doku!',
    ],
  },
  {
    isim: 'Supangle', mutfak: M, kategori: 'Tatlılar', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '3 yemek kaşığı'],
      ['Un', '2 yemek kaşığı'],
      ['Kakao', '3 yemek kaşığı'],
      ['Bitter Çikolata', '80 g'],
      ['Tereyağı', '1 yemek kaşığı (20 g)'],
      ['Kedi Dili Bisküvi', '8-10 adet (tabanı için)'],
      ['Fındık', 'üzeri için'],
    ],
    adimlar: [
      'Kase tabanlarına kedi dili bisküvileri (veya normal bisküvi) yerleştirin.',
      'Tencerede süt, şeker, nişasta, un ve kakaoyu soğukken çırpın; kakao topaklanmasın diye önce kuru malzemeleri kendi aralarında karıştırabilirsiniz.',
      'Orta ateşte, sürekli karıştırarak koyulaşana kadar 10-12 dakika pişirin.',
      'Ocağı kapatıp parçalanmış bitter çikolatayı ve tereyağını ekleyin; çikolata eriyene kadar karıştırın. İşte o parlak, ipeksi supangle dokusu!',
      'Sıcak kremayı bisküvili kaselere paylaştırın.',
      'Oda sıcaklığına gelince buzdolabında 3 saat soğutun.',
      'Üzerini çekilmiş fındıkla süsleyip servis edin.',
    ],
  },
  {
    isim: 'Tavuk Göğsü Tatlısı', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Tavuk Göğsü', '1 küçük parça (100 g)'],
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '4 yemek kaşığı'],
      ['Un', '2 yemek kaşığı'],
      ['Tereyağı', '1 yemek kaşığı'],
      ['Tarçın', 'üzeri için'],
    ],
    adimlar: [
      'Evet, içinde gerçekten tavuk var — ama korkmayın, tadı hiç belli olmaz; sadece o meşhur lifli dokuyu verir!',
      'Tavuk göğsünü haşlayın (20 dakika). Soğuyunca liflerine ayırın; lifleri soğuk suda 3-4 kez yıkayıp süzün — bu yıkama tavuk tadını tamamen alır.',
      'Lifleri mümkün olduğunca ince didikleyin, hatta bezin içinde ovarak iyice inceltin.',
      'Tencerede süt, şeker, nişasta ve unu soğukken çırpın; orta ateşte sürekli karıştırarak koyulaşana kadar pişirin.',
      'Tavuk liflerini ekleyin ve çırpma teliyle güçlüce çırparak 10 dakika daha pişirin; lifler kremanın içinde kaybolacak.',
      'Ocaktan alıp tereyağını karıştırın. Islak kaselere ya da tepsiye dökün.',
      'Soğuduktan sonra buzdolabında 3 saat dinlendirin. Kaşıkla dilim dilim alıp tarçın serperek servis edin — Osmanlı saray mutfağının en şaşırtıcı mirası!',
    ],
  },
];
