// Türk Mutfağı 1. bölüm: Çorbalar, Kahvaltılık, Salatalar & Mezeler.
// Tüm tarifler gramajlı malzeme listesi ve yeni başlayanlara göre
// adım adım detaylı anlatımla yazılmıştır.
import { type SeedTarif } from './seed-tarifler-turk';

const M = 'Türk Mutfağı';

export const TURK_1: SeedTarif[] = [
  // ─── ÇORBALAR ───
  {
    isim: 'Kırmızı Mercimek Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Kırmızı Mercimek', '1,5 su bardağı (250 g)'],
      ['Soğan', '1 adet orta boy'],
      ['Patates', '1 adet küçük boy'],
      ['Salça', '1 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Pul Biber', '1 çay kaşığı (servis için)'],
    ],
    adimlar: [
      'Mercimeği geniş bir süzgece boşaltın ve musluğun altında, elinizle karıştırarak yıkayın. İlk başta su bulanık ve köpüklü akar; berraklaşana kadar (yaklaşık yarım dakika) yıkamaya devam edin. Bu yıkama, hem tozunu alır hem de pişerken oluşan köpüğü büyük ölçüde azaltır, çorba daha berrak olur.',
      'Soğanın kabuğunu soyun, ikiye bölün ve önce ince dilimler, sonra minik küpler halinde doğrayın. Ne kadar küçük doğrarsanız kavrulurken o kadar eşit pişer ve çorbaya o kadar iyi karışır. Patatesi soyup küçük küpler halinde doğrayın — patates burada gizli kahraman: nişastası çorbaya blender sonrası o kadifemsi, kremamsı kıvamı verir.',
      'Kalın tabanlı bir tencereyi orta ateşte ısıtın, 1 yemek kaşığı tereyağını ekleyin. Tereyağı köpürüp erimeye başlayınca soğanları ekleyin. Tahta kaşıkla karıştırarak 4-5 dakika kavurun; soğanlar önce beyazlaşır, sonra camsı bir şeffaflık ve hafif pembelik alır. Renk almasını beklemek çorbanın tat temelini oluşturur, bu yüzden acele etmeyin ama yakmayın da.',
      'Salçayı ekleyin ve ateşi kısıp 1-2 dakika karıştırarak kavurun. Salça çiğken ekşi ve keskindir; yağda kavrulunca rengi koyulaşır, ham kokusu gider ve yerini tatlımsı, dolgun bir aromaya bırakır. Kaşığın dibinde hafifçe yapışmaya başladıysa tam kıvamındadır.',
      'Yıkanmış mercimeği ve patatesi tencereye ekleyip 1 dakika baharatla birlikte çevirin. Üzerine 6 su bardağı SICAK su ekleyin (soğuk su pişmeyi geciktirir ve tereyağını topaklar). Karıştırıp ateşi açın ve kaynamaya bırakın.',
      'Kaynama başlar başlamaz yüzeyde beyazımsı bir köpük toplanır; bunu bir kaşıkla alırsanız çorba daha berrak olur. Sonra ateşi kısın, kapağı hafif aralık bırakıp 25-30 dakika pişirin. Ara sıra karıştırıp dibin tutmadığından emin olun. Bir mercimek tanesini kaşıkla alıp parmaklarınız arasında ezdiğinizde hiç direnç göstermeden dağılıyorsa çorba hazırdır.',
      'Ocağı kapatın ve çorbayı 2-3 dakika dinlendirin (kaynar çorba blenderda sıçrayabilir). El blenderını tencerenin dibine kadar daldırıp, tencereyi hafif eğerek pürüzsüz, ipeksi bir kıvam elde edene kadar çekin. Blenderı kaldırmadan çalıştırmayın, sıçratır. Fazla koyu geldiyse biraz sıcak su ekleyip bir taşım daha kaynatın; kaşığın arkasını ince bir tabaka gibi kaplaması ideal kıvamdır.',
      'Tuzu şimdi ekleyin — baştan atılan tuz mercimeğin geç pişmesine yol açabilir. Karıştırıp tadına bakın ve gerekiyorsa ayarlayın.',
      'Servis sosu için küçük bir tavada kalan 1 kaşık tereyağını kısık ateşte eritin, pul biberi ekleyin ve 8-10 saniye, yağ kırmızıya boyanana kadar bekletip hemen ocaktan alın (fazla beklerse pul biber yanıp acılaşır). Bu parlak kırmızı yağı her kâsenin üzerine gezdirin. Yanında limon dilimi ve kızarmış ekmekle sofraya getirin.',
    ],
  },
  {
    isim: 'Ezogelin Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Kırmızı Mercimek', '1 su bardağı (170 g)'],
      ['Pirinç', '2 yemek kaşığı (25 g)'],
      ['İnce Bulgur', '2 yemek kaşığı (25 g)'],
      ['Soğan', '1 adet orta boy'],
      ['Sarımsak', '2 diş'],
      ['Salça', '1,5 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Kuru Nane', '1 tatlı kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Mercimek, pirinç ve bulguru aynı süzgeçte buluşturun ve musluğun altında, suyu berraklaşana kadar yıkayın. Üç malzemenin birlikte pişmesi ezogelini sıradan mercimek çorbasından ayıran şeydir: mercimek dağılıp kıvam verir, pirinç ve bulgur ise dişe gelen küçük taneler bırakır.',
      'Soğanı olabildiğince küçük, minik küpler halinde doğrayın. Sarımsakları bıçağın geniş yüzüyle bastırıp ezin (kabuğu böyle kolayca çıkar), sonra ince ince kıyın.',
      'Kalın tabanlı tencerede tereyağını orta ateşte eritin. Soğanları ekleyip 4-5 dakika, camsı bir şeffaflık alana kadar karıştırarak kavurun. Sarımsağı ekleyip 1 dakika daha çevirin; sarımsak çok çabuk yanıp acılaştığı için bu adımı kısa tutun ve gözünüzü ayırmayın.',
      'Salçayı ekleyin, ateşi kısıp 1-2 dakika karıştırarak kavurun. Rengi koyulaşıp ham kokusu kaybolunca ve yağ kenarlardan kırmızımsı sızmaya başlayınca hazırdır.',
      'Yıkanmış mercimek, pirinç ve bulguru ekleyip 1 dakika baharatla çevirin, taneler yağa bulansın. Üzerine 7 su bardağı sıcak su ekleyip karıştırın.',
      'Kaynayınca yüzeydeki köpüğü alın, ateşi kısın ve kapağı aralık bırakarak 30 dakika pişirin. Nişastalı bir çorba olduğu için dibi kolay tutar; her 5-6 dakikada bir tahta kaşığı dibe kadar gezdirerek karıştırın. Su fazla çekilip koyulaşırsa biraz sıcak su ekleyin.',
      'Kuru nane, pul biber ve tuzu ekleyip 5 dakika daha kaynatın. Kuru naneyi bu aşamada eklemek aromasının çorbaya işlemesini sağlar. Kâseye aldıktan sonra bolca limon sıkmak ezogelinin olmazsa olmazıdır — ekşilik, çorbanın toprağımsı tadını canlandırır.',
    ],
  },
  {
    isim: 'Yayla Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Pirinç', 'yarım su bardağı (90 g)'],
      ['Yoğurt', '2 su bardağı (400 g)'],
      ['Yumurta', '1 adet (sadece sarısı)'],
      ['Un', '1 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Kuru Nane', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Pirinci yıkayıp tencereye koyun, üzerine 5 su bardağı su ekleyin ve orta ateşte pirinçler iyice yumuşayana kadar (yaklaşık 15 dakika) haşlayın. Pirinç burada hem kıvam hem de gövde verir; tam pişip hafif dağılacak kıvama gelmesi önemli, diri kalmamalı.',
      'Bu sırada terbiyeyi hazırlayın: derin bir kasede yoğurt, yumurta sarısı ve unu çırpma teliyle, hiç topak kalmayana kadar pürüzsüzce çırpın. Yumurta sarısı ve un, yoğurdun pişerken kesilmesini (tanelenmesini) önleyen iki sigortadır — ikisini de atlamayın.',
      'İşin püf noktası burada: yoğurt sıcak çorbaya birden girerse şok olup kesilir, çorba pütür pütür olur. Bunu önlemek için kaynayan çorbadan bir kepçe sıcak suyu, ince ince dökerek ve durmadan çırparak yoğurda ekleyin. Bir kepçe daha ekleyip tekrar çırpın. Böylece yoğurdun sıcaklığı yavaşça yükselir, çorbanınkine yaklaşır.',
      'Ilıttığınız yoğurtlu terbiyeyi, bir eliniz kepçeyle sürekli karıştırırken diğer elinizle yavaşça tencereye dökün. Dökerken karıştırmayı asla bırakmayın.',
      'Ateşi kısık tutun ve tahta kaşıkla, hep aynı yönde, durmadan karıştırarak bir taşım kaynatın. Karıştırmayı bırakırsanız yoğurt yine kesilebilir. Çorba hafifçe koyulaşıp kaşığı kaplayınca tuzunu ekleyip karıştırın.',
      'Küçük bir tavada tereyağını eritip kuru naneyi ekleyin, kısık ateşte 8-10 saniye, nane yağa aromasını verene kadar kavurup hemen ocaktan alın. Bu naneli yağı her kâsenin üzerine gezdirip sıcak servis edin. Yayla çorbasının o meşhur kokusu bu son dokunuştan gelir.',
    ],
  },
  {
    isim: 'Tarhana Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 25, tur: 'yemek',
    malzemeler: [
      ['Tarhana', '3 yemek kaşığı (45 g)'],
      ['Salça', '1 yemek kaşığı'],
      ['Tereyağı', '1,5 yemek kaşığı (30 g)'],
      ['Sarımsak', '1 diş (isteğe bağlı)'],
      ['Tuz', '1 çay kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
    ],
    adimlar: [
      'Tarhanayı küçük bir kaseye koyun, üzerine 1 su bardağı ILIK su ekleyin (sıcak su tarhanayı topaklar) ve 10 dakika bekletin. Bu bekleme, kuru tarhananın suyu emip yumuşamasını sağlar. Sonra kaşığın arkasıyla kabın kenarına baste baste iyice ezin; ne kadar çok ezerseniz çorba o kadar pürüzsüz olur.',
      'Kalın tabanlı tencerede tereyağını orta ateşte eritin. Dilerseniz ezilmiş 1 diş sarımsağı ekleyip 30 saniye, kokusu çıkana kadar çevirin — sarımsak tarhananın ekşimsi tadıyla çok iyi gider.',
      'Salçayı ekleyip 1 dakika, ham kokusu geçene kadar kavurun.',
      'Islatıp ezdiğiniz tarhanayı tencereye alın ve karıştırın. Sonra 4 su bardağı sıcak suyu BİRDEN değil, azar azar, her seferinde çırpma teliyle iyice çırparak ekleyin. Suyu azar azar eklemek ve çırpma teli kullanmak topaklanmayı önleyen iki anahtardır.',
      'Ateşi kısın ve sık sık karıştırarak 10-15 dakika pişirin. Tarhana un içerdiği için dibi kolayca tutar; tahta kaşığı ara sıra dibe kadar gezdirin. Çorba kaşığın arkasını ince bir tabaka gibi kaplayacak kıvama gelince tuzunu ayarlayın. Çok koyulaştıysa biraz sıcak su ekleyin.',
      'Kâseye alıp üzerine pul biber serpin. Dilerseniz bir tavada kızdırdığınız tereyağına pul biber katıp üzerine gezdirebilirsiniz — köy usulü tarhananın en güzel hali budur.',
    ],
  },
  {
    isim: 'Domates Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Domates', '5 adet olgun (750 g)'],
      ['Un', '2 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Kaşar Peyniri', '1 su bardağı rendelenmiş (80 g)'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Domatesleri yıkayın, sap kısımlarını çıkarın ve ikiye bölün. Kesik yüzeyi rendeye gelecek şekilde, rendenin iri tarafında rendeleyin; kabuk avucunuzda düz bir parça olarak kalır, onu atın. Bu yöntem hem kabuğu kolayca ayırır hem de domatesin tüm suyunu ve etini alır. Olgun, kırmızı domates seçin — çorbanın rengi ve tatlılığı buna bağlı.',
      'Kalın tabanlı tencerede tereyağını orta ateşte eritin, unu ekleyin. Bu adım "meyane" denen koyulaştırıcı temeldir. Tahta kaşıkla DURMADAN karıştırarak 2-3 dakika kavurun; un önce hamurumsu olur, sonra rengi açık kum sarısına döner ve fındığımsı, mis gibi bir koku yayar. İşte o an hazırdır. Bir saniye bile gözünüzü ayırmayın — yanan un acılaşır ve tüm çorbayı mahveder.',
      'Rendelenmiş domatesi meyanenin üzerine ekleyin ve karıştırın. İlk başta un topaklanır gibi olur, panik yapmayın; karıştırdıkça açılır. 5-6 dakika, domatesin suyu çekilip rengi koyulaşana ve ekşimsi kokusu tatlıya dönene kadar pişirin.',
      '4 su bardağı sıcak suyu BİRDEN değil, azar azar, her seferinde çırpma teliyle karıştırarak ekleyin. Sıcak suyu azar azar eklemek ve çırpmak, pürüzsüz bir çorbanın sırrıdır.',
      'Daha da kadifemsi bir kıvam isterseniz çorbayı el blenderıyla kısaca çekin. Ateşi kısıp 10 dakika daha, ara sıra karıştırarak kaynatın; bu süre unun ham tadının tamamen gitmesini ve çorbanın koyulaşmasını sağlar. Tuz ve karabiberi ekleyin.',
      'Kâselere paylaştırıp üzerine bolca rendelenmiş kaşar serpin. Peynir sıcak çorbanın buğusunda erirken üzerine biraz kuru nane veya kızarmış ekmek de ekleyebilirsiniz.',
    ],
  },
  {
    isim: 'Şehriyeli Tavuk Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Tavuk Göğsü', '1 adet (250 g)'],
      ['Tel Şehriye', 'yarım su bardağı (50 g)'],
      ['Un', '1 yemek kaşığı'],
      ['Tereyağı', '1,5 yemek kaşığı (30 g)'],
      ['Limon', 'yarım adet'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Tavuk göğsünü tencereye koyun, üzerini 2 parmak geçecek kadar SOĞUK su (yaklaşık 6 su bardağı) ekleyin. Soğuk suda başlamak, tavuğun tüm lezzetinin suya geçmesini sağlar. Ateşi açın; kaynamaya yakın yüzeyde gri-beyaz bir köpük toplanır, bunu bir kaşıkla dikkatlice alın. Köpüğü almak suyun berrak ve temiz kalmasını sağlar. Ateşi kısıp 20 dakika, tavuk tamamen pişene kadar haşlayın.',
      'Haşlanan tavuğu delikli kaşıkla bir tabağa alın, birkaç dakika soğumaya bırakın. Elle tutulacak kadar ılıyınca liflerine ayırarak küçük parçalar halinde didikleyin. Haşlama suyunu SAKIN dökmeyin — çorbanın bütün lezzeti o suda. İçinde küçük kemik veya kıkırdak parçası varsa süzgeçten geçirin.',
      'Ayrı bir tencerede (ya da haşlama tenceresini boşaltıp silerek) tereyağını orta ateşte eritin, unu ekleyin. Tahta kaşıkla sürekli karıştırarak 2 dakika kavurun; un hafif sararıp fındığımsı koku verince hazırdır. Yakmamaya dikkat edin.',
      'Sıcak tavuk suyundan bir kepçe ekleyip hemen çırpma teliyle güçlüce çırpın — un bir anda macun gibi olur, korkmayın. Sonra kalan suyu azar azar, her seferinde çırparak ekleyin. Bu azar azar ekleme, hiç topak bırakmadan pürüzsüz bir çorba verir.',
      'Şehriyeyi ekleyin ve orta ateşte, ara sıra karıştırarak 8-10 dakika, şehriyeler yumuşayana kadar pişirin. Şehriye pişerken çorbayı da hafifçe koyulaştırır.',
      'Didiklenmiş tavukları, tuzu ve karabiberi ekleyip 2 dakika daha kaynatın. Ocaktan almadan tadına bakıp tuzunu ayarlayın. Kâseye aldıktan sonra bolca limon sıkın; ekşilik tavuk çorbasının yağını dengeleyip tadını canlandırır.',
    ],
  },
  {
    isim: 'Mantar Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Mantar', '400 g'],
      ['Un', '1,5 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Krema', '1 küçük paket (200 ml)'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Mantarları asla bol suda yıkamayın — sünger gibi su çekerler ve pişerken o suyu geri salıp lezzeti sulandırırlar. Bunun yerine nemli bir kâğıt havlu veya bezle her birini tek tek silerek toprağını temizleyin, sonra yarım santim kalınlığında dilimleyin.',
      'Kalın tabanlı tencerede tereyağını orta ateşte eritin, mantarları ekleyin. İlk aşamada mantarlar bolca su salar ve âdeta kendi suyunda haşlanır; karıştırarak bu suyun tamamen çekilmesini bekleyin. Su çekildikten sonra mantarlar hafifçe kızarıp altın rengi almaya başlar — işte gerçek mantar lezzeti bu kızarmayla ortaya çıkar. Bu aşama toplam 8-10 dakika sürer, acele etmeyin.',
      'Unu ekleyip 2 dakika, mantarlara ve yağa iyice karışıp ham kokusu geçene kadar karıştırarak kavurun.',
      '4 su bardağı sıcak suyu azar azar, her seferinde çırparak ekleyin ki un topaklanmasın. Kaynamaya bırakıp ateşi kısın ve 10 dakika pişirin.',
      'Ocağı kapatıp 2-3 dakika dinlendirin, sonra el blenderıyla pürüzsüz olana kadar çekin. İpucu: birkaç mantar dilimini blenderdan önce ayırıp kâsede süs olarak kullanırsanız hem güzel görünür hem de dişe gelen doku katarsınız.',
      'Kremayı ekleyip kısık ateşte, kaynatmadan sadece bir taşım ısıtın (krema yüksek ateşte kesilebilir). Tuz ve karabiberle tatlandırın. Kâseye alıp üzerine biraz taze çekilmiş karabiber ve isterseniz birkaç damla zeytinyağı gezdirerek sıcak servis edin.',
    ],
  },
  {
    isim: 'Sebze Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Havuç', '2 adet (200 g)'],
      ['Patates', '2 adet orta boy (300 g)'],
      ['Kabak', '1 adet (200 g)'],
      ['Soğan', '1 adet küçük'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Maydanoz', 'birkaç dal'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Bütün sebzeleri yıkayın. Havuç ve patatesi soyun; kabakla birlikte hepsini birbirine yakın boyutta, küçük küpler halinde doğrayın. Eşit boyut, sebzelerin aynı anda pişmesini sağlar. Soğanı da minik minik kıyın. Not: kabağın kabuğu inceyse soymanıza gerek yok, kabuklu çorbaya hoş bir yeşillik katar.',
      'Kalın tabanlı tencerede tereyağını orta ateşte eritin, önce soğanı 2-3 dakika, şeffaflaşana kadar kavurun.',
      'Havuçları ekleyip 2 dakika çevirin (havuç en sert sebze, önden başlaması iyi olur), sonra patates ve kabağı ekleyip 3 dakika daha, ara ara karıştırarak soteleyin. Bu ön kavurma adımı sebzelerin kenarlarını hafifçe mühürler ve çorbaya suda haşlamayla elde edemeyeceğiniz derin, tatlımsı bir lezzet verir — atlamayın.',
      '5 su bardağı sıcak su ekleyin. Kaynayınca altını kısıp kapağı aralık bırakarak, sebzeler çatalla hiç zorlanmadan ezilene kadar (yaklaşık 20 dakika) pişirin.',
      'Şimdi iki yol var: dişe gelen, köy usulü bir çorba istiyorsanız taneli bırakın; kadifemsi, kremamsı bir kıvam istiyorsanız el blenderıyla pürüzsüzleştirin. Yarısını çekip yarısını taneli bırakmak da güzel bir orta yoldur.',
      'Tuz ve karabiberi ekleyip tadına bakın. Kâseye alıp ince kıyılmış maydanoz serpin; isterseniz bir kaşık kaymak veya birkaç damla limon çorbayı taçlandırır.',
    ],
  },
  {
    isim: 'Düğün Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '250 g'],
      ['Yoğurt', '1 su bardağı (200 g)'],
      ['Yumurta', '1 adet (sadece sarısı)'],
      ['Un', '2 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Etleri küçük, kuşbaşından da minik parçalar halinde kesin — düğün çorbasında etler kaşığa gelecek kadar ufak olur. Tencereye koyup üzerine 6 su bardağı SOĞUK su ekleyin; soğukta başlamak etin lezzetini suya verir. Kaynamaya yakın yüzeyde toplanan köpüğü kaşıkla alın (berrak bir et suyu için şart) ve kısık ateşte, etler çatalla dağılacak kadar yumuşayana dek 40 dakika haşlayın. Düdüklü tencerede 20 dakika yeterlidir.',
      'Terbiyeyi hazırlayın: derin bir kasede yoğurt, yumurta sarısı ve unu çırpma teliyle, hiç topak kalmayana kadar pürüzsüzce çırpın. Yumurta sarısı ve un birlikte, yoğurdun sıcakta kesilmesini önler.',
      'Kritik adım — yoğurdu ısıya alıştırmak: kaynayan et suyundan bir kepçe alıp, durmadan çırparak yoğurtlu karışıma ince ince dökün. Bir kepçe daha ekleyip tekrar çırpın. Yoğurt böyle yavaşça ısınır, çorbaya girince şok olup kesilmez.',
      'Ilıttığınız terbiyeyi, bir eliniz kepçeyle sürekli karıştırırken diğer elinizle yavaşça tencereye dökün. Karıştırmayı bırakmayın.',
      'Ateşi kısık tutup, tahta kaşıkla durmadan karıştırarak bir taşım kaynatın. Çorba hafifçe koyulaşınca tuzunu ekleyip ayarlayın.',
      'Meşhur son dokunuş: küçük bir tavada tereyağını eritip pul biberi ekleyin, 8-10 saniye, yağ kırmızıya boyanınca — yakmadan — ocaktan alıp çorbanın üzerine cazırdatarak gezdirin. Bu kızgın yağ, düğün çorbasının imzasıdır.',
    ],
  },
  {
    isim: 'Yoğurtlu Yeşil Mercimek Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Yeşil Mercimek', '1 su bardağı (180 g)'],
      ['Erişte', '1 su bardağı (80 g)'],
      ['Yoğurt', '1,5 su bardağı (300 g)'],
      ['Sarımsak', '2 diş'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Kuru Nane', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Yeşil mercimeği yıkayıp tencereye koyun, 6 su bardağı su ekleyin. Yeşil mercimek kırmızıya göre daha diri kalır; kabuğu dağılmadan yumuşayana kadar yaklaşık 25 dakika haşlayın. Bir taneyi ezip kontrol edin — içi una dönmüş ama kabuğu bütünse hazırdır.',
      'Erişteleri ekleyip 10 dakika daha, yumuşayana kadar pişirin. Erişte hem doku hem de çorbaya hafif bir kıvam katar.',
      'Yoğurdu bir kasede ezilmiş sarımsak ve bir tutam tuzla karıştırın. Kesilmemesi için çorbadan bir kepçe sıcak suyu, çırparak yoğurda ekleyin; böylece yoğurt ısıya alışır.',
      'Ilıttığınız yoğurdu, sürekli karıştırarak tencereye yavaşça dökün ve kısık ateşte, karıştırmayı bırakmadan bir taşım kaynatın. Kaynattıktan sonra çok fazla pişirmeyin, yoğurt gevrekleşebilir.',
      'Tuzunu ayarlayın. Küçük tavada tereyağını eritip kuru naneyi ekleyin, 8-10 saniye kavurup her kâsenin üzerine gezdirin. Nane ve sarımsak, yeşil mercimeğin toprağımsı tadıyla çok güzel gider.',
    ],
  },

  // ─── KAHVALTILIK ───
  {
    isim: 'Menemen', mutfak: M, kategori: 'Kahvaltılık', sure: 20, tur: 'yemek',
    malzemeler: [
      ['Domates', '3 adet olgun (450 g)'],
      ['Sivri Biber', '3 adet'],
      ['Yumurta', '3 adet'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Tuz', '1 çay kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Biberleri yıkayıp saplarını kesin ve minik halkalar halinde doğrayın. Domatesleri rendenin iri tarafında rendeleyin; kabuklar elinizde kalsın.',
      'Geniş bir tavada tereyağını orta ateşte eritin. Biberleri ekleyip 3-4 dakika, yumuşayana kadar karıştırarak pişirin.',
      'Rendelenmiş domatesi ekleyin. Orta ateşte, ara ara karıştırarak domatesin suyu çekilene kadar 8-10 dakika pişirin. Suyu çekilmezse menemen sulu olur, acele etmeyin.',
      'Tuz ve karabiberi ekleyin. Kaşıkla harcın ortasında küçük boşluklar açıp yumurtaları bu boşluklara kırın.',
      'İsterseniz yumurtaları hiç karıştırmadan beyazları tutana kadar pişirin, isterseniz kaşıkla hafifçe karıştırın — ikisi de olur.',
      'Yumurtalar hâlâ hafif parlak ve akışkanken ocağı kapatın; tavanın sıcağı onları pişirmeye devam eder. Tavayla birlikte sıcak servis edin.',
    ],
  },
  {
    isim: 'Sucuklu Yumurta', mutfak: M, kategori: 'Kahvaltılık', sure: 15, tur: 'yemek',
    malzemeler: [
      ['Sucuk', '150 g (12-14 dilim)'],
      ['Yumurta', '3 adet'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Sucuğu yarım santim kalınlığında dilimleyin. Kabuğu varsa soyun; kolay soyulmazsa bıçakla kenarından çizin.',
      'Dilimleri yağ eklemeden tavaya dizin — sucuk kendi yağını salar. Orta ateşte 1-2 dakika pişirin.',
      'Dilimlerin kenarları hafif kıvrılıp yağını salınca hepsini ters çevirin.',
      'Yumurtaları sucukların arasındaki boşluklara kırın. Ocağı kısın ve tavanın kapağını kapatın.',
      'Yumurta beyazları tamamen beyazlaşana, sarıları ise hâlâ parlakken (2-3 dakika) pişirin. Karabiber serpip tavayla servis edin — ekmek banmayı unutmayın!',
    ],
  },
  {
    isim: 'Peynirli Omlet', mutfak: M, kategori: 'Kahvaltılık', sure: 10, tur: 'yemek',
    malzemeler: [
      ['Yumurta', '3 adet'],
      ['Kaşar Peyniri', 'yarım su bardağı rendelenmiş (50 g)'],
      ['Tereyağı', '1 yemek kaşığı (20 g)'],
      ['Tuz', '1 çay kaşığı'],
      ['Karabiber', 'bir tutam'],
    ],
    adimlar: [
      'Yumurtaları bir kaseye kırın, tuz ve karabiberi ekleyip çatalla iyice çırpın; rengi tek renk sarı olana kadar çırparsanız omlet daha kabarık olur.',
      'Tavayı orta ateşte ısıtıp tereyağını eritin; tavayı hafifçe döndürerek yağın her yere yayılmasını sağlayın.',
      'Çırpılmış yumurtayı dökün ve tavayı hiç karıştırmadan bekleyin. Kenarları pişmeye başlayınca spatulayla kenarlardan hafifçe kaldırıp akışkan kısmın alta akmasını sağlayın.',
      'Üstü hafif ıslak görünürken rendelenmiş kaşarı omletin bir yarısına serpin.',
      'Spatula yardımıyla boş yarısını peynirli tarafın üzerine katlayın. 1 dakika daha pişirin; peynir eriyince tabağa kaydırın.',
    ],
  },
  {
    isim: 'Patates Kavurması', mutfak: M, kategori: 'Kahvaltılık', sure: 25, tur: 'yemek',
    malzemeler: [
      ['Patates', '3 adet orta boy (450 g)'],
      ['Ayçiçek Yağı', '4 yemek kaşığı'],
      ['Yumurta', '2 adet (isteğe bağlı)'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
      ['Pul Biber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Patatesleri soyup küçük küpler halinde doğrayın. Doğradıklarınızı kağıt havluyla kurulayın — kuru patates daha güzel kızarır ve yağ sıçratmaz.',
      'Geniş tavada yağı orta ateşte ısıtın. Bir patates parçası attığınızda hemen cızırdıyorsa yağ hazırdır.',
      'Patatesleri tavaya ekleyin ve ilk 5 dakika hiç karıştırmadan pişirin; altları güzelce kızarsın.',
      'Sonra ara ara çevirerek her tarafı altın sarısı olana kadar 15 dakika kadar pişirin.',
      'Tuz, karabiber ve pul biberi serpin. İsterseniz ortasına 2 yumurta kırıp kapağı kapatın ve yumurtalar pişene kadar 3 dakika bekleyin.',
    ],
  },
  {
    isim: 'Çılbır', mutfak: M, kategori: 'Kahvaltılık', sure: 15, tur: 'yemek',
    malzemeler: [
      ['Yumurta', '2 adet'],
      ['Yoğurt', '1 su bardağı (200 g)'],
      ['Sarımsak', '1 diş'],
      ['Tereyağı', '1,5 yemek kaşığı (30 g)'],
      ['Sirke', '1 yemek kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Yoğurdu bir kasede ezilmiş sarımsak ve tuzla karıştırın; oda sıcaklığında bekletin (buzdolabı soğuğu yumurtayı hemen soğutur).',
      'Geniş bir tencereye 4-5 parmak su koyup kaynatın; sirkeyi ekleyin. Sirke, yumurtanın dağılmadan toparlanmasına yardım eder.',
      'Su fokur fokur değil, hafif kıpırdayacak kadar kaynarken ocağı kısın. Yumurtayı önce küçük bir kaseye kırın.',
      'Kaşıkla suda küçük bir girdap oluşturun ve yumurtayı girdabın ortasına yavaşça bırakın. 3-4 dakika pişirin; beyazı tutmuş, sarısı akışkan olmalı. Delikli kepçeyle alın. Diğer yumurta için tekrarlayın.',
      'Sarımsaklı yoğurdu tabağa yayın, poşe yumurtaları üzerine oturtun.',
      'Tavada tereyağını eritip pul biberi ekleyin, köpürünce yumurtaların üzerine gezdirin. Ekmekle sıcak servis edin.',
    ],
  },

  // ─── SALATALAR & MEZELER ───
  {
    isim: 'Çoban Salatası', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 15, tur: 'yemek',
    malzemeler: [
      ['Domates', '3 adet (450 g)'],
      ['Salatalık', '2 adet'],
      ['Sivri Biber', '2 adet'],
      ['Soğan', '1 adet küçük'],
      ['Maydanoz', 'yarım demet'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Limon', '1 adet (suyu)'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Bütün sebzeleri yıkayın. Domatesleri önce dilimlere, sonra küçük küplere doğrayın.',
      'Salatalıkları soyup (kabuğu acıysa) küçük küpler halinde kesin. Biberleri ince halkalar yapın.',
      'Soğanı ikiye bölüp ince yarım ay şeklinde doğrayın; keskinliği gitsin diye üzerine bir tutam tuz serpip elinizle hafifçe ovabilirsiniz.',
      'Maydanozların yapraklarını saplarından ayırıp ince ince kıyın.',
      'Hepsini geniş bir kasede buluşturun. Zeytinyağı, limon suyu ve tuzu üzerine gezdirip nazikçe karıştırın. Hemen servis edin — bekledikçe su salar.',
    ],
  },
  {
    isim: 'Gavurdağı Salatası', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 20, tur: 'yemek',
    malzemeler: [
      ['Domates', '3 adet (450 g)'],
      ['Soğan', '1 adet'],
      ['Sivri Biber', '2 adet'],
      ['Ceviz', 'yarım su bardağı iri çekilmiş (50 g)'],
      ['Maydanoz', 'yarım demet'],
      ['Nar Ekşisi', '2 yemek kaşığı'],
      ['Zeytinyağı', '2 yemek kaşığı'],
      ['Sumak', '1 tatlı kaşığı'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Bu salatanın sırrı her şeyin minicik doğranması. Domateslerin çekirdekli sulu kısımlarını kaşıkla alıp sadece etli kısmını minik küpler halinde doğrayın.',
      'Soğanı ve biberleri de olabildiğince küçük doğrayın; maydanozu incecik kıyın.',
      'Cevizleri bıçakla iri parçalar kalacak şekilde çekin — un gibi olmasın, dişe gelsin.',
      'Hepsini bir kasede birleştirin. Nar ekşisi, zeytinyağı, sumak ve tuzu ekleyin.',
      'Kaşıkla nazikçe harmanlayın ve 10 dakika dinlendirin; nar ekşisi sebzelere işlesin. Kebap ve etlerin yanına çok yakışır.',
    ],
  },
  {
    isim: 'Piyaz', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Kuru Fasulye', '1,5 su bardağı haşlanmış (250 g)'],
      ['Soğan', '1 adet'],
      ['Domates', '1 adet'],
      ['Yumurta', '2 adet'],
      ['Maydanoz', 'yarım demet'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Sirke', '1,5 yemek kaşığı'],
      ['Sumak', '1 tatlı kaşığı'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Fasulyeleri önceden haşlayın: bir gece suda beklettikten sonra yumuşayana kadar 40-50 dakika pişirin ve süzün (hazır haşlanmış konserve de kullanabilirsiniz — suyunu süzüp yıkayın).',
      'Yumurtaları kaynar suda 10 dakika haşlayıp soğuk suya alın; soyup dilimleyin.',
      'Soğanı ince yarım ay doğrayıp tuzla hafifçe ovun. Domatesi küp küp doğrayın, maydanozu kıyın.',
      'Fasulye, soğan, domates ve maydanozu kasede birleştirin. Zeytinyağı, sirke, sumak ve tuzu ekleyip karıştırın.',
      'Servis tabağına alıp üzerini yumurta dilimleriyle süsleyin. Köftenin yanında efsanedir.',
    ],
  },
  {
    isim: 'Haydari', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 10, tur: 'yemek',
    malzemeler: [
      ['Süzme Yoğurt', '2 su bardağı (400 g)'],
      ['Sarımsak', '2 diş'],
      ['Kuru Nane', '1 tatlı kaşığı'],
      ['Zeytinyağı', '2 yemek kaşığı'],
      ['Pul Biber', 'yarım çay kaşığı'],
      ['Tuz', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Süzme yoğurdu bir kaseye alın. Normal yoğurt kullanacaksanız bir tülbentte 2 saat süzdürün; koyu kıvam haydarinin olmazsa olmazı.',
      'Sarımsakları soyup tuzla birlikte ezin — tuz, sarımsağın kolayca ezilmesini sağlar.',
      'Yoğurda ezilmiş sarımsak, kuru nane ve 1 kaşık zeytinyağını ekleyin.',
      'Kaşıkla iyice karıştırıp pürüzsüz bir kıvam alın.',
      'Servis kasesine alın, kaşığın arkasıyla üzerinde küçük bir havuz açın. Kalan zeytinyağını bu havuza döküp pul biber serpin.',
    ],
  },
  {
    isim: 'Cacık', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 10, tur: 'yemek',
    malzemeler: [
      ['Yoğurt', '2 su bardağı (400 g)'],
      ['Salatalık', '2 adet'],
      ['Sarımsak', '1 diş'],
      ['Kuru Nane', '1 çay kaşığı'],
      ['Zeytinyağı', '1 yemek kaşığı'],
      ['Tuz', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Yoğurdu derin bir kaseye alın ve çırpma teliyle pürüzsüz olana kadar çırpın. Sulu cacık severseniz yarım su bardağı soğuk su ekleyin.',
      'Salatalıkları yıkayın; ister rendeleyin ister minik küpler halinde doğrayın.',
      'Sarımsağı tuzla ezip yoğurda ekleyin. Salatalıkları da ekleyip karıştırın.',
      'Tuzunu kontrol edin, kuru naneyi ekleyin.',
      'Kaselere paylaştırıp üzerine zeytinyağı gezdirin ve bir tutam nane serpin. Buz gibi servis edin.',
    ],
  },
  {
    isim: 'Kısır', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 30, tur: 'yemek',
    malzemeler: [
      ['İnce Bulgur', '2 su bardağı (320 g)'],
      ['Salça', '2 yemek kaşığı'],
      ['Maydanoz', '1 demet'],
      ['Taze Soğan', '4 dal'],
      ['Domates', '1 adet'],
      ['Nar Ekşisi', '2 yemek kaşığı'],
      ['Limon', 'yarım adet (suyu)'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Marul', 'birkaç yaprak (servis için)'],
    ],
    adimlar: [
      'Bulguru geniş bir kaba koyun. Üzerine 1,5 su bardağı kaynar su döküp hızlıca karıştırın ve kabın kapağını (veya bir tabağı) kapatın. 15 dakika bekleyin; bulgur suyu çekip şişecek.',
      'Bulgur ılıyınca salçayı, zeytinyağını, pul biberi ve tuzu ekleyin. Elinizle (yanmayacak kadar ılık olsun) 3-4 dakika iyice yoğurun; salça her taneye bulaşsın, renk eşit olsun.',
      'Maydanozu ve taze soğanı incecik kıyın. Domatesi minik küpler halinde doğrayın.',
      'Yeşillikleri ve domatesi bulgura ekleyin; nar ekşisi ve limon suyunu gezdirin.',
      'Nazikçe karıştırın ve tadına bakın — ekşisi, tuzu size göre olsun. Marul yaprağına sarıp yemek en güzelidir.',
    ],
  },
  {
    isim: 'Mercimek Köftesi', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Kırmızı Mercimek', '1 su bardağı (170 g)'],
      ['İnce Bulgur', '1 su bardağı (160 g)'],
      ['Soğan', '1 adet'],
      ['Salça', '1,5 yemek kaşığı'],
      ['Maydanoz', 'yarım demet'],
      ['Taze Soğan', '3 dal'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Kimyon', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Marul', 'servis için'],
      ['Limon', 'servis için'],
    ],
    adimlar: [
      'Mercimeği yıkayıp tencereye koyun, üzerine 2,5 su bardağı su ekleyin. Kısık ateşte, suyunu çekip lapa olana kadar yaklaşık 20 dakika pişirin.',
      'Ocağı kapatır kapatmaz bulguru ekleyip karıştırın ve kapağı kapatın. 20 dakika bekleyin; bulgur, mercimeğin sıcağıyla yumuşayacak.',
      'Bu arada soğanı minik doğrayıp 2 kaşık zeytinyağında pembeleşene kadar kavurun; salçayı ekleyip 1 dakika daha pişirin.',
      'Kavrulmuş soğanı mercimekli karışıma ekleyin. Kalan zeytinyağı, pul biber, kimyon ve tuzu da ekleyip elinizle iyice yoğurun.',
      'Kıyılmış maydanoz ve taze soğanı ekleyip bir kez daha karıştırın.',
      'Avucunuza aldığınız harcı sıkarak parmak izli klasik şeklini verin. Marul yaprağı ve limonla servis edin.',
    ],
  },
  {
    isim: 'Acılı Ezme', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 20, tur: 'yemek',
    malzemeler: [
      ['Domates', '3 adet (450 g)'],
      ['Sivri Biber', '3 adet (acılı severseniz acı biber)'],
      ['Soğan', '1 adet küçük'],
      ['Sarımsak', '1 diş'],
      ['Maydanoz', 'yarım demet'],
      ['Salça', '1 yemek kaşığı'],
      ['Nar Ekşisi', '1,5 yemek kaşığı'],
      ['Zeytinyağı', '2 yemek kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Sumak', '1 çay kaşığı'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Domateslerin çekirdeklerini kaşıkla çıkarın; sadece etli kısımlarını kullanacağız, yoksa ezme sulu olur.',
      'Domates, biber, soğan, sarımsak ve maydanozu olabildiğince ince kıyın. Acele etmeyin — gerçek ezmede makine değil bıçak kullanılır, ama zdrobot da kullanabilirsiniz (çok çekmeyin, püre olmasın).',
      'Kıydıklarınızı derin bir kaseye alın; salça, nar ekşisi, zeytinyağı ve baharatları ekleyin.',
      'Kaşıkla iyice karıştırın; salça her yere dağılsın.',
      'Üzerini kapatıp buzdolabında en az 1 saat dinlendirin — dinlendikçe lezzeti oturur. Soğuk servis edin.',
    ],
  },
  {
    isim: 'Patates Salatası', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Patates', '4 adet orta boy (600 g)'],
      ['Taze Soğan', '4 dal'],
      ['Maydanoz', 'yarım demet'],
      ['Dereotu', 'birkaç dal'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Limon', '1 adet (suyu)'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Patatesleri kabuklarıyla yıkayıp tencereye koyun, üzerini geçen suda haşlayın. Bıçak ucu kolayca giriyorsa (yaklaşık 20-25 dakika) hazırdır. Kabuklu haşlamak dağılmalarını önler.',
      'Süzüp biraz soğumaya bırakın; el yakmayacak sıcaklıkta kabuklarını soyun.',
      'Patatesleri iri küpler halinde doğrayıp geniş bir kaba alın.',
      'Taze soğan, maydanoz ve dereotunu ince kıyıp ekleyin.',
      'Zeytinyağı, limon suyu, tuz ve pul biberi küçük bir kavanozda çalkalayıp sos yapın; salatanın üzerine gezdirin.',
      'Patatesleri ezmeden, alttan üste nazikçe karıştırın. Ilık da soğuk da çok güzeldir.',
    ],
  },
  {
    isim: 'Semizotu Salatası', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 15, tur: 'yemek',
    malzemeler: [
      ['Semizotu', '1 demet (300 g)'],
      ['Yoğurt', '1,5 su bardağı (300 g)'],
      ['Sarımsak', '2 diş'],
      ['Zeytinyağı', '1 yemek kaşığı'],
      ['Tuz', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Semizotunun yapraklarını kalın saplarından tek tek ayırın; kalın saplar acımsı olur, kullanmayın.',
      'Yaprakları bol suda iki kez yıkayıp süzgeçte iyice süzün.',
      'İri yaprakları elinizle ikiye bölün, küçükleri olduğu gibi bırakın.',
      'Yoğurdu ezilmiş sarımsak ve tuzla çırpın.',
      'Semizotlarını yoğurtlu sosla harmanlayın, üzerine zeytinyağı gezdirip hemen servis edin.',
    ],
  },
  {
    isim: 'Etsiz Çiğ Köfte', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 60, tur: 'yemek',
    malzemeler: [
      ['İnce Bulgur', '3 su bardağı (480 g)'],
      ['Salça', '3 yemek kaşığı'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['İsot Biber', '2 yemek kaşığı'],
      ['Pul Biber', '1 yemek kaşığı'],
      ['Kimyon', '1 tatlı kaşığı'],
      ['Nar Ekşisi', '3 yemek kaşığı'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Limon', '1 adet'],
      ['Maydanoz', 'yarım demet'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Marul', 'servis için'],
    ],
    adimlar: [
      'Bulguru geniş bir leğene koyun. Üzerine 1,5 su bardağı kaynar su döküp karıştırın ve üzerini kapatarak 20 dakika bekletin.',
      'Soğan ve sarımsağı rendeleyin (veya robottan geçirin) ve bulgura ekleyin.',
      'Salça, isot, pul biber, kimyon ve tuzu ekleyin. Şimdi sabır işi başlıyor: elinizle en az 15-20 dakika yoğurun. Yoğurdukça bulgur yumuşar ve renk koyulaşır — çiğ köftenin sırrı bu yoğurmadadır.',
      'Ara ara elinizi ıslatarak (nar ekşili su ile) yoğurmaya devam edin. Harç, avucunuzda sıkınca dağılmayan bir hamur olunca hazırdır.',
      'Nar ekşisi, zeytinyağı ve kıyılmış maydanozu ekleyip son bir kez yoğurun.',
      'Avucunuzda sıkarak parmak izli köfteler yapın. Marul yaprağına koyup limon sıkarak yiyin.',
    ],
  },
  {
    isim: 'Havuç Tarator', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 15, tur: 'yemek',
    malzemeler: [
      ['Havuç', '3 adet (300 g)'],
      ['Yoğurt', '1,5 su bardağı (300 g)'],
      ['Sarımsak', '2 diş'],
      ['Zeytinyağı', '2 yemek kaşığı'],
      ['Ceviz', '2 yemek kaşığı çekilmiş (isteğe bağlı)'],
      ['Tuz', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Havuçları soyup rendenin ince tarafında rendeleyin.',
      'Tavada zeytinyağını ısıtıp havuçları ekleyin. Orta ateşte, karıştırarak 5-6 dakika, yumuşayıp tatlı kokusu çıkana kadar soteleyin. Sonra tamamen soğumaya bırakın — sıcak havuç yoğurdu kesebilir.',
      'Yoğurdu ezilmiş sarımsak ve tuzla çırpın.',
      'Soğuyan havuçları yoğurda ekleyip karıştırın.',
      'Servis kasesine alıp üzerine çekilmiş ceviz serpin. Buzdolabında yarım saat dinlenirse daha lezzetli olur.',
    ],
  },
];
