// Türk Mutfağı 3. bölüm: Zeytinyağlılar & Sebze, Pilav & Makarna, Hamur İşi, Tatlılar.
import { type SeedTarif } from './seed-tarifler-turk';

const M = 'Türk Mutfağı';

export const TURK_3: SeedTarif[] = [
  // ─── ZEYTİNYAĞLILAR & SEBZE ───
  {
    isim: 'İmam Bayıldı', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Patlıcan', '6 adet küçük'],
      ['Soğan', '3 adet'],
      ['Sarımsak', '4 diş'],
      ['Domates', '2 adet'],
      ['Maydanoz', 'yarım demet'],
      ['Zeytinyağı', 'yarım su bardağı (100 ml)'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'İnce, uzun ve küçük patlıcan seçin (çekirdeği az, eti bol olur). Alacalı soyun: bir şerit soyup bir şerit bırakın; bu, hem şık görünür hem patlıcanın dağılmadan durmasını sağlar. Tuzlu suda 15-20 dakika bekletin (acısını alır, az yağ çeker), sonra kâğıt havluyla iyice kurulayın.',
      'Tavada 3-4 kaşık zeytinyağı ısıtın ve patlıcanları her tarafı hafifçe kızarıp yumuşayana kadar orta ateşte çevirerek pişirin. Amaç patlıcanları tamamen pişirmek değil, kabuklarını yumuşatıp yuva açmaya hazır hale getirmek. Kâğıt havluya alın.',
      'İç harç, İmam Bayıldı\'nın ruhudur ve sabır ister: soğanları ince yarım ay doğrayın. Aynı tavada kalan yağa (gerekirse biraz daha ekleyin) soğanları alın ve KISIK ateşte 10-12 dakika, ara sıra karıştırarak, iyice yumuşayıp şekerlenene (hafif kavrulup tatlanana) kadar pişirin. Yemeğin adı "imam bayıldı" — rivayete göre imam bu yağlı, tatlı soğanlı lezzetten bayılmış; o lezzet işte bu yavaş pişen soğanda saklı.',
      'İnce kıyılmış sarımsağı ekleyip 1 dakika çevirin, sonra küp doğranmış 1 domatesi, şekeri ve tuzu ekleyip 5 dakika, domates suyunu bırakıp harç toparlanana kadar pişirin. Ocaktan alıp ince kıyılmış maydanozu karıştırın.',
      'Patlıcanları geniş, sığ bir tencereye yan yana dizin. Her birinin ortasını boydan boya, tabana kadar kesmeden yarıp iki yana bastırarak açın; içine soğanlı harcı bolca doldurun. Üzerlerine birer domates dilimi ve isterseniz birer parça sivri biber koyun.',
      'Yarım su bardağı sıcak su ve 1 kaşık zeytinyağını tencerenin kenarından (harcın üzerine değil) ekleyin. Kapağı kapatıp kısık ateşte 25-30 dakika, patlıcanlar tamamen yumuşayıp suyunu çekene kadar pişirin.',
      'En önemli kural: İmam Bayıldı SICAK yenmez. Tencerede oda sıcaklığına gelene kadar soğutun, hatta buzdolabında bekletip serin servis edin. Zeytinyağlılar soğudukça yağ ve baharat sebzeye işler, gerçek lezzet ancak o zaman ortaya çıkar.',
    ],
  },
  {
    isim: 'Zeytinyağlı Taze Fasulye', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Taze Fasulye', '500 g'],
      ['Soğan', '1 adet'],
      ['Domates', '2 adet'],
      ['Zeytinyağı', 'yarım çay bardağı (50 ml)'],
      ['Şeker', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Fasulyelerin iki ucunu koparın ve yan tarafındaki kılçık teli (varsa) uçla birlikte çekip çıkarın — bu tel dişe gelir. Boyuna büyük fasulyeleri ikiye ya da üçe bölün, yıkayıp süzün. Taze, gevrek fasulye seçin; kırdığınızda "cıt" diye kırılmalı.',
      'Soğanı ince doğrayıp tencerede zeytinyağıyla KISIK ateşte 5-6 dakika, şeffaflaşana kadar kavurun. Zeytinyağlılarda soğanı yakmadan, yavaşça yumuşatmak esastır.',
      'Fasulyeleri ekleyip 5 dakika birlikte çevirin; yağla iyice tanışsınlar, renkleri canlansın.',
      'Rendelenmiş domatesi, şekeri ve tuzu ekleyin. Bir tutam şeker, domatesin ekşiliğini dengeler ve zeytinyağlıya o hafif tatlımsı, yuvarlak tadı verir — atlamayın.',
      '1 su bardağı sıcak su ekleyip kapağı kapatın; kısık ateşte 35-40 dakika, fasulyeler çatalla kolayca ezilecek kadar yumuşayana ve suyu neredeyse çekilene kadar pişirin. Zeytinyağlı fasulye diri değil, ağızda dağılacak kadar yumuşak olmalı.',
      'Ocaktan alıp tencerede, kapağı açık soğumaya bırakın. Oda sıcaklığında ya da buzdolabında soğutup servis edin; üzerine taze zeytinyağı gezdirip limon sıkın. Bir gün beklerse lezzeti daha da oturur.',
    ],
  },
  {
    isim: 'Zeytinyağlı Yaprak Sarma', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Asma Yaprağı', '300 g (salamura)'],
      ['Pirinç', '2 su bardağı (360 g)'],
      ['Soğan', '3 adet'],
      ['Çam Fıstığı', '2 yemek kaşığı'],
      ['Kuru Üzüm', '2 yemek kaşığı'],
      ['Zeytinyağı', 'yarım su bardağı (100 ml)'],
      ['Limon', '2 adet'],
      ['Tarçın', 'yarım çay kaşığı'],
      ['Kuru Nane', '1 tatlı kaşığı'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Salamura yaprakları kaynar suda 3-4 dakika haşlayıp soğuk suda yıkayın; tuzu gitsin. Saplarını koparın.',
      'İç harç: zeytinyağının yarısında çam fıstıklarını pembeleşene kadar kavurun; ince doğranmış soğanları ekleyip 8 dakika yumuşatın.',
      'Yıkanmış pirinci ekleyip 3 dakika kavurun. Üzüm, tarçın, nane, şeker, tuz, karabiber ve 1 su bardağı sıcak su ekleyin; su çekilene kadar 5 dakika pişirip soğumaya bırakın. Pirinç yarı pişmiş olacak — tam pişmesi sarmanın içinde olur.',
      'Sarma vakti: yaprağı parlak yüzü alta, damarlı yüzü üste gelecek şekilde önünüze açın. Sap kısmına bir tatlı kaşığı harç koyun.',
      'Önce alt kenarı harcın üzerine katlayın, sonra iki yanı içe kapatıp yaprağı kalem gibi ince ve sıkı sarın.',
      'Tencerenin tabanına birkaç yaprak serin (dibi tutmasın), sarmaları sıkıca yan yana dizin. Üzerine limon dilimlerini yayıp düz bir tabak kapatın.',
      'Kalan zeytinyağı, 1 limonun suyu ve sarmaları yarı geçecek kadar sıcak su ekleyin. Kısık ateşte 45 dakika pişirin.',
      'Tencerede soğutup soğuk servis edin. Sabır ister ama her lokması buna değer!',
    ],
  },
  {
    isim: 'Zeytinyağlı Enginar', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Enginar', '4 adet (temizlenmiş)'],
      ['Havuç', '1 adet'],
      ['Patates', '1 adet'],
      ['Bezelye', 'yarım su bardağı (75 g)'],
      ['Soğan', '1 adet küçük'],
      ['Zeytinyağı', 'yarım çay bardağı (50 ml)'],
      ['Limon', '1,5 adet'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Dereotu', 'birkaç dal'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Enginar havayla temas edince hızla kararır; bu yüzden temizlenmiş enginarları limonlu suda (1 limonun suyunu sıktığınız su) bekletin. Hazır temizlenmiş dondurulmuş enginar da kullanabilirsiniz, çok pratiktir.',
      'Havuç, patates ve soğanı minik küpler halinde doğrayın. Küçük doğramak, iç harcın enginarın çukuruna güzelce yerleşmesini sağlar.',
      'Enginarları geniş bir tencereye, çukur kısımları yukarı bakacak şekilde yan yana yerleştirin (pişerken devrilmesinler diye sıkı dizin).',
      'Küp doğranmış sebzeleri ve bezelyeyi enginarların çukurlarına ve aralarındaki boşluklara paylaştırın.',
      'Zeytinyağı, yarım limonun suyu, şeker, tuz ve 1,5 su bardağı sıcak suyu tencerenin kenarından ekleyin. Şeker, zeytinyağlının o hafif tatlımsı, dengeli tadını verir.',
      'Kapağı kapatıp kısık ateşte 30-35 dakika, enginarlar bıçak ucu kolayca girecek kadar yumuşayana ve sebzeler pişene kadar pişirin.',
      'Tencerede tamamen soğutun (zeytinyağlı sıcak servis edilmez). Üzerine bol kıyılmış dereotu serpip, oda sıcaklığında veya soğuk servis edin. İlkbaharın en zarif zeytinyağlısıdır.',
    ],
  },
  {
    isim: 'Zeytinyağlı Barbunya', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Barbunya', '2 su bardağı (350 g, kuru) veya 500 g taze'],
      ['Soğan', '1 adet'],
      ['Havuç', '1 adet'],
      ['Domates', '2 adet'],
      ['Salça', '1 tatlı kaşığı'],
      ['Zeytinyağı', 'yarım çay bardağı (50 ml)'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Limon', 'servis için'],
      ['Maydanoz', 'birkaç dal'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Kuru barbunya kullanıyorsanız bir gece bol suda ıslatın, ıslatma suyunu döküp taze suyla yarı yumuşayana kadar 25 dakika haşlayıp süzün. Taze (iç) barbunya kullanıyorsanız bu ön haşlamaya gerek yok, doğrudan yemeğe girer.',
      'Soğanı ince doğrayıp zeytinyağında 5 dakika, yumuşayana kadar kavurun; halka halka doğranmış havucu ekleyip 3 dakika çevirin.',
      'Salçayı ekleyip 1 dakika, ham kokusu geçene kadar kavurun; rendelenmiş domatesi ekleyip 3 dakika pişirin.',
      'Barbunyaları, şekeri ve tuzu ekleyin; üzerine 2 su bardağı sıcak su koyun.',
      'Kapağı kapatıp kısık ateşte 30-35 dakika, taneler dilde dağılacak kadar yumuşayana ve suyu koyulaşana kadar pişirin. Barbunya diri değil, yumuşacık olmalı.',
      'Tencerede tamamen soğutun. Kıyılmış maydanoz serpip, üzerine taze zeytinyağı gezdirip limon dilimleriyle soğuk servis edin. Ertesi gün daha da lezzetlidir.',
    ],
  },
  {
    isim: 'Kabak Mücver', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Kabak', '3 adet (600 g)'],
      ['Yumurta', '2 adet'],
      ['Un', '4 yemek kaşığı'],
      ['Beyaz Peynir', '100 g'],
      ['Dereotu', 'yarım demet'],
      ['Taze Soğan', '3 dal'],
      ['Ayçiçek Yağı', 'kızartma için'],
      ['Yoğurt', 'servis için'],
      ['Tuz', '1 çay kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Kabakları yıkayıp rendenin iri tarafında rendeleyin. Rendelenmiş kabağa bir tutam tuz serpip 10 dakika bekletin — tuz, kabağın bol suyunu dışarı çeker.',
      'Mücverin başarısının %90\'ı bu adımda: rendelenmiş kabağı avuç avuç alıp iki elinizin arasında suyunu ADAMAKILLI sıkın, sıkılan suyu dökün. Islak kabak harcı sulandırır; mücver tavada dağılır, bol yağ çeker ve çıtır olmaz. İyi sıkılmış kabak neredeyse kuru görünmeli.',
      'Sıkılmış kabağı geniş bir kaba alın; yumurtaları, ufalanmış beyaz peyniri, ince kıyılmış dereotu ve taze soğanı ekleyin. Peynir tuzlu olduğu için tuzu en son, tada bakarak ayarlayın.',
      'Unu azar azar ekleyip karıştırın; kaşıktan zor akan, koyu bir kek hamuru kıvamı hedefleyin. Fazla cıvıksa 1 kaşık daha un, fazla katıysa çok az su ekleyin. Karabiberi de ekleyin.',
      'Geniş tavada 4-5 kaşık yağı orta ateşte kızdırın (yağ yeterince kızmazsa mücver yağ emer). Harçtan kaşık kaşık alıp tavaya bırakın ve kaşığın arkasıyla hafifçe yayıp yassılaştırın; kalın olursa içi çiğ kalır.',
      'Her yüzünü 3-4 dakika, kenarları çıtır ve altın kahve olana kadar kızartın; erken çevirmeyin, kabuk bağlasın. Kâğıt havluya alıp fazla yağını süzdürün.',
      'Sarımsaklı yoğurtla sıcak servis edin. Soğuk da lezzetlidir, ertesi gün kahvaltıya da yakışır.',
    ],
  },
  {
    isim: 'Ispanak Yemeği', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Ispanak', '750 g'],
      ['Soğan', '1 adet'],
      ['Pirinç', '2 yemek kaşığı'],
      ['Salça', '1 yemek kaşığı'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Yoğurt', 'servis için'],
      ['Sarımsak', '1 diş (yoğurt için)'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Ispanakları köklerinden ayırın ve bol suda, kum kalmayana kadar 2-3 kez yıkayın (ıspanak toprağa yakın büyür, yaprak diplerinde kum tutar). Süzüp iri iri doğrayın.',
      'Soğanı ince doğrayıp zeytinyağında 4-5 dakika, yumuşayana kadar kavurun; salçayı ekleyip 1 dakika daha, ham kokusu geçene kadar pişirin.',
      'Doğranmış ıspanakları tencereye ekleyin. Başta tencereden taşacak kadar çok görünür ama korkmayın — ıspanak 2-3 dakikada büzülüp söner ve bol su salar. Bu yüzden bu yemekte çok az su eklenir.',
      'Yıkanmış pirinci ve tuzu ekleyin; ıspanak az su salmışsa yarım su bardağı sıcak su koyun (pirincin pişmesine yetecek kadar).',
      'Kapağı kapatıp kısık ateşte 20 dakika, pirinçler yumuşayıp suyunu çekene kadar pişirin. Pirinç, ıspanağın suyunu emerek yemeği bir arada tutar.',
      'Sarımsaklı yoğurtla sıcak servis edin — ıspanak yemeğinin yanına yoğurt olmazsa olmazdır, ekşiliği ıspanağın toprağımsı tadını dengeler.',
    ],
  },
  {
    isim: 'Zeytinyağlı Pırasa', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Pırasa', '4 adet (800 g)'],
      ['Havuç', '1 adet'],
      ['Pirinç', '2 yemek kaşığı'],
      ['Zeytinyağı', 'yarım çay bardağı (50 ml)'],
      ['Limon', '1 adet'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Pırasaların sert koyu yeşil uçlarını ve köklerini kesin; kalan beyaz ve açık yeşil kısımları 2 cm kalınlığında halkalar halinde doğrayın. Halkaların arasında sıklıkla toprak-kum sıkışır; doğradıktan sonra bir kaba alıp bol suyla yıkayıp süzün.',
      'Havucu yarım halkalar şeklinde doğrayın (havuç, zeytinyağlı pırasaya hoş bir tatlılık ve renk katar).',
      'Tencereye zeytinyağını koyup havuçları 3 dakika soteleyin.',
      'Pırasaları ekleyip 5 dakika, hafif yumuşayıp hacmi küçülene kadar birlikte çevirin.',
      'Yıkanmış pirinci, şekeri (zeytinyağlının tatlımsı dengesi için), tuzu ve 1 su bardağı sıcak suyu ekleyin.',
      'Kapağı kapatıp kısık ateşte 25-30 dakika, pırasalar iyice yumuşayıp pirinç pişene kadar ağır ağır pişirin. Tencerede soğutun; oda sıcaklığında, üzerine limon sıkarak servis edin — zeytinyağlı pırasa soğuk yendiğinde tadı oturur.',
    ],
  },
  {
    isim: 'Türlü', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Patlıcan', '2 adet'],
      ['Kabak', '2 adet'],
      ['Patates', '2 adet'],
      ['Taze Fasulye', '200 g'],
      ['Sivri Biber', '3 adet'],
      ['Soğan', '1 adet'],
      ['Domates', '3 adet'],
      ['Sarımsak', '3 diş'],
      ['Salça', '1 yemek kaşığı'],
      ['Zeytinyağı', 'yarım çay bardağı (50 ml)'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Türlü, adı gibi "türlü türlü" sebzenin buluştuğu bir yemektir; ne bulursanız katabilirsiniz. Bütün sebzeleri yıkayın. Patlıcanları alacalı soyup iri küpler halinde doğrayın ve acısı çıksın diye tuzlu suda 10-15 dakika bekletin. Kabak, patates ve biberleri de iri iri doğrayın (küçük doğranan sebze türlüde dağılır, iri olmalı); fasulyelerin uçlarını alıp ikiye bölün.',
      'Kalın tabanlı geniş tencerede soğanı zeytinyağıyla 5 dakika, yumuşayana kadar kavurun; ezilmiş sarımsağı ve salçayı ekleyip 1 dakika daha, kokusu çıkana kadar pişirin.',
      'Sebzeleri pişme sürelerine göre sırayla ekleyin: önce en sert olan patates ve fasulyeyi koyup 5 dakika çevirin ki ötekilerle aynı anda yumuşasınlar.',
      'Sonra patlıcan, kabak ve biberi ekleyin (bunlar daha çabuk pişer). Rendelenmiş domatesleri en üste dökün — türlüde domates genelde karıştırılmaz, üstte pişip sebzelere sosunu salar.',
      'Tuzu ve 1 su bardağı sıcak suyu kenardan ekleyip kapağı kapatın (sebzeler pişerken kendi suyunu da salacağı için az su yeter).',
      'Kısık ateşte 35-40 dakika, tüm sebzeler yumuşayana kadar pişirin. Kaşıkla KARIŞTIRMAYIN — bunun yerine ara sıra tencerenin kulplarından tutup hafifçe sallayın; böylece sebzeler ezilip lapaya dönmez, formunu korur. Zeytinyağlı olarak soğuk da, sıcak ana yemek olarak da yenir; yanında yoğurt çok yakışır.',
    ],
  },

  // ─── PİLAV & MAKARNA ───
  {
    isim: 'Tereyağlı Pirinç Pilavı', mutfak: M, kategori: 'Pilav & Makarna', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Pirinç', '2 su bardağı (360 g)'],
      ['Tel Şehriye', '2 yemek kaşığı'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Pirinci bir kaba koyun, üzerine 1 tatlı kaşığı tuz atıp sıcak su ekleyin ve 20 dakika bekletin. Sonra soğuk suyla, su berrak akana kadar yıkayıp süzün — nişastası gidince pilav tane tane olur.',
      'Tencerede tereyağını orta ateşte eritin. Şehriyeleri ekleyip sürekli karıştırarak koyu pembe olana kadar kavurun — gözünüzü ayırmayın, bir anda yanabilir.',
      'Süzülmüş pirinci ekleyin ve 3 dakika, taneler cam gibi parlayana kadar birlikte kavurun.',
      '3 su bardağı sıcak su ve kalan tuzu ekleyin. Bir kez karıştırıp kapağı kapatın; bir daha karıştırmak yok!',
      'Önce orta ateşte kaynamasını bekleyin, sonra ocağı en kısığa alın ve suyunu tamamen çekene kadar 10-12 dakika pişirin.',
      'Ocağı kapatın; kapağın altına kağıt havlu yerleştirip 15 dakika demlendirin. Havlu fazla buharı emer, pilav kuru ve tane tane olur. Nazikçe karıştırıp servis edin.',
    ],
  },
  {
    isim: 'Bulgur Pilavı', mutfak: M, kategori: 'Pilav & Makarna', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Bulgur', '2 su bardağı (340 g, pilavlık)'],
      ['Soğan', '1 adet'],
      ['Sivri Biber', '2 adet'],
      ['Domates', '2 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Soğanı ve sivri biberleri küçük küpler halinde doğrayın; domatesleri rendeleyin. Pilavlık (iri) bulgur kullanın, köftelik (ince) bulgurdan pilav lapa olur.',
      'Kalın tabanlı tencerede tereyağını eritip soğanı 3-4 dakika, yumuşayana kadar kavurun; biberleri ekleyip 2 dakika daha çevirin.',
      'Salçayı ekleyip 1 dakika, ham kokusu geçene kadar kavurun; rendelenmiş domatesi ekleyip suyu çekilene ve yağı üzerine çıkana kadar 3-4 dakika pişirin.',
      'Bulguru ekleyin (bulgur pirinç gibi uzun uzun yıkanmaz; kısaca durulayıp süzmek yeter). Baharatlı sosla 2-3 dakika kavurun ki her tane yağı emsin — bu kavurma bulgur pilavını tane tane yapar.',
      '3 su bardağı SICAK su ve tuzu ekleyin (bulgur için su:bulgur oranı yaklaşık 1,5:1\'dir). Bir kez karıştırıp kapağı kapatın. Önce kaynatın, sonra ateşi en kısığa alıp suyunu tamamen çekene kadar 12-15 dakika pişirin.',
      'Ocaktan alıp kapağın altına bir kâğıt havlu koyup 10 dakika demlendirin (havlu fazla buharı emer, pilav dağılmaz). Çatalla havalandırarak karıştırın. Cacık ve yoğurtla, ya da et yemeklerinin yanında servis edin.',
    ],
  },
  {
    isim: 'İç Pilav', mutfak: M, kategori: 'Pilav & Makarna', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Pirinç', '2 su bardağı (360 g)'],
      ['Çam Fıstığı', '2 yemek kaşığı'],
      ['Kuru Üzüm', '2 yemek kaşığı'],
      ['Soğan', '1 adet'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Tarçın', 'yarım çay kaşığı'],
      ['Maydanoz', 'birkaç dal'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Pirinci tuzlu sıcak suda 20 dakika bekletip yıkayın. Kuru üzümleri de ılık suda 10 dakika bekletin.',
      'Tencerede tereyağını eritip çam fıstıklarını kısık ateşte, sürekli karıştırarak pembeleştirin — fıstıklar saniyeler içinde yanabilir, başından ayrılmayın.',
      'İnce doğranmış soğanı ekleyip 5 dakika yumuşatın.',
      'Pirinci ekleyip 3 dakika kavurun.',
      'Süzülmüş üzümleri, tarçını, karabiberi, tuzu ve 3 su bardağı sıcak suyu ekleyin.',
      'Kapağı kapatıp kısık ateşte suyunu çekene kadar 12 dakika pişirin; 15 dakika demlendirin.',
      'Kıyılmış maydanozu ekleyip nazikçe karıştırın. Tavuğun yanına da yakışır, tek başına da yenir.',
    ],
  },
  {
    isim: 'Nohutlu Pilav', mutfak: M, kategori: 'Pilav & Makarna', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Pirinç', '2 su bardağı (360 g)'],
      ['Nohut', '1 su bardağı haşlanmış (160 g)'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Pirinci bir kaseye alıp üzerine 1 tatlı kaşığı tuz ve sıcak su ekleyin, 20 dakika bekletin. Sonra soğuk suyla, su berrak akana kadar durulayıp süzün. Bu bekletme ve yıkama, pirincin nişastasını alıp pilavın tane tane olmasını sağlar.',
      'Nohutları bir gece ıslatıp yumuşayana kadar haşlayın (ya da vakit yoksa hazır haşlanmış nohut kullanın; suyunu süzüp durulayın). Kabuklarını sevmiyorsanız haşladıktan sonra avuçlarınız arasında ovup ayıklayabilirsiniz.',
      'Kalın tabanlı tencerede tereyağını eritin, süzülmüş pirinci ekleyip 3 dakika, taneler cam gibi parlayana kadar kavurun. Bu kavurma pilavın olmazsa olmazı.',
      'Nohutları ekleyip 1 dakika birlikte çevirin.',
      '3 su bardağı sıcak su ve kalan tuzu ekleyin. Bir kez karıştırıp kapağı kapatın; önce kaynatın, sonra ateşi en kısığa alıp suyunu tamamen çekene kadar 12 dakika pişirin. Kapağı sık sık açıp karıştırmayın.',
      'Ocaktan alıp kapağın altına kâğıt havlu koyarak 15 dakika demlendirin, sonra çatalla havalandırın. Suyun yerine tavuk suyu kullanırsanız lezzeti kat kat artar — düğün pilavı böyle yapılır.',
    ],
  },
  {
    isim: 'Fırın Makarna', mutfak: M, kategori: 'Pilav & Makarna', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Makarna', '500 g (kalem veya burgu)'],
      ['Yumurta', '3 adet'],
      ['Süt', '2 su bardağı (400 ml)'],
      ['Kaşar Peyniri', '2 su bardağı rendelenmiş (160 g)'],
      ['Beyaz Peynir', '100 g (isteğe bağlı)'],
      ['Tereyağı', '1 yemek kaşığı (20 g)'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Makarnayı bol tuzlu suda, paketin yazdığından 2 dakika EKSİK haşlayın (al dente). Fırında pişmeye devam edeceği için tam pişmiş makarna sonunda yumuşayıp dağılır. Süzüp içine tereyağını karıştırın; bu, makarnaların birbirine yapışmasını önler.',
      'Sos için yumurta, süt, tuz ve karabiberi bir kâsede çırpın. Bu sütlü-yumurtalı sos, fırında pişerken pıhtılaşıp makarnaları birbirine bağlar ve dilimlenebilir bir yapı verir.',
      'Süzülmüş makarnanın içine kaşarın yarısını ve ufalanmış beyaz peyniri karıştırın (çift peynir daha lezzetli olur).',
      'Yağlanmış fırın kabına makarnayı yayın; sütlü karışımı üzerine eşit şekilde dökün. Kabı hafifçe sallayarak veya çatalla iterek sosun makarnaların en altına kadar ulaşmasını sağlayın.',
      'Kalan kaşarı üzerine bolca serpin — bu üst tabaka fırında kızarıp çıtır bir kabuk oluşturacak.',
      'Önceden ısıtılmış 180 derece fırında 25-30 dakika, üzeri altın rengi ve kenarları çıtır olana kadar pişirin. Fırından çıkınca 10 dakika dinlendirin (sıcakken kesmek dağıtır), sonra kare dilimler kesin — o çıtır köşeler her zaman ilk kapışılan yerdir!',
    ],
  },
  {
    isim: 'Cevizli Erişte', mutfak: M, kategori: 'Pilav & Makarna', sure: 25, tur: 'yemek',
    malzemeler: [
      ['Erişte', '400 g'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Ceviz', '1 su bardağı çekilmiş (100 g)'],
      ['Lor Peyniri', '150 g'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Bol suyu kaynatıp tuzu ekleyin; ev yapımı veya hazır erişteleri 8-10 dakika, yumuşayana kadar haşlayıp süzün. Bir kepçe haşlama suyunu kenara ayırın; gerekirse erişteleri açmak için kullanırsınız.',
      'Geniş tavada tereyağını eritin ve orta ateşte, hafif kestane rengi alıp fındıksı bir koku yayana kadar 1-2 dakika bekleyin. Bu "kızmış/yakılmış tereyağı" (beurre noisette) eriştenin ruh ikizidir; sıradan eriyik tereyağından çok daha derin bir lezzet verir. Ama yakmayın, sadece renk değiştirsin.',
      'Çekilmiş cevizleri ekleyip 1 dakika kavurun; kavrulmuş ceviz kokusu tavaya yayılsın.',
      'Süzülmüş erişteleri tavaya alıp 2-3 dakika, her tel kızmış tereyağı ve cevizle kaplanana kadar çevirin. Kuru geldiyse ayırdığınız haşlama suyundan ekleyin.',
      'Ocağı kapatın, ufalanmış lor peynirini üzerine serpip bir kez karıştırın ve hemen servis edin. Sıcakken lorun hafif eridiği o an en lezzetli halidir.',
    ],
  },
  {
    isim: 'Sebzeli Bulgur Pilavı', mutfak: M, kategori: 'Pilav & Makarna', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Bulgur', '2 su bardağı (340 g)'],
      ['Kabak', '1 adet'],
      ['Havuç', '1 adet'],
      ['Sivri Biber', '2 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Kabak ve havucu küçük küpler, biberleri minik halkalar halinde doğrayın. Sebzeleri küçük doğramak, bulgurla birlikte eşit pişmelerini sağlar.',
      'Zeytinyağında önce en sert sebze olan havucu 3 dakika soteleyin, sonra kabak ve biberi ekleyip 4 dakika daha, sebzeler diriliğini koruyarak yumuşayana kadar çevirin.',
      'Salçayı ekleyip 1 dakika, ham kokusu geçene kadar kavurun.',
      'Pilavlık (iri) bulguru ekleyip 2-3 dakika kavurun; her tane yağı ve baharatı emsin — bu kavurma pilavın tane tane olmasının anahtarıdır.',
      '3 su bardağı sıcak su ve tuzu ekleyin. Bir kez karıştırıp kapağı kapatın; önce kaynatın, sonra ateşi kısıp suyunu çekene kadar 12-15 dakika pişirin.',
      'Ocaktan alıp kapağın altına kâğıt havlu koyarak 10 dakika demlendirin, sonra çatalla havalandırarak karıştırın. Sarımsaklı yoğurt veya cacıkla servis edin — hafif, doyurucu ve sağlıklı bir öğün.',
    ],
  },

  // ─── HAMUR İŞİ ───
  {
    isim: 'Sigara Böreği', mutfak: M, kategori: 'Hamur İşi', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Yufka', '3 adet'],
      ['Beyaz Peynir', '250 g'],
      ['Maydanoz', 'yarım demet'],
      ['Ayçiçek Yağı', 'kızartma için (1,5 su bardağı)'],
    ],
    adimlar: [
      'Peyniri bir kâsede çatalla ezin; ince kıyılmış maydanozu ekleyip karıştırın. Peynir çok tuzluysa harç yeterli, değilse bir tutam tuz katın. İsterseniz biraz da dereotu ekleyebilirsiniz.',
      'Yufkayı tezgâha serin ve nemli bir bezle üzerini örtün (yufka açıkta çabuk kurur, kuruyunca sararken çatlar). Yufkayı önce ikiye, sonra her yarımı üçgen dilimler halinde kesin — bir yufkadan yaklaşık 8 üçgen çıkar.',
      'Her üçgenin geniş (dış) kenarına bir tatlı kaşığı peynirli harcı, çubuk şeklinde yayarak koyun. Fazla harç koymayın, kızarırken dışarı akar.',
      'Geniş kenardan sıkıca sarmaya başlayın. Bir tur sardıktan sonra iki yan ucu içe doğru katlayın (harç uçlardan kaçmasın) ve sigara gibi ince, sıkı bir rulo halinde sarmaya devam edin. Sıkı sarmak, kızarırken açılmamasının anahtarıdır.',
      'Rulonun uç kısmına parmağınızla biraz su sürüp bastırarak yapıştırın; bu, kızgın yağda açılmasını önler.',
      'Yağı orta ateşte kızdırın — çok kızgın olursa böreğin içi ısınmadan dışı yanar, az kızgınsa yağ çeker. Bir parça yufka attığınızda etrafında kabarcıklar oluşup yüzeye çıkıyorsa yağ hazırdır. Börekleri kalabalık etmeden, azar azar atıp her tarafı altın sarısı olana kadar çevirerek kızartın.',
      'Kâğıt havluya alıp fazla yağını süzdürün. Sıcak sıcak, yanında çay ile servis edin — soğuyunca çıtırlığını kaybeder.',
    ],
  },
  {
    isim: 'Peynirli Gözleme', mutfak: M, kategori: 'Hamur İşi', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Un', '3 su bardağı (360 g)'],
      ['Beyaz Peynir', '200 g'],
      ['Maydanoz', 'birkaç dal'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Unu geniş bir kaba eleyin (elemek hamuru havalandırır), tuzu ekleyin. Ortasını havuz gibi açıp 1 su bardağı ILIK suyu azar azar ekleyerek yoğurmaya başlayın. Su miktarı unun cinsine göre biraz değişebilir; azar azar ekleyip kontrol edin.',
      'Kulak memesi yumuşaklığında, ele yapışmayan bir hamur elde edene kadar 8-10 dakika yoğurun. Üzerini nemli bezle örtüp 20-30 dakika dinlendirin. Bu dinlenme, hamurdaki glüteni gevşetir; dinlenen hamur incecik açılır, açarken geri toplanmaz ve yırtılmaz.',
      'Peyniri çatalla ezip ince kıyılmış maydanozla karıştırın. Klasik peynirli dışında ıspanaklı, patatesli ya da kıymalı harç da yapabilirsiniz.',
      'Hamuru 4 eşit bezeye ayırıp yuvarlayın. Bolca unlanmış tezgâhta her bezeyi oklavayla, tabak büyüklüğünde ve olabildiğince ince (yaklaşık 2 mm) açın — gözlemenin inceliği ustalığın göstergesidir.',
      'Açılan yufkanın yarısına peynirli harcı yayın, boş yarısını üzerine kapatıp yarım ay şekli verin ve kenarlarını parmakla bastırarak kapatın (harç dışarı taşmasın).',
      'Teflon tavayı veya varsa sacı orta ateşte, yağsız olarak ısıtın. Gözlemeyi tavaya alıp her yüzünü 2-3 dakika, üzerinde kahverengi kızarmış benekler oluşana kadar pişirin. Kabarırsa temiz bir bezle hafifçe bastırın.',
      'Tavadan aldığınız gibi, sıcakken üzerine tereyağı sürün; eriyip hamura işleyen tereyağı gözlemenin tacıdır. Ayran ile servis edin.',
    ],
  },
  {
    isim: 'Kıymalı Pide', mutfak: M, kategori: 'Hamur İşi', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Un', '3,5 su bardağı (420 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Kıyma', '300 g'],
      ['Soğan', '1 adet'],
      ['Sivri Biber', '2 adet'],
      ['Domates', '1 adet'],
      ['Tereyağı', '2 yemek kaşığı (sürmek için)'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
      ['Pul Biber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Mayayı ve şekeri 1,5 su bardağı ılık suda eritin; 5 dakika bekleyin, üzeri köpürünce maya canlanmış demektir.',
      'Unu ve tuzu ekleyip 10 dakika, ele yapışmayan yumuşak bir hamur olana kadar yoğurun. Üzerini örtüp sıcak bir köşede 40 dakika, iki katına çıkana kadar mayalandırın.',
      'Harç: kıymayı, minik doğranmış soğan, biber ve domatesle çiğ olarak karıştırın; tuz, karabiber ve pul biberi ekleyin. Pişmiş değil çiğ harç — fırında etin suyu pideye işler.',
      'Hamuru 4 bezeye bölün. Her bezeyi unlu tezgahta uzun bir elips şeklinde, yarım santim kalınlığında açın.',
      'Harcı ortaya boydan boya yayın; kenar boşluğu bırakın. İki uzun kenarı harcın üzerine hafifçe kıvırın, uçları birleştirip kayık şekli verin.',
      'Pideleri yağlı kağıt serili tepsiye alın. Önceden ısıtılmış 230 derece fırında 12-15 dakika, kenarları kızarana kadar pişirin.',
      'Çıkar çıkmaz kenarlarına tereyağı sürün, dilimleyip sıcak servis edin.',
    ],
  },
  {
    isim: 'Lahmacun', mutfak: M, kategori: 'Hamur İşi', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Un', '3 su bardağı (360 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Kıyma', '250 g (yağlı)'],
      ['Soğan', '1 adet'],
      ['Sarımsak', '2 diş'],
      ['Sivri Biber', '2 adet'],
      ['Domates', '2 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Maydanoz', 'yarım demet'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Tuz', '1,5 tatlı kaşığı'],
      ['Limon', 'servis için'],
    ],
    adimlar: [
      'Hamur: mayayı 1 su bardağı ılık suda eritin; un ve tuzla yumuşak bir hamur yoğurup 30 dakika mayalandırın.',
      'Harç: soğan, sarımsak, biber, domates ve maydanozu robotta çekin; süzgeçte 5 dakika süzün — sulu harç hamuru ıslatır. Kıyma, salça, pul biber ve tuzla karıştırın.',
      'Hamuru 6 küçük bezeye ayırın. Her bezeyi tabak büyüklüğünde, olabildiğince ince açın — lahmacunun sırrı incecik hamurdadır.',
      'Harcı ince bir tabaka halinde, kenarlarına kadar parmaklarınızla yayın (kalın sürmeyin, kurur).',
      'Fırının en yüksek ayarını (250 derece) önceden iyice ısıtın; tepsiyi de fırında ısıtırsanız tabanı çıtır olur.',
      'Lahmacunları sıcak tepsiye alıp 6-8 dakika, kenarları hafif kızarana kadar pişirin.',
      'İçine maydanoz koyup limon sıkın, dürüm yapıp afiyetle yiyin!',
    ],
  },
  {
    isim: 'Mantı', mutfak: M, kategori: 'Hamur İşi', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Un', '3 su bardağı (360 g)'],
      ['Yumurta', '1 adet'],
      ['Kıyma', '250 g'],
      ['Soğan', '1 adet'],
      ['Yoğurt', '2 su bardağı (400 g)'],
      ['Sarımsak', '2 diş'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Salça', '1 tatlı kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Kuru Nane', '1 çay kaşığı'],
      ['Tuz', '2 tatlı kaşığı'],
      ['Karabiber', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Hamur: un, yumurta, 1 çay kaşığı tuz ve yarım su bardağı suyla sert bir hamur yoğurun. Nemli bezle örtüp 30 dakika dinlendirin.',
      'İç harç: kıymayı rendelenmiş soğan, tuz ve karabiberle karıştırın.',
      'Hamuru ikiye bölüp unlu tezgahta olabildiğince ince açın (2-3 mm). Bıçakla 3x3 cm karelere kesin.',
      'Her karenin ortasına nohut büyüklüğünde harç koyun. Dört köşeyi ortada birleştirip parmak uçlarınızla sıkıca yapıştırın — bohça gibi.',
      'Bol tuzlu suyu kaynatın; mantıları atıp 8-10 dakika, hamur yumuşayana kadar haşlayın ve delikli kepçeyle alın.',
      'Yoğurdu ezilmiş sarımsak ve bir tutam tuzla çırpın; mantıların üzerine dökün.',
      'Tavada tereyağını eritip salça, pul biber ve naneyi ekleyin; köpüren sosu yoğurdun üzerine gezdirin. Elleriniz dert görmesin!',
    ],
  },
  {
    isim: 'Ispanaklı Börek', mutfak: M, kategori: 'Hamur İşi', sure: 55, tur: 'yemek',
    malzemeler: [
      ['Yufka', '3 adet'],
      ['Ispanak', '500 g'],
      ['Soğan', '1 adet'],
      ['Lor Peyniri', '150 g'],
      ['Yumurta', '2 adet'],
      ['Süt', '1 su bardağı (200 ml)'],
      ['Ayçiçek Yağı', 'yarım çay bardağı'],
      ['Çörek Otu', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Ispanakları yıkayıp doğrayın. Soğanı 2 kaşık yağda kavurun, ıspanakları ekleyip suyu çekilene kadar 5-6 dakika pişirin; tuzlayın ve soğutun. Lor peynirini karıştırın.',
      'Sos: 1 yumurta + 1 yumurta akı (sarısını üstü için ayırın), süt ve kalan yağı çırpın.',
      'Fırın tepsisini yağlayın. İlk yufkayı serin (kenarları taşsın), üzerine sostan gezdirin.',
      'İkinci yufkayı buruşturarak serin — buruşuk katlar böreği kat kat ve kabarık yapar. Yine sos gezdirip ıspanaklı harcın yarısını yayın.',
      'Taşan kenarları içe katlayın; kalan yufka ve harçla katları tekrarlayıp en üstü düz yufkayla kapatın.',
      'Ayırdığınız yumurta sarısını üzerine sürün, çörek otu serpin. Dilimlere kesin — pişmeden kesmek servisi kolaylaştırır.',
      'Önceden ısıtılmış 180 derece fırında 35 dakika, üzeri kızarana kadar pişirin.',
    ],
  },
  {
    isim: 'Poğaça', mutfak: M, kategori: 'Hamur İşi', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Un', '4 su bardağı (480 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Süt', '1 su bardağı ılık (200 ml)'],
      ['Ayçiçek Yağı', 'yarım su bardağı (100 ml)'],
      ['Yumurta', '2 adet (1 tanesi üzeri için)'],
      ['Şeker', '1 yemek kaşığı'],
      ['Beyaz Peynir', '200 g (iç için)'],
      ['Maydanoz', 'birkaç dal'],
      ['Çörek Otu', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Ilık süte (parmağınızı yakmayacak sıcaklıkta; sıcak süt mayayı öldürür) maya ve şekeri ekleyip eritin. 5 dakika bekleyin; üzeri köpük köpük olunca maya canlanmış demektir. Köpürmezse maya ölüdür, yenisiyle baştan başlayın.',
      'Geniş bir kaba mayalı sütü, sıvı yağı, 1 yumurtanın akını (sarısını üzerine sürmek için ayırın) ve tuzu koyun. Unu azar azar ekleyerek, ele yapışmayan ama yumuşacık bir hamur elde edene kadar 8-10 dakika yoğurun. Poğaçanın yumuşaklığı bu yağlı, yumuşak hamurdan gelir; sert hamur sert poğaça verir.',
      'Üzerini nemli bezle örtüp sıcak, cereyansız bir yerde 30-40 dakika, hamur iki katına çıkana kadar mayalandırın.',
      'İç harç için peyniri çatalla ezip ince kıyılmış maydanozla karıştırın.',
      'Mayalanan hamurdan mandalina büyüklüğünde bezeler koparın. Her bezeyi avuç içinde yassıltıp ortasına bir tatlı kaşığı peynir koyun, kenarları ortada birleştirip kapatın ve pürüzsüz bir top olacak şekilde yuvarlayın (birleşme yeri altta kalsın).',
      'Poğaçaları yağlı kâğıt serili tepsiye, kabaracakları için aralıklı dizin. 10-15 dakika daha dinlendirin, sonra üzerlerine ayırdığınız yumurta sarısını fırçayla sürüp çörek otu ve isterseniz susam serpin.',
      'Önceden ısıtılmış 180 derece fırında 20-25 dakika, üzerleri parlak kahverengi olana kadar pişirin. Yumuşacık, puf puf poğaçalar sıcakken de ertesi gün de lezzetlidir.',
    ],
  },
  {
    isim: 'Pişi', mutfak: M, kategori: 'Hamur İşi', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Un', '3,5 su bardağı (420 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Ayçiçek Yağı', 'kızartma için (2 su bardağı)'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Mayayı ve şekeri 1,5 su bardağı ILIK suda eritip 5 dakika, köpürene kadar bekletin.',
      'Un ve tuzu ekleyip yumuşak, hafif ele yapışan bir hamur yoğurun. Pişi hamuru poğaçadan biraz daha yumuşak, neredeyse akışkana yakın olmalı — kızarınca içi pofuduk olsun.',
      'Üzerini örtüp sıcak yerde 30-40 dakika, hamur iki katına çıkıp köpük köpük olana kadar mayalandırın.',
      'Elinizi ve tezgâhı yağlayıp (unlamayın, un yağı yakar) hamurdan yumurta büyüklüğünde parçalar koparın; her birini elinizle bastırarak yassı yuvarlaklar yapın. Ortasına parmakla bir delik açarsanız yağda daha güzel kabarır ve eşit pişer.',
      'Geniş bir tencerede bol yağı orta-yüksek ateşte kızdırın; küçük bir hamur parçası attığınızda hemen kabarcıklarla yüzeye çıkıyorsa yağ hazırdır. Yağ az kızgınsa pişiler yağ emer, ağırlaşır.',
      'Pişileri azar azar (yağı soğutmamak için kalabalık etmeden) atın; her yüzünü 1-2 dakika, altın rengi alıp balon gibi kabarana kadar kızartın.',
      'Kâğıt havluya alıp fazla yağını süzdürün. Yanına beyaz peynir koyup tuzlu, ya da üstüne pudra şekeri/reçel sürüp tatlı yiyin — köy kahvaltısının en keyifli hamur işi, iki türlü de bir başka!',
    ],
  },
  {
    isim: 'Su Böreği', mutfak: M, kategori: 'Hamur İşi', sure: 100, tur: 'yemek',
    malzemeler: [
      ['Un', '4 su bardağı (480 g)'],
      ['Yumurta', '4 adet'],
      ['Beyaz Peynir', '300 g'],
      ['Maydanoz', 'yarım demet'],
      ['Tereyağı', '125 g'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Un, yumurta, tuz ve gerekirse çok az suyla, kulak memesinden biraz daha sert bir hamur yoğurun (sert hamur incecik açılır, haşlanınca dağılmaz). Üzerini örtüp en az 30 dakika dinlendirin, sonra 6 eşit bezeye ayırın. Ev yapımı su böreğinin sırrı bu el açması yufkalardadır.',
      'Her bezeyi bolca nişasta veya un serperek, tepsinizden biraz büyük ve gazete gibi ince, arkası görünecek kadar açın. Açtıkça araya nişasta serpip katlarsanız yapışmaz.',
      'Geniş bir tencerede tuzlu su kaynatın; yanına içinde buzlu su olan büyük bir kap ve temiz kuru bezler hazırlayın. Bu üçlü kurulum haşlama adımını hızlandırır.',
      'Yufkaları tek tek kaynar suya atıp 30-40 saniye haşlayın (üstteki 2 yaprak ve en alttaki yaprak haşlanmaz, kuru serilir — böylece börek dağılmaz). Delikli kepçeyle alıp hemen buzlu suya batırın, sonra bezin üzerine serip fazla suyunu nazikçe alın. Bu "su verme" işlemi böreğe adını ve o eşsiz yumuşacık dokusunu kazandırır.',
      'Tereyağını (dilerseniz biraz sıvı yağla) eritin. Yağlanmış tepsiye önce kuru bir yaprak serin, üzerine bolca eritilmiş yağ gezdirin. Haşlanmış yaprakları sırayla dizip her katın arasına mutlaka yağ sürün — cimrilik yapmayın, yağ katları birbirinden ayırıp böreği kat kat yapar.',
      'Ortaya geldiğinizde (yaklaşık 3. kattan sonra) ezilmiş peynir ve kıyılmış maydanoz harcını eşitçe yayın; kalan haşlı yapraklarla devam edip en üste kuru yaprağı kapatın.',
      'En üst kata bolca tereyağı sürün ve keskin bıçakla dilimleri önceden çizin. Önceden ısıtılmış 190 derece fırında üzeri altın sarısı, kenarları çıtır olana kadar 30-35 dakika pişirin. Mümkünse ilk 15-20 dakikadan sonra böreği ters çevirip tepsiye geri alın; böylece alt yüzü de kızarır.',
      'Fırından çıkınca 10 dakika dinlendirip dilimleyin. Bol demli çayla servis edin — emek ve sabır ister ama gerçek su böreğinin yerini hiçbir şey tutmaz.',
    ],
  },
  {
    isim: 'Açma', mutfak: M, kategori: 'Hamur İşi', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Un', '4,5 su bardağı (540 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Süt', '1 su bardağı ılık (200 ml)'],
      ['Ayçiçek Yağı', 'yarım su bardağı (100 ml)'],
      ['Yumurta', '2 adet (1 tanesi üzeri için)'],
      ['Şeker', '2 yemek kaşığı'],
      ['Tereyağı', '2 yemek kaşığı yumuşak (40 g)'],
      ['Susam', '1 yemek kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Ilık sütte maya ve şekeri eritip 5 dakika bekletin.',
      'Yağ, 1 yumurta akı ve tuzu ekleyin; unu azar azar katarak çok yumuşak, hafif yapışkan bir hamur yoğurun. Açmanın pofuduğu bu yumuşak hamurdan gelir.',
      'Üzerini örtüp 45 dakika, iki katına çıkana kadar mayalandırın.',
      'Hamurdan iri bezeler koparıp her birini elinizle uzun şerit haline getirin; şeride yumuşak tereyağı sürün.',
      'Şeridi kendi etrafında burun, sonra iki ucunu birleştirip simit gibi halka yapın.',
      'Açmaları tepsiye dizip 15 dakika daha dinlendirin; üzerlerine yumurta sarısı sürüp susam serpin.',
      '180 derece fırında 20-22 dakika, üzerleri parlak kahverengi olana kadar pişirin.',
    ],
  },
  {
    isim: 'Bazlama', mutfak: M, kategori: 'Hamur İşi', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Un', '4 su bardağı (480 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Yoğurt', '2 yemek kaşığı'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Tereyağı', 'üzerine sürmek için'],
      ['Tuz', '1,5 tatlı kaşığı'],
    ],
    adimlar: [
      'Mayayı ve şekeri 1,5 su bardağı ILIK suda eritin; 5 dakika, köpürene kadar bekletin.',
      'Yoğurt, tuz ve unu ekleyip yumuşak, ele hafif yapışan bir hamur yoğurun. Yoğurt, bazlamaya yumuşaklık ve hafif ekşimsi bir tat katar.',
      'Üzerini nemli bezle örtüp sıcak yerde 45 dakika, iki katına çıkana kadar mayalandırın.',
      'Hamuru 6 bezeye ayırıp yuvarlayın; her bezeyi unlanmış tezgâhta elinizle veya oklavayla 1 cm kalınlığında yuvarlaklar halinde açın. Üzerlerini örtüp 10-15 dakika daha dinlendirin (bu ikinci dinlenme kabarmayı artırır).',
      'Teflon tavayı veya sacı orta ateşte, YAĞSIZ olarak ısıtın. Bazlama kuru tavada, ekmek gibi pişer.',
      'Bazlamaları tek tek tavaya koyun; alt yüzü benek benek kızarıp üstü kabarcıklanmaya başlayınca çevirin. Doğru mayalanıp doğru ısıda pişiyorsa balon gibi şişip kabaracak — bu, içinin kat kat ve yumuşak olduğunun işaretidir. Her yüzünü 2-3 dakika pişirin.',
      'Tavadan aldığınız gibi sıcakken üzerine tereyağı sürün; eriyen tereyağı bazlamaya işlesin. Köy kahvaltısının yıldızı; peynir, bal, kaymakla harika gider.',
    ],
  },

  // ─── TATLILAR ───
  {
    isim: 'Fırın Sütlaç', mutfak: M, kategori: 'Tatlılar', sure: 70, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Pirinç', 'yarım su bardağı (90 g)'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '2 yemek kaşığı'],
      ['Vanilya', '1 paket'],
    ],
    adimlar: [
      'Pirinci yıkayıp küçük bir tencerede 1,5 su bardağı suyla, suyunu tamamen çekene kadar 15 dakika haşlayın. Pirincin iyice yumuşaması önemli — yarı çiğ pirinç sütlaçta dişe gelir. Baldo veya osmancık gibi nişastası bol pirinç daha kıvamlı sütlaç verir.',
      'Haşlanan pirincin üzerine sütü ekleyip orta ateşe alın. Dibi kolayca tuttuğu için tahta kaşıkla ara ara dibini sıyırarak kaynatın.',
      'Şekeri ekleyin. Nişastayı yarım çay bardağı SOĞUK sütte (veya suda) topak kalmayana kadar ezin, sonra kaynayan sütlaca azar azar, sürekli karıştırarak ekleyin. Soğukta ezmek ve azar azar eklemek, nişastanın topaklanmasını önler.',
      'Kısık ateşte 8-10 dakika, sütlaç kaşığın arkasını hafifçe kaplayacak kıvama gelene kadar karıştırarak pişirin. Fazla koyulaştırmayın; fırında ve soğurken biraz daha koyulaşacak. Vanilyayı ekleyip ocağı kapatın.',
      'Fırına dayanıklı kâselere paylaştırın. Kâseleri derin bir fırın tepsisine dizip tepsiye, kâselerin yarısına gelecek kadar sıcak su doldurun. Bu benmari (su banyosu) yöntemi, sütlacın altını yakmadan sadece üstünün kızarmasını sağlar.',
      'Fırının üst ızgarasını (gril) açıp 220-250 derecede, sütlaçların üzeri yer yer kahverengi lekeler alana kadar 10-15 dakika pişirin. Gözünüzü ayırmayın, gril çok hızlı yakar; alacalı kızarmış yüzey fırın sütlacının imzasıdır.',
      'Oda sıcaklığına gelince buzdolabında en az 2-3 saat soğutun. Fırın sütlaç mutlaka buz gibi yenir — soğuk hali sıcağından bambaşkadır.',
    ],
  },
  {
    isim: 'Kazandibi', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '4 yemek kaşığı'],
      ['Un', '2 yemek kaşığı'],
      ['Tereyağı', '1 yemek kaşığı (tepsi için)'],
      ['Pudra Şekeri', '3 yemek kaşığı (taban için)'],
      ['Vanilya', '1 paket'],
      ['Tarçın', 'servis için'],
    ],
    adimlar: [
      'Süt, şeker, nişasta ve unu tencerede soğukken çırpın — soğukken karıştırmak topaklanmayı önler.',
      'Orta ateşte, sürekli karıştırarak muhallebi koyulaşana kadar 10-12 dakika pişirin; vanilyayı ekleyin.',
      'Dikdörtgen bir tepsinin tabanını tereyağıyla yağlayıp pudra şekerini eşit şekilde serpin.',
      'Muhallebiyi tepsiye dökün ve düzleyin.',
      'Şimdi kritik kısım: tepsiyi doğrudan ocağın üzerine koyun (orta ateş) ve tepsiyi döndüre döndüre tabanını yakın. Şeker karamelleşirken çıtırtı duyacaksınız; hafif yanık koku normal, istediğimiz tam da bu. 6-8 dakika sürer.',
      'Soğuduktan sonra buzdolabında 3 saat dinlendirin.',
      'Dikdörtgen dilimler kesin; spatulayla alıp yanık tarafı üste gelecek şekilde ters çevirerek tabağa koyun. Tarçın serpin ve rulo yapmadan ya da yaparak — keyfinize kalmış — servis edin.',
    ],
  },
  {
    isim: 'Muhallebi', mutfak: M, kategori: 'Tatlılar', sure: 25, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '4 yemek kaşığı'],
      ['Vanilya', '1 paket'],
      ['Fındık', '2 yemek kaşığı çekilmiş (üzeri için)'],
      ['Tarçın', 'üzeri için'],
    ],
    adimlar: [
      'Muhallebide topaksız bir sonuç için kritik kural: süt, şeker ve nişastayı tencereye SOĞUKKEN koyup çırpma teliyle iyice karıştırın. Nişastayı sıcak süte eklerseniz anında pıhtılaşıp topak yapar; soğukta çözünüp eşit dağılır.',
      'Tencereyi orta ateşe alın ve çırpma teliyle, tencerenin dibini ve kenarlarını tarayarak karıştırmayı HİÇ bırakmadan pişirin. Bir an durursanız dibi tutar ve topaklanır — kolunuz yorulacak ama pürüzsüz muhallebi buna değer.',
      'Karışım kaynayıp koyulaşınca ve kaşığın arkasını kaplayan bir kıvam alınca 2 dakika daha, nişastanın ham tadı tamamen gidene kadar pişirin.',
      'Vanilyayı ekleyip son bir kez karıştırın ve ocağı kapatın. Dilerseniz 1 kaşık tereyağı ekleyip çırparsanız daha ipeksi olur.',
      'Kâselere paylaştırın. Üzerinde kaymak tabakası oluşmasını istemiyorsanız streç filmi doğrudan muhallebinin yüzeyine değecek şekilde örtün. Oda sıcaklığına gelince buzdolabında en az 2 saat soğutun.',
      'Üzerine çekilmiş fındık, ceviz veya tarçın serperek soğuk servis edin. Meyve sosu veya çikolatayla da güzel gider.',
    ],
  },
  {
    isim: 'İrmik Helvası', mutfak: M, kategori: 'Tatlılar', sure: 40, tur: 'yemek',
    malzemeler: [
      ['İrmik', '2 su bardağı (340 g)'],
      ['Tereyağı', '125 g'],
      ['Çam Fıstığı', '2 yemek kaşığı'],
      ['Süt', '2 su bardağı (400 ml)'],
      ['Su', '1 su bardağı'],
      ['Şeker', '2 su bardağı (400 g)'],
      ['Tarçın', 'servis için'],
    ],
    adimlar: [
      'Önce şerbeti hazırlayın: süt, su ve şekeri kaynatıp şeker eriyince ocağı kapatın; sıcak bekletin.',
      'Geniş tencerede tereyağını eritin; irmiği ve çam fıstıklarını ekleyin.',
      'Kısık ateşte, tahta kaşıkla sürekli karıştırarak kavurun. Bu iş sabır ister: 20-25 dakika boyunca karıştırın. İrmik koyu altın rengine dönüp fıstıklar pembeleşince ve mis gibi koku mutfağı sarınca hazırdır.',
      'Ocağı en kısığa alın ve sıcak şerbeti dikkatlice, azar azar dökün — fokurdayıp sıçrayabilir, elinizi uzak tutun.',
      'Karıştırıp kapağı kapatın; 10 dakika, suyunu tamamen çekene kadar kısık ateşte pişirin.',
      'Ocağı kapatıp 10 dakika demlendirin. Kaşıkla havalandırıp servis tabağına alın; tarçın serpin. Kavrulmuş irmiğin kokusu evi bayram yerine çevirir!',
    ],
  },
  {
    isim: 'Revani', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['İrmik', '1 su bardağı (170 g)'],
      ['Un', '1 su bardağı (120 g)'],
      ['Yumurta', '3 adet'],
      ['Yoğurt', '1 su bardağı (200 g)'],
      ['Şeker', 'kek için yarım, şerbet için 2,5 su bardağı'],
      ['Ayçiçek Yağı', 'yarım su bardağı (100 ml)'],
      ['Kabartma Tozu', '1 paket'],
      ['Vanilya', '1 paket'],
      ['Limon', 'çeyrek adet (şerbet için)'],
      ['Hindistan Cevizi Rendesi', 'üzeri için'],
    ],
    adimlar: [
      'Önce şerbeti hazırlayın çünkü soğuması gerekir. Şerbetli tatlının altın kuralı: sıcakla soğuk buluşmalı — ya şerbet soğuk tatlı sıcak, ya tersi olmalı; ikisi de sıcak/ikisi de soğuk olursa tatlı şerbeti çekmez, ıslak kalır. 2,5 su bardağı şeker + 3 su bardağı suyu 10 dakika kaynatın, birkaç damla limon sıkın (limon şerbetin şekerlenip kristalleşmesini önler) ve tamamen soğumaya bırakın.',
      'Kek harcı: yumurta ve yarım bardak şekeri, hacmi artıp rengi açılana kadar 3-4 dakika çırpın. İyi çırpılan yumurta revaniyi kabartır.',
      'Yoğurt ve sıvı yağı ekleyip çırpın; irmik, un, kabartma tozu ve vanilyayı eleyerek ekleyin ve spatulayla, köpüğü söndürmeden alttan üste karıştırın. İrmiği kullanmadan 10 dakika beklerseniz şişip daha güzel doku verir.',
      'Hamuru yağlanmış fırın kabına dökün; önceden ısıtılmış 170 derece fırında 30-35 dakika, üzeri altın rengi olana kadar pişirin. Ortasına kürdan batırıp temiz çıkıyorsa hazırdır.',
      'Fırından çıkan SICAK kekin üzerine bıçakla baklava dilimleri çizin, sonra SOĞUK şerbeti kepçe kepçe, her köşesine gezdirerek dökün. Sıcak kek soğuk şerbeti "cız" diye emer.',
      'Üzerini örtüp en az 1 saat bekleyin; kek şerbeti tamamen içine çeksin. Hindistan cevizi serpip dilimleyerek servis edin. Üzerine bir top dondurma kaçamağın dozunu artırır!',
    ],
  },
  {
    isim: 'Şekerpare', mutfak: M, kategori: 'Tatlılar', sure: 55, tur: 'yemek',
    malzemeler: [
      ['Un', '2,5 su bardağı (300 g)'],
      ['İrmik', 'yarım su bardağı (85 g)'],
      ['Tereyağı', '125 g (oda sıcaklığında)'],
      ['Pudra Şekeri', '1 su bardağı (120 g)'],
      ['Yumurta', '1 adet'],
      ['Kabartma Tozu', '1 paket'],
      ['Badem', '20 adet (üzeri için)'],
      ['Şeker', '2,5 su bardağı (şerbet için)'],
      ['Limon', 'çeyrek adet'],
    ],
    adimlar: [
      'Şerbeti önce yapın çünkü soğuması şart (kural: sıcak tatlıya soğuk şerbet). 2,5 su bardağı şeker ve 3 su bardağı suyu 10 dakika kaynatın, birkaç damla limon sıkıp (şekerlenmeyi önler) tamamen soğumaya bırakın.',
      'Hamur: oda sıcaklığında yumuşamış tereyağı, pudra şekeri ve yumurtayı bir kâsede karıştırın. İrmik, kabartma tozu ve unu azar azar ekleyip toparlanana kadar HAFİFÇE yoğurun. Şekerparenin sırrı burada: az yoğurun — fazla yoğrulan hamur glüten geliştirir, tatlı yumuşak değil sert ve kuru olur.',
      'Ceviz büyüklüğünde parçalar koparıp avuç içinde pürüzsüz toplar yapın (çatlaksız olması için nazikçe yuvarlayın). Pişerken yayılıp büyüyecekleri için tepsiye aralıklı dizin.',
      'Her topun ortasına başparmağınızla hafifçe bastırıp birer badem (veya fındık) yerleştirin.',
      'Önceden ısıtılmış 170 derece fırında 20-25 dakika pişirin. Rengi açık altın sarısı olmalı — fazla kızartmayın; koyu renk alan sert kabuk şerbeti içeri geçirmez ve şekerpare içi kuru kalır.',
      'Fırından çıkan SICAK şekerparelerin üzerine SOĞUK şerbeti kaşıkla, her birine gelecek şekilde dökün.',
      'En az 2 saat, mümkünse birkaç saat bekleyin. Şekerpareler şerbeti yavaş yavaş emerek şişer ve içi ıslak, dışı yumuşacık olur. Aceleyle kesip yemeyin, sabır lezzeti tamamlar.',
    ],
  },
  {
    isim: 'Ev Baklavası', mutfak: M, kategori: 'Tatlılar', sure: 90, tur: 'yemek',
    malzemeler: [
      ['Baklavalık Yufka', '1 paket (40 yaprak)'],
      ['Ceviz', '2,5 su bardağı çekilmiş (250 g)'],
      ['Tereyağı', '250 g'],
      ['Şeker', '3 su bardağı (şerbet için)'],
      ['Limon', 'çeyrek adet'],
    ],
    adimlar: [
      'Şerbet: 3 bardak şeker + 3,5 bardak suyu kaynatın; 15 dakika kaynayıp hafif koyulaşınca limon sıkın ve soğumaya bırakın.',
      'Tereyağını eritin; üstteki köpüğü kaşıkla alın (köpüksüz yağ baklavayı daha parlak yapar).',
      'Tepsiyi yağlayın. Yufkaları teker teker serin: her 2 yaprakta bir, fırçayla eritilmiş tereyağı gezdirin. İlk 20 yaprağı bu şekilde dizin.',
      'Çekilmiş cevizi eşit şekilde yayın.',
      'Kalan 20 yaprağı da aynı şekilde, 2 yaprakta bir yağlayarak dizin. En üste bolca yağ sürün.',
      'Keskin bıçakla önce boyuna şeritler, sonra çapraz keserek baklava dilimleri oluşturun. Pişmeden kesmek şart — piştikten sonra kesilmez, dağılır.',
      'Önceden ısıtılmış 170 derece fırında 35-40 dakika, üzeri altın rengi olana kadar pişirin.',
      'Fırından çıkan sıcak baklavaya soğuk şerbeti yavaşça, her yerine gezdirerek dökün. Cızırtı sesi şerbetin doğru sıcaklıkta olduğunun kanıtı! En az 2 saat dinlendirin.',
    ],
  },
  {
    isim: 'Künefe', mutfak: M, kategori: 'Tatlılar', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Kadayıf', '500 g'],
      ['Lor Peyniri', '300 g (tuzsuz; künefelik peynir idealdir)'],
      ['Tereyağı', '150 g'],
      ['Şeker', '2 su bardağı (şerbet için)'],
      ['Antep Fıstığı', '2 yemek kaşığı çekilmiş'],
      ['Limon', 'çeyrek adet'],
    ],
    adimlar: [
      'Şerbet: 2 bardak şeker + 2 bardak suyu 10 dakika kaynatıp limon sıkın; ılık bekletin (künefede şerbet ılık dökülür).',
      'Kadayıfı bıçakla ince ince kıyın — uzun teller sarma yapar, kısa teller daha iyi.',
      'Tereyağını eritip kadayıfın üzerine dökün; elinizle iyice, her tel yağlanana kadar harmanlayın.',
      'Yağlanmış geniş tavaya (veya künefe tepsisine) kadayıfın yarısını koyup elinizle iyice bastırın.',
      'Peyniri eşit şekilde yayın; kenarlara 1 cm boşluk bırakın (peynir taşmasın).',
      'Kalan kadayıfı üzerine kapatıp yine iyice bastırın.',
      'Orta-kısık ateşte, tavayı döndüre döndüre alt tarafı altın kahve olana kadar 7-8 dakika pişirin. Sonra büyük bir tabak yardımıyla ters çevirip diğer tarafı da aynı şekilde pişirin.',
      'Sıcak künefenin üzerine ılık şerbeti dökün — cızz! Fıstık serpip hemen, peyniri uzaya uzaya yenecek sıcaklıkta servis edin.',
    ],
  },
  {
    isim: 'Aşure', mutfak: M, kategori: 'Tatlılar', sure: 120, tur: 'yemek',
    malzemeler: [
      ['Bulgur', '1 su bardağı (aşurelik buğday idealdir)'],
      ['Nohut', 'yarım su bardağı haşlanmış'],
      ['Kuru Fasulye', 'yarım su bardağı haşlanmış'],
      ['Kuru Kayısı', '8 adet'],
      ['Kuru Üzüm', 'yarım su bardağı'],
      ['Şeker', '2 su bardağı (400 g)'],
      ['Ceviz', 'yarım su bardağı'],
      ['Fındık', 'üzeri için'],
      ['Tarçın', 'üzeri için'],
    ],
    adimlar: [
      'Buğdayı (bulguru) bir gece önceden ıslatın. Nohut ve fasulyeyi de ayrı kaplarda ıslatıp ertesi gün yumuşayana kadar haşlayın.',
      'Buğdayı bol suyla (8 su bardağı) tencereye alın; taneler iyice yumuşayıp su hafif çorbamsı olana kadar 1 saat pişirin.',
      'Haşlanmış nohut ve fasulyeyi ekleyin.',
      'Kayısıları küçük doğrayıp üzümlerle birlikte ekleyin; 15 dakika birlikte kaynatın.',
      'Şekeri ekleyin ve karıştırarak 15 dakika daha pişirin. Kıvamı bal gibi, akışkan ama koyu olmalı; gerekirse sıcak su ekleyin.',
      'İri çekilmiş cevizi karıştırıp ocağı kapatın.',
      'Kaselere paylaştırın; soğuyunca üzerlerini fındık, ceviz ve tarçınla süsleyin. Komşulara dağıtmak serbest — aşurenin geleneği budur!',
    ],
  },
  {
    isim: 'Muzlu Magnolia', mutfak: M, kategori: 'Tatlılar', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '4 yemek kaşığı'],
      ['Vanilya', '1 paket'],
      ['Labne', '200 g'],
      ['Muz', '3 adet'],
      ['Bisküvi', '1 paket (150 g)'],
    ],
    adimlar: [
      'Süt, şeker ve nişastayı soğukken çırpıp orta ateşte, sürekli karıştırarak muhallebi kıvamına getirin; vanilyayı ekleyip ocaktan alın.',
      'Muhallebi ılıyınca labneyi ekleyip çırpın — labne, magnoliaya o ipeksi dokusunu verir.',
      '2 muzu çatalla ezip kremaya karıştırın.',
      'Bisküvileri poşete koyup oklavayla kırıntı haline getirin (robotta da çekebilirsiniz).',
      'Kaselere önce bir kat bisküvi kırıntısı, sonra muzlu krema koyun; katları tekrarlayın.',
      'En üstü bisküvi kırıntısı ve muz dilimleriyle süsleyin.',
      'Buzdolabında en az 2 saat soğutun. Kaşığı daldırınca katmanların görünmesi ayrı keyif!',
    ],
  },
  {
    isim: 'Kabak Tatlısı', mutfak: M, kategori: 'Tatlılar', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Bal Kabağı', '1 kg (temizlenmiş)'],
      ['Şeker', '1,5 su bardağı (300 g)'],
      ['Ceviz', '1 su bardağı iri çekilmiş'],
      ['Tahin', 'servis için (isteğe bağlı)'],
    ],
    adimlar: [
      'Kabağı kabuklarından ve çekirdeklerinden temizleyip iri dilimler halinde kesin.',
      'Dilimleri tencereye dizin ve şekeri üzerlerine eşit şekilde serpin.',
      'Kapağı kapatıp bir gece (en az 4 saat) bekletin. Sabah bakınca şaşırmayın: şeker, kabağın suyunu çekip şerbete dönüşmüş olacak. Su eklemeye gerek yok!',
      'Tencereyi kısık ateşe alın; kendi şerbetiyle, kapağı kapalı 35-40 dakika, kabaklar şeffaflaşıp yumuşayana kadar pişirin.',
      'Kapağı açıp 5 dakika daha kaynatın; şerbet koyulaşsın.',
      'Soğuduktan sonra servis tabağına alın; şerbetini üzerine gezdirin. Bol ceviz ve dilerseniz tahinle servis edin — Antep usulü tahinli kabak tatlısı başka bir alemdir.',
    ],
  },
  {
    isim: 'Ayva Tatlısı', mutfak: M, kategori: 'Tatlılar', sure: 70, tur: 'yemek',
    malzemeler: [
      ['Ayva', '3 adet büyük'],
      ['Şeker', '1,5 su bardağı (300 g)'],
      ['Limon', 'yarım adet'],
      ['Kaymak', 'servis için'],
      ['Antep Fıstığı', '2 yemek kaşığı çekilmiş'],
    ],
    adimlar: [
      'Ayvaları soyun, ikiye bölün ve çekirdek yuvalarını kaşıkla oyun. Kararmamaları için limonlu suda bekletin. Çekirdekleri atmayın!',
      'Ayvaları oyuk kısımları yukarı bakacak şekilde geniş tencereye dizin.',
      'Her yarımın üzerine ve oyuklarına şekeri paylaştırın. Çekirdekleri aralara atın — çekirdekler hem güzel kızıl rengi verir hem şerbeti pelte yapar.',
      '1 su bardağı su ekleyip kapağı kapatın; kısık ateşte 50-60 dakika, ayvalar yumuşayıp kızıl bir renk alana kadar pişirin. Renk için sabır gerekir, aceleyle olmaz.',
      'Kapağı açıp şerbet koyulaşana kadar 10 dakika daha pişirin.',
      'Soğuduktan sonra her yarımın oyuğuna bir top kaymak yerleştirip fıstık serpin. Bayram sofralarının klasiği hazır!',
    ],
  },
  {
    isim: 'Keşkül', mutfak: M, kategori: 'Tatlılar', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Badem', '1 su bardağı çekilmiş (100 g)'],
      ['Nişasta', '3 yemek kaşığı'],
      ['Yumurta', '2 adet (sadece sarısı)'],
      ['Vanilya', '1 paket'],
      ['Hindistan Cevizi Rendesi', 'üzeri için'],
    ],
    adimlar: [
      'Bademleri robotta un gibi olana kadar çekin — keşkülün kimliği bademdir.',
      'Tencerede süt, şeker, nişasta ve yumurta sarılarını soğukken çırpın.',
      'Çekilmiş bademleri ekleyip orta ateşe alın.',
      'Sürekli karıştırarak, koyulaşana kadar 12-15 dakika pişirin.',
      'Vanilyayı ekleyip ocağı kapatın; 2 dakika daha karıştırın.',
      'Kaselere paylaştırıp soğutun; buzdolabında 2 saat dinlendirin.',
      'Üzerine hindistan cevizi ve dilerseniz çekilmiş badem serperek servis edin.',
    ],
  },
  {
    isim: 'Güllaç', mutfak: M, kategori: 'Tatlılar', sure: 40, tur: 'yemek',
    malzemeler: [
      ['Güllaç Yaprağı', '1 paket (10 yaprak)'],
      ['Süt', '1,5 litre'],
      ['Şeker', '2 su bardağı (400 g)'],
      ['Ceviz', '1,5 su bardağı çekilmiş'],
      ['Antep Fıstığı', 'üzeri için'],
      ['Vanilya', '1 paket (veya 1 kaşık gül suyu)'],
    ],
    adimlar: [
      'Sütü şekerle birlikte, şeker eriyene kadar ısıtın — kaynatmayın, ılık-sıcak arası olsun. Vanilyayı (ya da gül suyunu) ekleyin.',
      'Geniş bir tepsiye 1 güllaç yaprağını mat yüzü üste gelecek şekilde yerleştirin.',
      'Üzerine sıcak sütlü karışımdan kepçeyle gezdirin; yaprak yumuşayıp şeffaflaşacak.',
      'Her katta aynısını tekrarlayarak 5 yaprak dizin. Beşinci yaprağın üzerine çekilmiş cevizi yayın.',
      'Kalan 5 yaprağı da aynı şekilde, her katı sütleyerek dizin.',
      'Kalan sütü en üstten yavaşça dökün; yapraklar tamamen süte doysun.',
      'Buzdolabında 2 saat dinlendirin. Kare dilimler kesip üzerini bol antep fıstığıyla süsleyin. Ramazan sofralarının en zarif tatlısı!',
    ],
  },
  {
    isim: 'Tulumba Tatlısı', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Un', '1,5 su bardağı (180 g)'],
      ['Yumurta', '3 adet'],
      ['Tereyağı', '2 yemek kaşığı (40 g)'],
      ['Nişasta', '1 yemek kaşığı'],
      ['İrmik', '1 yemek kaşığı'],
      ['Şeker', '3 su bardağı (şerbet için)'],
      ['Limon', 'çeyrek adet'],
      ['Ayçiçek Yağı', 'kızartma için (3 su bardağı)'],
    ],
    adimlar: [
      'Şerbet: 3 bardak şeker + 3 bardak suyu 15 dakika kaynatıp limon sıkın; tamamen soğumaya bırakın. Tulumbada şerbet buz gibi olmalı.',
      'Hamur: 1,5 su bardağı suyu tereyağıyla kaynatın. Unu bir kerede ekleyip tahta kaşıkla, top haline gelene kadar karıştırın; 2 dakika pişirip ocaktan alın.',
      'Hamur ılıyınca yumurtaları TEK TEK ekleyin; her yumurtadan sonra iyice yoğurun. İrmik ve nişastayı da ekleyin. Parlak, yumuşak ama akmayan bir hamur olmalı.',
      'Hamuru yıldız uçlu krema sıkma torbasına doldurun.',
      'ÖNEMLİ PÜF NOKTASI: yağı ısıtmadan, oda sıcaklığında tencereye koyun. Hamuru 3-4 cm parçalar halinde soğuk yağın içine sıkıp makasla kesin. Sonra tencereyi orta ateşe alın.',
      'Yağ yavaş yavaş ısınırken tulumbalar önce dibe çöker, sonra şişerek yüzeye çıkar. Karıştırarak her tarafı altın rengi kızarana kadar pişirin.',
      'Kızaran tulumbaları delikli kepçeyle alıp doğrudan soğuk şerbete atın; 4-5 dakika şerbette bekletip süzgeçli kepçeyle çıkarın. Dışı çıtır, içi şerbet dolu!',
    ],
  },
  {
    isim: 'Lokma', mutfak: M, kategori: 'Tatlılar', sure: 75, tur: 'yemek',
    malzemeler: [
      ['Un', '3 su bardağı (360 g)'],
      ['Maya', '1 paket kuru maya (10 g)'],
      ['Şeker', '1 tatlı kaşığı (hamur için) + 3 su bardağı (şerbet için)'],
      ['Nişasta', '1 yemek kaşığı'],
      ['Limon', 'çeyrek adet'],
      ['Ayçiçek Yağı', 'kızartma için'],
      ['Tarçın', 'üzeri için'],
      ['Tuz', 'yarım çay kaşığı'],
    ],
    adimlar: [
      'Şerbet: 3 bardak şeker + 3 bardak su, 15 dakika kaynasın; limon sıkıp soğutun.',
      'Hamur: mayayı 1 tatlı kaşığı şekerle 2 su bardağı ılık suda eritin. Un, nişasta ve tuzu ekleyip çırpma teliyle çırpın — bu hamur yoğrulmaz, cıvık bir hamurdur, boza kıvamında olmalı.',
      'Üzerini örtüp 1 saat mayalandırın; hamur köpük köpük kabaracak.',
      'Yağı kızdırın (orta-yüksek ateş). Bir elinizle avucunuza hamur alın, yumruğunuzu sıkın — baş parmakla işaret parmağınızın arasından çıkan hamuru yağlı bir kaşıkla kesip yağa bırakın. (Zor gelirse iki kaşıkla da şekil verebilirsiniz.)',
      'Lokmaları, altın rengi alana kadar çevire çevire kızartın.',
      'Kızaranları delikli kepçeyle alıp soğuk şerbetin içine atın; 2-3 dakika bekletip çıkarın.',
      'Üzerine tarçın serperek servis edin. Sıcak sıcak, yanında çayla!',
    ],
  },
  {
    isim: 'Trileçe', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Yumurta', '4 adet'],
      ['Şeker', '1 su bardağı (kek için) + yarım su bardağı (karamel için)'],
      ['Un', '1,5 su bardağı (180 g)'],
      ['Kabartma Tozu', '1 paket'],
      ['Vanilya', '1 paket'],
      ['Süt', '4 su bardağı (sosu için: 3 + karamel için: 1)'],
      ['Krema', '1 paket (200 ml)'],
    ],
    adimlar: [
      'Kek: yumurta ve 1 bardak şekeri, hacmi 3 katına çıkana kadar 5 dakika çırpın — kabarıklık bu çırpmadan gelir.',
      'Un, kabartma tozu ve vanilyayı eleyerek ekleyin; spatulayla, söndürmeden alttan üste karıştırın.',
      'Yağlı kağıt serili dikdörtgen kaba döküp 170 derece fırında 25 dakika pişirin. Soğumaya bırakın.',
      'Islatma sosu: 3 su bardağı süt ve kremayı karıştırın.',
      'Soğuyan kekin her yerini çatalla delik deşik edin — sosun içine işlemesi için ne kadar delik, o kadar iyi.',
      'Sütlü sosu kekin üzerine kepçe kepçe dökün. İlk başta "çok geldi" diye düşüneceksiniz ama kek hepsini emecek. Buzdolabında 2 saat dinlendirin.',
      'Karamel: yarım bardak şekeri tencerede, karıştırmadan eritin; kehribar rengini alınca 1 bardak sıcak sütü dikkatlice ekleyip pürüzsüzleşene kadar karıştırın. Soğutun.',
      'Karameli kekin üzerine ince bir tabaka halinde yayın. Dilimleyip soğuk servis edin — çatalı batırınca süt salıveren o meşhur doku!',
    ],
  },
  {
    isim: 'Supangle', mutfak: M, kategori: 'Tatlılar', sure: 35, tur: 'yemek',
    malzemeler: [
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '3 yemek kaşığı'],
      ['Un', '2 yemek kaşığı'],
      ['Kakao', '3 yemek kaşığı'],
      ['Bitter Çikolata', '80 g'],
      ['Tereyağı', '1 yemek kaşığı (20 g)'],
      ['Kedi Dili Bisküvi', '8-10 adet (tabanı için)'],
      ['Fındık', 'üzeri için'],
    ],
    adimlar: [
      'Kase tabanlarına kedi dili bisküvileri (veya normal bisküvi) yerleştirin.',
      'Tencerede süt, şeker, nişasta, un ve kakaoyu soğukken çırpın; kakao topaklanmasın diye önce kuru malzemeleri kendi aralarında karıştırabilirsiniz.',
      'Orta ateşte, sürekli karıştırarak koyulaşana kadar 10-12 dakika pişirin.',
      'Ocağı kapatıp parçalanmış bitter çikolatayı ve tereyağını ekleyin; çikolata eriyene kadar karıştırın. İşte o parlak, ipeksi supangle dokusu!',
      'Sıcak kremayı bisküvili kaselere paylaştırın.',
      'Oda sıcaklığına gelince buzdolabında 3 saat soğutun.',
      'Üzerini çekilmiş fındıkla süsleyip servis edin.',
    ],
  },
  {
    isim: 'Tavuk Göğsü Tatlısı', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Tavuk Göğsü', '1 küçük parça (100 g)'],
      ['Süt', '1 litre'],
      ['Şeker', '1 su bardağı (200 g)'],
      ['Nişasta', '4 yemek kaşığı'],
      ['Un', '2 yemek kaşığı'],
      ['Tereyağı', '1 yemek kaşığı'],
      ['Tarçın', 'üzeri için'],
    ],
    adimlar: [
      'Evet, içinde gerçekten tavuk var — ama korkmayın, tadı hiç belli olmaz; sadece o meşhur lifli dokuyu verir!',
      'Tavuk göğsünü haşlayın (20 dakika). Soğuyunca liflerine ayırın; lifleri soğuk suda 3-4 kez yıkayıp süzün — bu yıkama tavuk tadını tamamen alır.',
      'Lifleri mümkün olduğunca ince didikleyin, hatta bezin içinde ovarak iyice inceltin.',
      'Tencerede süt, şeker, nişasta ve unu soğukken çırpın; orta ateşte sürekli karıştırarak koyulaşana kadar pişirin.',
      'Tavuk liflerini ekleyin ve çırpma teliyle güçlüce çırparak 10 dakika daha pişirin; lifler kremanın içinde kaybolacak.',
      'Ocaktan alıp tereyağını karıştırın. Islak kaselere ya da tepsiye dökün.',
      'Soğuduktan sonra buzdolabında 3 saat dinlendirin. Kaşıkla dilim dilim alıp tarçın serperek servis edin — Osmanlı saray mutfağının en şaşırtıcı mirası!',
    ],
  },
];
