// Temel veri: mutfaklar ve malzeme sözlüğü.
// Malzeme adları tarif dosyalarındaki adlarla birebir eşleşmelidir;
// eşleşmeyen bir ad geçerse yükleyici onu "Diğer" kategorisiyle otomatik ekler.

export const MUTFAKLAR = [
  'Türk Mutfağı',
  'İtalyan Mutfağı',
  'Meksika Mutfağı',
  'Uzak Doğu Mutfağı',
  'Kokteyller & İçecekler',
];

export const MALZEMELER: [string, string][] = [
  // Sebze & Meyve
  ['Domates', 'Sebze & Meyve'],
  ['Soğan', 'Sebze & Meyve'],
  ['Sarımsak', 'Sebze & Meyve'],
  ['Sivri Biber', 'Sebze & Meyve'],
  ['Kırmızı Biber', 'Sebze & Meyve'],
  ['Dolmalık Biber', 'Sebze & Meyve'],
  ['Patlıcan', 'Sebze & Meyve'],
  ['Patates', 'Sebze & Meyve'],
  ['Kabak', 'Sebze & Meyve'],
  ['Bal Kabağı', 'Sebze & Meyve'],
  ['Havuç', 'Sebze & Meyve'],
  ['Ispanak', 'Sebze & Meyve'],
  ['Pırasa', 'Sebze & Meyve'],
  ['Lahana', 'Sebze & Meyve'],
  ['Karnabahar', 'Sebze & Meyve'],
  ['Brokoli', 'Sebze & Meyve'],
  ['Taze Fasulye', 'Sebze & Meyve'],
  ['Bamya', 'Sebze & Meyve'],
  ['Enginar', 'Sebze & Meyve'],
  ['Kereviz', 'Sebze & Meyve'],
  ['Mantar', 'Sebze & Meyve'],
  ['Salatalık', 'Sebze & Meyve'],
  ['Marul', 'Sebze & Meyve'],
  ['Roka', 'Sebze & Meyve'],
  ['Maydanoz', 'Sebze & Meyve'],
  ['Dereotu', 'Sebze & Meyve'],
  ['Taze Nane', 'Sebze & Meyve'],
  ['Fesleğen', 'Sebze & Meyve'],
  ['Taze Soğan', 'Sebze & Meyve'],
  ['Limon', 'Sebze & Meyve'],
  ['Misket Limonu', 'Sebze & Meyve'],
  ['Portakal', 'Sebze & Meyve'],
  ['Elma', 'Sebze & Meyve'],
  ['Muz', 'Sebze & Meyve'],
  ['Çilek', 'Sebze & Meyve'],
  ['Ayva', 'Sebze & Meyve'],
  ['Avokado', 'Sebze & Meyve'],
  ['Mısır', 'Sebze & Meyve'],
  ['Bezelye', 'Sebze & Meyve'],
  ['Semizotu', 'Sebze & Meyve'],
  ['Asma Yaprağı', 'Sebze & Meyve'],
  ['Kuru Soğan (Arpacık)', 'Sebze & Meyve'],
  ['Kornişon Turşu', 'Sebze & Meyve'],

  // Et, Tavuk & Balık
  ['Kıyma', 'Et, Tavuk & Balık'],
  ['Kuşbaşı Et', 'Et, Tavuk & Balık'],
  ['Dana Rosto Eti', 'Et, Tavuk & Balık'],
  ['Kuzu İncik', 'Et, Tavuk & Balık'],
  ['Tavuk Göğsü', 'Et, Tavuk & Balık'],
  ['Tavuk But', 'Et, Tavuk & Balık'],
  ['Bütün Tavuk', 'Et, Tavuk & Balık'],
  ['Somon', 'Et, Tavuk & Balık'],
  ['Levrek', 'Et, Tavuk & Balık'],
  ['Hamsi', 'Et, Tavuk & Balık'],
  ['Karides', 'Et, Tavuk & Balık'],
  ['Sucuk', 'Et, Tavuk & Balık'],
  ['Pastırma', 'Et, Tavuk & Balık'],
  ['Ton Balığı', 'Et, Tavuk & Balık'],
  ['İşkembe', 'Et, Tavuk & Balık'],
  ['Kuzu Ciğeri', 'Et, Tavuk & Balık'],
  ['Midye', 'Et, Tavuk & Balık'],
  ['Kalamar', 'Et, Tavuk & Balık'],

  // Süt Ürünleri & Yumurta
  ['Yumurta', 'Süt Ürünleri & Yumurta'],
  ['Süt', 'Süt Ürünleri & Yumurta'],
  ['Yoğurt', 'Süt Ürünleri & Yumurta'],
  ['Süzme Yoğurt', 'Süt Ürünleri & Yumurta'],
  ['Tereyağı', 'Süt Ürünleri & Yumurta'],
  ['Krema', 'Süt Ürünleri & Yumurta'],
  ['Labne', 'Süt Ürünleri & Yumurta'],
  ['Beyaz Peynir', 'Süt Ürünleri & Yumurta'],
  ['Kaşar Peyniri', 'Süt Ürünleri & Yumurta'],
  ['Lor Peyniri', 'Süt Ürünleri & Yumurta'],
  ['Tulum Peyniri', 'Süt Ürünleri & Yumurta'],
  ['Parmesan', 'Süt Ürünleri & Yumurta'],
  ['Mozzarella', 'Süt Ürünleri & Yumurta'],
  ['Kaymak', 'Süt Ürünleri & Yumurta'],

  // Bakliyat & Tahıl
  ['Kırmızı Mercimek', 'Bakliyat & Tahıl'],
  ['Yeşil Mercimek', 'Bakliyat & Tahıl'],
  ['Nohut', 'Bakliyat & Tahıl'],
  ['Kuru Fasulye', 'Bakliyat & Tahıl'],
  ['Barbunya', 'Bakliyat & Tahıl'],
  ['Kuru Bakla', 'Bakliyat & Tahıl'],
  ['Bulgur', 'Bakliyat & Tahıl'],
  ['İnce Bulgur', 'Bakliyat & Tahıl'],
  ['Pirinç', 'Bakliyat & Tahıl'],
  ['Un', 'Bakliyat & Tahıl'],
  ['İrmik', 'Bakliyat & Tahıl'],
  ['Makarna', 'Bakliyat & Tahıl'],
  ['Spagetti', 'Bakliyat & Tahıl'],
  ['Lazanya Yaprağı', 'Bakliyat & Tahıl'],
  ['Noodle', 'Bakliyat & Tahıl'],
  ['Pirinç Noodle', 'Bakliyat & Tahıl'],
  ['Tortilla', 'Bakliyat & Tahıl'],
  ['Yufka', 'Bakliyat & Tahıl'],
  ['Baklavalık Yufka', 'Bakliyat & Tahıl'],
  ['Kadayıf', 'Bakliyat & Tahıl'],
  ['Ekmek Kadayıfı', 'Bakliyat & Tahıl'],
  ['Güllaç Yaprağı', 'Bakliyat & Tahıl'],
  ['Lavaş', 'Bakliyat & Tahıl'],
  ['Ekmek', 'Bakliyat & Tahıl'],
  ['Galeta Unu', 'Bakliyat & Tahıl'],
  ['Arpa Şehriye', 'Bakliyat & Tahıl'],
  ['Tel Şehriye', 'Bakliyat & Tahıl'],
  ['Erişte', 'Bakliyat & Tahıl'],
  ['Tarhana', 'Bakliyat & Tahıl'],
  ['Yulaf', 'Bakliyat & Tahıl'],
  ['Kedi Dili Bisküvi', 'Bakliyat & Tahıl'],
  ['Bisküvi', 'Bakliyat & Tahıl'],

  // Baharat, Yağ & Sos
  ['Tuz', 'Baharat, Yağ & Sos'],
  ['Karabiber', 'Baharat, Yağ & Sos'],
  ['Pul Biber', 'Baharat, Yağ & Sos'],
  ['Kimyon', 'Baharat, Yağ & Sos'],
  ['Kekik', 'Baharat, Yağ & Sos'],
  ['Kuru Nane', 'Baharat, Yağ & Sos'],
  ['Tarçın', 'Baharat, Yağ & Sos'],
  ['Zencefil', 'Baharat, Yağ & Sos'],
  ['Zerdeçal', 'Baharat, Yağ & Sos'],
  ['Köri', 'Baharat, Yağ & Sos'],
  ['Sumak', 'Baharat, Yağ & Sos'],
  ['Defne Yaprağı', 'Baharat, Yağ & Sos'],
  ['Zeytinyağı', 'Baharat, Yağ & Sos'],
  ['Ayçiçek Yağı', 'Baharat, Yağ & Sos'],
  ['Sirke', 'Baharat, Yağ & Sos'],
  ['Nar Ekşisi', 'Baharat, Yağ & Sos'],
  ['Soya Sosu', 'Baharat, Yağ & Sos'],
  ['Salça', 'Baharat, Yağ & Sos'],
  ['Acı Biber Sosu', 'Baharat, Yağ & Sos'],
  ['Hardal', 'Baharat, Yağ & Sos'],
  ['Mayonez', 'Baharat, Yağ & Sos'],
  ['Ketçap', 'Baharat, Yağ & Sos'],
  ['Susam', 'Baharat, Yağ & Sos'],
  ['İsot Biber', 'Baharat, Yağ & Sos'],
  ['Çörek Otu', 'Baharat, Yağ & Sos'],
  ['Bal', 'Baharat, Yağ & Sos'],
  ['Pekmez', 'Baharat, Yağ & Sos'],
  ['Tahin', 'Baharat, Yağ & Sos'],
  ['Hindistan Cevizi Sütü', 'Baharat, Yağ & Sos'],

  // Pastacılık & Kuruyemiş
  ['Şeker', 'Pastacılık & Kuruyemiş'],
  ['Pudra Şekeri', 'Pastacılık & Kuruyemiş'],
  ['Vanilya', 'Pastacılık & Kuruyemiş'],
  ['Kabartma Tozu', 'Pastacılık & Kuruyemiş'],
  ['Karbonat', 'Pastacılık & Kuruyemiş'],
  ['Maya', 'Pastacılık & Kuruyemiş'],
  ['Nişasta', 'Pastacılık & Kuruyemiş'],
  ['Kakao', 'Pastacılık & Kuruyemiş'],
  ['Bitter Çikolata', 'Pastacılık & Kuruyemiş'],
  ['Hindistan Cevizi Rendesi', 'Pastacılık & Kuruyemiş'],
  ['Ceviz', 'Pastacılık & Kuruyemiş'],
  ['Fındık', 'Pastacılık & Kuruyemiş'],
  ['Antep Fıstığı', 'Pastacılık & Kuruyemiş'],
  ['Badem', 'Pastacılık & Kuruyemiş'],
  ['Yer Fıstığı', 'Pastacılık & Kuruyemiş'],
  ['Çam Fıstığı', 'Pastacılık & Kuruyemiş'],
  ['Kuru Üzüm', 'Pastacılık & Kuruyemiş'],
  ['Kuru Kayısı', 'Pastacılık & Kuruyemiş'],
  ['Hurma', 'Pastacılık & Kuruyemiş'],

  // İçecek & Kokteyl
  ['Rom', 'İçecek & Kokteyl'],
  ['Votka', 'İçecek & Kokteyl'],
  ['Cin', 'İçecek & Kokteyl'],
  ['Tekila', 'İçecek & Kokteyl'],
  ['Viski', 'İçecek & Kokteyl'],
  ['Soda', 'İçecek & Kokteyl'],
  ['Kola', 'İçecek & Kokteyl'],
  ['Tonik', 'İçecek & Kokteyl'],
  ['Portakal Suyu', 'İçecek & Kokteyl'],
  ['Vişne Suyu', 'İçecek & Kokteyl'],
  ['Ananas Suyu', 'İçecek & Kokteyl'],
  ['Nar Şurubu', 'İçecek & Kokteyl'],
  ['Espresso', 'İçecek & Kokteyl'],
  ['Buz', 'İçecek & Kokteyl'],
];
