// Türk Mutfağı 4. bölüm: sonradan eklenen klasik tarifler.
// Hepsi gramajlı malzeme listesi, derin/detaylı özgün anlatım ve
// yerel fotoğrafla (bkz. yerel-resimler.ts) birlikte gelir.
import { type SeedTarif } from './seed-tarifler-turk';

const M = 'Türk Mutfağı';

export const TURK_4: SeedTarif[] = [
  // ─── ÇORBALAR ───
  {
    isim: 'İşkembe Çorbası', mutfak: M, kategori: 'Çorbalar', sure: 60, tur: 'yemek',
    malzemeler: [
      ['İşkembe', '500 g (haşlanmış)'],
      ['Un', '2 yemek kaşığı'],
      ['Tereyağı', '3 yemek kaşığı (60 g)'],
      ['Yumurta', '1 adet (sarısı)'],
      ['Limon', '1 adet'],
      ['Sarımsak', '4 diş'],
      ['Sirke', '3 yemek kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Pul Biber', '1 tatlı kaşığı (servis için)'],
    ],
    adimlar: [
      'İşkembeyi iyice temizlenmiş ve önceden yumuşayana kadar haşlanmış olarak kullanın; markette çoğu zaman haşlanmış satılır. Haşlama suyunu dökmeyin, süzüp saklayın — çorbanın gövdesini o su verir. İşkembeyi tahtaya alıp önce ince şeritler, sonra minik, neredeyse kıyma inceliğinde parçalar halinde doğrayın. Ne kadar ince olursa çorba o kadar makbuldür.',
      'Kalın tabanlı bir tencerede tereyağını orta ateşte eritin. Unu ekleyip tahta kaşıkla sürekli karıştırarak 2-3 dakika kavurun. Un yanmamalı ama çiğ de kalmamalı; rengi açık krem tonuna dönüp fındıksı bir koku yaymaya başlayınca kıvamındadır. Bu kavrulmuş un (meyane) çorbaya o kadifemsi, hafif bulanık kıvamı verir.',
      'Ocağı kısıp, sakladığınız işkembe suyundan yaklaşık 6 su bardağını azar azar, her seferinde çırparak ekleyin. Un topak yapmasın diye ilk bardakları yavaş dökün ve tel çırpıcıyla karıştırın; pürüzsüz bir kıvam yakalayınca kalanını daha rahat ekleyebilirsiniz. Doğranmış işkembeyi de ekleyip karıştırın.',
      'Çorbayı kaynayana kadar ısıtın, sonra ateşi kısıp 15-20 dakika, ara sıra karıştırarak hafif fokurdatın. Kıvamı kaşığın arkasını ince bir tabaka gibi kaplamalı; fazla koyulaşırsa biraz sıcak su ekleyin.',
      'Terbiye için küçük bir kâsede yumurta sarısını, yarım limonun suyunu ve 2-3 kaşık çorba suyunu çırpın. Terbiyenin kesilmemesinin sırrı sıcaklığı yavaş yükseltmektir: çorbadan birkaç kaşık daha alıp terbiyeye ekleyerek ılıştırın, sonra bu karışımı çorbaya yavaşça, sürekli karıştırarak dökün. Bu aşamadan sonra çorbayı KAYNATMAYIN — yumurta pıhtılaşıp taneli olur.',
      'Tuzu ekleyip karıştırın ve ocaktan alın. Sarımsaklı sirke sosu için sarımsakları ezip sirkeyle karıştırın — herkes kendi kâsesine damak zevkine göre gezdirsin. Servis sırasında küçük bir tavada tereyağını eritip pul biberi 8-10 saniye kavurun ve kâselerin üzerine kırmızı yağı gezdirin. Yanında bol sarımsaklı sirke ve limon şart; işkembe çorbasının olmazsa olmazı budur.',
    ],
  },

  // ─── SALATALAR & MEZELER ───
  {
    isim: 'Fava', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 60, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Kuru Bakla', '2 su bardağı (iç bakla, 300 g)'],
      ['Soğan', '1 adet büyük boy'],
      ['Zeytinyağı', '0,5 su bardağı'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Dereotu', '1 demet'],
      ['Limon', '1 adet'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'İç baklayı (kabuğu soyulmuş kuru bakla) bol suda, mümkünse bir gece önceden ıslatın. Islatma pişme süresini kısaltır ve baklanın daha kolay ezilip pürüzsüzleşmesini sağlar. Süresi yoksa en az 3-4 saat bekletin, sonra suyunu süzün.',
      'Soğanı iri iri doğrayın — nasılsa sonunda ezilecek, ince doğramaya gerek yok. Kalın tabanlı tencerede 3 kaşık zeytinyağını ısıtıp soğanı ekleyin ve kısık ateşte, renk aldırmadan 5-6 dakika yumuşayana kadar çevirin.',
      'Süzülmüş baklayı tencereye ekleyin. Üzerini 2-3 parmak geçecek kadar sıcak su ilave edin, şekeri ve yarım kaşık tuzu ekleyip karıştırın. Şeker baklanın hafif tatlımsı tadını dengeler ve rengini canlı tutar. Kaynayınca ateşi kısın.',
      'Kapağı aralık bırakarak 40-45 dakika, bakla tamamen dağılıp lapa kıvamına gelene kadar pişirin. Ara sıra karıştırın; su çekilirse azar azar sıcak su ekleyin. Sonunda tencerede yumuşak, koyu bir püre olmalı — bir taneyi kaşıkla ezdiğinizde hiç direnç kalmamalı.',
      'Ocaktan alıp sıcakken el blenderıyla veya çırpıcıyla pürüzsüz bir püre elde edin. Kalan zeytinyağını ve yarım limonun suyunu ekleyip karıştırın; asit ve yağ, favaya o ipeksi dokuyu ve dengeyi verir. Tadına bakıp tuzunu ayarlayın.',
      'Karışım sıcakken düz tabaklara veya küçük kaselere dökün ve spatülayla yüzeyini düzleyin — soğudukça jölemsi kıvam alıp şeklini korur. En az 2-3 saat, mümkünse buzdolabında iyice soğutun. Üzerine bolca kıyılmış dereotu serpin, zeytinyağı gezdirip limon dilimleriyle servis edin. Soğuk fava, sıcak ekmekle bambaşkadır.',
    ],
  },
  {
    isim: 'Humus', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 45, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Nohut', '2 su bardağı (haşlanmış, 400 g)'],
      ['Tahin', '3 yemek kaşığı'],
      ['Sarımsak', '2 diş'],
      ['Limon', '1 adet'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Kimyon', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Pul Biber', '1 çay kaşığı (servis için)'],
    ],
    adimlar: [
      'Nohutu bir gece ıslatıp yumuşayana kadar haşlayın (ya da haşlanmış kullanın). İpeksi bir humusun sırrı burada: haşlanmış nohutları avuç içinde hafifçe ovarak kabuklarını çıkarın. Zahmetli ama kabuğu alınmış nohut, blenderda çok daha pürüzsüz olur. Servis için birkaç tane bütün nohut ayırın.',
      'Sarımsağı ezin; çiğ sarımsak baskın gelmesin diye önce yarım limonun suyunda 5 dakika beklettmek keskinliğini yumuşatır. Bu küçük numara humusu daha dengeli yapar.',
      'Nohutları mutfak robotuna alın, tahini, sarımsak-limon karışımını, kimyonu ve tuzu ekleyin. Robotu çalıştırıp, kenarlarını ara ara sıyırarak 2-3 dakika çekin. Karışım koyu ve topaklıysa panik yapmayın — sıradaki adım çözecek.',
      'Robot çalışırken azar azar 4-5 yemek kaşığı BUZ GİBİ su ekleyin. Soğuk su, tahinle birleşince humusu açıp kabartır, rengini soluklaştırır ve o meşhur bulut gibi kıvamı verir. İstediğiniz akışkanlığa gelene kadar su ekleyip birkaç dakika daha çekin; ne kadar uzun çekerseniz o kadar pürüzsüz olur.',
      'Tadına bakın: tuz, limon veya tahin dengesini damağınıza göre ayarlayın. Humus soğudukça koyulaşır, bu yüzden kıvamı istediğinizden bir tık akışkan bırakın.',
      'Servis tabağına alıp kaşığın arkasıyla ortasını havuz gibi çukurlaştırın. Bu çukura zeytinyağını dökün, ayırdığınız bütün nohutları serpin, üzerine pul biber ve isterseniz bir tutam kimyon ekin. Sıcak pide veya lavaşla servis edin.',
    ],
  },
  {
    isim: 'Babagannuş', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 40, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Patlıcan', '3 adet büyük boy'],
      ['Tahin', '2 yemek kaşığı'],
      ['Sarımsak', '2 diş'],
      ['Limon', '1 adet'],
      ['Zeytinyağı', '3 yemek kaşığı'],
      ['Süzme Yoğurt', '2 yemek kaşığı (isteğe bağlı)'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Babagannuşun tüm karakteri patlıcanın közlenmesinde, o dumanlı tatta saklıdır. Patlıcanları çatalla birkaç yerinden delin (közlenirken patlamasın diye) ve doğrudan ocağın alevi üzerinde, közde veya fırının ızgara katında çevirerek pişirin. Kabuğu her yerinden kapkara kömürleşmeli, içi ise tamamen yumuşayıp sönmeli — bu 15-20 dakika sürer.',
      'Közlenen patlıcanları bir kaseye alıp üzerini kapatın; 5 dakika buharında dinlenince kabukları daha kolay soyulur. Ilıyınca kabuğun tamamını soyun. Birkaç minik siyah zerre kalması sorun değil, hatta tada katkı sağlar — ama büyük yanık parçaları acılık verir, onları temizleyin.',
      'Soyulmuş patlıcan bol su tutar; bir süzgece alıp elinizle hafifçe sıkın veya 10 dakika süzülmeye bırakın. Fazla su alınmazsa babagannuş cıvık olur. Sonra patlıcanı tahtada bıçakla iri iri kıyın veya çatalla ezin — makbul olanı, birazı ezilirken birazının dokusunun kalmasıdır.',
      'Sarımsağı ezip patlıcana ekleyin. Tahini, yarım limonun suyunu ve tuzu ilave edin. İsterseniz süzme yoğurt eklemek daha kremamsı ve hafif bir sonuç verir (klasik tarifte yoğurtsuz da yapılır). Çatalla karıştırarak tatları birleştirin.',
      'Tadına bakın; dumanlı tada limon ve sarımsak eşlik etmeli, tahin ise geride hafif bir acılık bırakmalı. Dengeyi damağınıza göre ayarlayın.',
      'Tabağa alıp yüzeyini kaşıkla yayın, üzerine bolca zeytinyağı gezdirin. İsteğe göre nar taneleri veya kıyılmış maydanozla süsleyip sıcak ekmekle servis edin.',
    ],
  },
  {
    isim: 'Şakşuka', mutfak: M, kategori: 'Zeytinyağlılar & Sebze', sure: 45, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Patlıcan', '2 adet'],
      ['Patates', '2 adet orta boy'],
      ['Sivri Biber', '3 adet'],
      ['Domates', '3 adet olgun'],
      ['Sarımsak', '3 diş'],
      ['Salça', '1 yemek kaşığı'],
      ['Zeytinyağı', 'kızartma için'],
      ['Şeker', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Patlıcanları alacalı soyun (bir şerit kabuklu, bir şerit soyulmuş) ve küp küp doğrayın. Acısını almak için tuzlu suda 15 dakika bekletip sonra iyice sıkın; bu hem acılığı alır hem de kızarırken daha az yağ çekmesini sağlar. Patatesleri de aynı boyda küp doğrayıp nişastası aksın diye yıkayın ve kurulayın.',
      'Derin bir tavada zeytinyağını kızdırın. Patatesleri altın sarısı olana kadar kızartıp kağıt havluya alın. Aynı yağda patlıcanları kızartın — patlıcan çok yağ çeker ama kızardıkça bir kısmını geri bırakır; kenarları kızarıp içi kremsi olunca alın. Son olarak sivri biberleri kısa süre çevirip çıkarın. Hepsini havlu üzerinde biriktirin.',
      'Domatesleri rendeleyin veya kabuğunu soyup küçük küp doğrayın. Tavadaki yağın fazlasını alıp 2 kaşık bırakın, ezilmiş sarımsağı 20 saniye çevirin (yakmayın), salçayı ekleyip 1 dakika kavurun.',
      'Rendelenmiş domatesi, şekeri ve tuzu ekleyin. Şeker domatesin ekşiliğini dengeler. Sosu orta ateşte, suyunu salıp koyulaşana ve yağı üzerine çıkana kadar 8-10 dakika pişirin. Kıvamı ne çok sulu ne çok koyu, kaşıkta akmayan bir sos olmalı.',
      'Kızarmış sebzeleri geniş bir servis tabağına dizin, üzerlerine sıcak domates sosunu gezdirin. Şakşuka sıcak da yenir ama asıl lezzeti soğuyunca, tatlar birbirine geçtiğinde ortaya çıkar.',
      'En az yarım saat dinlendirin. Üzerine sarımsaklı yoğurt gezdirmek çok yakışır. Buzdolabında 2 gün rahatça durur ve her geçen gün daha lezzetli olur.',
    ],
  },
  {
    isim: 'Muhammara', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 30, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Kırmızı Biber', '3 adet (közlenmiş) veya 3 yemek kaşığı biber salçası'],
      ['Ceviz', '1,5 su bardağı'],
      ['Galeta Unu', '0,5 su bardağı'],
      ['Nar Ekşisi', '2 yemek kaşığı'],
      ['Zeytinyağı', '4 yemek kaşığı'],
      ['Sarımsak', '2 diş'],
      ['Kimyon', '1 çay kaşığı'],
      ['Pul Biber', '1 tatlı kaşığı'],
      ['Tuz', '1 çay kaşığı'],
    ],
    adimlar: [
      'Muhammaranın gövdesini ceviz ve kırmızı biber kurar. Taze kırmızı biber kullanacaksanız közleyip kabuğunu soyun ve suyunu iyice süzün; pratik yol olarak tatlı biber salçası da kullanabilirsiniz. Cevizleri kuru bir tavada 2-3 dakika, kokusu çıkana kadar hafif kavurmak aromayı derinleştirir — ama yakmayın, acılaşır.',
      'Cevizleri mutfak robotunda veya bıçakla kıyarak orta iri çekin. Tamamen un olmasın; içinde dişe gelen küçük parçalar kalması muhammaraya dokusunu verir.',
      'Bir kaseye çekilmiş cevizi, közlenmiş biberi (veya salçayı), galeta ununu, ezilmiş sarımsağı, nar ekşisini, kimyonu, pul biberi ve tuzu alın. Galeta unu hem karışımı bağlar hem fazla nemi çeker.',
      'Zeytinyağını azar azar ekleyerek karıştırın. Karışım önce dağınık durur, yağ ve nar ekşisiyle birleştikçe koyu, yayılabilir bir macun kıvamı alır. Fazla kuru geldiyse biraz daha zeytinyağı, fazla yağlıysa biraz galeta unu ekleyin.',
      'Tadına bakın — muhammara tatlı (nar ekşisi/biber), ekşi, hafif acı ve kimyonlu-topraksı tatların dengesidir. Nar ekşisini ve pul biberi damağınıza göre ayarlayın, sonra 30 dakika buzdolabında dinlendirin ki tatlar otursun.',
      'Servis tabağına yayıp üzerine zeytinyağı gezdirin, isterseniz birkaç ceviz içi ve nar tanesiyle süsleyin. Sıcak lavaş, pide veya kıtır ekmekle servis edin.',
    ],
  },
  {
    isim: 'Rus Salatası', mutfak: M, kategori: 'Salatalar & Mezeler', sure: 40, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Patates', '3 adet orta boy'],
      ['Havuç', '2 adet'],
      ['Bezelye', '1 su bardağı (haşlanmış)'],
      ['Yumurta', '2 adet'],
      ['Kornişon Turşu', '5-6 adet'],
      ['Mayonez', '4 yemek kaşığı'],
      ['Limon', '0,5 adet'],
      ['Tuz', '1 çay kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
    ],
    adimlar: [
      'Patates ve havuçları KABUKLU haşlayın — kabuklu haşlamak hem suda dağılmalarını önler hem de sulu, tatsız olmalarının önüne geçer. Ayrı bir tencerede yumurtaları da 9-10 dakika katı haşlayın. Patatese çatal batırdığınızda kolay giriyor ama parçalanmıyorsa tam kıvamındadır; fazla pişerse salata lapaya döner.',
      'Haşlanmışları soğumaya bırakın. Sıcakken doğramayın; sıcak sebze mayonezi eritir ve salata cıvır. Patates, havuç ve yumurtaları hepsi aynı boyda, küçük ve düzgün küpler halinde doğrayın — göze güzel görünmesi ve her çatalda tüm tatların bir arada olması için eşit doğramak önemlidir.',
      'Kornişon turşuları da minik küpler halinde doğrayıp bir tülbent veya kağıt havluyla suyunu iyice sıkın. Turşunun ekşi-tuzlu keskinliği, salatanın mayonezli yumuşaklığını dengeleyen asıl unsurdur; ama suyu alınmazsa salatayı sulandırır.',
      'Geniş bir kapta tüm doğranmışları ve haşlanmış bezelyeyi nazikçe birleştirin. Bezelyeyi en sona bırakıp hafif karıştırın ki ezilmesin.',
      'Mayonezi, yarım limonun suyunu, tuz ve karabiberi ekleyin. Kaşıkla değil, spatülayla alttan üste katlayarak karıştırın — böyle karıştırmak küpleri ezmez. Mayonez az geldiyse ekleyin ama fazla kaçırmayın; salata boğulmamalı, taneler görünmeli.',
      'En az 1 saat buzdolabında dinlendirin. Soğukta tatlar birbirine geçer ve kıvam oturur. Üzerini haşlanmış yumurta dilimleri, zeytin veya kırmızı biberle süsleyip soğuk servis edin.',
    ],
  },

  // ─── ET YEMEKLERİ ───
  {
    isim: 'İnegöl Köfte', mutfak: M, kategori: 'Et Yemekleri', sure: 45, tur: 'yemek',
    malzemeler: [
      ['Kıyma', '500 g (dana-kuzu karışık)'],
      ['Soğan', '1 adet büyük boy'],
      ['Galeta Unu', '3 yemek kaşığı'],
      ['Karbonat', '0,5 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
    ],
    adimlar: [
      'İnegöl köftesinin sırrı sadeliğinde ve yoğrulmasında saklıdır: klasik tarifte sarımsak ve baharat bombardımanı YOKTUR, eti ve soğanı öne çıkaran temiz bir tat aranır. Kıymanın yarı yağlı (dana-kuzu karışık) olması köftenin sulu ve yumuşak olmasını sağlar; yağsız kıyma kuru köfte verir.',
      'Soğanı rendeleyin ve suyunu bir tülbentle iyice sıkın. Soğanın SUYU değil kendisi lazım; suyu köfteyi gevşetir ve pişerken dağıtır. Sıkılmış soğanı kıymaya ekleyin.',
      'Galeta unu, karbonat, tuz ve karabiberi ekleyin. Karbonat, İnegöl köftesine o hafif kabarık, yumuşak dokuyu veren gizli malzemedir. Şimdi en önemli adım: harcı en az 8-10 dakika, avuç içinizle bastırıp yoğurun. Uzun yoğurma etin proteinlerini açar, harç birbirine kenetlenir ve köfte ızgarada dağılmaz, dişe gelen o esnek dokuyu kazanır.',
      'Yoğrulmuş harcı üzeri kapalı şekilde buzdolabında en az 1 saat, mümkünse birkaç saat dinlendirin. Dinlenme hem tatların oturmasını hem de harcın sıkılaşıp şekil almasını sağlar.',
      'Islak elle harçtan ceviz büyüklüğünde parçalar alıp önce yuvarlayın, sonra hafifçe bastırıp parmak kalınlığında, kısa oval köfteler şekillendirin. Islak el harcın ele yapışmasını önler.',
      'Köfteleri iyice kızmış ızgarada veya kalın tavada pişirin. Önce bir yüzünü, altı güzelce mühürlenip kızarana kadar oynatmadan pişirin; erken çevirirseniz yapışıp dağılır. Sonra çevirip diğer yüzünü pişirin. İçi pembe kalmayacak ama kurumayacak şekilde, dışı karamelize olunca alın. Yanında ızgara domates-biber, soğan piyazı ve ekmekle servis edin.',
    ],
  },
  {
    isim: 'Arnavut Ciğeri', mutfak: M, kategori: 'Et Yemekleri', sure: 30, tur: 'yemek',
    malzemeler: [
      ['Kuzu Ciğeri', '500 g'],
      ['Un', '3 yemek kaşığı'],
      ['Ayçiçek Yağı', 'kızartma için'],
      ['Soğan', '1 adet'],
      ['Maydanoz', '0,5 demet'],
      ['Pul Biber', '1 tatlı kaşığı'],
      ['Sumak', '1 yemek kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Ciğerin üzerindeki ince zarı soyun (parmakla kenarından tutup çekince kolay gelir) ve içindeki büyük damarları temizleyin; bu zar pişince sertleşir ve ciğeri büzer. Ciğeri 1,5-2 cm küpler halinde doğrayın. Kağıt havluyla iyice kurulayın — ıslak ciğer kızgın yağda sıçrar ve un tutmaz.',
      'ÖNEMLİ KURAL: ciğeri pişirmeden önce TUZLAMAYIN. Erken tuz ciğerin suyunu çeker, sertleşip kösele gibi olur. Tuz en sona saklanır.',
      'Ciğer küplerini bir poşete veya kaseye alıp un serpin ve iyice bulayın, sonra fazla unu eleyerek silkeleyin. İnce un tabakası hem dışını çıtır yapar hem içini sulu tutar.',
      'Geniş bir tavada 2 parmak yağı iyice kızdırın (yağ yeterince kızmazsa ciğer yağ çeker ve ağırlaşır). Ciğerleri tavayı kalabalık etmeden, birkaç partide ekleyin. Yüksek ateşte, sadece 2-3 dakika, dışı kızarıp mühürlenene kadar pişirin. Ciğer çok çabuk pişer; fazla tutarsanız içi de sertleşir. Kızaranları delikli kaşıkla kağıt havluya alın.',
      'Soğanı ince yarım ay dilimleyip bir tutam tuz ve sumakla ovun; ovmak soğanın acısını alır ve suyunu çıkararak yumuşatır. Maydanozu kıyıp soğana karıştırın — bu sumaklı soğan salatası Arnavut ciğerinin ayrılmaz eşlikçisidir.',
      'Sıcak ciğerleri servis tabağına alın, ÜZERİNE şimdi tuz ve pul biber serpin. Yanına sumaklı soğan piyazını koyup hemen servis edin; ciğer bekledikçe sertleşir, sıcak sıcak yenmeli.',
    ],
  },
  {
    isim: 'Sac Kavurma', mutfak: M, kategori: 'Et Yemekleri', sure: 50, tur: 'yemek',
    malzemeler: [
      ['Kuşbaşı Et', '600 g (kuzu veya dana)'],
      ['Soğan', '1 adet'],
      ['Domates', '2 adet'],
      ['Sivri Biber', '3 adet'],
      ['Kırmızı Biber', '1 adet'],
      ['Salça', '1 yemek kaşığı'],
      ['Sarımsak', '2 diş'],
      ['Tereyağı', '2 yemek kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Kekik', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Eti küçük, bir lokmalık kuşbaşı doğrayın ve kağıt havluyla kurulayın. Kavurmanın kilit noktası eti KENDİ SUYUNDA pişirip sonra kavurmaktır. Kalın tabanlı bir tava veya sacı yağ eklemeden iyice kızdırın, eti ekleyin.',
      'Et önce suyunu salacaktır — panik yapmayın. Orta-yüksek ateşte, ara sıra karıştırarak eti kendi suyunda pişirin. Su yavaş yavaş çekilecek. Bu aşama etin yumuşamasını sağlar ve 15-20 dakika sürebilir; suyu tamamen çekilene kadar bekleyin.',
      'Su çekilip et cızırdamaya, yağ kalıp kavrulmaya başlayınca tereyağını ekleyin. Eti bu yağda birkaç dakika, dış yüzeyi kızarıp kahverengi bir renk alana kadar kavurun. İşte kavurmanın o derin, karamelize tadı bu adımda oluşur.',
      'Yarım ay doğranmış soğanı ekleyip 3-4 dakika çevirin, pembeleşsin. Ezilmiş sarımsağı ve salçayı ekleyip 1-2 dakika kavurun; salçanın ham kokusu geçsin.',
      'İri doğranmış sivri ve kırmızı biberleri ekleyip 2-3 dakika çevirin. Sonra küp doğranmış domatesi ekleyin. Domates suyunu salıp hafif bir sos oluşturacak — kavurma çorba gibi sulu olmamalı, domates suyu çekilip yağa dönmeli.',
      'Karabiber, kekik ve tuzu ekleyin (tuzu sona bırakmak eti sertleştirmez). Kısık ateşte 5 dakika daha, sos koyulaşıp yağ üzerine çıkana kadar pişirin. Sıcak sıcak, yanında lavaş veya pide, közlenmiş biber ve soğanla servis edin.',
    ],
  },

  // ─── BALIK & DENİZ ÜRÜNLERİ ───
  {
    isim: 'Midye Dolma', mutfak: M, kategori: 'Balık & Deniz Ürünleri', sure: 90, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Midye', '30 adet büyük boy'],
      ['Pirinç', '1,5 su bardağı'],
      ['Soğan', '2 adet büyük boy'],
      ['Zeytinyağı', '0,5 su bardağı'],
      ['Çam Fıstığı', '2 yemek kaşığı'],
      ['Kuru Üzüm', '2 yemek kaşığı'],
      ['Tarçın', '0,5 çay kaşığı'],
      ['Karabiber', '1 çay kaşığı'],
      ['Kuru Nane', '1 çay kaşığı'],
      ['Limon', '2 adet'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Midyeleri tek tek kontrol edin: açık olan veya kabuğu kırık midyeleri atın (bozuk olabilir). Kabukların üzerindeki sakalları ve yosunları bir bıçakla kazıyıp bol suyla, fırçayla ovarak temizleyin. Deniz ürününde temizlik en kritik adımdır; kum ve yosun kalırsa iç harca karışır.',
      'İç pilav harcı için soğanları olabildiğince küçük doğrayın. Geniş bir tavada zeytinyağını ısıtıp çam fıstığını ekleyin, kısık ateşte altın sarısı olana kadar kavurun (çabuk yanar, gözünüzü ayırmayın). Soğanları ekleyip 8-10 dakika, iyice yumuşayıp hafif renk alana kadar sabırla kavurun — iç pilavın tadı bu uzun soğan kavurmasından gelir.',
      'Yıkanıp süzülmüş pirinci ekleyip 3-4 dakika kavurun, taneler yağa bulanıp şeffaflaşsın. Kuru üzüm, tarçın, karabiber, kuru nane ve tuzu ekleyin. Üzerine pirincin yarısı kadar (yaklaşık 1 bardak) sıcak su ekleyip karıştırın, suyunu çekene kadar kısık ateşte pişirin. Pirinç yarı pişmiş, diriçe kalmalı — kabukta buğulanırken tamamlanacak.',
      'Midyeleri açmak için: kör tarafından değil, düz kenarından bir bıçakla iterek, menteşeli uçtan KIRMADAN aralayın. Kabuğu tamamen koparmayın, kitap gibi açık kalsın. İçindeki siyah torbayı temizleyin.',
      'Her midyenin içine yarı pişmiş pilavdan bir tatlı kaşığı doldurun, ağzını kapatın. Fazla doldurmayın; pilav pişerken şişer ve taşarsa kabuk kapanmaz.',
      'Doldurulmuş midyeleri geniş bir tencereye sıkışık şekilde, ağızları yukarı gelecek biçimde dizin. Üzerine bir tabak kapatıp bastırın (pişerken açılmasınlar). Tencere yüksekliğinin yarısına kadar sıcak su ekleyip kapağı kapatın, kısık ateşte 30-35 dakika pişirin. Pirinç tamamen pişip suyu çekilince ocaktan alın.',
      'Tenceredeyken tamamen soğumaya bırakın (sıcakken çıkarmaya çalışırsanız dağılırlar). Bol limon sıkarak servis edin; midye dolmanın olmazsa olmazı, her lokmadan önce sıkılan limondur.',
    ],
  },
  {
    isim: 'Hamsili Pilav', mutfak: M, kategori: 'Balık & Deniz Ürünleri', sure: 60, tur: 'yemek',
    malzemeler: [
      ['Hamsi', '750 g'],
      ['Pirinç', '2 su bardağı'],
      ['Soğan', '2 adet'],
      ['Tereyağı', '3 yemek kaşığı'],
      ['Çam Fıstığı', '2 yemek kaşığı'],
      ['Kuru Üzüm', '2 yemek kaşığı'],
      ['Maydanoz', '0,5 demet'],
      ['Karabiber', '1 çay kaşığı'],
      ['Kuru Nane', '1 çay kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
    ],
    adimlar: [
      'Hamsileri ayıklayın: baş kısmını koparıp aşağı doğru çekince iç organları ve orta kılçık çoğunlukla birlikte gelir. Başparmağınızla karnından açıp orta kılçığı kuyruğa doğru sıyırın; kuyruk kalabilir. Ayıklanmış hamsileri tuzlu suda yıkayıp süzün ve kağıt havluda kurutun. Zahmetli ama Karadeniz mutfağının bu incisi buna değer.',
      'Önce iç pilavı hazırlayın: tereyağında çam fıstığını kavurup soğanları ekleyin, yumuşayana kadar çevirin. Yıkanmış pirinci ekleyip 3-4 dakika kavurun, kuru üzümü, karabiberi, kuru naneyi ve tuzu ekleyin. Üzerine 2,5 bardak sıcak su ekleyip suyunu çekene kadar pişirin, sonra kıyılmış maydanozu karıştırın. Pilav diriçe olmalı; asıl pişme fırında olacak.',
      'Yağlanmış bir fırın kabının veya tepsinin tabanına, hamsileri kuyrukları merkeze bakacak şekilde, çiçek/güneş deseni oluşturarak yan yana dizin. Aralık bırakmadan tüm tabanı kaplayın; bu kat pilavın altına yapışmasını önler ve pişerken yağını pilava verir.',
      'Hazırladığınız iç pilavı hamsilerin üzerine döküp spatülayla düzleyin, bastırmayın. Üzerini de ikinci bir kat hamsiyle, yine desenli şekilde tamamen kaplayın.',
      'Önceden 190°C ısıtılmış fırında 30-35 dakika, üstteki hamsiler kızarıp kenarları çıtırlaşana kadar pişirin. Hamsi çabuk pişer; üzeri altın rengini alınca hazırdır.',
      'Fırından alıp 10 dakika dinlendirin. Servis için bir tabakla ters çevirebilir (alttaki desenli hamsiler üste gelir) veya doğrudan kabından dilimleyerek verebilirsiniz. Yanında limonla, sıcak servis edin.',
    ],
  },

  // ─── HAMUR İŞİ ───
  {
    isim: 'Çiğ Börek', mutfak: M, kategori: 'Hamur İşi', sure: 60, tur: 'yemek', porsiyon: 4,
    malzemeler: [
      ['Un', '3 su bardağı'],
      ['Yoğurt', '2 yemek kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Kıyma', '300 g'],
      ['Soğan', '1 adet'],
      ['Karabiber', '1 çay kaşığı'],
      ['Pul Biber', '1 çay kaşığı'],
      ['Ayçiçek Yağı', 'kızartma için'],
    ],
    adimlar: [
      'Adı "çiğ" olsa da börek kızartılır; adı, içinin çiğ kıymayla doldurulup hamurla birlikte piştiği için verilmiştir. Hamur için unu geniş bir kaba eleyin, ortasını havuz yapıp yoğurt, tuz ve yaklaşık 1 su bardağı ılık su ekleyin. Yoğurt hamura esneklik ve o meşhur kabarcıklı çıtırlığı verir.',
      'Kulak memesinden biraz sert bir hamur elde edene kadar 8-10 dakika yoğurun. İyi yoğrulmuş, pürüzsüz hamur açılırken yırtılmaz. Üzerini nemli bezle örtüp en az 30 dakika dinlendirin — dinlenen hamurun gluteni gevşer ve incecik açılır.',
      'İç harç için soğanı rendeleyip suyunu hafifçe sıkın, kıymayla birleştirin. Karabiber, pul biber ve tuzu ekleyin. Harcın yayılabilir olması için 2-3 kaşık soğuk su veya soda ekleyip iyice yoğurun; sulu-yumuşak harç, ince hamurun içinde güzel yayılır ve börek kuru olmaz.',
      'Dinlenen hamuru ceviz büyüklüğünde bezelere bölün. Her bezeyi unlanmış tezgahta olabildiğince İNCE, yaklaşık 20 cm çapında yuvarlak açın. Hamur ne kadar ince olursa börek o kadar çıtır olur.',
      'Açtığınız yuvarlağın yarısına ince bir tabaka harç sürün, kenarda parmak genişliğinde boşluk bırakın. Hamuru ikiye katlayıp yarım ay yapın. Kenarlarını parmakla veya çatalla iyice bastırarak yapıştırın — kızarırken açılmaması için sızdırmaz olmalı. Bir tabağın kenarıyla kesip düzeltin.',
      'Geniş ve derin bir tavada bol yağı kızdırın (börek yağda yüzmeli). Börekleri kızgın yağa atın; hemen kabarıp yüzeye çıkacaklar. Bir yüzü altın-kahve olunca çevirin. Kızarırken kaşıkla üzerine yağ gezdirmek kabarcıkların oluşmasını sağlar. Kızaranları kağıt havluya alıp sıcak servis edin; yanında ayran şart.',
    ],
  },
  {
    isim: 'Simit', mutfak: M, kategori: 'Hamur İşi', sure: 150, tur: 'yemek', porsiyon: 6,
    malzemeler: [
      ['Un', '4 su bardağı'],
      ['Maya', '1 paket instant (10 g)'],
      ['Şeker', '1 tatlı kaşığı'],
      ['Tuz', '1 tatlı kaşığı'],
      ['Pekmez', '4 yemek kaşığı'],
      ['Susam', '1,5 su bardağı'],
    ],
    adimlar: [
      'Bir kaseye 1,5 su bardağı ılık su (parmağınızı yakmayan, el ısısında), mayayı ve şekeri ekleyip karıştırın, 5-10 dakika bekletin. Yüzeyde köpük/kabarcık oluşması mayanın canlı olduğunu gösterir; oluşmazsa maya ölüdür, hamur kabarmaz.',
      'Unu ve tuzu geniş bir kaba alın (tuzu mayadan uzağa koyun, doğrudan temas mayayı yavaşlatır). Maya karışımını ekleyip yoğurmaya başlayın, gerekirse azar azar ılık su ilave edin. 10 dakika, yumuşak ama ele yapışmayan, pürüzsüz bir hamur olana kadar yoğurun.',
      'Kabın üzerini nemli bezle örtüp ılık bir yerde, hacmi iki katına çıkana kadar yaklaşık 1 saat mayalandırın. Hamura parmakla bastırdığınızda iz yavaşça geri geliyorsa mayalanma tamamdır.',
      'Mayalanan hamurun gazını alıp 6 eşit bezeye bölün. Her bezeyi ikiye ayırıp iki uzun ip (yaklaşık 40 cm) haline getirin. İki ipi bir çırpı gibi birbirine sarıp burun, sonra iki ucunu birleştirerek halka yapın. Bu burgu deseni simidin klasik görünümüdür.',
      'Bir tabağa pekmezi 3-4 kaşık suyla inceltin, başka bir tabağa susamı yayın. Her simidi önce pekmezli suya batırıp çıkarın (pekmez hem rengi hem tadı verir), sonra susama iki tarafını da bastırarak bolca bulayın. Susamın yapışması için pekmez şart.',
      'Simitleri yağlı kağıt serili tepsiye dizip 15-20 dakika daha dinlendirin. Önceden 220°C ısıtılmış fırında 18-22 dakika, üzerleri koyu altın rengi ve susamlar kızarana kadar pişirin. Dışı çıtır, içi yumuşak olmalı. Fırından çıkınca üzerine hafif su serpip 1 dakika beklemek kabuğu güzelleştirir. Ilıkken, peynir ve çayla en güzeldir.',
    ],
  },
  {
    isim: 'Kol Böreği', mutfak: M, kategori: 'Hamur İşi', sure: 70, tur: 'yemek', porsiyon: 6,
    malzemeler: [
      ['Yufka', '4 adet'],
      ['Beyaz Peynir', '300 g'],
      ['Maydanoz', '1 demet'],
      ['Yumurta', '2 adet'],
      ['Süt', '1 su bardağı'],
      ['Zeytinyağı', '0,5 su bardağı'],
      ['Susam', '1 yemek kaşığı'],
    ],
    adimlar: [
      'Kol böreğini tepsi böreğinden ayıran şey, ıslatma sosunun az tutulup yufkanın kat kat, çıtır kalmasıdır. Önce sosu hazırlayın: bir kaseye sütü, zeytinyağını ve 1 yumurtayı (sarısını süslemeye ayırıp beyazını kullanın) çırpın. Bu ıslatma yufkayı yumuşatır ama boğmaz.',
      'İç harç için beyaz peyniri bir çatalla ezin, ince kıyılmış maydanozu ekleyip karıştırın. Peynir çok tuzluysa 10 dakika suda bekletip süzün; yoksa börek fazla tuzlu olur. Peynir harcına yumurta koymaya gerek yok, maydanoz ve peynir yeterli.',
      'Bir yufkayı tezgaha serin, üzerine hazırladığınız sostan fırça veya elle ince ince gezdirin — her yeri ıslatmayın, hafif nemlendirin. İkinci yarım yufkayı üzerine koyup yine hafif ıslatın.',
      'Yufkanın geniş kenarına, bir kenardan 3-4 cm boşluk bırakarak peynirli harçtan bir çizgi halinde yerleştirin. Şimdi yufkayı harcın olduğu kenardan başlayarak, ne çok sıkı ne çok gevşek, rulo yapın. Çok sıkarsanız pişerken çatlar, gevşek olursa dağılır.',
      'Ruloyu yağlanmış tepsiye, hafif bir salyangoz/spiral şeklinde kıvırarak yerleştirin. Diğer yufkalarla da aynısını yapıp spiralin devamına ekleyin; böylece tek büyük sarmal bir börek oluşur.',
      'Ayırdığınız yumurta sarısını 1 kaşık sütle çırpıp böreğin üzerine sürün (bu, altın parlak bir kabuk verir), susam serpin. Önceden 190°C ısıtılmış fırında 35-40 dakika, üzeri kızarıp çıtırlaşana kadar pişirin. 10 dakika dinlendirip dilimleyerek servis edin; çayla harika gider.',
    ],
  },

  // ─── TATLILAR ───
  {
    isim: 'Ekmek Kadayıfı', mutfak: M, kategori: 'Tatlılar', sure: 45, tur: 'yemek', porsiyon: 6,
    malzemeler: [
      ['Ekmek Kadayıfı', '2 adet (hazır)'],
      ['Şeker', '3 su bardağı'],
      ['Limon', '0,5 adet'],
      ['Kaymak', '200 g (servis için)'],
      ['Ceviz', '0,5 su bardağı'],
    ],
    adimlar: [
      'Hazır ekmek kadayıfı (kuru, gözenekli yuvarlak taban) kullanın. Önce şerbeti hazırlayın çünkü kadayıf pişerken şerbetin ILIK olması gerekir: 3 su bardağı şeker ve 3 su bardağı suyu tencereye alıp kaynatın, 12-15 dakika hafif kıvamlanana kadar pişirin, yarım limonun suyunu ekleyip (şekerlenmeyi önler) ocaktan alın. Şerbetin altta ılık kalmasını sağlayın.',
      'Ekmek kadayıflarını geniş, kenarları yüksek bir tavaya veya tepsiye yerleştirin. Üzerlerine, tamamen ıslanmaları için yaklaşık 2-3 bardak ılık suyu yavaşça gezdirin. Kadayıf suyu içine çekip yumuşayacak; birkaç dakika bekletin. Fazla suyu tavayı eğerek dökün.',
      'Tavayı kısık ateşe alın. Kadayıflar suyunu çekip alttan hafif kızarmaya başlayacak. Bu aşamada dikkatli olun, dibi tutmasın; tavayı ara ara döndürün.',
      'Şimdi kritik adım: ILIK şerbeti, sıcak kadayıfın üzerine kepçeyle yavaşça gezdirin. Altın kural — biri sıcaksa diğeri ılık/soğuk olmalı; ikisi de kaynar sıcak olursa kadayıf şerbeti içine çekmez, hamurlaşır ve dağılır. Şerbeti azar azar ekleyip kadayıfın emmesini bekleyin.',
      'Kadayıf şerbeti çekip parlak, dolgun bir hal alınca ve kenarlarında şerbet fokurdayıp koyulaşınca ocaktan alın. Üzeri camsı bir parlaklık almalı, içi ıslak sünger gibi olmalı ama dağılmamalı.',
      'Tamamen soğutun (sıcak kesilince dağılır). Dilimleyip her porsiyonun üzerine bir kaşık kaymak ve üzerine dövülmüş ceviz koyarak servis edin. Kaymağın serinliği, şerbetin yoğun tatlılığını dengeler — ekmek kadayıfının klasik ikilisidir.',
    ],
  },
  {
    isim: 'Kalburabastı', mutfak: M, kategori: 'Tatlılar', sure: 75, tur: 'yemek', porsiyon: 6,
    malzemeler: [
      ['Un', '3 su bardağı'],
      ['İrmik', '0,5 su bardağı'],
      ['Yoğurt', '0,5 su bardağı'],
      ['Tereyağı', '125 g'],
      ['Yumurta', '1 adet'],
      ['Kabartma Tozu', '1 paket'],
      ['Ceviz', '1 su bardağı (iç harç)'],
      ['Şeker', '3 su bardağı (şerbet)'],
      ['Limon', '0,5 adet'],
    ],
    adimlar: [
      'Şerbeti önceden yapın ve SOĞUMAYA bırakın: 3 bardak şeker + 3 bardak su kaynayıp 12-15 dakika pişsin, yarım limon suyu ekleyip ocaktan alın. Kuralımız: sıcak hamur işine soğuk şerbet gider. Sıcak-sıcak buluşurlarsa tatlı şerbeti çekmez, dışı ıslak-içi kuru kalır.',
      'Oda sıcaklığındaki tereyağını yumurta ve yoğurtla çırpın. İrmiği ekleyip karıştırın ve 10 dakika bekletin; irmik nemi çekip şişince tatlı ağızda dağılan, kumlu-yumuşak bir doku kazanır.',
      'Kabartma tozunu unla karıştırıp azar azar ekleyerek yumuşak, ele yapışmayan bir hamur yoğurun. Fazla yoğurmayın — çok yoğrulan hamur sertleşir, kalburabastı ise lokum gibi yumuşak olmalı. Hamuru 15 dakika dinlendirin.',
      'İç harç için cevizi iri kıyın. Hamurdan ceviz büyüklüğünde parça alıp avucunuzda açın, ortasına bir tutam ceviz koyup kapatın ve oval şekil verin.',
      'Kalburabastının adı ve deseni buradan gelir: her parçayı bir kalburun (veya rende/hasır servis altlığının) üzerine bastırıp yuvarlayarak desenli izler oluşturun. Bu desen hem güzel görünür hem de şerbetin tutunacağı yüzeyi artırır. Desenli yüz yukarı gelecek şekilde yağlı kağıtlı tepsiye dizin.',
      'Önceden 170°C ısıtılmış fırında 25-30 dakika, üzerleri altın sarısı olana kadar pişirin. Aceleyle yüksek ateşte pişirmeyin; içi çiğ kalır. Fırından çıkar çıkmaz, SICAK tatlının üzerine SOĞUK şerbeti kepçeyle gezdirin. 30-40 dakika bekletip şerbeti tamamen çektikten sonra servis edin.',
    ],
  },
  {
    isim: 'Zerde', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek', porsiyon: 6,
    malzemeler: [
      ['Pirinç', '0,5 su bardağı'],
      ['Şeker', '2 su bardağı'],
      ['Nişasta', '2 yemek kaşığı'],
      ['Zerdeçal', '0,5 çay kaşığı'],
      ['Ceviz', '0,5 su bardağı'],
      ['Kuru Üzüm', '3 yemek kaşığı'],
      ['Çam Fıstığı', '2 yemek kaşığı'],
    ],
    adimlar: [
      'Zerde, düğün ve mevlütlerin geleneksel sarı tatlısıdır; rengini normalde safran verir, ama ulaşması zorsa bir tutam zerdeçal hem rengi hem hafif toprağımsı aromayı verir (safranınız varsa ılık suda bekletip suyunu kullanın). Pirinci yıkayıp 5-6 su bardağı suda, kısık ateşte tanelerin tamamen dağılıp lapalaşacağı kıvama kadar 25-30 dakika pişirin.',
      'Pirinç iyice yumuşayıp su nişastalı-bulanık bir hal alınca şekeri ekleyin. Şekeri baştan eklerseniz pirinç geç pişer; bu yüzden pirinç dağıldıktan sonra eklemek önemlidir. Karıştırıp 5 dakika daha kaynatın.',
      'Zerdeçalı birkaç kaşık ılık suda ezip pütürsüz hale getirin ve tencereye ekleyin, güzel bir altın-sarı renk alsın. Renk açık gelirse azar azar ekleyip ayarlayın; fazlası acılaştırır.',
      'Nişastayı yarım bardak SOĞUK suda topaksız çözün (sıcakta atarsanız hemen topaklanır). Tencere kaynarken nişasta suyunu ince ince, sürekli karıştırarak dökün. Zerde muhallebi gibi koyu olmamalı — kaşıktan akan, hafif jölemsi bir kıvam yeterli; soğuyunca biraz daha koyulaşacağını unutmayın. 2-3 dakika kaynatıp ocaktan alın.',
      'Kuru üzümü sıcak suda 10 dakika bekletip şişirin. Zerdeyi kaselere paylaştırın ve henüz sıcakken üzerlerini kapatmadan ılımaya bırakın.',
      'Buzdolabında iyice soğutun; zerde soğuk servis edilir. Üzerine dövülmüş ceviz, şişmiş kuru üzüm, çam fıstığı ve (varsa) nar taneleri serpin. Bu kuruyemişli süsleme hem görüntü hem de her kaşıkta farklı doku için şarttır.',
    ],
  },
  {
    isim: 'Cezerye', mutfak: M, kategori: 'Tatlılar', sure: 60, tur: 'yemek', porsiyon: 8,
    malzemeler: [
      ['Havuç', '1 kg'],
      ['Şeker', '2 su bardağı'],
      ['Nişasta', '3 yemek kaşığı'],
      ['Ceviz', '1 su bardağı'],
      ['Antep Fıstığı', '0,5 su bardağı'],
      ['Hindistan Cevizi Rendesi', '1 su bardağı'],
    ],
    adimlar: [
      'Cezerye, Mersin yöresinin havuçtan yapılan meşhur tatlısıdır. Havuçları yıkayıp soyun ve en ince gözle rendeleyin (veya rondoda çok ince çekin). Ne kadar ince olursa tatlı o kadar pürüzsüz ve homojen olur.',
      'Rendelenmiş havucu geniş, kalın tabanlı bir tencereye alın ve üzerine yarım bardak su ekleyin. Kapağı kapatıp kısık ateşte, ara sıra karıştırarak havuç tamamen yumuşayıp suyunu salana kadar 15-20 dakika pişirin.',
      'Havuç yumuşayınca şekeri ekleyin. Şeker eriyince havuç bir kez daha sulanacak; şimdi sabır aşaması başlıyor. Kısık-orta ateşte, tahta kaşıkla SÜREKLİ karıştırarak suyunu uçurun. Karışım koyulaşıp reçelimsi, parlak bir hal alacak — bu 20-25 dakika sürebilir ve dibi kolay tuttuğu için kaşığı elinizden bırakmayın.',
      'Nişastayı birkaç kaşık soğuk suda ezip karışıma ekleyin. Nişasta cezeryeyi bağlar, kesilince şeklini korumasını sağlar. Karıştırmaya devam edin; karışım tencerenin dibinden top gibi ayrılıp spatülaya yapışmaz hale gelince kıvamındadır.',
      'Ocaktan alıp iri kıyılmış ceviz ve antep fıstığını ekleyip karıştırın (sıcakken eklenirse aroması karışıma işler). Karışımı, yağlı kağıt serili bir tepsiye yaklaşık 1,5-2 cm kalınlığında dökün ve spatülayla düzleyin.',
      'Tamamen soğuyup sertleşmesi için birkaç saat (mümkünse buzdolabında) bekletin. Bir tabağa hindistan cevizi rendesini yayın. Soğuyan cezeryeyi baklava dilimi veya kare kesin, her parçayı hindistan cevizine bulayın. Kapalı kapta haftalarca tazeliğini korur.',
    ],
  },
];
