// Tarif adı → yerel (uygulamaya gömülü) görsel eşlemesi.
// Görseller assets/tarifler/ altında; Metro require() ile bunları
// paket içine dahil eder, böylece uygulama ÇEVRİMDIŞI çalışır.
// Kaynak: Wikimedia Commons (açık lisanslı). Bkz. GORSEL-LISANSLAR.md
import { type ImageSourcePropType } from 'react-native';

export const YEREL_RESIM: Record<string, ImageSourcePropType> = {
  'Adana Kebap (Tava Usulü)': require('../../assets/tarifler/adana-kebap-tava-usulu.jpg'),
  'Ali Nazik': require('../../assets/tarifler/ali-nazik.jpg'),
  'Asya Usulü Tavuk Dürüm': require('../../assets/tarifler/asya-usulu-tavuk-durum.jpg'),
  'Ayva Tatlısı': require('../../assets/tarifler/ayva-tatlisi.jpg'),
  'Açma': require('../../assets/tarifler/acma.jpg'),
  'Aşure': require('../../assets/tarifler/asure.jpg'),
  'Bazlama': require('../../assets/tarifler/bazlama.jpg'),
  'Bulgur Pilavı': require('../../assets/tarifler/bulgur-pilavi.jpg'),
  'Burrito': require('../../assets/tarifler/burrito.jpg'),
  'Cacık': require('../../assets/tarifler/cacik.jpg'),
  'Chili Con Carne': require('../../assets/tarifler/chili-con-carne.jpg'),
  'Cuba Libre': require('../../assets/tarifler/cuba-libre.jpg'),
  'Dana Rosto': require('../../assets/tarifler/dana-rosto.jpg'),
  'Domates Çorbası': require('../../assets/tarifler/domates-corbasi.jpg'),
  'Düğün Çorbası': require('../../assets/tarifler/dugun-corbasi.jpg'),
  'Espresso Martini': require('../../assets/tarifler/espresso-martini.jpg'),
  'Et Kavurma': require('../../assets/tarifler/et-kavurma.jpg'),
  'Etli Biber Dolması': require('../../assets/tarifler/etli-biber-dolmasi.jpg'),
  'Etli Kuru Fasulye': require('../../assets/tarifler/etli-kuru-fasulye.jpg'),
  'Etsiz Çiğ Köfte': require('../../assets/tarifler/etsiz-cig-kofte.jpg'),
  'Ev Baklavası': require('../../assets/tarifler/ev-baklavasi.png'),
  'Ev Yapımı Ayran': require('../../assets/tarifler/ev-yapimi-ayran.jpg'),
  'Ezogelin Çorbası': require('../../assets/tarifler/ezogelin-corbasi.jpg'),
  'Fajita': require('../../assets/tarifler/fajita.jpg'),
  'Fettuccine Alfredo': require('../../assets/tarifler/fettuccine-alfredo.png'),
  'Fırın Makarna': require('../../assets/tarifler/firin-makarna.jpg'),
  'Fırın Sütlaç': require('../../assets/tarifler/firin-sutlac.jpg'),
  'Fırında Bütün Tavuk': require('../../assets/tarifler/firinda-butun-tavuk.jpg'),
  'Gavurdağı Salatası': require('../../assets/tarifler/gavurdagi-salatasi.jpg'),
  'Gin Tonic': require('../../assets/tarifler/gin-tonic.jpg'),
  'Guacamole': require('../../assets/tarifler/guacamole.jpg'),
  'Güllaç': require('../../assets/tarifler/gullac.jpg'),
  'Hasanpaşa Köfte': require('../../assets/tarifler/hasanpasa-kofte.jpg'),
  'Havuç Tarator': require('../../assets/tarifler/havuc-tarator.jpg'),
  'Haydari': require('../../assets/tarifler/haydari.jpg'),
  'Hünkar Beğendi': require('../../assets/tarifler/hunkar-begendi.jpg'),
  'Ispanaklı Börek': require('../../assets/tarifler/ispanakli-borek.jpg'),
  'Kabak Mücver': require('../../assets/tarifler/kabak-mucver.jpg'),
  'Kabak Tatlısı': require('../../assets/tarifler/kabak-tatlisi.jpg'),
  'Kadınbudu Köfte': require('../../assets/tarifler/kadinbudu-kofte.jpg'),
  'Karidesli Körili Pilav': require('../../assets/tarifler/karidesli-korili-pilav.jpg'),
  'Karnıyarık': require('../../assets/tarifler/karniyarik.jpg'),
  'Kazandibi': require('../../assets/tarifler/kazandibi.jpg'),
  'Keşkül': require('../../assets/tarifler/keskul.jpg'),
  'Kremalı Mantarlı Makarna': require('../../assets/tarifler/kremali-mantarli-makarna.png'),
  'Kremalı Mantarlı Tavuk': require('../../assets/tarifler/kremali-mantarli-tavuk.jpg'),
  'Kuru Köfte': require('../../assets/tarifler/kuru-kofte.jpg'),
  'Künefe': require('../../assets/tarifler/kunefe.jpg'),
  'Kırmızı Mercimek Çorbası': require('../../assets/tarifler/kirmizi-mercimek-corbasi.jpg'),
  'Kısır': require('../../assets/tarifler/kisir.jpg'),
  'Lahana Sarması': require('../../assets/tarifler/lahana-sarmasi.jpg'),
  'Lahmacun': require('../../assets/tarifler/lahmacun.jpg'),
  'Lazanya': require('../../assets/tarifler/lazanya.jpg'),
  'Lokma': require('../../assets/tarifler/lokma.jpg'),
  'Mantar Çorbası': require('../../assets/tarifler/mantar-corbasi.jpg'),
  'Mantarlı Risotto': require('../../assets/tarifler/mantarli-risotto.jpg'),
  'Mantı': require('../../assets/tarifler/manti.jpg'),
  'Margarita': require('../../assets/tarifler/margarita.jpg'),
  'Margherita Pizza': require('../../assets/tarifler/margherita-pizza.jpg'),
  'Menemen': require('../../assets/tarifler/menemen.jpg'),
  'Mercimek Köftesi': require('../../assets/tarifler/mercimek-koftesi.jpg'),
  'Minestrone Çorbası': require('../../assets/tarifler/minestrone-corbasi.jpg'),
  'Mojito': require('../../assets/tarifler/mojito.jpg'),
  'Moscow Mule': require('../../assets/tarifler/moscow-mule.jpg'),
  'Muhallebi': require('../../assets/tarifler/muhallebi.jpg'),
  'Muzlu Magnolia': require('../../assets/tarifler/muzlu-magnolia.jpg'),
  'Nachos': require('../../assets/tarifler/nachos.jpg'),
  'Naneli Ev Limonatası': require('../../assets/tarifler/naneli-ev-limonatasi.jpg'),
  'Nohutlu Pilav': require('../../assets/tarifler/nohutlu-pilav.jpg'),
  'Pad Thai': require('../../assets/tarifler/pad-thai.jpg'),
  'Panna Cotta': require('../../assets/tarifler/panna-cotta.jpg'),
  'Patates Kavurması': require('../../assets/tarifler/patates-kavurmasi.jpg'),
  'Patates Salatası': require('../../assets/tarifler/patates-salatasi.jpg'),
  'Patlıcan Musakka': require('../../assets/tarifler/patlican-musakka.jpg'),
  'Penne Arrabbiata': require('../../assets/tarifler/penne-arrabbiata.jpg'),
  'Pesto Soslu Makarna': require('../../assets/tarifler/pesto-soslu-makarna.jpg'),
  'Peynirli Omlet': require('../../assets/tarifler/peynirli-omlet.jpg'),
  'Piyaz': require('../../assets/tarifler/piyaz.jpg'),
  'Piña Colada': require('../../assets/tarifler/pi-a-colada.jpg'),
  'Pişi': require('../../assets/tarifler/pisi.jpg'),
  'Poğaça': require('../../assets/tarifler/pogaca.jpg'),
  'Revani': require('../../assets/tarifler/revani.jpg'),
  'Salsa Sosu': require('../../assets/tarifler/salsa-sosu.jpg'),
  'Screwdriver': require('../../assets/tarifler/screwdriver.jpg'),
  'Sebze Çorbası': require('../../assets/tarifler/sebze-corbasi.jpg'),
  'Sebzeli Bulgur Pilavı': require('../../assets/tarifler/sebzeli-bulgur-pilavi.jpg'),
  'Sebzeli Wok': require('../../assets/tarifler/sebzeli-wok.jpg'),
  'Sebzeli Çorba (Uzak Doğu Usulü)': require('../../assets/tarifler/sebzeli-corba-uzak-dogu-usulu.jpg'),
  'Spaghetti Bolognese': require('../../assets/tarifler/spaghetti-bolognese.jpg'),
  'Spaghetti Pomodoro': require('../../assets/tarifler/spaghetti-pomodoro.jpg'),
  'Su Böreği': require('../../assets/tarifler/su-boregi.jpg'),
  'Sulu Köfte': require('../../assets/tarifler/sulu-kofte.jpg'),
  'Supangle': require('../../assets/tarifler/supangle.jpg'),
  'Taco': require('../../assets/tarifler/taco.jpg'),
  'Tarhana Çorbası': require('../../assets/tarifler/tarhana-corbasi.jpg'),
  'Tas Kebabı': require('../../assets/tarifler/tas-kebabi.jpg'),
  'Tavuk Göğsü Tatlısı': require('../../assets/tarifler/tavuk-gogsu-tatlisi.jpg'),
  'Tavuk Kapama': require('../../assets/tarifler/tavuk-kapama.jpg'),
  'Tavuk Şiş': require('../../assets/tarifler/tavuk-sis.jpg'),
  'Tavuklu Noodle': require('../../assets/tarifler/tavuklu-noodle.jpg'),
  'Tavuklu Parmigiana': require('../../assets/tarifler/tavuklu-parmigiana.jpg'),
  'Tavuklu Pilav': require('../../assets/tarifler/tavuklu-pilav.jpg'),
  'Tequila Sunrise': require('../../assets/tarifler/tequila-sunrise.jpg'),
  'Tereyağlı Pirinç Pilavı': require('../../assets/tarifler/tereyagli-pirinc-pilavi.jpg'),
  'Teriyaki Tavuk': require('../../assets/tarifler/teriyaki-tavuk.jpg'),
  'Tiramisu': require('../../assets/tarifler/tiramisu.jpg'),
  'Trileçe': require('../../assets/tarifler/trilece.jpg'),
  'Türlü': require('../../assets/tarifler/turlu.jpg'),
  'Virgin Mojito': require('../../assets/tarifler/virgin-mojito.jpg'),
  'Whiskey Sour': require('../../assets/tarifler/whiskey-sour.jpg'),
  'Yayla Çorbası': require('../../assets/tarifler/yayla-corbasi.jpg'),
  'Yoğurtlu Yeşil Mercimek Çorbası': require('../../assets/tarifler/yogurtlu-yesil-mercimek-corbasi.jpg'),
  'Yumurtalı Çin Pilavı': require('../../assets/tarifler/yumurtali-cin-pilavi.jpg'),
  'Zeytinyağlı Barbunya': require('../../assets/tarifler/zeytinyagli-barbunya.jpg'),
  'Zeytinyağlı Yaprak Sarma': require('../../assets/tarifler/zeytinyagli-yaprak-sarma.jpg'),
  'Çilekli Milkshake': require('../../assets/tarifler/cilekli-milkshake.jpg'),
  'Çoban Salatası': require('../../assets/tarifler/coban-salatasi.jpg'),
  'Çılbır': require('../../assets/tarifler/cilbir.jpg'),
  'İmam Bayıldı': require('../../assets/tarifler/imam-bayildi.jpg'),
  'İrmik Helvası': require('../../assets/tarifler/irmik-helvasi.jpg'),
  'İskender': require('../../assets/tarifler/iskender.jpg'),
  'İzmir Köfte': require('../../assets/tarifler/izmir-kofte.jpg'),
  'İç Pilav': require('../../assets/tarifler/ic-pilav.jpg'),
  'İçli Köfte (Haşlama)': require('../../assets/tarifler/icli-kofte-haslama.jpg'),
  'Şehriyeli Tavuk Çorbası': require('../../assets/tarifler/sehriyeli-tavuk-corbasi.jpg'),
  'Şekerpare': require('../../assets/tarifler/sekerpare.jpg'),
};
