// Tarif adı → yerel (uygulamaya gömülü) görsel eşlemesi.
// Görseller assets/tarifler/ altında; Metro require() ile bunları
// paket içine dahil eder, böylece uygulama ÇEVRİMDIŞI çalışır.
// Kaynak: Wikimedia Commons (açık lisanslı). Bkz. GORSEL-LISANSLAR.md
import { type ImageSourcePropType } from 'react-native';

export const YEREL_RESIM: Record<string, ImageSourcePropType> = {
  // ─── Commons aramasıyla eklenen tarifler (seed-turk-6) ───
  'Kelle Paça Çorbası': require('../../assets/tarifler/kelle-paca.jpg'),
  'Toyga Çorbası': require('../../assets/tarifler/toyga-corbasi.jpg'),
  'Kuzu Tandır': require('../../assets/tarifler/kuzu-tandir.jpg'),
  'Etli Bamya': require('../../assets/tarifler/etli-bamya.jpg'),
  'Etli Nohut': require('../../assets/tarifler/etli-nohut.jpg'),
  'Kalamar Tava': require('../../assets/tarifler/kalamar-tava.jpg'),
  'Patlıcan Kızartması': require('../../assets/tarifler/patlican-kizartmasi.jpg'),
  'Domatesli Pilav': require('../../assets/tarifler/domatesli-pilav.jpg'),
  'Peynirli Pide': require('../../assets/tarifler/peynirli-pide.jpg'),
  'İncir Reçeli': require('../../assets/tarifler/incir-receli.jpg'),
  // ─── Reçel, turşu ve klasik tarifler (seed-turk-5) ───
  'Vişne Reçeli': require('../../assets/tarifler/visne-receli.jpg'),
  'Çilek Reçeli': require('../../assets/tarifler/cilek-receli.jpg'),
  'Kayısı Reçeli': require('../../assets/tarifler/kayisi-receli.jpg'),
  'Gül Reçeli': require('../../assets/tarifler/gul-receli.jpg'),
  'Portakal Marmelatı': require('../../assets/tarifler/portakal-marmelati.jpg'),
  'Ayva Reçeli': require('../../assets/tarifler/ayva-receli.jpg'),
  'Karışık Turşu': require('../../assets/tarifler/karisik-tursu.jpg'),
  'Salatalık Turşusu': require('../../assets/tarifler/salatalik-tursusu.jpg'),
  'Beyran': require('../../assets/tarifler/beyran.jpg'),
  'Analı Kızlı': require('../../assets/tarifler/analikizli.jpg'),
  'Balık Çorbası': require('../../assets/tarifler/balik-corbasi.jpg'),
  'Mıhlama': require('../../assets/tarifler/mihlama.jpg'),
  'Kaygana': require('../../assets/tarifler/kaygana.jpg'),
  'Sahanda Yumurta': require('../../assets/tarifler/sahanda-yumurta.jpg'),
  'Girit Ezmesi': require('../../assets/tarifler/girit-ezmesi.jpg'),
  'Urfa Kebabı': require('../../assets/tarifler/urfa-kebabi.jpg'),
  'Beyti Kebap': require('../../assets/tarifler/beyti.jpg'),
  'Testi Kebabı': require('../../assets/tarifler/testi-kebabi.jpg'),
  'Çökertme Kebabı': require('../../assets/tarifler/cokertme-kebabi.jpg'),
  'Kağıt Kebabı': require('../../assets/tarifler/kagit-kebabi.jpg'),
  'Çöp Şiş': require('../../assets/tarifler/cop-sis.jpg'),
  'Tekirdağ Köftesi': require('../../assets/tarifler/tekirdag-kofte.jpg'),
  'Papaz Yahnisi': require('../../assets/tarifler/papaz-yahnisi.jpg'),
  'Şiş Köfte': require('../../assets/tarifler/sis-kofte.jpg'),
  'Elbasan Tava': require('../../assets/tarifler/elbasan-tava.jpg'),
  'Patlıcan Kebabı': require('../../assets/tarifler/patlican-kebabi.jpg'),
  'Manisa Kebabı': require('../../assets/tarifler/manisa-kebabi.jpg'),
  'Tavuk Döner': require('../../assets/tarifler/tavuk-doner.jpg'),
  'Çıtır Tavuk': require('../../assets/tarifler/citir-tavuk.jpg'),
  'Balık Ekmek': require('../../assets/tarifler/balik-ekmek.jpg'),
  'Midye Tava': require('../../assets/tarifler/midye-tava.jpg'),
  'Perde Pilavı': require('../../assets/tarifler/perde-pilavi.jpg'),
  'Etli Ekmek': require('../../assets/tarifler/etli-ekmek.jpg'),
  'Ramazan Pidesi': require('../../assets/tarifler/ramazan-pidesi.jpg'),
  'Boyoz': require('../../assets/tarifler/boyoz.jpg'),
  'Kete': require('../../assets/tarifler/kete.jpg'),
  'Tel Kadayıf': require('../../assets/tarifler/tel-kadayif.jpg'),
  'Şöbiyet': require('../../assets/tarifler/sobiyet.jpg'),
  'Un Helvası': require('../../assets/tarifler/un-helvasi.jpg'),
  'Kemalpaşa Tatlısı': require('../../assets/tarifler/kemalpasa-tatlisi.jpg'),
  'Bülbül Yuvası': require('../../assets/tarifler/bulbul-yuvasi.jpg'),
  'Profiterol': require('../../assets/tarifler/profiterol.jpg'),
  'Lokum': require('../../assets/tarifler/lokum.jpg'),
  'Pişmaniye': require('../../assets/tarifler/pismaniye.jpg'),
  'Pestil': require('../../assets/tarifler/pestil.jpg'),
  // ─── Sonradan eklenen Türk tarifleri (seed-turk-4) ───
  'İşkembe Çorbası': require('../../assets/tarifler/iskembe-corbasi.jpg'),
  'Fava': require('../../assets/tarifler/fava.jpg'),
  'Humus': require('../../assets/tarifler/humus.jpg'),
  'Babagannuş': require('../../assets/tarifler/babagannus.jpg'),
  'Şakşuka': require('../../assets/tarifler/saksuka.jpg'),
  'Muhammara': require('../../assets/tarifler/muhammara.jpg'),
  'Rus Salatası': require('../../assets/tarifler/rus-salatasi.jpg'),
  'İnegöl Köfte': require('../../assets/tarifler/inegol-kofte.jpg'),
  'Arnavut Ciğeri': require('../../assets/tarifler/arnavut-cigeri.jpg'),
  'Sac Kavurma': require('../../assets/tarifler/sac-kavurma.jpg'),
  'Midye Dolma': require('../../assets/tarifler/midye-dolma.jpg'),
  'Hamsili Pilav': require('../../assets/tarifler/hamsili-pilav.jpg'),
  'Çiğ Börek': require('../../assets/tarifler/cig-borek.jpg'),
  'Simit': require('../../assets/tarifler/simit.jpg'),
  'Kol Böreği': require('../../assets/tarifler/kol-boregi.jpg'),
  'Ekmek Kadayıfı': require('../../assets/tarifler/ekmek-kadayifi.jpg'),
  'Kalburabastı': require('../../assets/tarifler/kalburabasti.jpg'),
  'Zerde': require('../../assets/tarifler/zerde.jpg'),
  'Cezerye': require('../../assets/tarifler/cezerye.jpg'),
  'Adana Kebap (Tava Usulü)': require('../../assets/tarifler/adana-kebap-tava-usulu.jpg'),
  'Ali Nazik': require('../../assets/tarifler/ali-nazik.jpg'),
  'Asya Usulü Tavuk Dürüm': require('../../assets/tarifler/asya-usulu-tavuk-durum.jpg'),
  'Ayva Tatlısı': require('../../assets/tarifler/ayva-tatlisi.jpg'),
  'Açma': require('../../assets/tarifler/acma.jpg'),
  'Aşure': require('../../assets/tarifler/asure.jpg'),
  'Bazlama': require('../../assets/tarifler/bazlama.jpg'),
  'Bulgur Pilavı': require('../../assets/tarifler/bulgur-pilavi.jpg'),
  'Burrito': require('../../assets/tarifler/burrito.jpg'),
  'Cacık': require('../../assets/tarifler/cacik.jpg'),
  'Chili Con Carne': require('../../assets/tarifler/chili-con-carne.jpg'),
  'Cuba Libre': require('../../assets/tarifler/cuba-libre.jpg'),
  'Dana Rosto': require('../../assets/tarifler/dana-rosto.jpg'),
  'Domates Çorbası': require('../../assets/tarifler/domates-corbasi.jpg'),
  'Düğün Çorbası': require('../../assets/tarifler/dugun-corbasi.jpg'),
  'Espresso Martini': require('../../assets/tarifler/espresso-martini.jpg'),
  'Et Kavurma': require('../../assets/tarifler/et-kavurma.jpg'),
  'Etli Biber Dolması': require('../../assets/tarifler/etli-biber-dolmasi.jpg'),
  'Etli Kuru Fasulye': require('../../assets/tarifler/etli-kuru-fasulye.jpg'),
  'Etsiz Çiğ Köfte': require('../../assets/tarifler/etsiz-cig-kofte.jpg'),
  'Ev Baklavası': require('../../assets/tarifler/ev-baklavasi.png'),
  'Ev Yapımı Ayran': require('../../assets/tarifler/ev-yapimi-ayran.jpg'),
  'Ezogelin Çorbası': require('../../assets/tarifler/ezogelin-corbasi.jpg'),
  'Fajita': require('../../assets/tarifler/fajita.jpg'),
  'Fettuccine Alfredo': require('../../assets/tarifler/fettuccine-alfredo.png'),
  'Fırın Makarna': require('../../assets/tarifler/firin-makarna.jpg'),
  'Fırın Sütlaç': require('../../assets/tarifler/firin-sutlac.jpg'),
  'Fırında Bütün Tavuk': require('../../assets/tarifler/firinda-butun-tavuk.jpg'),
  'Gavurdağı Salatası': require('../../assets/tarifler/gavurdagi-salatasi.jpg'),
  'Gin Tonic': require('../../assets/tarifler/gin-tonic.jpg'),
  'Guacamole': require('../../assets/tarifler/guacamole.jpg'),
  'Güllaç': require('../../assets/tarifler/gullac.jpg'),
  'Hasanpaşa Köfte': require('../../assets/tarifler/hasanpasa-kofte.jpg'),
  'Havuç Tarator': require('../../assets/tarifler/havuc-tarator.jpg'),
  'Haydari': require('../../assets/tarifler/haydari.jpg'),
  'Hünkar Beğendi': require('../../assets/tarifler/hunkar-begendi.jpg'),
  'Ispanaklı Börek': require('../../assets/tarifler/ispanakli-borek.jpg'),
  'Kabak Mücver': require('../../assets/tarifler/kabak-mucver.jpg'),
  'Kabak Tatlısı': require('../../assets/tarifler/kabak-tatlisi.jpg'),
  'Kadınbudu Köfte': require('../../assets/tarifler/kadinbudu-kofte.jpg'),
  'Karidesli Körili Pilav': require('../../assets/tarifler/karidesli-korili-pilav.jpg'),
  'Karnıyarık': require('../../assets/tarifler/karniyarik.jpg'),
  'Kazandibi': require('../../assets/tarifler/kazandibi.jpg'),
  'Keşkül': require('../../assets/tarifler/keskul.jpg'),
  'Kremalı Mantarlı Makarna': require('../../assets/tarifler/kremali-mantarli-makarna.png'),
  'Kremalı Mantarlı Tavuk': require('../../assets/tarifler/kremali-mantarli-tavuk.jpg'),
  'Kuru Köfte': require('../../assets/tarifler/kuru-kofte.jpg'),
  'Künefe': require('../../assets/tarifler/kunefe.jpg'),
  'Kırmızı Mercimek Çorbası': require('../../assets/tarifler/kirmizi-mercimek-corbasi.jpg'),
  'Kısır': require('../../assets/tarifler/kisir.jpg'),
  'Lahana Sarması': require('../../assets/tarifler/lahana-sarmasi.jpg'),
  'Lahmacun': require('../../assets/tarifler/lahmacun.jpg'),
  'Lazanya': require('../../assets/tarifler/lazanya.jpg'),
  'Lokma': require('../../assets/tarifler/lokma.jpg'),
  'Mantar Çorbası': require('../../assets/tarifler/mantar-corbasi.jpg'),
  'Mantarlı Risotto': require('../../assets/tarifler/mantarli-risotto.jpg'),
  'Mantı': require('../../assets/tarifler/manti.jpg'),
  'Margarita': require('../../assets/tarifler/margarita.jpg'),
  'Margherita Pizza': require('../../assets/tarifler/margherita-pizza.jpg'),
  'Menemen': require('../../assets/tarifler/menemen.jpg'),
  'Mercimek Köftesi': require('../../assets/tarifler/mercimek-koftesi.jpg'),
  'Minestrone Çorbası': require('../../assets/tarifler/minestrone-corbasi.jpg'),
  'Mojito': require('../../assets/tarifler/mojito.jpg'),
  'Moscow Mule': require('../../assets/tarifler/moscow-mule.jpg'),
  'Muhallebi': require('../../assets/tarifler/muhallebi.jpg'),
  'Muzlu Magnolia': require('../../assets/tarifler/muzlu-magnolia.jpg'),
  'Nachos': require('../../assets/tarifler/nachos.jpg'),
  'Naneli Ev Limonatası': require('../../assets/tarifler/naneli-ev-limonatasi.jpg'),
  'Nohutlu Pilav': require('../../assets/tarifler/nohutlu-pilav.jpg'),
  'Pad Thai': require('../../assets/tarifler/pad-thai.jpg'),
  'Panna Cotta': require('../../assets/tarifler/panna-cotta.jpg'),
  'Patates Kavurması': require('../../assets/tarifler/patates-kavurmasi.jpg'),
  'Patates Salatası': require('../../assets/tarifler/patates-salatasi.jpg'),
  'Patlıcan Musakka': require('../../assets/tarifler/patlican-musakka.jpg'),
  'Penne Arrabbiata': require('../../assets/tarifler/penne-arrabbiata.jpg'),
  'Pesto Soslu Makarna': require('../../assets/tarifler/pesto-soslu-makarna.jpg'),
  'Peynirli Omlet': require('../../assets/tarifler/peynirli-omlet.jpg'),
  'Piyaz': require('../../assets/tarifler/piyaz.jpg'),
  'Piña Colada': require('../../assets/tarifler/pi-a-colada.jpg'),
  'Pişi': require('../../assets/tarifler/pisi.jpg'),
  'Poğaça': require('../../assets/tarifler/pogaca.jpg'),
  'Revani': require('../../assets/tarifler/revani.jpg'),
  'Salsa Sosu': require('../../assets/tarifler/salsa-sosu.jpg'),
  'Screwdriver': require('../../assets/tarifler/screwdriver.jpg'),
  'Sebze Çorbası': require('../../assets/tarifler/sebze-corbasi.jpg'),
  'Sebzeli Bulgur Pilavı': require('../../assets/tarifler/sebzeli-bulgur-pilavi.jpg'),
  'Sebzeli Wok': require('../../assets/tarifler/sebzeli-wok.jpg'),
  'Sebzeli Çorba (Uzak Doğu Usulü)': require('../../assets/tarifler/sebzeli-corba-uzak-dogu-usulu.jpg'),
  'Spaghetti Bolognese': require('../../assets/tarifler/spaghetti-bolognese.jpg'),
  'Spaghetti Pomodoro': require('../../assets/tarifler/spaghetti-pomodoro.jpg'),
  'Su Böreği': require('../../assets/tarifler/su-boregi.jpg'),
  'Sulu Köfte': require('../../assets/tarifler/sulu-kofte.jpg'),
  'Supangle': require('../../assets/tarifler/supangle.jpg'),
  'Taco': require('../../assets/tarifler/taco.jpg'),
  'Tarhana Çorbası': require('../../assets/tarifler/tarhana-corbasi.jpg'),
  'Tas Kebabı': require('../../assets/tarifler/tas-kebabi.jpg'),
  'Tavuk Göğsü Tatlısı': require('../../assets/tarifler/tavuk-gogsu-tatlisi.jpg'),
  'Tavuk Kapama': require('../../assets/tarifler/tavuk-kapama.jpg'),
  'Tavuk Şiş': require('../../assets/tarifler/tavuk-sis.jpg'),
  'Tavuklu Noodle': require('../../assets/tarifler/tavuklu-noodle.jpg'),
  'Tavuklu Parmigiana': require('../../assets/tarifler/tavuklu-parmigiana.jpg'),
  'Tavuklu Pilav': require('../../assets/tarifler/tavuklu-pilav.jpg'),
  'Tequila Sunrise': require('../../assets/tarifler/tequila-sunrise.jpg'),
  'Tereyağlı Pirinç Pilavı': require('../../assets/tarifler/tereyagli-pirinc-pilavi.jpg'),
  'Teriyaki Tavuk': require('../../assets/tarifler/teriyaki-tavuk.jpg'),
  'Tiramisu': require('../../assets/tarifler/tiramisu.jpg'),
  'Trileçe': require('../../assets/tarifler/trilece.jpg'),
  'Türlü': require('../../assets/tarifler/turlu.jpg'),
  'Virgin Mojito': require('../../assets/tarifler/virgin-mojito.jpg'),
  'Whiskey Sour': require('../../assets/tarifler/whiskey-sour.jpg'),
  'Yayla Çorbası': require('../../assets/tarifler/yayla-corbasi.jpg'),
  'Yoğurtlu Yeşil Mercimek Çorbası': require('../../assets/tarifler/yogurtlu-yesil-mercimek-corbasi.jpg'),
  'Yumurtalı Çin Pilavı': require('../../assets/tarifler/yumurtali-cin-pilavi.jpg'),
  'Zeytinyağlı Barbunya': require('../../assets/tarifler/zeytinyagli-barbunya.jpg'),
  'Zeytinyağlı Yaprak Sarma': require('../../assets/tarifler/zeytinyagli-yaprak-sarma.jpg'),
  'Çilekli Milkshake': require('../../assets/tarifler/cilekli-milkshake.jpg'),
  'Çoban Salatası': require('../../assets/tarifler/coban-salatasi.jpg'),
  'Çılbır': require('../../assets/tarifler/cilbir.jpg'),
  'İmam Bayıldı': require('../../assets/tarifler/imam-bayildi.jpg'),
  'İrmik Helvası': require('../../assets/tarifler/irmik-helvasi.jpg'),
  'İskender': require('../../assets/tarifler/iskender.jpg'),
  'İzmir Köfte': require('../../assets/tarifler/izmir-kofte.jpg'),
  'İç Pilav': require('../../assets/tarifler/ic-pilav.jpg'),
  'İçli Köfte (Haşlama)': require('../../assets/tarifler/icli-kofte-haslama.jpg'),
  'Şehriyeli Tavuk Çorbası': require('../../assets/tarifler/sehriyeli-tavuk-corbasi.jpg'),
  'Şekerpare': require('../../assets/tarifler/sekerpare.jpg'),
};
